export const VARIABLES = {
  // ── Mechanik ──
  F: { name: 'Kraft', unit: 'N', desc: 'Kraft in Newton. 1 N = 1 kg·m/s². F = m·a' },
  m: { name: 'Masse', unit: 'kg', desc: 'Masse des Körpers in Kilogramm' },
  a: { name: 'Beschleunigung', unit: 'm/s²', desc: 'Änderungsrate der Geschwindigkeit. a = F/m' },
  g: { name: 'Erdbeschleunigung', unit: 'm/s²', desc: 'g ≈ 9,81 m/s² auf der Erdoberfläche' },
  v: { name: 'Geschwindigkeit', unit: 'm/s', desc: 'Momentangeschwindigkeit des Körpers' },
  s: { name: 'Weg / Strecke', unit: 'm', desc: 'Zurückgelegter Weg oder Verschiebung' },
  t: { name: 'Zeit', unit: 's', desc: 'Zeitvariable in Sekunden' },
  W: { name: 'Arbeit', unit: 'J', desc: 'Mechanische Arbeit. W = F·s·cos(α). 1 J = 1 Nm' },
  P: { name: 'Leistung', unit: 'W', desc: 'Arbeit pro Zeit. P = W/t = F·v. 1 W = 1 J/s' },
  M: { name: 'Drehmoment', unit: 'Nm', desc: 'Moment = Kraft × senkrechter Hebelarm. M = F·l⊥' },
  'ω': { name: 'Winkelgeschwindigkeit', unit: 'rad/s', desc: 'Kreisfrequenz. ω = 2πf = 2π/T = 2πn/60' },
  'α': { name: 'Winkel', unit: 'rad / °', desc: 'Winkel in Radiant oder Grad. π rad = 180°' },
  'μ': { name: 'Reibkoeffizient', unit: '–', desc: 'Verhältnis Reibkraft/Normalkraft. FR = μ·FN' },
  'FG': { name: 'Gewichtskraft', unit: 'N', desc: 'FG = m·g. Kraft durch Schwerkraft' },
  'FR': { name: 'Reibkraft', unit: 'N', desc: 'FR = μ·FN. Reibung an Kontaktfläche' },
  'FN': { name: 'Normalkraft', unit: 'N', desc: 'Kraft senkrecht zur Oberfläche' },
  'Ekin': { name: 'Kinetische Energie', unit: 'J', desc: 'Ekin = ½·m·v². Bewegungsenergie' },
  'Epot': { name: 'Potentielle Energie', unit: 'J', desc: 'Epot = m·g·h. Lageenergie' },

  // ── Festigkeitslehre ──
  'σ': { name: 'Normalspannung', unit: 'MPa', desc: 'Kraft pro Querschnittsfläche. σ = F/A. 1 MPa = 1 N/mm²' },
  'τ': { name: 'Schubspannung', unit: 'MPa', desc: 'Tangentiale Spannung. τ = Fs/A' },
  'ε': { name: 'Dehnung', unit: '–', desc: 'Relative Längenänderung. ε = Δl/l₀ (dimensionslos)' },
  E: { name: 'E-Modul', unit: 'MPa', desc: 'Elastizitätsmodul (Steifigkeit). Stahl: ~210.000 MPa. σ = E·ε' },
  A: { name: 'Querschnittsfläche', unit: 'mm²', desc: 'Fläche des Querschnitts senkrecht zur Kraft' },
  I: { name: 'Flächenmoment 2. Grades', unit: 'mm⁴', desc: 'Flächenträgheitsmoment. Rechteck: I = bh³/12' },
  Wb: { name: 'Widerstandsmoment', unit: 'mm³', desc: 'W = I/e. Rechteck: W = bh²/6. Kreis: W = πd³/32' },
  'σy': { name: 'Streckgrenze', unit: 'MPa', desc: 'Beginn der plastischen Verformung. S235: σy = 235 MPa' },
  S: { name: 'Sicherheitsfaktor', unit: '–', desc: 'S = σzul/σvorh. Muss > 1 sein für sicheren Betrieb' },
  D: { name: 'Dämpfungsgrad', unit: '–', desc: 'D = d/(2√(km)). D < 1: unterdämpft, D = 1: kritisch, D > 1: überdämpft' },
  'σv': { name: 'Vergleichsspannung', unit: 'MPa', desc: 'Von Mises: σv = √(σ² + 3τ²)' },
  'σb': { name: 'Biegespannung', unit: 'MPa', desc: 'σb = Mb/Wb. Max. an der Randfaser' },
  'Mb': { name: 'Biegemoment', unit: 'Nm', desc: 'Moment das Biegung verursacht' },
  Re: { name: 'Streckgrenze (Werkstoff)', unit: 'MPa', desc: 'Mindeststreckgrenze. S235 → Re = 235 MPa' },
  Rm: { name: 'Zugfestigkeit', unit: 'MPa', desc: 'Maximale Spannung im Zugversuch' },
  Wp: { name: 'Polares Widerstandsmoment', unit: 'mm³', desc: 'Für Torsion. Kreis: Wp = πd³/16. Doppelt so groß wie axiales W bei Vollkreis' },
  Mt: { name: 'Torsionsmoment', unit: 'Nm', desc: 'Moment um die Längsachse. τ = Mt/Wp' },

  // ── Thermodynamik ──
  T: { name: 'Temperatur', unit: 'K', desc: 'Absolute Temperatur in Kelvin. T = °C + 273,15' },
  p: { name: 'Druck', unit: 'Pa', desc: 'Kraft pro Fläche. 1 bar = 100.000 Pa = 100 kPa' },
  V: { name: 'Volumen', unit: 'm³', desc: 'Rauminhalt in Kubikmeter' },
  Q: { name: 'Wärme', unit: 'J', desc: 'Übertragene Wärmemenge in Joule' },
  U: { name: 'Innere Energie', unit: 'J', desc: 'Thermodynamische innere Energie. ΔU = Q − W' },
  'η': { name: 'Wirkungsgrad', unit: '–', desc: 'η = Pnutz/Pzu = Enutz/Ezu (0 bis 1, bzw. 0% bis 100%)' },
  R: { name: 'Gaskonstante', unit: 'J/(mol·K)', desc: 'Universelle Gaskonstante R = 8,314 J/(mol·K)' },
  n: { name: 'Stoffmenge', unit: 'mol', desc: 'Anzahl der Mole. pV = nRT' },
  'γ': { name: 'Isentropenexponent', unit: '–', desc: 'γ = cp/cv. Luft: γ ≈ 1,4. Für pVγ = const (Adiabat)' },
  cp: { name: 'Spez. Wärme (p=const)', unit: 'J/(kg·K)', desc: 'Spezifische Wärmekapazität bei konstantem Druck' },
  cv: { name: 'Spez. Wärme (V=const)', unit: 'J/(kg·K)', desc: 'Spezifische Wärmekapazität bei konstantem Volumen' },
  'ηC': { name: 'Carnot-Wirkungsgrad', unit: '–', desc: 'ηC = 1 − Tkalt/Twarm. Maximal möglicher Wirkungsgrad' },
  COP: { name: 'Leistungszahl', unit: '–', desc: 'Coefficient of Performance. Wärmepumpe: COPWP = Qab/Wzu. Kältemaschine: COPK = Qzu/Wzu' },
  'κ': { name: 'Adiabatenexponent', unit: '–', desc: 'κ = cp/cv. Luft: κ ≈ 1,4. Für Adiabat: pVκ = const' },

  // ── Fluidmechanik ──
  'ρ': { name: 'Dichte', unit: 'kg/m³', desc: 'Masse pro Volumen. Wasser: ~1000 kg/m³, Luft: ~1,2 kg/m³' },
  'Re_fluid': { name: 'Reynolds-Zahl', unit: '–', desc: 'Re = ρvd/μ. Laminar: Re < 2300, turbulent: Re > 4000' },
  FA: { name: 'Auftriebskraft', unit: 'N', desc: 'FA = ρFluid·g·Vverdrängt (Archimedes)' },
  'μ_dyn': { name: 'Dynamische Viskosität', unit: 'Pa·s', desc: 'Maß für Zähflüssigkeit. Wasser: ~0,001 Pa·s' },
  'Vdot': { name: 'Volumenstrom', unit: 'm³/s', desc: 'V̇ = A·v. Volumen pro Zeiteinheit' },

  // ── Maschinenelemente ──
  i: { name: 'Übersetzung', unit: '–', desc: 'i = z₂/z₁ = n₁/n₂. i > 1: Untersetzung (langsamer, stärker)' },
  z: { name: 'Zähnezahl', unit: '–', desc: 'Anzahl der Zähne eines Zahnrads' },
  d: { name: 'Durchmesser', unit: 'mm', desc: 'Durchmesser (Welle, Zahnrad, Rohr, etc.)' },
  k: { name: 'Federsteifigkeit', unit: 'N/m', desc: 'Federkonstante. F = k·x (Hookesches Federgesetz)' },
  Ft: { name: 'Umfangskraft', unit: 'N', desc: 'Ft = 2M/d. Tangentialkraft am Zahnrad' },
  'n_dreh': { name: 'Drehzahl', unit: '1/min', desc: 'Umdrehungen pro Minute. ω = 2πn/60' },
  FV: { name: 'Vorspannkraft', unit: 'N', desc: 'Schraubenvorspannung nach Anziehen. FV = σ·As. Muss bei Betriebslasten erhalten bleiben' },
  MA: { name: 'Anziehdrehmoment', unit: 'Nm', desc: 'Drehmoment beim Anziehen der Schraube. MA ≈ K·FV·d mit K ≈ 0,2 (K ≈ 0,12 geölt)' },
  As: { name: 'Spannungsquerschnitt', unit: 'mm²', desc: 'Tragender Gewindequerschnitt der Schraube. Immer kleiner als πd²/4 (steht in DIN-Tabellen)' },

  // ── Schwingungen ──
  'ω0': { name: 'Eigenkreisfrequenz', unit: 'rad/s', desc: 'ω₀ = √(k/m). Frequenz der freien Schwingung' },
  f: { name: 'Frequenz', unit: 'Hz', desc: 'Schwingungen pro Sekunde. f = 1/T = ω/(2π)' },
  'T_per': { name: 'Periodendauer', unit: 's', desc: 'Dauer einer Schwingung. T = 1/f = 2π/ω' },

  // ── Mathematik ──
  x: { name: 'Variable x', unit: '–', desc: 'Unabhängige Variable / Unbekannte' },
  y: { name: 'Variable y', unit: '–', desc: 'Abhängige Variable / Funktionswert' },
  'π': { name: 'Kreiszahl Pi', unit: '–', desc: 'π ≈ 3,14159. Umfang = π·d. Fläche = π·r²' },
  e: { name: 'Eulersche Zahl', unit: '–', desc: 'e ≈ 2,71828. Basis des natürlichen Logarithmus ln' },
  b: { name: 'Breite', unit: 'mm', desc: 'Breite (z.B. eines Querschnitts)' },
  h: { name: 'Höhe', unit: 'mm / m', desc: 'Höhe (Querschnittshöhe, Fallhöhe, etc.)' },
  r: { name: 'Radius', unit: 'mm / m', desc: 'Abstand vom Mittelpunkt' },
  L: { name: 'Länge', unit: 'm', desc: 'Gesamtlänge (Balken, Stab, Rohr, etc.)' },
  l: { name: 'Hebelarm / Länge', unit: 'm', desc: 'Senkrechter Abstand oder Teillänge' },
}

export const CATEGORIES = [
  { name: 'Mechanik', keys: ['F', 'FG', 'FN', 'FR', 'm', 'a', 'g', 'v', 's', 't', 'W', 'P', 'M', 'ω', 'α', 'μ', 'Ekin', 'Epot'] },
  { name: 'Festigkeitslehre', keys: ['σ', 'σb', 'σv', 'σy', 'τ', 'ε', 'E', 'A', 'I', 'Wb', 'Wp', 'Mb', 'Mt', 'Re', 'Rm', 'S', 'D'] },
  { name: 'Thermodynamik', keys: ['T', 'p', 'V', 'Q', 'U', 'η', 'ηC', 'COP', 'R', 'n', 'γ', 'κ', 'cp', 'cv'] },
  { name: 'Fluidmechanik', keys: ['ρ', 'Re_fluid', 'FA', 'μ_dyn', 'Vdot'] },
  { name: 'Maschinenelemente', keys: ['i', 'z', 'd', 'k', 'Ft', 'n_dreh', 'FV', 'MA', 'As'] },
  { name: 'Schwingungen', keys: ['ω0', 'f', 'T_per'] },
  { name: 'Geometrie / Mathe', keys: ['x', 'y', 'π', 'e', 'b', 'h', 'r', 'L', 'l'] },
]

export const DISPLAY_LABELS = {
  FG: 'F_G', FN: 'F_N', FR: 'F_R', FA: 'F_A', Ft: 'F_t',
  Ekin: 'E_kin', Epot: 'E_pot',
  σb: 'σ_b', σv: 'σ_v', σy: 'σ_y',
  Wb: 'W_b', Mb: 'M_b', Rm: 'R_m', Re: 'R_e',
  Re_fluid: 'Re', μ_dyn: 'μ', Vdot: 'V̇',
  ω0: 'ω₀', T_per: 'T', n_dreh: 'n',
  cp: 'c_p', cv: 'c_v', ηC: 'η_C',
}
