import type { PracticeExercise } from '@/types/practice'

export const ableitungPractice: PracticeExercise[] = [
  {
    id: 'pr-abl-1',
    topicId: 'ableitung',
    title: 'Kurvendiskussion einer Polynomfunktion',
    difficulty: 'klausur',
    points: 12,
    estimatedMinutes: 15,
    context: `Gegeben sei die Funktion
$$f(x) = x^3 - 6x^2 + 9x + 1.$$
Untersuchen Sie Extrem- und Wendestelle.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Bestimmen Sie die kleinere $x$-Koordinate einer Extremstelle.',
        answer: 1,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `$f'(x) = 3x^2 - 12x + 9 = 3(x^2 - 4x + 3) = 3(x-1)(x-3) = 0 \\Rightarrow x = 1$ oder $x = 3$.`,
      },
      {
        id: 'b',
        prompt: 'b) Berechnen Sie den $y$-Wert des Hochpunkts $f(1)$.',
        answer: 5,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$f(1) = 1 - 6 + 9 + 1 = 5$. Mit $f''(1) = 6 - 12 = -6 < 0$ ist das ein Hochpunkt $H(1\\,|\\,5)$.`,
      },
      {
        id: 'c',
        prompt: 'c) Bestimmen Sie die $x$-Koordinate der Wendestelle.',
        answer: 2,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `$f''(x) = 6x - 12 = 0 \\Rightarrow x = 2$. $f'''(2) = 6 \\neq 0$ bestätigt Wendestelle.`,
      },
      {
        id: 'd',
        prompt: 'd) Berechnen Sie die Steigung der Wendetangente $f\'(2)$.',
        answer: -3,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$f'(2) = 3\\cdot 4 - 24 + 9 = -3$. Steigung der Wendetangente.`,
      },
      {
        id: 'e',
        prompt: 'e) An welcher Stelle $x$ schneidet die Tangente im Hochpunkt die $x$-Achse? (Erwartet: keine / $\\infty$ ist nicht möglich, also geben Sie $x = 1$ ein als Stelle, an der die horizontale Hochpunkt-Tangente liegt.)',
        answer: 1,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `Im Hochpunkt gilt $f'(1) = 0$, die Tangente ist horizontal: $y = 5$. Diese schneidet die $x$-Achse nicht; formal ist aber der Hochpunkt-Fußpunkt bei $x = 1$.`,
      },
    ],
    hints: [
      `Vollständige Kurvendiskussion: $f'$, $f''$, Nullstellen von $f'$ untersuchen, Vorzeichenwechsel prüfen.`,
      `Tangentengleichung: $y - y_0 = f'(x_0)(x - x_0)$.`,
    ],
    wrapUp: `Typisches Klausur-Muster: Funktion dritten Grades $\\Rightarrow$ zwei Extremstellen, eine Wendestelle.`,
    tags: ['kurvendiskussion', 'polynom', 'extrema'],
  },
  {
    id: 'pr-abl-2',
    topicId: 'ableitung',
    title: 'Produkt- und Kettenregel kombiniert',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Gegeben:
$$g(x) = x^2 \\cdot e^{-2x}.$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Berechnen Sie $g\'(x)$ und werten Sie an $x = 1$ aus. Geben Sie $g\'(1)$ als Dezimalzahl auf 4 Nachkommastellen ein.',
        answer: 0.0,
        alternates: ['0'],
        unit: '',
        tolerance: 0.01,
        points: 3,
        explanation: `Produkt- + Kettenregel: $g'(x) = 2x\\,e^{-2x} + x^2 \\cdot (-2)e^{-2x} = e^{-2x}(2x - 2x^2)$. An $x=1$: $e^{-2}(2-2) = 0$.`,
      },
      {
        id: 'b',
        prompt: 'b) Ist $x=1$ eine Extremstelle? Klassifizieren Sie: $1$ = Hochpunkt, $2$ = Tiefpunkt, $0$ = Sattelpunkt.',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 3,
        explanation: `$g''(x) = e^{-2x}(2 - 8x + 4x^2)$. An $x=1$: $e^{-2}(2-8+4) = -2e^{-2} < 0$, also Hochpunkt.`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie den Funktionswert $g(1)$ auf 4 Nachkommastellen.',
        answer: 0.1353,
        unit: '',
        tolerance: 0.002,
        points: 2,
        explanation: `$g(1) = 1\\cdot e^{-2} = e^{-2} \\approx 0{,}1353$. Der Hochpunkt liegt also bei $(1;0{,}1353)$.`,
      },
    ],
    hints: [
      'Faktor $e^{-2x}$ ausklammern, erspart Rechenfehler.',
      'Vorzeichenwechsel von $g\'$ um $x=1$ herum prüfen, dann ist keine Zweite-Ableitung-Rechnung nötig.',
    ],
    tags: ['kettenregel', 'produktregel', 'exponential'],
  },
  {
    id: 'pr-abl-3',
    topicId: 'ableitung',
    title: 'Tangente, Normale und Linearisierung',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Für die Funktion
$$f(x) = \\sqrt{x} + \\ln(x), \\quad x > 0,$$
ist die Stelle $x_0 = 1$ betrachtet.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Bestimmen Sie $f(1)$.',
        answer: 1,
        unit: '',
        tolerance: 1e-6,
        points: 1,
        explanation: `$f(1) = \\sqrt{1} + \\ln 1 = 1 + 0 = 1$.`,
      },
      {
        id: 'b',
        prompt: 'b) Berechnen Sie $f\'(1)$.',
        answer: 1.5,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `$f'(x) = \\tfrac{1}{2\\sqrt{x}} + \\tfrac{1}{x}$. An $x = 1$: $\\tfrac12 + 1 = \\tfrac{3}{2} = 1{,}5$.`,
      },
      {
        id: 'c',
        prompt: 'c) Wie lautet die Steigung der Normalen in $x_0 = 1$?',
        answer: -0.6667,
        alternates: ['-2/3'],
        unit: '',
        tolerance: 0.01,
        points: 3,
        explanation: `Normalensteigung $m_N = -1/f'(1) = -1/1{,}5 = -2/3 \\approx -0{,}667$.`,
      },
      {
        id: 'd',
        prompt: 'd) Näherungswert von $f(1{,}05)$ über die Tangente (Linearisierung)?',
        answer: 1.075,
        unit: '',
        tolerance: 0.005,
        points: 3,
        explanation: `$f(1{,}05) \\approx f(1) + f'(1)\\cdot 0{,}05 = 1 + 1{,}5\\cdot 0{,}05 = 1{,}075$. Exakter Wert: $\\sqrt{1{,}05}+\\ln(1{,}05) \\approx 1{,}0247 + 0{,}04879 \\approx 1{,}0735$.`,
      },
    ],
    hints: [
      'Normalensteigung = negatives Reziprokes der Tangentensteigung.',
      'Linearisierung: $f(x_0+h) \\approx f(x_0) + h\\,f\'(x_0)$.',
    ],
    tags: ['tangente', 'normale', 'linearisierung'],
  },
]
