import type { PracticeExercise } from '@/types/practice'

export const algebraPractice: PracticeExercise[] = [
  {
    id: 'pr-alg-1',
    topicId: 'algebra',
    title: 'Quadratische Gleichung und Funktionsanalyse',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 12,
    context: `Gegeben sei die quadratische Funktion
$$f(x) = 2x^2 - 8x + 6.$$
Bestimmen Sie die Nullstellen, den Scheitelpunkt und den Funktionswert an der Stelle $x = 3$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Berechnen Sie die kleinere Nullstelle $x_1$ der Funktion.',
        answer: 1,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `Mit der großen Lösungsformel: $x_{1,2} = \\frac{8 \\pm \\sqrt{64 - 48}}{4} = \\frac{8 \\pm 4}{4}$. Also $x_1 = 1$, $x_2 = 3$.`,
      },
      {
        id: 'b',
        prompt: 'b) Bestimmen Sie die $x$-Koordinate des Scheitels $x_S$.',
        answer: 2,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `Scheitel liegt in der Mitte der Nullstellen: $x_S = \\frac{1+3}{2} = 2$. Alternativ $x_S = -\\frac{b}{2a} = \\frac{8}{4} = 2$.`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie den Scheitel-Funktionswert $y_S = f(x_S)$.',
        answer: -2,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$f(2) = 2\\cdot 4 - 16 + 6 = -2$. Der Scheitel ist also $(2;-2)$, die Parabel ist nach oben geöffnet.`,
      },
      {
        id: 'd',
        prompt: 'd) Werten Sie $f(3)$ aus.',
        answer: 0,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$f(3) = 18 - 24 + 6 = 0$ — bestätigt, dass $x=3$ eine Nullstelle ist.`,
      },
    ],
    hints: [
      'Große Lösungsformel: $x_{1,2} = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}$.',
      'Scheitel-x-Wert liegt exakt mittig zwischen den Nullstellen, falls sie reell sind.',
    ],
    wrapUp: `Plausibilität: Parabel $2x^2-8x+6$ öffnet nach oben ($a>0$), hat zwei reelle Nullstellen, Diskriminante $16>0$ bestätigt das.`,
    tags: ['quadratisch', 'scheitel', 'nullstellen'],
  },
  {
    id: 'pr-alg-2',
    topicId: 'algebra',
    title: 'Bruchgleichung mit Definitionsbereich',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Gegeben ist die Bruchgleichung
$$\\frac{2}{x-1} + \\frac{3}{x+2} = 1.$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Geben Sie die kleinere der beiden ausgeschlossenen Stellen des Definitionsbereichs an ($x =$ ?).',
        answer: -2,
        unit: '',
        tolerance: 1e-6,
        points: 2,
        explanation: `Die Nenner $x-1$ und $x+2$ dürfen nicht Null werden: $x \\neq 1$ und $x \\neq -2$. Die kleinere Stelle ist $-2$.`,
      },
      {
        id: 'b',
        prompt: 'b) Multiplizieren Sie mit dem Hauptnenner $(x-1)(x+2)$ und bringen Sie die Gleichung in die Form $x^2 + px + q = 0$. Geben Sie $p$ an.',
        answer: -4,
        unit: '',
        tolerance: 1e-6,
        points: 3,
        explanation: `$2(x+2) + 3(x-1) = (x-1)(x+2) = x^2 + x - 2$. Links vereinfacht zu $5x + 1$. Umstellen: $x^2 - 4x - 3 = 0$, also $p = -4$ und $q = -3$.`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie die kleinere Lösung der resultierenden quadratischen Gleichung (gerundet auf 3 Nachkommastellen).',
        answer: -0.646,
        alternates: ['2 - sqrt(7)'],
        unit: '',
        tolerance: 0.01,
        points: 3,
        explanation: `Aus $x^2 - 4x - 3 = 0$ folgt $x_{1,2} = 2 \\pm \\sqrt{7}$. Kleinere Lösung: $2 - \\sqrt{7} \\approx -0{,}6458$.`,
      },
      {
        id: 'd',
        prompt: 'd) Liegt die kleinere Lösung im Definitionsbereich (1 = ja, 0 = nein)?',
        answer: 1,
        unit: '',
        tolerance: 0.5,
        points: 2,
        explanation: `$-0{,}646 \\neq 1$ und $\\neq -2$, also im Definitionsbereich. Beide Lösungen $2\\pm\\sqrt{7}$ sind gültig.`,
      },
    ],
    hints: [
      'Definitionsbereich ZUERST notieren, sonst werden Scheinlösungen übersehen.',
      'Nach dem Aufmultiplizieren quadratische Normalform anstreben.',
    ],
    wrapUp: `In Klausur-Aufgaben zu Bruchgleichungen werden Punkte oft nicht nur fürs Lösen, sondern für die ausdrückliche Nennung des Definitionsbereichs und die Überprüfung vergeben.`,
    tags: ['bruchgleichung', 'definitionsbereich'],
  },
  {
    id: 'pr-alg-3',
    topicId: 'algebra',
    title: 'Exponential- und Logarithmusgleichung',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Ein Kondensator entlädt sich gemäß
$$U(t) = U_0 \\cdot e^{-t/\\tau}, \\quad U_0 = 12~\\text{V}, \\; \\tau = 50~\\text{ms}.$$
Bestimmen Sie den Spannungsverlauf zu gegebenen Zeiten.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Wie groß ist die Spannung nach $t = 100~\\text{ms}$?',
        answer: 1.624,
        unit: 'V',
        tolerance: 0.02,
        points: 3,
        explanation: `$U(100\\,\\text{ms}) = 12\\cdot e^{-2} = 12\\cdot 0{,}1353 \\approx 1{,}624~\\text{V}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Nach welcher Zeit (in ms) ist die Spannung auf $U = 3~\\text{V}$ abgefallen?',
        answer: 69.3,
        unit: 'ms',
        tolerance: 0.5,
        points: 3,
        explanation: `$3 = 12\\cdot e^{-t/50}\\Rightarrow e^{-t/50}=0{,}25 \\Rightarrow -t/50 = \\ln(0{,}25) = -1{,}3863 \\Rightarrow t \\approx 69{,}3~\\text{ms}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Welchen Bruchteil seiner Anfangsspannung hat der Kondensator nach einer Zeitkonstanten $\\tau$ noch (Antwort als Dezimalzahl, 3 Nachkommastellen)?',
        answer: 0.368,
        unit: '',
        tolerance: 0.005,
        points: 2,
        explanation: `$U(\\tau)/U_0 = e^{-1} \\approx 0{,}368$. Merkwert für jedes RC-/LR-/Zerfalls-System.`,
      },
    ],
    hints: [
      'Trennen Sie Exponential- und Nicht-Exponentialteile vor dem Logarithmieren.',
      '$\\ln(1/4) = -\\ln 4 = -2\\ln 2$.',
    ],
    tags: ['exponential', 'logarithmus', 'entladung'],
  },
]
