import type { PracticeExercise } from '@/types/practice'

export const dglPractice: PracticeExercise[] = [
  {
    id: 'pr-dgl-1',
    topicId: 'differentialgleichungen',
    title: 'Lineare DGL 1. Ordnung mit Anfangsbedingung',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 12,
    context: `Ein Tank mit $V = 200~\\text{L}$ Wasser wird mit Salzlösung versorgt. Die Salzmasse $m(t)$ genügt
$$\\dot m(t) + \\tfrac{1}{50}\\, m(t) = 4 ~[\\text{g/min}], \\quad m(0) = 0.$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Wie lautet die stationäre Lösung $m_\\infty$ (in g)?',
        answer: 200,
        unit: 'g',
        tolerance: 1e-3,
        points: 2,
        explanation: `Stationärer Zustand: $\\dot m = 0 \\Rightarrow m_\\infty/50 = 4 \\Rightarrow m_\\infty = 200~\\text{g}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Homogene Lösung hat die Form $m_h = C\\,e^{-t/\\tau}$. Geben Sie $\\tau$ (in min) an.',
        answer: 50,
        unit: 'min',
        tolerance: 1e-3,
        points: 2,
        explanation: `Koeffizient vor $m$ ist $1/50$, also $\\tau = 50~\\text{min}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Wie lautet die Konstante $C$ in der Gesamtlösung $m(t) = m_\\infty + C\\,e^{-t/50}$?',
        answer: -200,
        unit: 'g',
        tolerance: 1e-3,
        points: 3,
        explanation: `$m(0) = 200 + C = 0 \\Rightarrow C = -200$. Vollständig: $m(t) = 200(1 - e^{-t/50})$.`,
      },
      {
        id: 'd',
        prompt: 'd) Wie viel Salz (in g) ist nach $t = 100~\\text{min}$ im Tank?',
        answer: 172.93,
        unit: 'g',
        tolerance: 0.3,
        points: 3,
        explanation: `$m(100) = 200(1 - e^{-2}) = 200(1 - 0{,}1353) \\approx 172{,}93~\\text{g}$.`,
      },
    ],
    hints: [
      'Lineare inhomogene DGL $\\dot y + ay = b$ hat allgemeine Lösung $y = b/a + C\\,e^{-at}$.',
      'Zeitkonstante $\\tau$ ist Kehrwert des Koeffizienten vor der Funktion.',
    ],
    tags: ['lineare-dgl', 'zeitkonstante'],
  },
  {
    id: 'pr-dgl-2',
    topicId: 'differentialgleichungen',
    title: 'Homogene DGL 2. Ordnung mit charakteristischem Polynom',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Ein mechanischer Schwinger wird beschrieben durch
$$\\ddot x + 4\\dot x + 13 x = 0, \\quad x(0) = 2, \\; \\dot x(0) = 0.$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Welche Diskriminante hat das charakteristische Polynom $\\lambda^2 + 4\\lambda + 13 = 0$?',
        answer: -36,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `Diskriminante $D = 16 - 52 = -36 < 0$, also komplexe Eigenwerte $\\Rightarrow$ gedämpfte Schwingung.`,
      },
      {
        id: 'b',
        prompt: 'b) Bestimmen Sie den Dämpfungsexponenten $\\delta$ (mit $x(t) = e^{-\\delta t}(A\\cos\\omega t + B\\sin\\omega t)$).',
        answer: 2,
        unit: '1/s',
        tolerance: 1e-3,
        points: 2,
        explanation: `$\\lambda = -2 \\pm 3i$, also $\\delta = 2$, $\\omega = 3$.`,
      },
      {
        id: 'c',
        prompt: 'c) Bestimmen Sie $\\omega$ (die Kreisfrequenz der gedämpften Schwingung).',
        answer: 3,
        unit: 'rad/s',
        tolerance: 1e-3,
        points: 2,
        explanation: `Imaginärteil der Eigenwerte: $\\sqrt{36}/2 = 3$.`,
      },
      {
        id: 'd',
        prompt: 'd) Bestimmen Sie die Konstante $B$ (Amplitude der Sinus-Komponente).',
        answer: 1.333,
        alternates: ['4/3'],
        unit: '',
        tolerance: 0.01,
        points: 4,
        explanation: `$x(0) = A = 2$. $\\dot x = e^{-2t}(-2A\\cos + 2B\\cdot ?... )$. Rechnung: $\\dot x(0) = -2A + 3B = 0 \\Rightarrow B = 2A/3 = 4/3 \\approx 1{,}333$.`,
      },
    ],
    hints: [
      'Komplexe Eigenwerte $\\lambda = -\\delta \\pm i\\omega$ liefern $x(t) = e^{-\\delta t}(A\\cos\\omega t + B\\sin\\omega t)$.',
      'Anfangsbedingungen: erst $x(0)$, dann $\\dot x(0)$.',
    ],
    wrapUp: `Gedämpfte Schwingung mit Abklingzeit $1/\\delta = 0{,}5~\\text{s}$ und Periode $2\\pi/\\omega \\approx 2{,}09~\\text{s}$.`,
    tags: ['schwingung', 'dämpfung', 'charakteristisches-polynom'],
  },
  {
    id: 'pr-dgl-3',
    topicId: 'differentialgleichungen',
    title: 'Trennung der Variablen',
    difficulty: 'klausur-einstieg',
    points: 6,
    estimatedMinutes: 6,
    context: `Gegeben ist die DGL $\\dot y = y\\cdot x$ mit $y(0) = 3$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Trennen Sie die Variablen und integrieren Sie. Geben Sie die Lösung bei $x=0$ an — das entspricht $y(0)$.',
        answer: 3,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$dy/y = x\\,dx \\Rightarrow \\ln|y| = x^2/2 + C$, also $y = K\\,e^{x^2/2}$. $y(0) = K = 3$.`,
      },
      {
        id: 'b',
        prompt: 'b) Wie groß ist $y(2)$?',
        answer: 22.17,
        unit: '',
        tolerance: 0.1,
        points: 2,
        explanation: `$y(2) = 3\\,e^{2} = 3\\cdot 7{,}389 \\approx 22{,}17$.`,
      },
      {
        id: 'c',
        prompt: 'c) Bei welchem $x > 0$ hat $y$ den Wert $y = 12$? (auf 3 Nachkommastellen)',
        answer: 1.666,
        unit: '',
        tolerance: 0.02,
        points: 2,
        explanation: `$12 = 3\\,e^{x^2/2} \\Rightarrow e^{x^2/2} = 4 \\Rightarrow x^2 = 2\\ln 4 = 4\\ln 2 \\approx 2{,}7726 \\Rightarrow x \\approx 1{,}665$.`,
      },
    ],
    hints: [
      'Trennung: alles mit $y$ links, alles mit $x$ rechts.',
      'Integrationskonstante aus der Anfangsbedingung bestimmen.',
    ],
    tags: ['trennung-der-variablen'],
  },
]
