import type { PracticeExercise } from '@/types/practice'

export const elektrotechnikPractice: PracticeExercise[] = [
  {
    id: 'pr-et-1',
    topicId: 'elektrotechnik',
    title: 'Gleichstromnetz — Kirchhoff und Leistung',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Eine Spannungsquelle $U = 24~\\text{V}$ (Innenwiderstand vernachlässigt) versorgt zwei parallel geschaltete Widerstände $R_1 = 8~\\Omega$ und $R_2 = 12~\\Omega$, die ihrerseits in Reihe mit $R_3 = 3{,}2~\\Omega$ verbunden sind.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Parallelwiderstand $R_{12} = R_1 R_2/(R_1+R_2)$ (in $\\Omega$)?',
        answer: 4.8,
        unit: 'Ω',
        tolerance: 0.02,
        points: 2,
        explanation: `$R_{12} = 8\\cdot 12/20 = 96/20 = 4{,}8~\\Omega$.`,
      },
      {
        id: 'b',
        prompt: 'b) Gesamtwiderstand $R_{ges} = R_{12} + R_3$ (in $\\Omega$)?',
        answer: 8,
        unit: 'Ω',
        tolerance: 0.05,
        points: 1,
        explanation: `$R_{ges} = 4{,}8 + 3{,}2 = 8~\\Omega$.`,
      },
      {
        id: 'c',
        prompt: 'c) Gesamtstrom $I = U/R_{ges}$ (in A)?',
        answer: 3,
        unit: 'A',
        tolerance: 0.02,
        points: 2,
        explanation: `$I = 24/8 = 3~\\text{A}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Strom durch $R_1$ (in A)? (Stromteiler: $I_1 = I\\cdot R_2/(R_1+R_2)$)',
        answer: 1.8,
        unit: 'A',
        tolerance: 0.02,
        points: 2,
        explanation: `$I_1 = 3\\cdot 12/20 = 1{,}8~\\text{A}$.`,
      },
      {
        id: 'e',
        prompt: 'e) Gesamte Verlustleistung $P_{ges}$ (in W)?',
        answer: 72,
        unit: 'W',
        tolerance: 0.5,
        points: 3,
        explanation: `$P = UI = 24\\cdot 3 = 72~\\text{W}$. Kontrolle: $I^2 R_{ges} = 9\\cdot 8 = 72~\\text{W}$.`,
      },
    ],
    hints: [
      'Parallelschaltung: Leitwerte addieren sich ($1/R = \\sum 1/R_i$).',
      'Stromteiler: $I_k = I\\cdot R_{\\text{gegenüber}}/\\sum R$.',
    ],
    tags: ['kirchhoff', 'gleichstrom', 'leistung'],
  },
  {
    id: 'pr-et-2',
    topicId: 'elektrotechnik',
    title: 'RC-Tiefpass — Grenzfrequenz und Phase',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Ein passiver RC-Tiefpass mit $R = 10~\\text{k}\\Omega$ und $C = 100~\\text{nF}$ wird mit einer Sinusspannung $u_e(t) = \\hat U\\sin(2\\pi f t)$ angeregt.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Grenzfrequenz $f_g = 1/(2\\pi R C)$ (in Hz)?',
        answer: 159.15,
        unit: 'Hz',
        tolerance: 0.5,
        points: 3,
        explanation: `$f_g = 1/(2\\pi\\cdot 10^4\\cdot 10^{-7}) = 1/(2\\pi\\cdot 10^{-3}) \\approx 159{,}15~\\text{Hz}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Amplitudenverhältnis $|H|$ bei $f = f_g$?',
        answer: 0.7071,
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `Bei der Grenzfrequenz gilt $|H| = 1/\\sqrt 2 \\approx 0{,}7071$ ($-3~\\text{dB}$).`,
      },
      {
        id: 'c',
        prompt: 'c) Phasenverschiebung $\\varphi$ bei $f = f_g$ (in Grad)?',
        answer: -45,
        unit: '°',
        tolerance: 0.5,
        points: 2,
        explanation: `$\\varphi = -\\arctan(\\omega RC) = -\\arctan(1) = -45°$.`,
      },
      {
        id: 'd',
        prompt: 'd) Amplitudenverhältnis bei $f = 10\\,f_g$ (in dB, negativ)?',
        answer: -20.04,
        unit: 'dB',
        tolerance: 0.2,
        points: 3,
        explanation: `$|H| = 1/\\sqrt{1 + 100} \\approx 1/\\sqrt{101} \\approx 0{,}0995$. $20\\log_{10}(0{,}0995) \\approx -20{,}04~\\text{dB}$.`,
      },
    ],
    hints: [
      'RC-Tiefpass: $|H(f)| = 1/\\sqrt{1 + (f/f_g)^2}$, $\\varphi = -\\arctan(f/f_g)$.',
      'Jede Dekade über $f_g$ bedeutet einen Abfall von -20 dB.',
    ],
    tags: ['rc-glied', 'tiefpass', 'bode'],
  },
  {
    id: 'pr-et-3',
    topicId: 'elektrotechnik',
    title: 'Drehstrom — Sternschaltung, Leistung',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Ein symmetrischer Drehstromverbraucher in Sternschaltung hat je Strang $R = 20~\\Omega$ und $X_L = 15~\\Omega$ (induktiv). Netzspannung (Außenleiter) $U_{L} = 400~\\text{V}$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Strangspannung $U_{Str}$ (in V)?',
        answer: 230.94,
        unit: 'V',
        tolerance: 0.5,
        points: 2,
        explanation: `Stern: $U_{Str} = U_L/\\sqrt 3 = 400/1{,}732 \\approx 230{,}94~\\text{V}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Scheinwiderstand $Z$ je Strang (in $\\Omega$)?',
        answer: 25,
        unit: 'Ω',
        tolerance: 0.1,
        points: 2,
        explanation: `$Z = \\sqrt{R^2 + X_L^2} = \\sqrt{400 + 225} = \\sqrt{625} = 25~\\Omega$.`,
      },
      {
        id: 'c',
        prompt: 'c) Strangstrom $I_{Str}$ (in A)?',
        answer: 9.238,
        unit: 'A',
        tolerance: 0.05,
        points: 2,
        explanation: `$I_{Str} = U_{Str}/Z = 230{,}94/25 \\approx 9{,}238~\\text{A}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Gesamtwirkleistung $P = 3 U_{Str} I_{Str}\\cos\\varphi$ (in W)? $\\cos\\varphi = R/Z$.',
        answer: 5120,
        unit: 'W',
        tolerance: 20,
        points: 2,
        explanation: `$\\cos\\varphi = 20/25 = 0{,}8$. $P = 3\\cdot 230{,}94\\cdot 9{,}238\\cdot 0{,}8 \\approx 5120~\\text{W}$. Alternativ $P = 3 I^2 R = 3\\cdot 85{,}3\\cdot 20 \\approx 5120~\\text{W}$.`,
      },
    ],
    hints: [
      'Stern: $U_L = \\sqrt 3\\,U_{Str}$; $I_L = I_{Str}$.',
      'Wirkleistung: $P = \\sqrt 3\\,U_L I_L\\cos\\varphi$ (symmetrisch).',
    ],
    tags: ['drehstrom', 'stern', 'wirkleistung'],
  },
]
