import type { PracticeExercise } from '@/types/practice'

export const festigkeitslehrePractice: PracticeExercise[] = [
  {
    id: 'pr-fest-1',
    topicId: 'festigkeitslehre',
    title: 'Zugstab — Spannung, Dehnung, Verlängerung',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Ein runder Zugstab aus S355 hat die Länge $L = 2~\\text{m}$ und den Durchmesser $d = 12~\\text{mm}$. Er wird mit $F = 18~\\text{kN}$ belastet. Materialkennwerte: $E = 210~\\text{GPa}$, $R_e = 355~\\text{MPa}$, Sicherheit $S = 1{,}5$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Querschnittsfläche $A$ (in mm²)?',
        answer: 113.1,
        unit: 'mm²',
        tolerance: 0.3,
        points: 2,
        explanation: `$A = \\pi d^2/4 = \\pi\\cdot 144/4 = 36\\pi \\approx 113{,}1~\\text{mm}^2$.`,
      },
      {
        id: 'b',
        prompt: 'b) Zugspannung $\\sigma$ (in MPa = N/mm²)?',
        answer: 159.2,
        unit: 'MPa',
        tolerance: 0.5,
        points: 3,
        explanation: `$\\sigma = F/A = 18000/113{,}1 \\approx 159{,}2~\\text{N/mm}^2 = 159{,}2~\\text{MPa}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Verlängerung $\\Delta L$ (in mm)?',
        answer: 1.516,
        unit: 'mm',
        tolerance: 0.02,
        points: 3,
        explanation: `$\\Delta L = \\frac{FL}{EA} = \\frac{18000\\cdot 2000}{210000\\cdot 113{,}1} \\approx 1{,}516~\\text{mm}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Hält der Stab gegenüber der zulässigen Spannung $\\sigma_{zul} = R_e/S$? ($1$ = ja, $0$ = nein)',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 2,
        explanation: `$\\sigma_{zul} = 355/1{,}5 \\approx 236{,}7~\\text{MPa}$. Da $\\sigma = 159{,}2 < 236{,}7$, hält der Stab.`,
      },
    ],
    hints: [
      'Einheiten beachten: MPa = N/mm² → Rechnen in mm, N und MPa erspart Umrechnen.',
      '$\\Delta L = FL/(EA)$ — klassische Formel des Hooke-Zugs.',
    ],
    tags: ['zugstab', 'hookesches-gesetz'],
  },
  {
    id: 'pr-fest-2',
    topicId: 'festigkeitslehre',
    title: 'Biegung — maximale Biegespannung',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Ein Rechteckbalken $b\\times h = 40\\times 80~\\text{mm}$ ist einseitig eingespannt (Kragarm, $L = 1{,}2~\\text{m}$) und wird am freien Ende durch $F = 1{,}5~\\text{kN}$ nach unten belastet.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Axiales Flächenträgheitsmoment $I_y$ (in mm⁴).',
        answer: 1706667,
        unit: 'mm⁴',
        tolerance: 2000,
        points: 3,
        explanation: `$I_y = bh^3/12 = 40\\cdot 80^3/12 = 40\\cdot 512000/12 = 1.706.667~\\text{mm}^4$.`,
      },
      {
        id: 'b',
        prompt: 'b) Widerstandsmoment $W_y$ (in mm³)?',
        answer: 42667,
        unit: 'mm³',
        tolerance: 50,
        points: 2,
        explanation: `$W_y = I_y/(h/2) = 1.706.667/40 \\approx 42.667~\\text{mm}^3$. Oder direkt: $bh^2/6 = 40\\cdot 6400/6 \\approx 42.667$.`,
      },
      {
        id: 'c',
        prompt: 'c) Maximales Biegemoment im Einspannpunkt (in Nm)?',
        answer: 1800,
        unit: 'Nm',
        tolerance: 5,
        points: 2,
        explanation: `$M_{max} = F\\cdot L = 1500\\cdot 1{,}2 = 1800~\\text{Nm}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Maximale Biegespannung $\\sigma_b$ (in MPa)?',
        answer: 42.19,
        unit: 'MPa',
        tolerance: 0.3,
        points: 3,
        explanation: `$\\sigma_b = M/W = 1.800.000/42.667 \\approx 42{,}19~\\text{N/mm}^2$.`,
      },
    ],
    hints: [
      '$\\sigma_b = M_b / W_y$ — wobei $W_y$ vom Querschnitt abhängt.',
      'Bei Rechteckquerschnitt: $W = bh^2/6$.',
    ],
    tags: ['biegung', 'widerstandsmoment', 'kragarm'],
  },
  {
    id: 'pr-fest-3',
    topicId: 'festigkeitslehre',
    title: 'Torsion einer Welle',
    difficulty: 'klausur-plus',
    points: 12,
    estimatedMinutes: 12,
    context: `Eine Vollwelle aus Stahl ($G = 80~\\text{GPa}$) überträgt eine Leistung $P = 50~\\text{kW}$ bei $n = 1500~\\text{min}^{-1}$. Durchmesser $d = 35~\\text{mm}$, Länge $L = 0{,}8~\\text{m}$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Winkelgeschwindigkeit $\\omega$ (in rad/s)?',
        answer: 157.08,
        unit: 'rad/s',
        tolerance: 0.5,
        points: 2,
        explanation: `$\\omega = 2\\pi n / 60 = 2\\pi\\cdot 1500/60 = 50\\pi \\approx 157{,}08~\\text{rad/s}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Torsionsmoment $T$ (in Nm)?',
        answer: 318.3,
        unit: 'Nm',
        tolerance: 1,
        points: 3,
        explanation: `$T = P/\\omega = 50000/157{,}08 \\approx 318{,}31~\\text{Nm}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Polares Widerstandsmoment $W_p$ (in mm³) für Vollkreis.',
        answer: 8418.5,
        unit: 'mm³',
        tolerance: 30,
        points: 3,
        explanation: `$W_p = \\pi d^3/16 = \\pi\\cdot 42875/16 \\approx 8418{,}5~\\text{mm}^3$.`,
      },
      {
        id: 'd',
        prompt: 'd) Maximale Schubspannung $\\tau_{max}$ (in MPa)?',
        answer: 37.81,
        unit: 'MPa',
        tolerance: 0.3,
        points: 2,
        explanation: `$\\tau_{max} = T/W_p = 318310/8418{,}5 \\approx 37{,}81~\\text{N/mm}^2$.`,
      },
      {
        id: 'e',
        prompt: 'e) Verdrehwinkel $\\varphi$ (in rad, Vollkreis: $I_p = \\pi d^4/32$).',
        answer: 0.0216,
        unit: 'rad',
        tolerance: 0.0005,
        points: 2,
        explanation: `$I_p = \\pi d^4/32 = \\pi\\cdot 35^4/32 \\approx 147.324~\\text{mm}^4$. $\\varphi = TL/(G I_p) = 318310\\cdot 800/(80000\\cdot 147324) \\approx 0{,}0216~\\text{rad}$ ($\\approx 1{,}24°$).`,
      },
    ],
    hints: [
      '$T = P/\\omega$, wenn $\\omega$ in rad/s.',
      'Polare Momente: $I_p = \\pi d^4/32$, $W_p = \\pi d^3/16$ für Vollkreis.',
    ],
    tags: ['torsion', 'welle', 'schubspannung'],
  },
]
