import type { PracticeExercise } from '@/types/practice'

export const fluidmechanikPractice: PracticeExercise[] = [
  {
    id: 'pr-flu-1',
    topicId: 'fluidmechanik',
    title: 'Bernoulli — Rohrverengung',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Wasser ($\\rho = 1000~\\text{kg/m}^3$) strömt durch ein horizontales Rohr. Am Querschnitt 1: $d_1 = 80~\\text{mm}$, $p_1 = 2{,}5~\\text{bar}$, $v_1 = 2~\\text{m/s}$. Am Querschnitt 2: $d_2 = 40~\\text{mm}$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Volumenstrom $\\dot V$ (in L/s)?',
        answer: 10.05,
        unit: 'L/s',
        tolerance: 0.05,
        points: 2,
        explanation: `$A_1 = \\pi d_1^2/4 = \\pi\\cdot 0{,}08^2/4 \\approx 5{,}027\\cdot 10^{-3}~\\text{m}^2$. $\\dot V = A_1 v_1 \\approx 0{,}01005~\\text{m}^3/\\text{s} = 10{,}05~\\text{L/s}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Geschwindigkeit $v_2$ an der Verengung (in m/s)?',
        answer: 8,
        unit: 'm/s',
        tolerance: 0.05,
        points: 3,
        explanation: `Kontinuität: $A_1 v_1 = A_2 v_2$, Flächen wie $d^2$, also $v_2 = v_1 (d_1/d_2)^2 = 2\\cdot 4 = 8~\\text{m/s}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Druck $p_2$ an der Verengung (in bar)?',
        answer: 2.2,
        unit: 'bar',
        tolerance: 0.02,
        points: 4,
        explanation: `Bernoulli horizontal: $p_2 = p_1 + \\tfrac\\rho 2(v_1^2 - v_2^2) = 2{,}5\\cdot 10^5 + 500\\cdot(4-64) = 2{,}5\\cdot 10^5 - 3\\cdot 10^4 = 2{,}2\\cdot 10^5~\\text{Pa} = 2{,}2~\\text{bar}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Wie groß müsste die gemessene Druckdifferenz sein, wenn $v_2 = 10~\\text{m/s}$ wäre? ($\\Delta p = p_1 - p_2$ in kPa)',
        answer: 48,
        unit: 'kPa',
        tolerance: 0.5,
        points: 1,
        explanation: `$\\Delta p = \\tfrac{\\rho}{2}(v_2^2 - v_1^2) = 500\\cdot(100-4) = 48.000~\\text{Pa} = 48~\\text{kPa}$.`,
      },
    ],
    hints: [
      'Kontinuität: $A\\cdot v = $ konst. → Geschwindigkeit steigt bei Verengung.',
      'Bernoulli (inkompressibel, verlustfrei, horizontal): $p + \\tfrac\\rho 2 v^2 = $ konst.',
    ],
    tags: ['bernoulli', 'kontinuität', 'rohr'],
  },
  {
    id: 'pr-flu-2',
    topicId: 'fluidmechanik',
    title: 'Reynoldszahl und Rohrreibungsverlust',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `In einer Rohrleitung $d = 50~\\text{mm}$, $L = 20~\\text{m}$ strömt Öl ($\\rho = 850~\\text{kg/m}^3$, $\\nu = 80\\cdot 10^{-6}~\\text{m}^2/\\text{s}$) mit $v = 1{,}5~\\text{m/s}$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Reynoldszahl $\\operatorname{Re}$?',
        answer: 937.5,
        unit: '',
        tolerance: 5,
        points: 3,
        explanation: `$\\operatorname{Re} = v d/\\nu = 1{,}5\\cdot 0{,}05/80\\cdot 10^{-6} = 937{,}5$.`,
      },
      {
        id: 'b',
        prompt: 'b) Ist die Strömung laminar ($<$ 2300)? $1$ = ja, $0$ = nein.',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 1,
        explanation: `$\\operatorname{Re} = 937{,}5 < 2300 \\Rightarrow$ laminar.`,
      },
      {
        id: 'c',
        prompt: 'c) Rohrreibungszahl laminar: $\\lambda = 64/\\operatorname{Re}$. Zahlenwert?',
        answer: 0.0683,
        unit: '',
        tolerance: 0.001,
        points: 2,
        explanation: `$\\lambda = 64/937{,}5 = 0{,}06827$.`,
      },
      {
        id: 'd',
        prompt: 'd) Druckverlust $\\Delta p_V$ (in kPa) mit $\\Delta p_V = \\lambda \\frac{L}{d}\\frac{\\rho}{2}v^2$.',
        answer: 26.1,
        unit: 'kPa',
        tolerance: 0.3,
        points: 4,
        explanation: `$\\rho v^2/2 = 850\\cdot 2{,}25/2 = 956{,}25\\,\\text{Pa}$. $\\lambda\\cdot L/d = 0{,}06827\\cdot 400 = 27{,}31$. $\\Delta p_V = 27{,}31\\cdot 956{,}25 \\approx 26113\\,\\text{Pa} \\approx 26{,}1\\,\\text{kPa}$.`,
      },
    ],
    hints: [
      '$\\operatorname{Re} = vd/\\nu$ ist dimensionslos.',
      'Laminar: $\\lambda = 64/\\operatorname{Re}$; turbulent: Colebrook oder Moody-Diagramm.',
    ],
    tags: ['reynolds', 'laminar', 'druckverlust'],
  },
  {
    id: 'pr-flu-3',
    topicId: 'fluidmechanik',
    title: 'Kontinuität und statischer Druck',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 7,
    context: `Wasser ($\\rho = 1000\\,\\text{kg/m}^3$) strömt in einer horizontalen Leitung mit $d_1 = 80\\,\\text{mm}$ und $v_1 = 2\\,\\text{m/s}$. Die Leitung verengt sich auf $d_2 = 40\\,\\text{mm}$. Der Druck vor der Verengung beträgt $p_1 = 200\\,\\text{kPa}$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Geschwindigkeit $v_2$ nach der Verengung (in m/s).',
        answer: 8,
        unit: 'm/s',
        tolerance: 0.05,
        points: 3,
        explanation: `Kontinuitätsgleichung: $A_1 v_1 = A_2 v_2$. Mit $A\\propto d^2$: $v_2 = v_1\\,(d_1/d_2)^2 = 2\\cdot (80/40)^2 = 2\\cdot 4 = 8\\,\\text{m/s}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Dynamischer Druckanstieg $\\Delta p_{\\text{dyn}} = \\tfrac{\\rho}{2}(v_2^2 - v_1^2)$ (in kPa).',
        answer: 30,
        unit: 'kPa',
        tolerance: 0.5,
        points: 3,
        explanation: `$\\Delta p_{\\text{dyn}} = \\tfrac{1000}{2}\\,(64 - 4) = 500\\cdot 60 = 30{,}000\\,\\text{Pa} = 30\\,\\text{kPa}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Statischer Druck $p_2$ nach Bernoulli (verlustfrei, in kPa).',
        answer: 170,
        unit: 'kPa',
        tolerance: 0.5,
        points: 2,
        explanation: `Bernoulli horizontal: $p_1 + \\tfrac{\\rho}{2}v_1^2 = p_2 + \\tfrac{\\rho}{2}v_2^2 \\Rightarrow p_2 = p_1 - \\Delta p_{\\text{dyn}} = 200 - 30 = 170\\,\\text{kPa}$.`,
      },
    ],
    hints: [
      'Kontinuität: $A_1 v_1 = A_2 v_2$; für kreisrunde Rohre $A\\propto d^2$.',
      'Bernoulli ohne Höhenterm: $p + \\rho v^2/2 = \\text{const}$.',
      'Wo es schneller wird, sinkt der statische Druck — Venturi-Effekt.',
    ],
    wrapUp: `Plausibilität: $v$ vervierfacht sich, $v^2$ wird 16× größer, die Druckdifferenz ist signifikant. Reale Anlagen haben zusätzlich Reibungsverluste; dort wäre $p_2 < 170\\,\\text{kPa}$.`,
    tags: ['kontinuität', 'bernoulli', 'venturi'],
  },
]
