import type { PracticeExercise } from '@/types/practice'

export const fourierLaplacePractice: PracticeExercise[] = [
  {
    id: 'pr-fl-1',
    topicId: 'fourier-laplace',
    title: 'Laplace-Transformation einer DGL',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Gegeben: $\\ddot y + 3\\dot y + 2y = 0$, $y(0)=1$, $\\dot y(0)=0$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Algebraische Form nach Laplace: $s^2 Y + 3sY + 2Y - (s+3)\\cdot y(0) - \\dot y(0) = 0$ (mit Anfangsbedingungen vereinfacht). Koeffizient von $Y$ nennt man charakteristisches Polynom. Geben Sie dessen Wert bei $s = -1$ an.',
        answer: 0,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `Charakteristisches Polynom: $s^2 + 3s + 2 = (s+1)(s+2)$. Bei $s=-1$ gleich Null.`,
      },
      {
        id: 'b',
        prompt: 'b) Partialbruchzerlegung: $Y(s) = \\frac{s+3}{(s+1)(s+2)} = \\frac{A}{s+1} + \\frac{B}{s+2}$. Bestimmen Sie $A$.',
        answer: 2,
        unit: '',
        tolerance: 1e-3,
        points: 4,
        explanation: `Einsetzen $s = -1$: $A = \\frac{-1+3}{-1+2} = 2$. Analog $B = \\frac{-2+3}{-2+1} = -1$.`,
      },
      {
        id: 'c',
        prompt: 'c) $B$?',
        answer: -1,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `Siehe b): $B = -1$.`,
      },
      {
        id: 'd',
        prompt: 'd) Rücktransformation: $y(t) = A\\,e^{-t} + B\\,e^{-2t}$. Wert $y(1)$ auf 4 Nachkommastellen.',
        answer: 0.6002,
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `$y(1) = 2e^{-1} - e^{-2} = 2\\cdot 0{,}3679 - 0{,}1353 \\approx 0{,}7358 - 0{,}1353 \\approx 0{,}6005$.`,
      },
    ],
    hints: [
      'Laplace-Transformation macht aus linearen DGLs mit konstanten Koeffizienten algebraische Gleichungen.',
      'Typische Rücktransformationen: $1/(s+a) \\to e^{-at}$.',
    ],
    tags: ['laplace', 'partialbruch'],
  },
  {
    id: 'pr-fl-2',
    topicId: 'fourier-laplace',
    title: 'Fourierreihe eines Rechteckimpulses',
    difficulty: 'klausur-plus',
    points: 10,
    estimatedMinutes: 12,
    context: `Ein periodisches Rechtecksignal mit Periode $T = 2\\pi$:
$$f(t) = \\begin{cases} 1 & 0 \\le t < \\pi \\\\ -1 & \\pi \\le t < 2\\pi \\end{cases}$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Gleichanteil $a_0$ (Mittelwert über eine Periode)?',
        answer: 0,
        unit: '',
        tolerance: 1e-6,
        points: 2,
        explanation: `Symmetrisches Signal: $a_0 = 0$.`,
      },
      {
        id: 'b',
        prompt: 'b) Sind die $a_n$ alle Null? ($1$ = ja, $0$ = nein)',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 2,
        explanation: `Signal ist ungerade (bei passender Verschiebung), daher enthält die Reihe nur Sinus-Terme. Die $a_n$ verschwinden.`,
      },
      {
        id: 'c',
        prompt: 'c) Fourierkoeffizient $b_1$?',
        answer: 1.2732,
        alternates: ['4/pi'],
        unit: '',
        tolerance: 0.005,
        points: 3,
        explanation: `$b_n = \\frac{2}{\\pi}\\int_0^\\pi \\sin(nt)\\,dt - \\frac{2}{\\pi}\\int_\\pi^{2\\pi}\\sin(nt)\\,dt = \\frac{2(1-\\cos n\\pi)}{n\\pi}$. Für $n=1$: $b_1 = 4/\\pi \\approx 1{,}2732$.`,
      },
      {
        id: 'd',
        prompt: 'd) Welcher Koeffizient ist die kleinste nicht-verschwindende Amplitude nach $b_1$, $b_3$, $b_5$, …? Geben Sie $b_3$ an.',
        answer: 0.4244,
        alternates: ['4/(3 pi)'],
        unit: '',
        tolerance: 0.005,
        points: 3,
        explanation: `$b_3 = 4/(3\\pi) \\approx 0{,}4244$. Nur ungerade Harmonische sind vorhanden: $b_1, b_3, b_5, \\ldots = 4/(n\\pi)$.`,
      },
    ],
    hints: [
      'Für ungerade Funktionen verschwinden alle $a_n$; für gerade die $b_n$.',
      'Das Rechtecksignal enthält nur ungerade Harmonische mit $1/n$-Abfall.',
    ],
    tags: ['fourier', 'rechtecksignal', 'harmonische'],
  },
]
