import type { PracticeExercise } from '@/types/practice'

export const integralrechnungPractice: PracticeExercise[] = [
  {
    id: 'pr-int-1',
    topicId: 'integralrechnung',
    title: 'Fläche zwischen zwei Kurven',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 12,
    context: `Gegeben sind die Funktionen
$$f(x) = x^2 \\qquad \\text{und} \\qquad g(x) = 2x.$$
Berechnen Sie die von beiden Kurven eingeschlossene Fläche.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Bestimmen Sie die obere Schnittstelle $x_2$ (mit $x_2 > x_1$).',
        answer: 2,
        unit: '',
        tolerance: 1e-6,
        points: 2,
        explanation: `$x^2 = 2x \\Rightarrow x(x-2) = 0 \\Rightarrow x_1 = 0$, $x_2 = 2$.`,
      },
      {
        id: 'b',
        prompt: 'b) Welche Funktion verläuft im Intervall $[0;2]$ oben? Geben Sie $1 = g$ oder $2 = f$ ein.',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 2,
        explanation: `Für $x = 1$: $g(1) = 2$, $f(1) = 1$. Also $g(x) \\ge f(x)$ auf $[0;2]$.`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie das bestimmte Integral $\\int_0^2 (2x - x^2)\\,dx$.',
        answer: 1.333,
        alternates: ['4/3'],
        unit: '',
        tolerance: 0.005,
        points: 4,
        explanation: `$\\int_0^2 (2x - x^2)\\,dx = [x^2 - x^3/3]_0^2 = 4 - 8/3 = 12/3 - 8/3 = 4/3 \\approx 1{,}333$.`,
      },
      {
        id: 'd',
        prompt: 'd) Volumen beim Rotieren dieser Fläche um die $x$-Achse (Formel: $V = \\pi\\int_0^2 (g^2 - f^2)\\,dx$). Geben Sie $V/\\pi$ als Dezimalzahl ein.',
        answer: 4.267,
        alternates: ['64/15'],
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `$V/\\pi = \\int_0^2 (4x^2 - x^4)\\,dx = [4x^3/3 - x^5/5]_0^2 = 32/3 - 32/5 = (160-96)/15 = 64/15 \\approx 4{,}267$.`,
      },
    ],
    hints: [
      'Fläche zwischen Kurven: Immer erst herausfinden, welche Funktion oben liegt.',
      'Bei Rotation um die $x$-Achse: $V = \\pi\\int (f_{oben}^2 - f_{unten}^2)\\,dx$.',
    ],
    tags: ['fläche', 'schnittpunkte', 'rotationsvolumen'],
  },
  {
    id: 'pr-int-2',
    topicId: 'integralrechnung',
    title: 'Substitution und partielle Integration',
    difficulty: 'klausur-plus',
    points: 10,
    estimatedMinutes: 12,
    context: `Berechnen Sie die folgenden bestimmten Integrale schrittweise.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) $\\int_0^1 x \\cdot e^{x^2}\\,dx$ — welche Substitution liegt nahe? Geben Sie $u(1)$ an, wenn $u = x^2$.',
        answer: 1,
        unit: '',
        tolerance: 1e-6,
        points: 2,
        explanation: `Substitution $u = x^2$, $du = 2x\\,dx$. Grenzen: $x=0 \\to u=0$, $x=1 \\to u=1$.`,
      },
      {
        id: 'b',
        prompt: 'b) Führen Sie die Substitution durch und geben Sie den Wert von $\\int_0^1 x\\,e^{x^2}\\,dx$ auf 4 Nachkommastellen an.',
        answer: 0.8591,
        alternates: ['(e-1)/2'],
        unit: '',
        tolerance: 0.005,
        points: 3,
        explanation: `$\\int_0^1 x e^{x^2} dx = \\tfrac12\\int_0^1 e^u\\,du = \\tfrac12(e - 1) \\approx \\tfrac12\\cdot 1{,}7183 \\approx 0{,}8591$.`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie $\\int_0^{\\pi} x \\sin(x)\\,dx$ mittels partieller Integration.',
        answer: 3.1416,
        alternates: ['pi', 'π'],
        unit: '',
        tolerance: 0.01,
        points: 3,
        explanation: `Partielle Integration: $u = x$, $dv = \\sin x\\,dx$. Dann $du = dx$, $v = -\\cos x$. $\\int x\\sin x\\,dx = -x\\cos x + \\int\\cos x\\,dx = -x\\cos x + \\sin x$. Ausgewertet von $0$ bis $\\pi$: $[-x\\cos x + \\sin x]_0^\\pi = \\pi + 0 - 0 - 0 = \\pi$.`,
      },
      {
        id: 'd',
        prompt: 'd) Welchen Wert hat $\\int_0^{\\pi} \\cos^2(x)\\,dx$? Tipp: Verwenden Sie $\\cos^2 = \\tfrac12(1 + \\cos 2x)$.',
        answer: 1.5708,
        alternates: ['pi/2'],
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `$\\int_0^\\pi \\cos^2 x\\,dx = \\tfrac12\\int_0^\\pi(1+\\cos 2x)\\,dx = \\tfrac12[x + \\tfrac12\\sin 2x]_0^\\pi = \\tfrac12\\pi = \\pi/2$.`,
      },
    ],
    hints: [
      'Substitution: $dx$ komplett durch $du$ ersetzen — inklusive Grenzen.',
      'Partielle Integration: $\\int u\\,dv = uv - \\int v\\,du$. Wahl: $u$ wählt man meist so, dass $u\'$ einfacher wird.',
    ],
    tags: ['substitution', 'partielle-integration'],
  },
  {
    id: 'pr-int-3',
    topicId: 'integralrechnung',
    title: 'Uneigentliches Integral und Konvergenzprüfung',
    difficulty: 'klausur',
    points: 8,
    estimatedMinutes: 8,
    context: `Untersuchen Sie das uneigentliche Integral
$$I_p = \\int_1^{\\infty} \\frac{1}{x^p}\\,dx.$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Für welchen Grenzwert $p^*$ kippt die Konvergenz um? Geben Sie $p^*$ ein.',
        answer: 1,
        unit: '',
        tolerance: 1e-6,
        points: 2,
        explanation: `Stammfunktion $x^{1-p}/(1-p)$ (für $p\\neq 1$). Für $p > 1$ konvergiert der Grenzwert bei $\\infty$, für $p \\le 1$ divergiert er. Grenzfall $p^* = 1$ (Logarithmus).`,
      },
      {
        id: 'b',
        prompt: 'b) Berechnen Sie $I_2$.',
        answer: 1,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$I_2 = \\int_1^\\infty x^{-2}\\,dx = [-1/x]_1^\\infty = 0 - (-1) = 1$.`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie $I_{1/2}$: $1 =$ divergent, sonst numerischer Wert.',
        answer: 1,
        unit: '',
        tolerance: 0.5,
        points: 2,
        explanation: `Stammfunktion $2\\sqrt{x}$ divergiert für $x\\to\\infty$, daher divergent. Antwort 1 steht für "divergent".`,
      },
      {
        id: 'd',
        prompt: 'd) $I_3$ numerisch (auf 3 Nachkommastellen).',
        answer: 0.5,
        alternates: ['1/2'],
        unit: '',
        tolerance: 0.005,
        points: 2,
        explanation: `$I_3 = [-x^{-2}/2]_1^\\infty = 0 + 1/2 = 1/2 = 0{,}5$.`,
      },
    ],
    hints: [
      'Uneigentliche Integrale werden über Grenzwert definiert: $\\int_1^\\infty = \\lim_{b\\to\\infty}\\int_1^b$.',
      'Allgemein: $I_p$ konvergiert genau dann, wenn $p > 1$.',
    ],
    wrapUp: `Dieses Ergebnis ist die Grundlage für das **Minorantenkriterium**: alle Integranden, die sich durch $C/x^p$ mit $p>1$ abschätzen lassen, konvergieren.`,
    tags: ['uneigentlich', 'konvergenz', 'p-test'],
  },
]
