import type { PracticeExercise } from '@/types/practice'

export const komplexeZahlenPractice: PracticeExercise[] = [
  {
    id: 'pr-kom-1',
    topicId: 'komplexe-zahlen',
    title: 'Rechnen mit komplexen Zahlen — Polarform',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Gegeben: $z_1 = 3 + 4i$ und $z_2 = 1 - i$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Betrag $|z_1|$?',
        answer: 5,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$|z_1| = \\sqrt{9 + 16} = 5$.`,
      },
      {
        id: 'b',
        prompt: 'b) Argument (Phasenwinkel) $\\varphi_1$ in Grad.',
        answer: 53.13,
        unit: '°',
        tolerance: 0.2,
        points: 2,
        explanation: `$\\varphi_1 = \\arctan(4/3) \\approx 53{,}13°$. (Im 1. Quadranten — keine Korrektur nötig.)`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie den Realteil von $z_1 \\cdot z_2$.',
        answer: 7,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `$(3+4i)(1-i) = 3 - 3i + 4i - 4i^2 = 3 + i + 4 = 7 + i$. Realteil: $7$.`,
      },
      {
        id: 'd',
        prompt: 'd) Realteil von $z_1 / z_2$?',
        answer: -0.5,
        alternates: ['-1/2'],
        unit: '',
        tolerance: 0.01,
        points: 3,
        explanation: `$z_1/z_2 = (3+4i)/(1-i) \\cdot (1+i)/(1+i) = (3+4i)(1+i)/2 = (3+3i+4i+4i^2)/2 = (-1+7i)/2 = -0{,}5 + 3{,}5 i$.`,
      },
    ],
    hints: [
      'Division: mit Konjugiertem des Nenners erweitern, damit der Nenner reell wird.',
      'Multiplikation in Polarform: $|z_1 z_2| = |z_1||z_2|$, $\\arg(z_1 z_2) = \\arg z_1 + \\arg z_2$.',
    ],
    tags: ['polarform', 'multiplikation', 'division'],
  },
  {
    id: 'pr-kom-2',
    topicId: 'komplexe-zahlen',
    title: 'Potenzen und Wurzeln nach de Moivre',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Sei $z = 1 + i$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Polarform: Betrag $|z|$?',
        answer: 1.4142,
        alternates: ['sqrt(2)'],
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `$|z| = \\sqrt{2} \\approx 1{,}4142$. $\\arg z = 45° = \\pi/4$.`,
      },
      {
        id: 'b',
        prompt: 'b) Realteil von $z^8$?',
        answer: 16,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `$z^8 = (\\sqrt{2})^8 \\cdot e^{i\\cdot 8\\pi/4} = 16\\cdot e^{i\\cdot 2\\pi} = 16 \\cdot 1 = 16$.`,
      },
      {
        id: 'c',
        prompt: 'c) Wieviele dritte Wurzeln hat $z$?',
        answer: 3,
        unit: '',
        tolerance: 0.3,
        points: 1,
        explanation: `Die Gleichung $w^3 = z$ hat immer genau 3 verschiedene Lösungen in $\\mathbb{C}$ (n-te Wurzel → n Werte).`,
      },
      {
        id: 'd',
        prompt: 'd) Winkel (in Grad) der dritten Wurzel mit kleinstem positivem Argument.',
        answer: 15,
        unit: '°',
        tolerance: 0.3,
        points: 2,
        explanation: `$\\arg w_0 = \\arg z / 3 = 45°/3 = 15°$. Die übrigen liegen bei $15° + 120°$ und $15° + 240°$.`,
      },
    ],
    hints: [
      'Polarform $z = re^{i\\varphi}$ erleichtert Potenzen drastisch.',
      'Die $n$-te Wurzel einer komplexen Zahl bildet ein reguläres $n$-Eck im Komplexen.',
    ],
    tags: ['de-moivre', 'wurzel', 'polarform'],
  },
  {
    id: 'pr-kom-3',
    topicId: 'komplexe-zahlen',
    title: 'Grundrechenarten und Konjugation',
    difficulty: 'klausur-einstieg',
    points: 7,
    estimatedMinutes: 6,
    context: `Gegeben seien $z_1 = 3 + 4i$ und $z_2 = 1 - 2i$. Führen Sie die Rechnungen exakt und mit Beträgen durch.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Betrag $|z_1|$.',
        answer: 5,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$|z_1|=\\sqrt{3^2+4^2}=\\sqrt{25}=5$. (Klassisches pythagoräisches Paar.)`,
      },
      {
        id: 'b',
        prompt: 'b) Realteil von $z_1\\cdot z_2$.',
        answer: 11,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$z_1 z_2 = (3+4i)(1-2i) = 3-6i+4i-8i^2 = 3 - 2i + 8 = 11 - 2i$. $\\operatorname{Re}(z_1 z_2)=11$.`,
      },
      {
        id: 'c',
        prompt: 'c) Realteil von $z_1/z_2$ (auf 3 Nachkommastellen).',
        answer: -1,
        unit: '',
        tolerance: 0.02,
        points: 3,
        explanation: `Mit konjugiertem Nenner erweitern: $\\tfrac{z_1}{z_2}=\\tfrac{(3+4i)(1+2i)}{(1-2i)(1+2i)} = \\tfrac{3+6i+4i+8i^2}{1+4} = \\tfrac{-5+10i}{5} = -1+2i$. $\\operatorname{Re}=-1$.`,
      },
    ],
    hints: [
      'Für Division: Zähler und Nenner mit dem konjugiert Komplexen des Nenners multiplizieren, so wird der Nenner reell.',
      '$i^2 = -1$ konsequent anwenden — häufigster Vorzeichenfehler bei Produkten.',
      'Der Betrag ist multiplikativ: $|z_1 z_2|=|z_1|\\,|z_2|$; gute Plausibilitätsprüfung.',
    ],
    wrapUp: `Probe: $|z_1 z_2|=\\sqrt{11^2+(-2)^2}=\\sqrt{125}=5\\sqrt{5}\\approx 11{,}18$. Das stimmt mit $|z_1||z_2|=5\\cdot\\sqrt{5}=5\\sqrt{5}$ überein — Regel erfüllt.`,
    tags: ['konjugation', 'division', 'betrag'],
  },
]
