import type { PracticeExercise } from '@/types/practice'

export const komplexeZahlenPractice: PracticeExercise[] = [
  {
    id: 'pr-kom-1',
    topicId: 'komplexe-zahlen',
    title: 'Rechnen mit komplexen Zahlen — Polarform',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Gegeben: $z_1 = 3 + 4i$ und $z_2 = 1 - i$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Betrag $|z_1|$?',
        answer: 5,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$|z_1| = \\sqrt{9 + 16} = 5$.`,
      },
      {
        id: 'b',
        prompt: 'b) Argument (Phasenwinkel) $\\varphi_1$ in Grad.',
        answer: 53.13,
        unit: '°',
        tolerance: 0.2,
        points: 2,
        explanation: `$\\varphi_1 = \\arctan(4/3) \\approx 53{,}13°$. (Im 1. Quadranten — keine Korrektur nötig.)`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie den Realteil von $z_1 \\cdot z_2$.',
        answer: 7,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `$(3+4i)(1-i) = 3 - 3i + 4i - 4i^2 = 3 + i + 4 = 7 + i$. Realteil: $7$.`,
      },
      {
        id: 'd',
        prompt: 'd) Realteil von $z_1 / z_2$?',
        answer: -0.5,
        alternates: ['-1/2'],
        unit: '',
        tolerance: 0.01,
        points: 3,
        explanation: `$z_1/z_2 = (3+4i)/(1-i) \\cdot (1+i)/(1+i) = (3+4i)(1+i)/2 = (3+3i+4i+4i^2)/2 = (-1+7i)/2 = -0{,}5 + 3{,}5 i$.`,
      },
    ],
    hints: [
      'Division: mit Konjugiertem des Nenners erweitern, damit der Nenner reell wird.',
      'Multiplikation in Polarform: $|z_1 z_2| = |z_1||z_2|$, $\\arg(z_1 z_2) = \\arg z_1 + \\arg z_2$.',
    ],
    tags: ['polarform', 'multiplikation', 'division'],
  },
  {
    id: 'pr-kom-2',
    topicId: 'komplexe-zahlen',
    title: 'Potenzen und Wurzeln nach de Moivre',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Sei $z = 1 + i$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Polarform: Betrag $|z|$?',
        answer: 1.4142,
        alternates: ['sqrt(2)'],
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `$|z| = \\sqrt{2} \\approx 1{,}4142$. $\\arg z = 45° = \\pi/4$.`,
      },
      {
        id: 'b',
        prompt: 'b) Realteil von $z^8$?',
        answer: 16,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `$z^8 = (\\sqrt{2})^8 \\cdot e^{i\\cdot 8\\pi/4} = 16\\cdot e^{i\\cdot 2\\pi} = 16 \\cdot 1 = 16$.`,
      },
      {
        id: 'c',
        prompt: 'c) Wieviele dritte Wurzeln hat $z$?',
        answer: 3,
        unit: '',
        tolerance: 0.3,
        points: 1,
        explanation: `Die Gleichung $w^3 = z$ hat immer genau 3 verschiedene Lösungen in $\\mathbb{C}$ (n-te Wurzel → n Werte).`,
      },
      {
        id: 'd',
        prompt: 'd) Winkel (in Grad) der dritten Wurzel mit kleinstem positivem Argument.',
        answer: 15,
        unit: '°',
        tolerance: 0.3,
        points: 2,
        explanation: `$\\arg w_0 = \\arg z / 3 = 45°/3 = 15°$. Die übrigen liegen bei $15° + 120°$ und $15° + 240°$.`,
      },
    ],
    hints: [
      'Polarform $z = re^{i\\varphi}$ erleichtert Potenzen drastisch.',
      'Die $n$-te Wurzel einer komplexen Zahl bildet ein reguläres $n$-Eck im Komplexen.',
    ],
    tags: ['de-moivre', 'wurzel', 'polarform'],
  },
]
