import type { PracticeExercise } from '@/types/practice'

export const lineareAlgebraPractice: PracticeExercise[] = [
  {
    id: 'pr-lin-1',
    topicId: 'lineare-algebra',
    title: 'LGS mit Gauß-Algorithmus',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 12,
    context: `Gegeben ist das Gleichungssystem
$$\\begin{aligned} 2x_1 + 4x_2 + 2x_3 &= 16 \\\\ x_1 + 3x_2 - x_3 &= 4 \\\\ 3x_1 + 5x_2 + 4x_3 &= 25 \\end{aligned}$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Bestimmen Sie die Determinante der Koeffizientenmatrix.',
        answer: -2,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `Entwicklung nach der ersten Zeile: $\\det A = 2(3\\cdot 4 - (-1)\\cdot 5) - 4(1\\cdot 4 - (-1)\\cdot 3) + 2(1\\cdot 5 - 3\\cdot 3) = 2\\cdot 17 - 4\\cdot 7 + 2\\cdot(-4) = 34 - 28 - 8 = -2$. Da $\\det A \\neq 0$, hat das System eine eindeutige Lösung.`,
      },
      {
        id: 'b',
        prompt: 'b) Bestimmen Sie $x_3$ (führen Sie dazu einen Gauß-Schritt durch).',
        answer: 3,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `Eliminiere $x_1$: $R_2 \\to 2R_2 - R_1$: $(0;2;-4\\,|\\,-8)$. $R_3 \\to 2R_3 - 3R_1$: $(0;-2;2\\,|\\,2)$. Addition $R_3 + R_2$: $(0;0;-2\\,|\\,-6) \\Rightarrow x_3 = 3$.`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie $x_2$.',
        answer: 2,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `Aus der reduzierten zweiten Zeile $2x_2 - 4\\cdot 3 = -8 \\Rightarrow 2x_2 = 4 \\Rightarrow x_2 = 2$.`,
      },
      {
        id: 'd',
        prompt: 'd) Berechnen Sie $x_1$.',
        answer: 1,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$2x_1 + 4\\cdot 2 + 2\\cdot 3 = 16 \\Rightarrow 2x_1 = 2 \\Rightarrow x_1 = 1$. Probe: Zeile 2: $1+6-3=4$ ✓.`,
      },
    ],
    hints: [
      'Erste Zeile als Pivot wählen, dann $x_1$ aus den folgenden Zeilen eliminieren.',
      'Rückwärts einsetzen: Aus der letzten Stufe $x_3$, dann $x_2$, zuletzt $x_1$.',
    ],
    wrapUp: `Probe: Lösung $(1;2;3)$ in alle drei Gleichungen einsetzen — $2+8+6=16$, $1+6-3=4$, $3+10+12=25$. ✓`,
    tags: ['gauß', 'determinante', 'lgs'],
  },
  {
    id: 'pr-lin-2',
    topicId: 'lineare-algebra',
    title: 'Eigenwerte und Eigenvektoren einer 2×2-Matrix',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Gegeben ist die Matrix
$$A = \\begin{pmatrix} 4 & 1 \\\\ 2 & 3 \\end{pmatrix}.$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Berechnen Sie $\\det(A)$.',
        answer: 10,
        unit: '',
        tolerance: 1e-6,
        points: 2,
        explanation: `$\\det A = 4\\cdot 3 - 1\\cdot 2 = 10$.`,
      },
      {
        id: 'b',
        prompt: 'b) Berechnen Sie die Spur $\\operatorname{tr}(A)$.',
        answer: 7,
        unit: '',
        tolerance: 1e-6,
        points: 1,
        explanation: `Spur = Summe der Diagonalelemente $= 4 + 3 = 7$.`,
      },
      {
        id: 'c',
        prompt: 'c) Bestimmen Sie den größeren Eigenwert $\\lambda_2$.',
        answer: 5,
        unit: '',
        tolerance: 1e-3,
        points: 4,
        explanation: `Charakteristisches Polynom: $\\lambda^2 - 7\\lambda + 10 = 0$. Lösungen: $\\lambda = (7\\pm\\sqrt{49-40})/2 = (7\\pm 3)/2$, also $\\lambda_1 = 2$, $\\lambda_2 = 5$.`,
      },
      {
        id: 'd',
        prompt: 'd) Welcher Eigenvektor gehört zu $\\lambda_2 = 5$? Geben Sie das Verhältnis $v_2/v_1$ an.',
        answer: 1,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `$(A-5I)\\vec v = 0$: $\\begin{pmatrix}-1&1\\\\2&-2\\end{pmatrix}\\vec v = 0 \\Rightarrow v_1 = v_2$, also $\\vec v_2 \\propto (1;1)^T$.`,
      },
    ],
    hints: [
      'Bei 2×2-Matrizen ist die Summe der Eigenwerte gleich der Spur, das Produkt gleich der Determinante.',
      'Eigenvektor löst $(A-\\lambda I)\\vec v = 0$; Zeilen sind linear abhängig, eine Komponente frei wählbar.',
    ],
    tags: ['eigenwert', 'eigenvektor', 'determinante'],
  },
]
