import type { PracticeExercise } from '@/types/practice'

export const mechanikPractice: PracticeExercise[] = [
  {
    id: 'pr-mech-1',
    topicId: 'technische-mechanik',
    title: 'Einachsig gelagerter Träger — Auflagerreaktionen',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Ein waagrechter Balken der Länge $L = 6~\\text{m}$ ist bei $A$ (links, Fest-/Gelenklager) und $B$ (rechts, Loslager) gelagert. Er trägt eine Einzellast $F = 12~\\text{kN}$ im Abstand $a = 2~\\text{m}$ rechts von $A$ sowie eine **gleichmäßige Streckenlast** $q = 3~\\text{kN/m}$ über die volle Länge. Gewicht vernachlässigt.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Resultierende der Streckenlast (in kN)?',
        answer: 18,
        unit: 'kN',
        tolerance: 0.1,
        points: 2,
        explanation: `$Q = q\\cdot L = 3\\cdot 6 = 18~\\text{kN}$, Wirkungslinie in der Balkenmitte ($x = 3~\\text{m}$).`,
      },
      {
        id: 'b',
        prompt: 'b) Auflagerkraft $B$ (vertikal, in kN) aus Momentengleichgewicht um $A$.',
        answer: 13,
        unit: 'kN',
        tolerance: 0.05,
        points: 3,
        explanation: `$\\sum M_A = 0$: $B\\cdot 6 - F\\cdot 2 - Q\\cdot 3 = 0 \\Rightarrow 6B = 24 + 54 = 78 \\Rightarrow B = 13~\\text{kN}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Auflagerkraft $A$ (vertikal, in kN)?',
        answer: 17,
        unit: 'kN',
        tolerance: 0.05,
        points: 2,
        explanation: `$\\sum F_y = 0$: $A + B - F - Q = 0 \\Rightarrow A = 12 + 18 - 13 = 17~\\text{kN}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Maximales Biegemoment (in kNm, Betrag)?',
        answer: 28,
        unit: 'kNm',
        tolerance: 0.5,
        points: 3,
        explanation: `Querkraftverlauf: bei $x=2^-$: $A - qx = 17 - 6 = 11$. Nach $F$ wird $Q$ zu $11 - 12 = -1$. Null-Durchgang zwischen $x=2$ und $x=6$: $11 - 12 - q(x-2) = 0 \\Rightarrow x = 2 - 1/q$... Tatsächlich: nach $F$ beträgt $Q(x) = -1 - q(x-2)$, also $Q(2) = -1$ und direkt monoton fallend. Maximum von $M$ liegt bei $x=2$: $M(2) = A\\cdot 2 - q\\cdot 2\\cdot 1 = 34 - 6 = 28~\\text{kNm}$.`,
      },
    ],
    hints: [
      'Momentengleichgewicht um ein Lager eliminiert dessen unbekannte Kraft.',
      'Streckenlast durch Resultierende in ihrem Schwerpunkt ersetzen.',
    ],
    wrapUp: `Plausibilitätskontrolle: $A + B = 17 + 13 = 30 = F + Q = 12 + 18$. ✓`,
    tags: ['balken', 'auflager', 'biegemoment'],
  },
  {
    id: 'pr-mech-2',
    topicId: 'technische-mechanik',
    title: 'Reibung auf schiefer Ebene',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Ein Block mit Masse $m = 50~\\text{kg}$ liegt auf einer Ebene, geneigt um $\\alpha = 20°$. Haftreibungskoeffizient $\\mu_H = 0{,}30$, $g = 9{,}81~\\text{m/s}^2$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Normalkraft $N$ (in N)?',
        answer: 460.95,
        unit: 'N',
        tolerance: 1,
        points: 2,
        explanation: `$N = mg\\cos\\alpha = 490{,}5\\cdot 0{,}9397 \\approx 460{,}95~\\text{N}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Hangabtriebskraft $F_H$ (in N)?',
        answer: 167.73,
        unit: 'N',
        tolerance: 1,
        points: 2,
        explanation: `$F_H = mg\\sin\\alpha = 490{,}5\\cdot 0{,}342 \\approx 167{,}73~\\text{N}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Maximale Haftreibung $R_H = \\mu_H N$?',
        answer: 138.28,
        unit: 'N',
        tolerance: 1,
        points: 2,
        explanation: `$R_H = 0{,}3\\cdot 460{,}95 \\approx 138{,}28~\\text{N}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Rutscht der Block? ($1$ = ja, $0$ = nein)',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 2,
        explanation: `$F_H > R_H$ ($167{,}7 > 138{,}3~\\text{N}$), also kein Gleichgewicht — der Block rutscht.`,
      },
    ],
    hints: [
      'Ziel: Normalkraft, Hangabtrieb, maximale Reibungskraft vergleichen.',
      'Grenzfall $\\mu_{H,\\text{krit}} = \\tan\\alpha$.',
    ],
    tags: ['reibung', 'schiefe-ebene'],
  },
  {
    id: 'pr-mech-3',
    topicId: 'technische-mechanik',
    title: 'Energieerhaltung beim freien Fall',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 6,
    context: `Ein Körper der Masse $m = 2~\\text{kg}$ fällt aus Ruhe von $h = 10~\\text{m}$. $g = 9{,}81~\\text{m/s}^2$, Luftwiderstand vernachlässigt.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Potentielle Energie $E_{pot}$ zu Beginn (in J)?',
        answer: 196.2,
        unit: 'J',
        tolerance: 0.5,
        points: 2,
        explanation: `$E_{pot} = mgh = 2\\cdot 9{,}81\\cdot 10 = 196{,}2~\\text{J}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Auftreffgeschwindigkeit (in m/s)?',
        answer: 14.01,
        unit: 'm/s',
        tolerance: 0.1,
        points: 3,
        explanation: `Energieerhaltung: $mgh = \\tfrac12 m v^2 \\Rightarrow v = \\sqrt{2gh} = \\sqrt{196{,}2} \\approx 14{,}01~\\text{m/s}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Fallzeit (in s)?',
        answer: 1.428,
        unit: 's',
        tolerance: 0.02,
        points: 3,
        explanation: `$t = v/g = 14{,}01/9{,}81 \\approx 1{,}428~\\text{s}$. Alternativ $t=\\sqrt{2h/g}$.`,
      },
    ],
    hints: [
      'Energieerhaltung vermeidet mühsame Zeitintegration.',
      'Faustformel: $v = \\sqrt{2gh}$ (nur bei Ruhe-Start).',
    ],
    tags: ['energieerhaltung', 'freier-fall'],
  },
]
