import type { PracticeExercise } from '@/types/practice'

export const numerikPractice: PracticeExercise[] = [
  {
    id: 'pr-num-1',
    topicId: 'numerik',
    title: 'Newton-Verfahren',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Gesucht ist eine Nullstelle von $f(x) = x^2 - 2$ mit dem Newton-Verfahren, Startwert $x_0 = 1$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Iterationsvorschrift: $x_{n+1} = x_n - f(x_n)/f\'(x_n)$. $f\'(x)$ bei $x = 1$?',
        answer: 2,
        unit: '',
        tolerance: 1e-6,
        points: 2,
        explanation: `$f'(x) = 2x$, an $x=1$: $2$.`,
      },
      {
        id: 'b',
        prompt: 'b) $x_1$ nach einem Schritt?',
        answer: 1.5,
        alternates: ['3/2'],
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `$x_1 = 1 - (-1)/2 = 1 + 0{,}5 = 1{,}5$.`,
      },
      {
        id: 'c',
        prompt: 'c) $x_2$?',
        answer: 1.4167,
        alternates: ['17/12'],
        unit: '',
        tolerance: 0.002,
        points: 3,
        explanation: `$f(1{,}5) = 0{,}25$, $f'(1{,}5) = 3$. $x_2 = 1{,}5 - 0{,}25/3 = 1{,}5 - 0{,}0833 \\approx 1{,}4167$.`,
      },
      {
        id: 'd',
        prompt: 'd) Fehler zu $\\sqrt 2$ nach $x_2$ (absoluter Wert).',
        answer: 0.002,
        unit: '',
        tolerance: 0.002,
        points: 2,
        explanation: `$\\sqrt 2 \\approx 1{,}41421$; $|x_2 - \\sqrt 2| \\approx |1{,}41667 - 1{,}41421| \\approx 0{,}0025$.`,
      },
    ],
    hints: [
      'Newton konvergiert bei guten Startwerten quadratisch.',
      'Die Iteration für $\\sqrt a$ lautet $x_{n+1} = (x_n + a/x_n)/2$.',
    ],
    tags: ['newton', 'iteration'],
  },
  {
    id: 'pr-num-2',
    topicId: 'numerik',
    title: 'Numerische Integration (Simpson-Regel)',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Nähern Sie $\\int_0^2 e^{-x^2}\\,dx$ mit der Simpson-Regel bei $n = 2$ Teilintervallen.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Schrittweite $h$?',
        answer: 1,
        unit: '',
        tolerance: 1e-6,
        points: 1,
        explanation: `$h = (2-0)/2 = 1$.`,
      },
      {
        id: 'b',
        prompt: 'b) Funktionswerte: $f(0)$?',
        answer: 1,
        unit: '',
        tolerance: 1e-6,
        points: 1,
        explanation: `$f(0) = e^0 = 1$.`,
      },
      {
        id: 'c',
        prompt: 'c) $f(1)$? (auf 4 Nachkommastellen)',
        answer: 0.3679,
        unit: '',
        tolerance: 0.002,
        points: 1,
        explanation: `$f(1) = e^{-1} \\approx 0{,}3679$.`,
      },
      {
        id: 'd',
        prompt: 'd) Simpson-Näherung: $S = h/3 \\cdot [f(0) + 4f(1) + f(2)]$. Wert auf 3 Nachkommastellen.',
        answer: 0.829,
        unit: '',
        tolerance: 0.02,
        points: 5,
        explanation: `$f(2) = e^{-4} \\approx 0{,}01832$. $S = 1/3\\,[1 + 4\\cdot 0{,}3679 + 0{,}0183] = 1/3\\cdot 2{,}4898 \\approx 0{,}8299$.`,
      },
    ],
    hints: [
      'Simpson: $S = h/3 \\cdot [y_0 + 4y_1 + 2y_2 + 4y_3 + \\ldots + y_n]$; bei $n=2$: $[y_0 + 4y_1 + y_2]$.',
      'Simpson hat Fehlerordnung $O(h^4)$ — deutlich besser als Trapezregel.',
    ],
    wrapUp: `Exakter Wert: $\\int_0^2 e^{-x^2}\\,dx \\approx 0{,}8821$ → Simpson liefert bei $n=2$ schon 2-3 signifikante Stellen.`,
    tags: ['simpson', 'quadratur'],
  },
  {
    id: 'pr-num-3',
    topicId: 'numerik',
    title: 'Newton-Verfahren für Nullstelle',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Gesucht ist die positive Nullstelle von $f(x) = x^2 - 2$ mit dem Newton-Verfahren. Startwert $x_0 = 2$.
$$x_{n+1} = x_n - \\frac{f(x_n)}{f'(x_n)}.$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Iterationsvorschrift vereinfachen: Welchen Wert hat $x_{n+1}$, ausgedrückt als $\\tfrac12(x_n + a/x_n)$? Geben Sie $a$ an.',
        answer: 2,
        unit: '',
        tolerance: 1e-6,
        points: 2,
        explanation: `$x_{n+1}=x_n-\\tfrac{x_n^2-2}{2x_n}=\\tfrac{2x_n^2-x_n^2+2}{2x_n}=\\tfrac{x_n^2+2}{2x_n}=\\tfrac12(x_n+2/x_n)$. Also $a=2$.`,
      },
      {
        id: 'b',
        prompt: 'b) Erste Iterierte $x_1$ (auf 5 Nachkommastellen).',
        answer: 1.5,
        unit: '',
        tolerance: 1e-4,
        points: 2,
        explanation: `$x_1 = \\tfrac12(2 + 2/2) = \\tfrac12(2 + 1) = 1{,}5$.`,
      },
      {
        id: 'c',
        prompt: 'c) Zweite Iterierte $x_2$ (auf 5 Nachkommastellen).',
        answer: 1.41667,
        unit: '',
        tolerance: 5e-4,
        points: 4,
        explanation: `$x_2 = \\tfrac12(1{,}5 + 2/1{,}5) = \\tfrac12(1{,}5 + 1{,}3333) = \\tfrac12\\cdot 2{,}8333 \\approx 1{,}41667$. Vergleich mit $\\sqrt{2}\\approx 1{,}41421$: bereits drei richtige Stellen.`,
      },
    ],
    hints: [
      'Newton konvergiert quadratisch, sobald der Startwert nahe genug an der Nullstelle ist.',
      'Bei $f(x)=x^2-a$ entsteht die klassische Heron-Iteration: $x_{n+1}=\\tfrac12(x_n+a/x_n)$.',
      'Abbruchkriterium in der Klausur: $|x_{n+1}-x_n|<\\varepsilon$ mit vorgegebenem $\\varepsilon$.',
    ],
    wrapUp: `$x_3 \\approx 1{,}41422$ — fünf korrekte Nachkommastellen nach nur drei Schritten: typische quadratische Newton-Konvergenz.`,
    tags: ['newton', 'nullstelle', 'heron'],
  },
]
