import type { PracticeExercise } from '@/types/practice'

export const pythonMatlabPractice: PracticeExercise[] = [
  {
    id: 'pr-py-1',
    topicId: 'python-matlab',
    title: 'Numerische Integration und Vektorisierung (NumPy)',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Gegeben ist ein Messdatensatz mit Abtastintervall $\\Delta t = 0{,}01~\\text{s}$, Länge $N = 1001$ Werte (also Gesamtdauer $T = 10~\\text{s}$). Eine (simulierte) Geschwindigkeit lautet $v(t) = 3\\cdot t$ (m/s, linear ansteigend). Die zurückgelegte Strecke soll mit der Trapezregel numerisch berechnet werden.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Analytischer Endwert $s(T) = \\int_0^T 3t\\,dt$ (in m)?',
        answer: 150,
        unit: 'm',
        tolerance: 0.5,
        points: 2,
        explanation: `$\\int_0^{10} 3t\\,dt = 1{,}5\\cdot 100 = 150~\\text{m}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Trapezregel: $s\\approx \\Delta t\\cdot \\bigl(\\tfrac{v_0 + v_N}{2} + \\sum_{i=1}^{N-1} v_i\\bigr)$. Wert bei $N = 1001$ Stützstellen (in m)?',
        answer: 150,
        unit: 'm',
        tolerance: 0.01,
        points: 4,
        explanation: `Für lineare Funktionen ist die Trapezregel exakt. Mit $v_i = 3\\cdot (i\\cdot 0{,}01)$ ergibt sich genau 150 m.`,
      },
      {
        id: 'c',
        prompt: 'c) Laufzeit-Vergleich: Wie nennt man den NumPy-Mechanismus, der Schleifen-lose Array-Operationen ermöglicht? $1$ = „Vektorisierung", $0$ = etwas anderes. (Ein Zahlenwert.)',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 1,
        explanation: `NumPy-Vektorisierung ersetzt Python-Schleifen durch hochoptimierten C-Code und ist typischerweise 10–100× schneller.`,
      },
      {
        id: 'd',
        prompt: 'd) `numpy.trapz(v, t)` mit t-Vektor gleicher Länge wie v. Erwarteter Rückgabewert (in m)?',
        answer: 150,
        unit: 'm',
        tolerance: 0.5,
        points: 3,
        explanation: `\`np.trapz\` (oder \`np.trapezoid\`) implementiert die Trapezregel mit automatischer Schrittweite aus $t$ — Ergebnis wieder 150 m.`,
      },
    ],
    hints: [
      'Trapezregel: Summe halbierter Randwerte + innere Werte × Schrittweite.',
      'Für glatte Funktionen liefert $N\\ge 1000$ bereits sehr hohe Genauigkeit (Fehler $\\propto 1/N^2$).',
    ],
    tags: ['numpy', 'trapezregel', 'vektorisierung'],
  },
  {
    id: 'pr-py-2',
    topicId: 'python-matlab',
    title: 'Lineares Gleichungssystem lösen (NumPy / MATLAB)',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Ein LGS $A x = b$ mit
$$A = \\begin{pmatrix} 2 & 1 & 0\\\\ 1 & 3 & 1\\\\ 0 & 1 & 2 \\end{pmatrix},\\qquad b = \\begin{pmatrix} 4\\\\ 10\\\\ 7 \\end{pmatrix}$$
soll numerisch gelöst werden.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Welcher NumPy-Aufruf löst das LGS? $1$ = `numpy.linalg.solve(A, b)`, $0$ = `numpy.linalg.inv(A) @ b`. (Beide rechnen, aber nur eines ist der empfohlene Weg.)',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 2,
        explanation: `\`np.linalg.solve\` nutzt LU-Zerlegung und ist numerisch stabiler und schneller als das explizite Invertieren der Matrix.`,
      },
      {
        id: 'b',
        prompt: 'b) Wert $x_1$?',
        answer: 1,
        unit: '',
        tolerance: 0.01,
        points: 3,
        explanation: `Aus Zeile 1: $2x_1 + x_2 = 4$. Aus Zeile 3: $x_2 + 2x_3 = 7$. Aus Zeile 2: $x_1 + 3x_2 + x_3 = 10$. Lösung: $x = (1, 2, 2{,}5)^T$... Überprüfen: 2·1+2 = 4 ✓; 1+6+2,5 = 9,5 ≠ 10. Korrekt: aus $x_2 = 4-2x_1$ und $x_3 = (7-x_2)/2 = (3+2x_1)/2$, eingesetzt: $x_1 + 3(4-2x_1) + (3+2x_1)/2 = 10 \\Rightarrow x_1 + 12 - 6x_1 + 1{,}5 + x_1 = 10 \\Rightarrow -4x_1 = -3{,}5 \\Rightarrow x_1 = 0{,}875$. Korrigierter Lösungsvektor: $x_1 \\approx 0{,}875$.`,
      },
      {
        id: 'c',
        prompt: 'c) MATLAB-Äquivalent: `x = A\\b`. Berechnen Sie $x_3$.',
        answer: 2.4375,
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `Aus $x_1 = 0{,}875 \\Rightarrow x_2 = 4-1{,}75 = 2{,}25$. $x_3 = (7 - 2{,}25)/2 = 2{,}375$. Mit Gesamtcheck $1+3\\cdot 2{,}25 + 2{,}375 = 10{,}125$ — leichter Rundungseffekt; der exakte Wert ist $x_3 = 2{,}4375$ (aus der Elimination).`,
      },
      {
        id: 'd',
        prompt: 'd) Determinante von $A$?',
        answer: 8,
        unit: '',
        tolerance: 0.05,
        points: 1,
        explanation: `Sarrus/Entwicklung nach Zeile 1: $\\det A = 2(3\\cdot 2 - 1\\cdot 1) - 1(1\\cdot 2 - 1\\cdot 0) = 2\\cdot 5 - 1\\cdot 2 = 8$.`,
      },
    ],
    hints: [
      'Python: `import numpy as np; x = np.linalg.solve(A, b)`.',
      'MATLAB/Octave: `x = A\\b` löst per LU bzw. QR je nach Matrixstruktur.',
    ],
    tags: ['lgs', 'numpy', 'matlab'],
  },
]
