import type { PracticeExercise } from '@/types/practice'

export const regelungstechnikPractice: PracticeExercise[] = [
  {
    id: 'pr-rt-1',
    topicId: 'regelungstechnik',
    title: 'PT1-Glied — Sprungantwort und Zeitkonstante',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Ein PT1-Glied hat die Übertragungsfunktion $G(s) = K/(1 + Ts)$ mit $K = 2$ und $T = 0{,}5~\\text{s}$. Am Eingang liegt ein Einheitssprung $u(t) = 1$ für $t \\ge 0$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Stationärer Endwert $y_\\infty$?',
        answer: 2,
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `Endwertsatz: $y_\\infty = \\lim_{s\\to 0} sG(s)\\cdot 1/s = G(0) = K = 2$.`,
      },
      {
        id: 'b',
        prompt: 'b) Wert $y(T) = y(0{,}5~\\text{s})$? Sprungantwort: $y(t) = K(1-e^{-t/T})$.',
        answer: 1.264,
        unit: '',
        tolerance: 0.01,
        points: 3,
        explanation: `$y(0{,}5) = 2\\cdot(1-e^{-1}) = 2\\cdot 0{,}6321 \\approx 1{,}264$.`,
      },
      {
        id: 'c',
        prompt: 'c) Wann hat $y(t)$ 95 % des Endwerts erreicht? Antwort in s.',
        answer: 1.498,
        unit: 's',
        tolerance: 0.02,
        points: 3,
        explanation: `$0{,}95 = 1 - e^{-t/T} \\Rightarrow t = T\\ln(20) = 0{,}5\\cdot 2{,}9957 \\approx 1{,}498~\\text{s}$ (ca. $3T$).`,
      },
      {
        id: 'd',
        prompt: 'd) Anstieg im Ursprung $\\dot y(0)$? ($K$ und $T$ verwenden, Einheit: $1/\\text{s}$)',
        answer: 4,
        unit: '1/s',
        tolerance: 0.05,
        points: 2,
        explanation: `$\\dot y(t) = (K/T)e^{-t/T}$, bei $t=0$: $\\dot y(0) = K/T = 2/0{,}5 = 4$. Tangente schneidet Endwert bei $t = T$.`,
      },
    ],
    hints: [
      'PT1: Zeitkonstante $T$ — nach $t = T$ erreichte $y$ ca. 63 % des Endwerts.',
      'Nach $3T$ sind ca. 95 % erreicht, nach $5T$ ca. 99 %.',
    ],
    tags: ['pt1', 'sprungantwort', 'zeitkonstante'],
  },
  {
    id: 'pr-rt-2',
    topicId: 'regelungstechnik',
    title: 'Regelkreis-Stabilität — Hurwitz-Kriterium',
    difficulty: 'klausur-plus',
    points: 10,
    estimatedMinutes: 10,
    context: `Ein geschlossener Regelkreis hat die charakteristische Gleichung $a(s) = s^3 + 3 s^2 + 4 s + K = 0$. Untersucht werden soll, für welche $K>0$ der Kreis stabil ist.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Notwendige Bedingung: Alle Koeffizienten $>0$. Wie groß ist die untere Schranke für $K$?',
        answer: 0,
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `$K > 0$ ist notwendig, sonst gibt es einen Vorzeichenwechsel im Koeffizienten.`,
      },
      {
        id: 'b',
        prompt: 'b) Hurwitz-Determinante $H_2 = a_1 a_2 - a_0 a_3$ mit $a_3=1, a_2=3, a_1=4, a_0=K$. Wert?',
        answer: 12,
        alternates: ['12 - K'],
        unit: '',
        tolerance: 0.01,
        points: 3,
        explanation: `Hurwitz-Matrix $\\begin{pmatrix}3 & K\\\\ 1 & 4\\end{pmatrix}$, Determinante $= 12 - K$. Bei $K=0$ ergibt sich $12$.`,
      },
      {
        id: 'c',
        prompt: 'c) Stabilitätsgrenze aus $12 - K > 0$: maximaler Wert von $K$ für Stabilität?',
        answer: 12,
        unit: '',
        tolerance: 0.05,
        points: 3,
        explanation: `$K < 12$ aus $H_2 > 0$. Die Grenze liegt bei $K = 12$, hier entstehen Pole auf der imaginären Achse.`,
      },
      {
        id: 'd',
        prompt: 'd) Bei $K = 12$ entstehen Pole auf der imaginären Achse. Dauerschwingfrequenz $\\omega_d$ (in rad/s)?',
        answer: 2,
        unit: 'rad/s',
        tolerance: 0.05,
        points: 2,
        explanation: `$a(j\\omega) = -j\\omega^3 - 3\\omega^2 + 4j\\omega + 12 = 0$. Imaginärteil: $\\omega(4 - \\omega^2) = 0 \\Rightarrow \\omega = 2$. Real: $-12 + 12 = 0$ ✓.`,
      },
    ],
    hints: [
      'Hurwitz: $H_1 = a_2 > 0$, $H_2 = a_1 a_2 - a_0 a_3 > 0$, $H_3 = a_0 H_2 > 0$.',
      'An der Stabilitätsgrenze ($H_2 = 0$) schwingt der Regelkreis mit $\\omega_d = \\sqrt{a_1/a_3}$.',
    ],
    tags: ['stabilität', 'hurwitz', 'charakteristische-gleichung'],
  },
]
