import type { PracticeExercise } from '@/types/practice'

export const reihenFolgenPractice: PracticeExercise[] = [
  {
    id: 'pr-rei-1',
    topicId: 'reihen-folgen',
    title: 'Konvergenzprüfung einer Reihe',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Untersuchen Sie die Reihe
$$\\sum_{n=1}^{\\infty} \\frac{n^2}{2^n}.$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Welches Konvergenzkriterium bietet sich an? $1$ = Quotient, $2$ = Wurzel, $3$ = Majorante, $4$ = Leibniz.',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 2,
        explanation: `Quotientenkriterium ist wegen des $2^n$-Anteils am einfachsten: $a_{n+1}/a_n \\to L$.`,
      },
      {
        id: 'b',
        prompt: 'b) Berechnen Sie den Grenzwert $L = \\lim a_{n+1}/a_n$.',
        answer: 0.5,
        alternates: ['1/2'],
        unit: '',
        tolerance: 0.01,
        points: 4,
        explanation: `$\\frac{a_{n+1}}{a_n} = \\frac{(n+1)^2 / 2^{n+1}}{n^2/2^n} = \\frac{(n+1)^2}{2n^2} \\to \\frac{1}{2}$ für $n\\to\\infty$.`,
      },
      {
        id: 'c',
        prompt: 'c) Konvergiert die Reihe? ($1$ = ja, $0$ = nein)',
        answer: 1,
        unit: '',
        tolerance: 0.3,
        points: 2,
        explanation: `$L = 1/2 < 1$, also absolut konvergent.`,
      },
      {
        id: 'd',
        prompt: 'd) Zusatz: Grenzwert $\\sum_{n=1}^{\\infty} n^2 x^n$ für $|x|<1$ ist bekannt als $x(1+x)/(1-x)^3$. Wert bei $x = 1/2$?',
        answer: 6,
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `$\\frac{x(1+x)}{(1-x)^3} = \\frac{0{,}5\\cdot 1{,}5}{0{,}125} = \\frac{0{,}75}{0{,}125} = 6$.`,
      },
    ],
    hints: [
      'Quotientenkriterium: $\\lim |a_{n+1}/a_n| < 1$ ⇒ absolut konvergent.',
      'Bei Leibniz-Reihen zusätzlich monotone Nullfolge prüfen.',
    ],
    tags: ['quotientenkriterium', 'konvergenz'],
  },
  {
    id: 'pr-rei-2',
    topicId: 'reihen-folgen',
    title: 'Geometrische und harmonische Reihe',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Bekannte Standardreihen.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Wert der geometrischen Reihe $\\sum_{n=0}^\\infty (1/3)^n$?',
        answer: 1.5,
        alternates: ['3/2'],
        unit: '',
        tolerance: 0.005,
        points: 2,
        explanation: `$\\sum_{n=0}^\\infty q^n = 1/(1-q)$ für $|q|<1$. Mit $q = 1/3$: $1/(2/3) = 3/2$.`,
      },
      {
        id: 'b',
        prompt: 'b) Konvergiert die harmonische Reihe $\\sum 1/n$? ($1$ = ja, $0$ = nein)',
        answer: 0,
        unit: '',
        tolerance: 0.3,
        points: 2,
        explanation: `Die harmonische Reihe divergiert (langsam); Standardbeispiel — trotz $a_n \\to 0$ keine Konvergenz.`,
      },
      {
        id: 'c',
        prompt: 'c) Wert von $\\sum_{n=1}^\\infty 1/n^2$ (Basel-Problem)?',
        answer: 1.6449,
        alternates: ['pi^2/6'],
        unit: '',
        tolerance: 0.005,
        points: 2,
        explanation: `Euler 1735: $\\sum 1/n^2 = \\pi^2/6 \\approx 1{,}6449$.`,
      },
      {
        id: 'd',
        prompt: 'd) Teilsumme $s_{10}$ der geometrischen Reihe mit $q=1/2$, $a_0 = 1$, auf 4 Nachkommastellen.',
        answer: 1.9980,
        unit: '',
        tolerance: 0.005,
        points: 2,
        explanation: `$s_{10} = (1-(1/2)^{11})/(1-1/2) = 2 - 2/2048 = 2 - 1/1024 \\approx 1{,}99902$.`,
      },
    ],
    hints: [
      'p-Reihen $\\sum 1/n^p$: konvergent genau dann, wenn $p > 1$.',
      'Geometrische Reihe: Standardgrenzwert $1/(1-q)$.',
    ],
    tags: ['geometrisch', 'harmonisch', 'basel'],
  },
  {
    id: 'pr-rei-3',
    topicId: 'reihen-folgen',
    title: 'Folgen-Grenzwert und Monotonie',
    difficulty: 'klausur-einstieg',
    points: 7,
    estimatedMinutes: 7,
    context: `Untersuchen Sie die Folge
$$a_n = \\frac{3n+1}{n+2}, \\qquad n \\in \\mathbb{N}_0.$$`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Grenzwert $\\lim_{n\\to\\infty} a_n$ (auf 3 Nachkommastellen).',
        answer: 3,
        unit: '',
        tolerance: 1e-3,
        points: 3,
        explanation: `Führende Potenz von $n$ heraushebe: $a_n = \\tfrac{n(3+1/n)}{n(1+2/n)} = \\tfrac{3+1/n}{1+2/n} \\to \\tfrac{3}{1} = 3$.`,
      },
      {
        id: 'b',
        prompt: 'b) Welchen Wert hat $a_{10}$ (auf 3 Nachkommastellen)?',
        answer: 2.583,
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `$a_{10}=\\tfrac{31}{12}\\approx 2{,}583$. Erwartet: nahe bei $3$, aber kleiner (die Folge nähert sich $3$ von unten).`,
      },
      {
        id: 'c',
        prompt: 'c) Ist die Folge monoton wachsend (1 = ja, 0 = nein)?',
        answer: 1,
        unit: '',
        tolerance: 1e-3,
        points: 2,
        explanation: `$a_{n+1}-a_n=\\tfrac{3(n+1)+1}{n+3}-\\tfrac{3n+1}{n+2}=\\tfrac{(3n+4)(n+2)-(3n+1)(n+3)}{(n+2)(n+3)}=\\tfrac{5}{(n+2)(n+3)}>0$. Also streng monoton wachsend.`,
      },
    ],
    hints: [
      'Für den Grenzwert rationaler Ausdrücke in $n$ die höchste auftretende Potenz von $n$ kürzen.',
      'Monotonie am besten über das Vorzeichen von $a_{n+1}-a_n$ prüfen; bei Rationalen hilft ein gemeinsamer Nenner.',
      'Schranken: $a_n<3$ folgt aus dem positiven Zählerdefizit $3(n+2)-(3n+1)=5$.',
    ],
    wrapUp: `Die Folge ist streng monoton wachsend und nach oben durch $3$ beschränkt — damit ist sie konvergent mit Grenzwert $3$ (Satz von der monotonen Konvergenz).`,
    tags: ['grenzwert', 'monotonie', 'rational'],
  },
]
