import type { PracticeExercise } from '@/types/practice'

export const thermodynamikPractice: PracticeExercise[] = [
  {
    id: 'pr-thermo-1',
    topicId: 'thermodynamik',
    title: 'Ideales Gas — Zustandsänderung bei konstantem Druck',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `In einem Zylinder wird $n = 0{,}5~\\text{mol}$ ideales Gas (Luft, $R = 8{,}314~\\text{J/(mol K)}$, $\\kappa = 1{,}4$) von $T_1 = 300~\\text{K}$ isobar auf $T_2 = 600~\\text{K}$ erwärmt. Druck $p = 1{,}0~\\text{bar} = 10^5~\\text{Pa}$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Anfangsvolumen $V_1$ (in L)?',
        answer: 12.47,
        unit: 'L',
        tolerance: 0.05,
        points: 2,
        explanation: `$V_1 = nRT_1/p = 0{,}5\\cdot 8{,}314\\cdot 300/10^5 = 0{,}01247~\\text{m}^3 \\approx 12{,}47~\\text{L}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Endvolumen $V_2$ (in L)?',
        answer: 24.94,
        unit: 'L',
        tolerance: 0.1,
        points: 2,
        explanation: `Isobar: $V/T = $ konst. $\\Rightarrow V_2 = V_1\\cdot T_2/T_1 = 24{,}94~\\text{L}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Verrichtete Volumenarbeit $W = p\\Delta V$ (in J, positiv = vom Gas geleistet)?',
        answer: 1247,
        unit: 'J',
        tolerance: 5,
        points: 3,
        explanation: `$W = p\\,(V_2 - V_1) = 10^5\\cdot 0{,}01247 = 1247~\\text{J}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Zugeführte Wärme $Q$ (in J)? Tipp: $c_p = \\frac{\\kappa}{\\kappa-1}R$.',
        answer: 4365,
        unit: 'J',
        tolerance: 15,
        points: 3,
        explanation: `$c_p = 1{,}4/0{,}4 \\cdot 8{,}314 = 29{,}1~\\text{J/(mol K)}$. $Q = n c_p \\Delta T = 0{,}5\\cdot 29{,}1\\cdot 300 = 4365~\\text{J}$.`,
      },
    ],
    hints: [
      '1. Hauptsatz isobar: $Q = \\Delta U + W = n c_p \\Delta T$.',
      'Für Luft gilt $c_p \\approx 1005~\\text{J/(kg K)}$ oder $c_p = 7R/2$ pro mol.',
    ],
    wrapUp: `Prüfung: $\\Delta U = nc_v\\Delta T = 0{,}5\\cdot (5R/2)\\cdot 300 \\approx 3118~\\text{J}$. $Q = \\Delta U + W = 3118 + 1247 = 4365$ ✓`,
    tags: ['isobar', 'ideales-gas'],
  },
  {
    id: 'pr-thermo-2',
    topicId: 'thermodynamik',
    title: 'Carnot-Wirkungsgrad und maximale Arbeit',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `Eine Wärmekraftmaschine arbeitet zwischen $T_w = 800~\\text{K}$ (warme Quelle) und $T_k = 300~\\text{K}$ (kalte Senke). Zugeführte Wärme: $Q_{zu} = 1000~\\text{kJ}$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Carnot-Wirkungsgrad $\\eta_C$ (in %)?',
        answer: 62.5,
        unit: '%',
        tolerance: 0.2,
        points: 3,
        explanation: `$\\eta_C = 1 - T_k/T_w = 1 - 300/800 = 0{,}625 = 62{,}5~\\%$.`,
      },
      {
        id: 'b',
        prompt: 'b) Maximale Arbeit $W_{max}$ (in kJ)?',
        answer: 625,
        unit: 'kJ',
        tolerance: 2,
        points: 3,
        explanation: `$W_{max} = \\eta_C\\cdot Q_{zu} = 0{,}625\\cdot 1000 = 625~\\text{kJ}$.`,
      },
      {
        id: 'c',
        prompt: 'c) An die kalte Senke abgegebene Wärme $Q_{ab}$ (in kJ)?',
        answer: 375,
        unit: 'kJ',
        tolerance: 2,
        points: 2,
        explanation: `$Q_{ab} = Q_{zu} - W_{max} = 1000 - 625 = 375~\\text{kJ}$.`,
      },
    ],
    hints: [
      'Temperaturen unbedingt in Kelvin einsetzen.',
      '$\\eta_C$ ist eine theoretische Obergrenze — reale Maschinen liegen darunter.',
    ],
    tags: ['carnot', 'wirkungsgrad'],
  },
  {
    id: 'pr-thermo-3',
    topicId: 'thermodynamik',
    title: 'Adiabate Verdichtung (Otto-Kompressor)',
    difficulty: 'klausur-plus',
    points: 10,
    estimatedMinutes: 10,
    context: `Luft ($R = 287~\\text{J/(kg K)}$, $\\kappa = 1{,}4$) wird in einem Kompressor isentrop von $p_1 = 1~\\text{bar}$, $T_1 = 293~\\text{K}$ auf $p_2 = 8~\\text{bar}$ verdichtet.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Endtemperatur $T_2$ (in K)? Adiabatenformel $T_2/T_1 = (p_2/p_1)^{(\\kappa-1)/\\kappa}$.',
        answer: 530.9,
        unit: 'K',
        tolerance: 1,
        points: 4,
        explanation: `$(\\kappa-1)/\\kappa = 0{,}2857$. $T_2 = 293\\cdot 8^{0{,}2857} = 293\\cdot 1{,}8114 \\approx 530{,}9~\\text{K}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Temperaturdifferenz $\\Delta T$ (in K)?',
        answer: 237.9,
        unit: 'K',
        tolerance: 1,
        points: 1,
        explanation: `$\\Delta T = 530{,}9 - 293 = 237{,}9~\\text{K}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Spezifische technische Arbeit $w_t = c_p\\Delta T$ (in kJ/kg)? Mit $c_p = \\kappa R/(\\kappa-1)$.',
        answer: 239.0,
        unit: 'kJ/kg',
        tolerance: 1,
        points: 3,
        explanation: `$c_p = 1{,}4\\cdot 287/0{,}4 = 1004{,}5~\\text{J/(kg K)}$. $w_t = 1004{,}5\\cdot 237{,}9 \\approx 239.000~\\text{J/kg} = 239~\\text{kJ/kg}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Bei Massenstrom $\\dot m = 0{,}1~\\text{kg/s}$ — erforderliche Leistung $P$ (in kW)?',
        answer: 23.9,
        unit: 'kW',
        tolerance: 0.2,
        points: 2,
        explanation: `$P = \\dot m\\cdot w_t = 0{,}1\\cdot 239 = 23{,}9~\\text{kW}$.`,
      },
    ],
    hints: [
      'Adiabatenexponent $\\kappa = c_p/c_v$; Luft etwa $1{,}4$.',
      'Technische Arbeit ist bei offenen Systemen die relevante Größe ($w_t = \\int v\\,dp$).',
    ],
    tags: ['adiabat', 'kompressor', 'isentrop'],
  },
]
