import type { PracticeExercise } from '@/types/practice'

export const trigonometryPractice: PracticeExercise[] = [
  {
    id: 'pr-trig-1',
    topicId: 'trigonometry',
    title: 'Schiefer Wurf — Reichweite und Steigzeit',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Ein Geschoss wird mit $v_0 = 40~\\text{m/s}$ unter dem Winkel $\\alpha = 35°$ zur Horizontalen abgeschossen. Luftwiderstand wird vernachlässigt, $g = 9{,}81~\\text{m/s}^2$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Bestimmen Sie die Horizontal- und Vertikalkomponente der Anfangsgeschwindigkeit. Geben Sie $v_{0y}$ in m/s an.',
        answer: 22.943,
        unit: 'm/s',
        tolerance: 0.1,
        points: 2,
        explanation: `$v_{0y} = v_0 \\sin(\\alpha) = 40\\cdot\\sin(35°) = 40\\cdot 0{,}5736 \\approx 22{,}94~\\text{m/s}$. ($v_{0x} \\approx 32{,}77~\\text{m/s}$.)`,
      },
      {
        id: 'b',
        prompt: 'b) Nach welcher Zeit $t_S$ (in s) erreicht das Geschoss den höchsten Punkt?',
        answer: 2.339,
        unit: 's',
        tolerance: 0.02,
        points: 3,
        explanation: `Im Scheitel gilt $v_y = 0$: $t_S = v_{0y}/g = 22{,}94/9{,}81 \\approx 2{,}339~\\text{s}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie die maximale Steighöhe $h_{max}$ (in m) über dem Abschussniveau.',
        answer: 26.83,
        unit: 'm',
        tolerance: 0.2,
        points: 2,
        explanation: `$h_{max} = v_{0y}^2/(2g) = 22{,}94^2/19{,}62 \\approx 26{,}83~\\text{m}$.`,
      },
      {
        id: 'd',
        prompt: 'd) Bestimmen Sie die Wurfweite $w$ (in m) beim Einschlag auf demselben Niveau.',
        answer: 153.3,
        unit: 'm',
        tolerance: 1,
        points: 3,
        explanation: `$w = \\frac{v_0^2 \\sin(2\\alpha)}{g} = \\frac{1600 \\cdot \\sin(70°)}{9{,}81} = \\frac{1600\\cdot 0{,}9397}{9{,}81} \\approx 153{,}3~\\text{m}$.`,
      },
    ],
    hints: [
      'Immer zuerst Komponentenzerlegung $v_{0x}=v_0\\cos\\alpha$, $v_{0y}=v_0\\sin\\alpha$.',
      'Wurfweite: $w = v_0^2 \\sin(2\\alpha)/g$ (nur bei gleicher Abschuss- und Ankunftshöhe).',
    ],
    wrapUp: `Zur Kontrolle: Maximum der Wurfweite liegt bei $\\alpha = 45°$; 35° liefert $\\sin(70°) \\approx 0{,}94$, also etwa 94 % des Maximalwerts.`,
    tags: ['schiefer-wurf', 'sinus', 'cosinus'],
  },
  {
    id: 'pr-trig-2',
    topicId: 'trigonometry',
    title: 'Dreiecksberechnung mit Sinus- und Kosinussatz',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 8,
    context: `In einem Dreieck sind gegeben: $a = 12$, $b = 9$ und der eingeschlossene Winkel $\\gamma = 65°$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Berechnen Sie die Seite $c$ mit dem Kosinussatz (auf 2 Nachkommastellen).',
        answer: 11.49,
        unit: '',
        tolerance: 0.05,
        points: 3,
        explanation: `$c^2 = a^2 + b^2 - 2ab\\cos\\gamma = 144 + 81 - 216\\cdot 0{,}4226 = 225 - 91{,}28 = 133{,}72$, also $c \\approx 11{,}49$.`,
      },
      {
        id: 'b',
        prompt: 'b) Bestimmen Sie mit dem Sinussatz den Winkel $\\alpha$ (in Grad).',
        answer: 71.22,
        unit: '°',
        tolerance: 0.3,
        points: 3,
        explanation: `$\\frac{\\sin\\alpha}{a} = \\frac{\\sin\\gamma}{c} \\Rightarrow \\sin\\alpha = \\frac{12\\cdot\\sin 65°}{11{,}49} = \\frac{10{,}876}{11{,}49} \\approx 0{,}9466$. $\\alpha \\approx 71{,}2°$.`,
      },
      {
        id: 'c',
        prompt: 'c) Berechnen Sie die Dreiecksfläche $A$.',
        answer: 48.94,
        unit: '',
        tolerance: 0.3,
        points: 2,
        explanation: `$A = \\tfrac{1}{2} a b \\sin\\gamma = 0{,}5 \\cdot 12 \\cdot 9 \\cdot 0{,}9063 \\approx 48{,}94$.`,
      },
    ],
    hints: [
      'Liegt der gegebene Winkel zwischen zwei bekannten Seiten, ist der Kosinussatz erste Wahl.',
      'Nach dem Sinussatz: Prüfen, ob ein stumpfer Winkel möglich ist (SSA-Mehrdeutigkeit).',
    ],
    tags: ['sinussatz', 'kosinussatz', 'dreieck'],
  },
]
