import type { PracticeExercise } from '@/types/practice'

export const vektorenPractice: PracticeExercise[] = [
  {
    id: 'pr-vek-1',
    topicId: 'vektoren',
    title: 'Kräftegleichgewicht mit Vektoren',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Drei Kräfte greifen in einem Punkt an:
$$\\vec F_1 = \\begin{pmatrix}4\\\\0\\\\3\\end{pmatrix}~\\text{N}, \\quad \\vec F_2 = \\begin{pmatrix}-2\\\\5\\\\-1\\end{pmatrix}~\\text{N}, \\quad \\vec F_3 = ?$$
Der Punkt soll im Gleichgewicht sein.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Bestimmen Sie die $x$-Komponente von $\\vec F_3$ (in N).',
        answer: -2,
        unit: 'N',
        tolerance: 1e-6,
        points: 2,
        explanation: `Gleichgewicht: $\\vec F_1 + \\vec F_2 + \\vec F_3 = \\vec 0$. $F_{3x} = -(4 + (-2)) = -2$.`,
      },
      {
        id: 'b',
        prompt: 'b) Berechnen Sie den Betrag $|\\vec F_3|$ (auf 3 Nachkommastellen).',
        answer: 5.745,
        unit: 'N',
        tolerance: 0.02,
        points: 3,
        explanation: `$\\vec F_3 = (-2; -5; -2)$. $|\\vec F_3| = \\sqrt{4 + 25 + 4} = \\sqrt{33} \\approx 5{,}745~\\text{N}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Welchen Winkel (in °) schließt $\\vec F_3$ mit der $x$-Achse ein? Tipp: $\\cos\\varphi = F_{3x}/|\\vec F_3|$.',
        answer: 110.36,
        unit: '°',
        tolerance: 0.5,
        points: 3,
        explanation: `$\\cos\\varphi = -2/\\sqrt{33} \\approx -0{,}3482 \\Rightarrow \\varphi \\approx 110{,}36°$.`,
      },
      {
        id: 'd',
        prompt: 'd) Skalarprodukt $\\vec F_1 \\cdot \\vec F_2$?',
        answer: -11,
        unit: 'N²',
        tolerance: 1e-3,
        points: 2,
        explanation: `$\\vec F_1 \\cdot \\vec F_2 = 4\\cdot(-2) + 0\\cdot 5 + 3\\cdot(-1) = -8 - 3 = -11$.`,
      },
    ],
    hints: [
      'Kräftegleichgewicht: alle Komponenten getrennt zu Null.',
      'Winkel einer Kraft zur Koordinatenachse: $\\cos\\varphi = $ Komponente / Betrag.',
    ],
    tags: ['gleichgewicht', 'skalarprodukt', 'betrag'],
  },
  {
    id: 'pr-vek-2',
    topicId: 'vektoren',
    title: 'Kreuzprodukt — Drehmoment und Fläche',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Eine Kraft $\\vec F = (0; 40; 0)~\\text{N}$ wirkt an einem Hebel mit dem Ortsvektor
$\\vec r = (0{,}3;\\,0{,}1;\\,0)~\\text{m}$ gemessen vom Drehpunkt.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Berechnen Sie die $z$-Komponente des Drehmoments $\\vec M = \\vec r \\times \\vec F$ (in Nm).',
        answer: 12,
        unit: 'Nm',
        tolerance: 1e-3,
        points: 3,
        explanation: `$\\vec M = \\vec r\\times\\vec F$. $z$-Komponente: $r_x F_y - r_y F_x = 0{,}3\\cdot 40 - 0{,}1\\cdot 0 = 12~\\text{Nm}$.`,
      },
      {
        id: 'b',
        prompt: 'b) Wie groß ist der Betrag $|\\vec M|$?',
        answer: 12,
        unit: 'Nm',
        tolerance: 1e-3,
        points: 2,
        explanation: `Nur die $z$-Komponente ist ungleich Null, also $|\\vec M| = 12~\\text{Nm}$.`,
      },
      {
        id: 'c',
        prompt: 'c) Welchen Winkel $\\varphi$ (in °) schließen $\\vec r$ und $\\vec F$ ein (Tipp: $|\\vec M| = |\\vec r||\\vec F|\\sin\\varphi$)?',
        answer: 71.57,
        unit: '°',
        tolerance: 0.5,
        points: 3,
        explanation: `$|\\vec r| = \\sqrt{0{,}09+0{,}01} = \\sqrt{0{,}1} \\approx 0{,}3162~\\text{m}$, $|\\vec F| = 40~\\text{N}$. $\\sin\\varphi = 12/(0{,}3162\\cdot 40) = 12/12{,}649 \\approx 0{,}9487 \\Rightarrow \\varphi \\approx 71{,}57°$.`,
      },
      {
        id: 'd',
        prompt: 'd) Welche Fläche eines Parallelogramms spannen $\\vec r$ und $\\vec F$ auf (in Nm)?',
        answer: 12,
        unit: 'Nm',
        tolerance: 1e-3,
        points: 2,
        explanation: `Die Fläche des Parallelogramms ist gerade $|\\vec r\\times\\vec F| = 12$ (Einheit hier Nm, weil wir Kraft × Länge betrachten).`,
      },
    ],
    hints: [
      'Drehmoment als Kreuzprodukt: Reihenfolge $\\vec r\\times\\vec F$, nicht umgekehrt.',
      'Der Betrag des Kreuzprodukts ist die Parallelogrammfläche.',
    ],
    tags: ['kreuzprodukt', 'drehmoment', 'fläche'],
  },
  {
    id: 'pr-vek-3',
    topicId: 'vektoren',
    title: 'Gerade und Ebene — Schnittpunkt, Winkel, Abstand',
    difficulty: 'klausur-plus',
    points: 12,
    estimatedMinutes: 14,
    context: `Gegeben sind die Gerade
$$g:\\;\\vec x = \\begin{pmatrix}1\\\\0\\\\2\\end{pmatrix} + t\\begin{pmatrix}2\\\\1\\\\-1\\end{pmatrix}$$
und die Ebene
$$E:\\;x + 2y + z = 5.$$
Untersuchen Sie Lage und Abstand.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Berechnen Sie den Parameter $t$ des Schnittpunkts $S = g \\cap E$ (auf 3 Nachkommastellen).',
        answer: 0.667,
        unit: '',
        tolerance: 0.005,
        points: 3,
        explanation: `Geraden­punkte in $E$ einsetzen: $(1+2t) + 2\\,t + (2-t) = 5 \\Rightarrow 3 + 3t = 5 \\Rightarrow t = \\tfrac{2}{3} \\approx 0{,}667$.`,
      },
      {
        id: 'b',
        prompt: 'b) Bestimmen Sie die $x$-Koordinate des Schnittpunkts $S$ (auf 3 Nachkommastellen).',
        answer: 2.333,
        unit: '',
        tolerance: 0.01,
        points: 2,
        explanation: `$S_x = 1 + 2\\cdot\\tfrac{2}{3} = \\tfrac{7}{3} \\approx 2{,}333$. (Entsprechend $S_y=\\tfrac23$, $S_z=\\tfrac43$.)`,
      },
      {
        id: 'c',
        prompt: 'c) Welchen Winkel $\\alpha$ (in °) schließt die Gerade $g$ mit der Ebene $E$ ein?',
        answer: 30,
        unit: '°',
        tolerance: 0.5,
        points: 4,
        explanation: `Formel: $\\sin\\alpha = |\\vec v\\cdot\\vec n|/(|\\vec v|\\cdot|\\vec n|)$. $\\vec v=(2;1;-1)$, $\\vec n=(1;2;1)$, $\\vec v\\cdot\\vec n = 2+2-1 = 3$, $|\\vec v|=|\\vec n|=\\sqrt{6}$. $\\sin\\alpha = 3/6 = 0{,}5 \\Rightarrow \\alpha = 30°$.`,
      },
      {
        id: 'd',
        prompt: 'd) Wie weit ist der Punkt $P=(1;1;1)$ von der Ebene $E$ entfernt (Hessesche Normalform, auf 3 Nachkommastellen)?',
        answer: 0.408,
        unit: '',
        tolerance: 0.005,
        points: 3,
        explanation: `$d = |x_P + 2y_P + z_P - 5|/|\\vec n| = |1 + 2 + 1 - 5|/\\sqrt{6} = 1/\\sqrt{6} \\approx 0{,}408$.`,
      },
    ],
    hints: [
      'Schnittpunkt: Gerade komponentenweise in die Ebenen­gleichung einsetzen und nach $t$ auflösen.',
      'Winkel Gerade–Ebene: es wird $\\sin\\alpha$ verwendet (Projektion auf die Normale), nicht $\\cos\\alpha$.',
      'Abstand Punkt–Ebene: $d = |ax_0+by_0+cz_0-d_0|/\\sqrt{a^2+b^2+c^2}$; Vorzeichen entscheidet nur über die Seite.',
    ],
    wrapUp: `Plausibilität: $\\vec v$ und $\\vec n$ sind nicht parallel, also trifft $g$ die Ebene schräg (hier $30°$). $P$ liegt nur $1/\\sqrt{6}\\approx 0{,}41$ von $E$ entfernt — ein Klausur-typischer kleiner Abstand.`,
    tags: ['gerade', 'ebene', 'abstand', 'hessesche-normalform'],
  },
]
