import type { PracticeExercise } from '@/types/practice'

export const werkstoffkundePractice: PracticeExercise[] = [
  {
    id: 'pr-wk-1',
    topicId: 'werkstoffkunde',
    title: 'Zugversuch — Kennwerte aus Spannungs-Dehnungs-Diagramm',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Bei einem Zugversuch an einer zylindrischen Probe (Durchmesser $d_0 = 10~\\text{mm}$, Messlänge $L_0 = 50~\\text{mm}$) werden gemessen: Streckgrenzenkraft $F_{eH} = 27{,}5~\\text{kN}$, Höchstkraft $F_m = 42~\\text{kN}$, Bruchkraft $F_B = 34~\\text{kN}$, Länge beim Bruch $L_u = 64{,}5~\\text{mm}$. $E = 210~\\text{GPa}$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Anfangsquerschnitt $S_0$ (in mm²)?',
        answer: 78.54,
        unit: 'mm²',
        tolerance: 0.1,
        points: 2,
        explanation: `$S_0 = \\pi d_0^2/4 = \\pi\\cdot 25 \\approx 78{,}54~\\text{mm}^2$.`,
      },
      {
        id: 'b',
        prompt: 'b) Streckgrenze $R_{eH} = F_{eH}/S_0$ (in MPa)?',
        answer: 350.1,
        unit: 'MPa',
        tolerance: 1,
        points: 2,
        explanation: `$R_{eH} = 27500/78{,}54 \\approx 350{,}1~\\text{N/mm}^2$ — typisch für S355.`,
      },
      {
        id: 'c',
        prompt: 'c) Zugfestigkeit $R_m = F_m/S_0$ (in MPa)?',
        answer: 534.7,
        unit: 'MPa',
        tolerance: 1,
        points: 2,
        explanation: `$R_m = 42000/78{,}54 \\approx 534{,}7~\\text{N/mm}^2$.`,
      },
      {
        id: 'd',
        prompt: 'd) Bruchdehnung $A = (L_u - L_0)/L_0$ (in %)?',
        answer: 29,
        unit: '%',
        tolerance: 0.2,
        points: 2,
        explanation: `$A = (64{,}5 - 50)/50 = 0{,}29 = 29~\\%$ — sehr duktil.`,
      },
      {
        id: 'e',
        prompt: 'e) Dehnung bei Streckgrenze (elastisch): $\\varepsilon_{eH} = R_{eH}/E$ (in ‰)?',
        answer: 1.667,
        unit: '‰',
        tolerance: 0.02,
        points: 2,
        explanation: `$\\varepsilon_{eH} = 350{,}1/210000 = 0{,}001667 = 1{,}667~‰$.`,
      },
    ],
    hints: [
      'Im Hooke-Bereich gilt $\\sigma = E\\varepsilon$.',
      'Technische Spannung bezieht sich auf $S_0$, die wahre Spannung auf den tatsächlichen Querschnitt.',
    ],
    tags: ['zugversuch', 'streckgrenze', 'zugfestigkeit', 'bruchdehnung'],
  },
  {
    id: 'pr-wk-2',
    topicId: 'werkstoffkunde',
    title: 'Eisen-Kohlenstoff-Diagramm — Hebelgesetz',
    difficulty: 'klausur',
    points: 10,
    estimatedMinutes: 10,
    context: `Betrachtet wird eine Stahllegierung mit $c_0 = 0{,}6~\\text{Masse-\\%~C}$ unmittelbar unterhalb der eutektoiden Temperatur ($723°$C). Kohlenstoffgehalte der Phasen: $\\alpha$-Eisen (Ferrit) $c_\\alpha = 0{,}02~\\%$, Fe$_3$C (Zementit) $c_{Fe_3C} = 6{,}67~\\%$, Perlit entsteht aus Eutektoid $c_e = 0{,}8~\\%$.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Unmittelbar oberhalb $723°$C liegt $\\gamma$-Eisen (Austenit, $c_\\gamma = 0{,}8~\\%$) neben Ferrit ($c_\\alpha = 0{,}02~\\%$) vor. Anteil Ferrit (in %)?',
        answer: 25.64,
        unit: '%',
        tolerance: 0.2,
        points: 3,
        explanation: `Hebelgesetz: $f_\\alpha = (c_\\gamma - c_0)/(c_\\gamma - c_\\alpha) = (0{,}8 - 0{,}6)/(0{,}8 - 0{,}02) = 0{,}2/0{,}78 \\approx 25{,}64~\\%$.`,
      },
      {
        id: 'b',
        prompt: 'b) Anteil Austenit oberhalb $723°$C (in %)?',
        answer: 74.36,
        unit: '%',
        tolerance: 0.2,
        points: 2,
        explanation: `$f_\\gamma = 1 - f_\\alpha = 100 - 25{,}64 = 74{,}36~\\%$. Bei Unterschreitung der Temperatur wandelt genau dieser Anteil in Perlit um.`,
      },
      {
        id: 'c',
        prompt: 'c) Anteil Primärferrit + Perlit nach der eutektoiden Umwandlung: Perlit-Anteil (in %) entspricht Austenit-Anteil.',
        answer: 74.36,
        unit: '%',
        tolerance: 0.3,
        points: 2,
        explanation: `Direkt nach der Eutektoidlinie: $f_{\\text{Perlit}} = f_\\gamma = 74{,}36~\\%$ und $f_{\\text{Primär-}\\alpha} = 25{,}64~\\%$.`,
      },
      {
        id: 'd',
        prompt: 'd) Anteil Zementit im Perlit (Perlit besteht aus $\\alpha$ + Fe$_3$C bei $0{,}8~\\%$): $f_{Fe_3C}$ (in %)?',
        answer: 11.73,
        unit: '%',
        tolerance: 0.2,
        points: 3,
        explanation: `Hebelgesetz zwischen $c_\\alpha = 0{,}02$ und $c_{Fe_3C} = 6{,}67$: $f_{Fe_3C} = (0{,}8 - 0{,}02)/(6{,}67 - 0{,}02) = 0{,}78/6{,}65 \\approx 11{,}73~\\%$.`,
      },
    ],
    hints: [
      'Hebelgesetz: Anteil einer Phase = gegenüberliegender Hebelarm / Gesamthebel.',
      'Eutektoide Zusammensetzung bei $0{,}8~\\%$ C: 100 % Perlit nach Abkühlung.',
    ],
    tags: ['eisen-kohlenstoff', 'hebelgesetz', 'perlit'],
  },
  {
    id: 'pr-wk-3',
    topicId: 'werkstoffkunde',
    title: 'Härteprüfung — Vickers und Umrechnung',
    difficulty: 'klausur-einstieg',
    points: 8,
    estimatedMinutes: 6,
    context: `Bei einem Vickers-Härteversuch mit Prüflast $F = 294{,}2~\\text{N}$ ($= 30~\\text{kgf}$, HV30) wird die mittlere Diagonale $d = 0{,}485~\\text{mm}$ gemessen.`,
    subtasks: [
      {
        id: 'a',
        prompt: 'a) Vickershärte $\\text{HV} = 0{,}1891\\cdot F/d^2$ mit $F$ in N, $d$ in mm. Wert?',
        answer: 236.7,
        unit: 'HV',
        tolerance: 1,
        points: 4,
        explanation: `$\\text{HV} = 0{,}1891\\cdot 294{,}2/0{,}485^2 = 55{,}63/0{,}2352 \\approx 236{,}7$.`,
      },
      {
        id: 'b',
        prompt: 'b) Abschätzung Zugfestigkeit $R_m \\approx 3{,}3\\cdot \\text{HV}$ (in MPa)?',
        answer: 781,
        unit: 'MPa',
        tolerance: 5,
        points: 2,
        explanation: `$R_m \\approx 3{,}3\\cdot 236{,}7 \\approx 781~\\text{MPa}$. Diese Faustformel gilt für unlegierte und niedriglegierte Stähle.`,
      },
      {
        id: 'c',
        prompt: 'c) Eindringtiefe $h = d/(2\\cdot\\sqrt 2\\cdot \\tan(68°))$ (in μm)?',
        answer: 69.3,
        unit: 'μm',
        tolerance: 1,
        points: 2,
        explanation: `Pyramidenspitze mit Öffnungswinkel 136° → Flankenwinkel 68° zur Achse. $h = d/(2\\sqrt 2\\cdot \\tan 68°)$. Vereinfacht: $h \\approx d/7 = 485/7 \\approx 69{,}3~\\mu\\text{m}$.`,
      },
    ],
    hints: [
      'Vickers-Eindringkörper: Diamantpyramide, Flächenwinkel 136°.',
      'Brinell (HB) und Vickers (HV) sind bis $\\approx 400~\\text{HV}$ nahezu identisch.',
    ],
    tags: ['härte', 'vickers', 'zugfestigkeit'],
  },
]
