function mc(question, options, correctIndex, explanation, hints = [], wrongAnswerExplanations = undefined) {
  return {
    type: 'multiple-choice',
    question,
    options,
    correctIndex,
    explanation,
    hints,
    ...(wrongAnswerExplanations ? { wrongAnswerExplanations } : {}),
  }
}

function ni(question, correctValue, tolerance, unit, explanation, hints = []) {
  return { type: 'number-input', question, correctValue, tolerance, unit, explanation, hints }
}

function tf(statement, correct, explanation, hints = []) {
  return { type: 'true-false', statement, correct, explanation, hints }
}

function matching(question, pairs, explanation, hints = []) {
  return { type: 'matching', question, pairs, explanation, hints }
}

function sorting(question, items, correctOrder, explanation, hints = []) {
  return { type: 'sorting', question, items, correctOrder, explanation, hints }
}

function withExamPrefix(exercise, exam) {
  if (!exam) return exercise
  if (exercise.question && !exercise.question.includes('[PRÜFUNG]')) {
    return { ...exercise, question: `[PRÜFUNG] ${exercise.question}` }
  }
  if (exercise.statement && !exercise.statement.includes('[PRÜFUNG]')) {
    return { ...exercise, statement: `[PRÜFUNG] ${exercise.statement}` }
  }
  return exercise
}

function bank(profile) {
  const exercises = [
    mc(profile.conceptQuestion, profile.conceptOptions, profile.conceptCorrect, profile.conceptExplanation, profile.conceptHints, profile.conceptWrongAnswers),
    ni(profile.calcQuestion, profile.calcAnswer, profile.calcTolerance, profile.calcUnit, profile.calcExplanation, profile.calcHints),
    tf(profile.trueFalseStatement, profile.trueFalseCorrect, profile.trueFalseExplanation, profile.trueFalseHints),
    matching(profile.matchingQuestion, profile.matchingPairs, profile.matchingExplanation, profile.matchingHints),
    sorting(profile.sortingQuestion, profile.sortingItems, profile.sortingOrder, profile.sortingExplanation, profile.sortingHints),
    mc(profile.errorQuestion, profile.errorOptions, profile.errorCorrect, profile.errorExplanation, profile.errorHints, profile.errorWrongAnswers),
    ni(profile.transferQuestion, profile.transferAnswer, profile.transferTolerance, profile.transferUnit, profile.transferExplanation, profile.transferHints),
  ]
  return exercises.map((exercise) => withExamPrefix(exercise, profile.exam))
}

const profiles = {
  'abl-1-1': {
    explanation: String.raw`**Vertiefung Ableitungsbegriff:** Die Ableitung $f'(x)$ ist der Grenzwert des Differenzenquotienten für $h \to 0$. Geometrisch ist sie die Steigung der Tangente an $f$ im Punkt $x$. Merke: Sekante (mittlere Steigung) wird durch Grenzwert zur Tangente (momentane Steigung).`,
    conceptQuestion: 'Was beschreibt der Differenzenquotient [f(x+h) − f(x)] / h geometrisch?',
    conceptOptions: [
      'Die Steigung der Tangente im Punkt x',
      'Die mittlere Steigung der Sekante zwischen x und x+h',
      'Den Flächeninhalt unter f auf [x, x+h]',
      'Den Funktionswert f(x)',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'Der Differenzenquotient ist die Steigung der Sekante durch (x, f(x)) und (x+h, f(x+h)). Erst im Grenzwert h→0 wird die Sekante zur Tangente und man erhält f\'(x).',
    conceptHints: ['Sekante verbindet zwei Punkte; Tangente berührt nur einen.', 'h→0: Die zwei Punkte rücken zusammen.'],
    calcQuestion: 'Berechne den Differenzenquotienten von f(x) = x² zwischen x = 2 und x+h = 3. Gib die mittlere Steigung an.',
    calcAnswer: 5,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: '[f(3)−f(2)]/(3−2) = (9−4)/1 = 5. Das ist die Sekantensteigung; die Tangentensteigung f\'(2) = 2·2 = 4 ist kleiner.',
    calcHints: ['Zähler: f(3) − f(2). Nenner: 3 − 2 = 1.', 'f(x) = x², also f(2) = 4 und f(3) = 9.'],
    trueFalseStatement: 'Wenn f\'(x₀) = 0, dann hat f bei x₀ zwingend ein lokales Extremum.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. f\'(x₀) = 0 ist nur notwendig, nicht hinreichend. Gegenbeispiel: f(x) = x³ hat bei x = 0 eine waagerechte Tangente, aber keinen Extrempunkt — nur einen Sattelpunkt.',
    trueFalseHints: ['Denke an f(x) = x³ bei x = 0.', 'Notwendig heißt: ohne f\' = 0 kein Extremum. Aber f\' = 0 allein genügt nicht.'],
    matchingQuestion: 'Ordne den Begriff seinem geometrischen Objekt zu.',
    matchingPairs: [
      { left: 'Differenzenquotient', right: 'Steigung der Sekante' },
      { left: 'Differentialquotient f\'(x)', right: 'Steigung der Tangente' },
      { left: 'f\'(x₀) = 0', right: 'waagerechte Tangente' },
    ],
    matchingExplanation: 'Sekante: zwei Punkte, mittlere Steigung. Tangente: ein Punkt, momentane Steigung = Grenzwert des Differenzenquotienten.',
    matchingHints: ['h→0 verwandelt Sekante in Tangente.', 'Waagerecht = Steigung 0.'],
    sortingQuestion: 'Bringe die Herleitung von f\'(x) für f(x) = x² in die richtige Reihenfolge.',
    sortingItems: [
      'Differenzenquotient aufschreiben: [(x+h)²−x²]/h',
      'Zähler ausmultiplizieren: x²+2xh+h²−x²',
      'Vereinfachen: (2xh+h²)/h = 2x+h',
      'Grenzwert h→0 bilden',
      'Ergebnis: f\'(x) = 2x',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Schritt für Schritt: Quotient aufschreiben → Zähler ausrechnen → kürzen → Grenzwert → Ergebnis.',
    sortingHints: ['Immer erst den Zähler vereinfachen, bevor h→0 genommen wird.', 'Das h im Nenner muss weggekürzt werden, bevor h = 0 gesetzt wird.'],
    errorQuestion: 'Welcher Fehler steckt in der Aussage "f\'(x) = [f(x+h) − f(x)] / h für h = 0"?',
    errorOptions: [
      'Division durch 0 ist nicht erlaubt; man braucht einen Grenzwert h→0',
      'Der Zähler muss quadriert werden',
      'f(x+h) muss durch f(x·h) ersetzt werden',
      'Der Differenzenquotient ist immer negativ',
    ],
    errorCorrect: 0,
    errorExplanation: 'Man darf h = 0 nicht direkt einsetzen, da das den Nenner null macht. Der korrekte Weg ist der Grenzwert lim(h→0).',
    errorHints: ['h = 0 → Nenner 0 → undefiniert.', 'Grenzwert heißt: h nähert sich 0, wird aber nie 0.'],
    transferQuestion: 'f(x) = 3x². Berechne f\'(4) mit der Potenzregel.',
    transferAnswer: 24,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'f\'(x) = 6x. Einsetzen: f\'(4) = 6·4 = 24. Das ist die Tangentensteigung im Punkt (4, 48).',
    transferHints: ['Potenzregel: (3x²)\' = 6x.', 'Einsetzen: x = 4.'],
  },

  'abl-1-2': {
    explanation: String.raw`**Vertiefung Potenz- und Summenregel:** $(x^n)' = n \cdot x^{n-1}$ gilt für alle reellen $n$ — auch für negative und gebrochene Exponenten. Die Summenregel erlaubt es, jedes Glied getrennt abzuleiten. Konstanten fallen weg: $(c)' = 0$.`,
    conceptQuestion: 'Was ist die Ableitung von f(x) = 5x³ − 2x + 7?',
    conceptOptions: [
      '15x² − 2',
      '5x² − 2',
      '15x² − 2x',
      '15x³ − 2',
    ],
    conceptCorrect: 0,
    conceptExplanation: '(5x³)\' = 15x², (−2x)\' = −2, (7)\' = 0. Summenregel: f\'(x) = 15x² − 2.',
    conceptHints: ['Jedes Glied einzeln ableiten.', 'Konstante fällt weg: (7)\' = 0.'],
    calcQuestion: 'f(x) = 2x⁴ − 3x² + 7. Berechne f\'(2).',
    calcAnswer: 52,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'f\'(x) = 8x³ − 6x. f\'(2) = 8·8 − 6·2 = 64 − 12 = 52.',
    calcHints: ['Erst ableiten: f\'(x) = 8x³ − 6x.', 'Dann x = 2 einsetzen.'],
    trueFalseStatement: 'Die Ableitung von f(x) = x^(−2) ist f\'(x) = −2x^(−3).',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Potenzregel mit n = −2: f\'(x) = (−2)·x^(−2−1) = −2x^(−3) = −2/x³.',
    trueFalseHints: ['Potenzregel gilt auch für negative Exponenten.', 'n = −2: f\'(x) = −2·x^(−3).'],
    matchingQuestion: 'Ordne die Funktion ihrer Ableitung zu.',
    matchingPairs: [
      { left: 'f(x) = x⁵', right: "f'(x) = 5x⁴" },
      { left: 'f(x) = √x = x^(1/2)', right: "f'(x) = 1/(2√x)" },
      { left: 'f(x) = 1/x = x^(−1)', right: "f'(x) = −1/x²" },
    ],
    matchingExplanation: 'Potenzregel für alle n: Exponent nach vorne, Exponent um 1 reduzieren. Gilt auch für Brüche und negative Exponenten.',
    matchingHints: ['(x^(1/2))\' = (1/2)·x^(−1/2) = 1/(2√x).', '(x^(−1))\' = −1·x^(−2) = −1/x².'],
    sortingQuestion: 'Leite f(x) = 4x³ − 6x² + 2x − 5 korrekt ab. Ordne die Schritte.',
    sortingItems: [
      'Jeden Term einzeln identifizieren',
      'Potenzregel auf 4x³ anwenden: 12x²',
      'Potenzregel auf −6x² anwenden: −12x',
      'Potenzregel auf 2x anwenden: 2',
      'Konstante −5 fällt weg: 0',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'f\'(x) = 12x² − 12x + 2. Jeder Term wird einzeln abgeleitet; Konstanten fallen weg.',
    sortingHints: ['Jeden Term getrennt behandeln.', 'Konstante ableiten = 0.'],
    errorQuestion: 'Welcher Fehler steckt in: "f(x) = x³ + x², daher f\'(x) = 3x³ + 2x"?',
    errorOptions: [
      'Der Exponent wurde nicht um 1 reduziert',
      'Die Summenregel wurde nicht angewendet',
      'x² wurde nicht abgeleitet',
      'f\' darf nicht zwei Terme haben',
    ],
    errorCorrect: 0,
    errorExplanation: 'Fehler: Der Exponent muss um 1 sinken. Korrekt: (x³)\' = 3x², (x²)\' = 2x. Also f\'(x) = 3x² + 2x, nicht 3x³ + 2x.',
    errorHints: ['Potenzregel: n vorne, dann n − 1 im Exponenten.', 'x³ → 3x², nicht 3x³.'],
    transferQuestion: 'f(x) = x^(−3). Berechne f\'(2) als Dezimalzahl.',
    transferAnswer: -0.09375,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'f\'(x) = −3x^(−4) = −3/x⁴. f\'(2) = −3/16 = −0,09375.',
    transferHints: ['n = −3: f\'(x) = −3·x^(−4).', '−3/2⁴ = −3/16.'],
  },

  'abl-1-3': {
    explanation: String.raw`**Vertiefung elementare Ableitungen:** Lerne die Tabelle auswendig: $(\sin x)' = \cos x$, $(\cos x)' = -\sin x$, $(e^x)' = e^x$, $(\ln x)' = 1/x$. Der Ableitungszyklus $\sin \to \cos \to -\sin \to -\cos \to \sin$ hilft beim Einprägen.`,
    conceptQuestion: 'Welche Funktion ist ihre eigene Ableitung?',
    conceptOptions: [
      'f(x) = x²',
      'f(x) = eˣ',
      'f(x) = sin(x)',
      'f(x) = ln(x)',
    ],
    conceptCorrect: 1,
    conceptExplanation: '(eˣ)\' = eˣ. Die Exponentialfunktion zur Basis e ist die einzige Funktion (bis auf Vielfache), die gleich ihrer Ableitung ist. Das macht sie in der Technik besonders wertvoll.',
    conceptHints: ['Welche Funktion bleibt beim Ableiten unverändert?', 'Nicht sin, nicht cos, nicht ln — nur eˣ.'],
    calcQuestion: 'f(x) = sin(x) + eˣ − 3x². Berechne f\'(0).',
    calcAnswer: 1,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'f\'(x) = cos(x) + eˣ − 6x. f\'(0) = cos(0) + e⁰ − 0 = 1 + 1 − 0 = 2. Warte — Neurechnung: cos(0) = 1, e⁰ = 1, 6·0 = 0. f\'(0) = 1 + 1 = 2.',
    calcTolerance: 0.001,
    calcAnswer: 2,
    calcExplanation: 'f\'(x) = cos(x) + eˣ − 6x. f\'(0) = cos(0) + e⁰ − 6·0 = 1 + 1 − 0 = 2.',
    calcHints: ['Jedes Glied ableiten: (sin x)\' = cos x, (eˣ)\' = eˣ, (3x²)\' = 6x.', 'cos(0) = 1, e⁰ = 1.'],
    trueFalseStatement: 'Die Ableitung von f(x) = ln(x) ist f\'(x) = 1/x und gilt für alle reellen x.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. (ln x)\' = 1/x gilt nur für x > 0, da ln(x) nur für positive x definiert ist.',
    trueFalseHints: ['Definitionsbereich von ln(x): x > 0.', '1/x existiert auch für x < 0, aber ln(x) nicht.'],
    matchingQuestion: 'Ordne die Funktion ihrer Ableitung zu.',
    matchingPairs: [
      { left: 'sin(x)', right: 'cos(x)' },
      { left: 'cos(x)', right: '−sin(x)' },
      { left: 'ln(x)', right: '1/x' },
    ],
    matchingExplanation: 'Diese drei Paare sind Kernwissen. Der Zyklus sin→cos→−sin→−cos→sin hilft beim Merken.',
    matchingHints: ['sin leitet zu cos ab.', 'cos leitet zu −sin ab (Minus beachten!).'],
    sortingQuestion: 'Ordne die Ableitungen im Zyklus: sin → ? → ? → ? → sin.',
    sortingItems: [
      'sin(x)',
      'cos(x)',
      '−sin(x)',
      '−cos(x)',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Vier Ableitungen bringen sin(x) wieder zu sin(x). Der Zyklus: sin → cos → −sin → −cos → sin.',
    sortingHints: ['Erste Ableitung von sin ist cos.', 'Zweite Ableitung von sin ist −sin.'],
    errorQuestion: 'Welche Ableitung ist falsch?',
    errorOptions: [
      '(sin x)\' = cos x',
      '(eˣ)\' = eˣ',
      '(ln x)\' = 1/x',
      '(cos x)\' = sin x',
    ],
    errorCorrect: 3,
    errorExplanation: '(cos x)\' = −sin x, nicht +sin x. Das Minuszeichen ist entscheidend und wird häufig vergessen.',
    errorHints: ['Ableitungszyklus: cos → −sin.', 'Das Minus bei cos ist der häufigste Fehler.'],
    transferQuestion: 'f(x) = 2·sin(x) − ln(x) + eˣ. Berechne f\'(1) näherungsweise mit e¹ ≈ 2,718 und cos(1) ≈ 0,540.',
    transferAnswer: 4.258,
    transferTolerance: 0.02,
    transferUnit: '',
    transferExplanation: 'f\'(x) = 2cos(x) − 1/x + eˣ. f\'(1) = 2·0,540 − 1 + 2,718 = 1,080 − 1 + 2,718 = 2,798. Warte — Neurechnung: 1,080 + 1,718 = 2,798.',
    transferAnswer: 2.798,
    transferTolerance: 0.02,
    transferExplanation: 'f\'(x) = 2cos(x) − 1/x + eˣ. f\'(1) = 2·0,540 − 1/1 + 2,718 = 1,080 − 1 + 2,718 = 2,798.',
    transferHints: ['f\'(x) = 2cos(x) − 1/x + eˣ.', 'Einsetzen: 2·0,540 − 1 + 2,718.'],
  },

  'abl-1-4': {
    explanation: String.raw`**Vertiefung Kettenregel:** $[f(g(x))]' = f'(g(x)) \cdot g'(x)$. Strategie: (1) Äußere Funktion identifizieren, (2) äußere ableiten (innere stehen lassen), (3) mal innere Ableitung. Besonders häufig: $(e^{g(x)})' = e^{g(x)} \cdot g'(x)$ und $(\sin(g(x)))' = \cos(g(x)) \cdot g'(x)$.`,
    conceptQuestion: 'f(x) = e^(3x²). Welche Ableitung ist korrekt?',
    conceptOptions: [
      '3x²·e^(3x²−1)',
      '6x·e^(3x²)',
      'e^(6x)',
      '3x·e^(3x²)',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'Kettenregel: Äußere e^u → e^u, innere 3x² → 6x. f\'(x) = e^(3x²)·6x = 6x·e^(3x²).',
    conceptHints: ['Äußere: e^u bleibt e^u.', 'Innere: (3x²)\' = 6x.'],
    calcQuestion: 'f(x) = sin(2x). Berechne f\'(π/4). Hinweis: cos(π/2) = 0.',
    calcAnswer: 0,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'Kettenregel: f\'(x) = cos(2x)·2 = 2cos(2x). f\'(π/4) = 2·cos(π/2) = 2·0 = 0.',
    calcHints: ['f\'(x) = 2·cos(2x) (Kettenregel).', 'cos(2·π/4) = cos(π/2) = 0.'],
    trueFalseStatement: 'Für f(x) = (x²+1)³ gilt f\'(x) = 3(x²+1)².',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Die Kettenregel erfordert die innere Ableitung: (x²+1)\' = 2x. Also f\'(x) = 3(x²+1)²·2x = 6x(x²+1)².',
    trueFalseHints: ['Äußere Ableitung: u³ → 3u². Innere Ableitung: x²+1 → 2x.', 'Die innere Ableitung 2x darf nicht vergessen werden.'],
    matchingQuestion: 'Ordne die verkettete Funktion ihrer Ableitung zu.',
    matchingPairs: [
      { left: 'sin(5x)', right: '5·cos(5x)' },
      { left: 'e^(−x)', right: '−e^(−x)' },
      { left: 'ln(x²)', right: '2/x' },
    ],
    matchingExplanation: 'Bei sin(5x): äußere cos, innere 5. Bei e^(−x): äußere e^u, innere −1. Bei ln(x²): äußere 1/u, innere 2x → 2x/x² = 2/x.',
    matchingHints: ['Innere Ableitung von 5x ist 5.', 'Innere Ableitung von −x ist −1.'],
    sortingQuestion: 'Leite f(x) = cos(x³+1) mit der Kettenregel ab. Ordne die Schritte.',
    sortingItems: [
      'Äußere Funktion identifizieren: cos(u)',
      'Innere Funktion identifizieren: u = x³+1',
      'Äußere ableiten: −sin(u) = −sin(x³+1)',
      'Innere ableiten: u\' = 3x²',
      'Multiplizieren: f\'(x) = −3x²·sin(x³+1)',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Kettenregel-Schema: Äußere identifizieren → Innere identifizieren → Äußere ableiten → Innere ableiten → Multiplizieren.',
    sortingHints: ['Erst identifizieren, dann ableiten.', 'Äußere Ableitung behält innere Funktion drin.'],
    errorQuestion: 'f(x) = e^(x²). Jemand rechnet f\'(x) = e^(x²). Was wurde vergessen?',
    errorOptions: [
      'Die innere Ableitung 2x als Faktor',
      'Das Minuszeichen',
      'Den Quotienten 1/x',
      'Die Summenregel anzuwenden',
    ],
    errorCorrect: 0,
    errorExplanation: 'Korrekt: f\'(x) = e^(x²)·(x²)\' = e^(x²)·2x. Die innere Ableitung 2x muss als Faktor multipliziert werden.',
    errorHints: ['e^u bleibt e^u, aber mal u\'.', '(x²)\' = 2x.'],
    transferQuestion: 'f(x) = (3x+2)⁴. Berechne f\'(0).',
    transferAnswer: 216,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'Kettenregel: f\'(x) = 4(3x+2)³·3 = 12(3x+2)³. f\'(0) = 12·2³ = 12·8 = 96. Neurechnung: 12·(0+2)³ = 12·8 = 96.',
    transferAnswer: 96,
    transferTolerance: 0.001,
    transferExplanation: 'f\'(x) = 4·(3x+2)³·3 = 12(3x+2)³. f\'(0) = 12·(2)³ = 12·8 = 96.',
    transferHints: ['f\'(x) = 4(3x+2)³·3 = 12(3x+2)³.', '(3·0+2)³ = 8.'],
  },

  'abl-1-5': {
    explanation: String.raw`**Vertiefung Extremwerte:** Notwendig: $f'(x_0) = 0$. Hinreichend: $f''(x_0) < 0$ → lokales Maximum, $f''(x_0) > 0$ → lokales Minimum. Alternativ: Vorzeichenwechsel von $f'$ bei $x_0$ prüfen. Ein Vorzeichenwechsel $+ \to -$ bedeutet Maximum, $- \to +$ bedeutet Minimum.`,
    conceptQuestion: 'f(x) = x³ − 3x. f\'(x) = 3x² − 3 = 0 ergibt x = ±1. Was gilt bei x = 1?',
    conceptOptions: [
      'Lokales Maximum, da f\'\'(1) < 0',
      'Lokales Minimum, da f\'\'(1) = 6 > 0',
      'Wendepunkt, da f\'(1) = 0',
      'Keine Aussage möglich ohne weiteres Kriterium',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'f\'\'(x) = 6x. f\'\'(1) = 6 > 0 → linksgekrümmt (Schüssel) → lokales Minimum bei x = 1 mit f(1) = 1 − 3 = −2.',
    conceptHints: ['f\'\'(1) = 6·1 = 6 > 0.', 'Positives f\'\' bedeutet Minimum (Schüssel).'],
    calcQuestion: 'f(x) = x² − 4x + 3. An welcher Stelle liegt das lokale Minimum? Gib den x-Wert an.',
    calcAnswer: 2,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'f\'(x) = 2x − 4 = 0 → x = 2. f\'\'(x) = 2 > 0 → Minimum. f(2) = 4 − 8 + 3 = −1.',
    calcHints: ['f\'(x) = 2x − 4. Gleich null setzen.', '2x = 4 → x = 2.'],
    trueFalseStatement: 'f\'\'(x₀) < 0 ist hinreichend für ein lokales Maximum bei x₀, wenn f\'(x₀) = 0.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Die Kombination f\'(x₀) = 0 (notwendige Bedingung) und f\'\'(x₀) < 0 (Kurve nach unten geöffnet) garantiert ein lokales Maximum.',
    trueFalseHints: ['f\' = 0: waagerechte Tangente. f\'\' < 0: Hügelform.', 'Beide Bedingungen zusammen sind hinreichend.'],
    matchingQuestion: 'Ordne das Vorzeichen von f\'\'(x₀) der Extremstelle zu.',
    matchingPairs: [
      { left: "f''(x₀) > 0", right: 'lokales Minimum' },
      { left: "f''(x₀) < 0", right: 'lokales Maximum' },
      { left: "f''(x₀) = 0", right: 'weitere Untersuchung nötig' },
    ],
    matchingExplanation: 'Positives f\'\' → Kurve wölbt sich nach oben (Schüssel) → Minimum. Negatives f\'\' → Kurve wölbt sich nach unten (Hügel) → Maximum.',
    matchingHints: ['Schüssel-Form ∪ = Minimum.', 'Hügel-Form ∩ = Maximum.'],
    sortingQuestion: 'Bestimme die Extrema von f(x) = x³ − 3x in der richtigen Reihenfolge.',
    sortingItems: [
      'f\'(x) = 3x² − 3 berechnen',
      'f\'(x) = 0 setzen: 3x² = 3 → x = ±1',
      'f\'\'(x) = 6x berechnen',
      'f\'\'(1) = 6 > 0 → Minimum bei x = 1',
      'f\'\'(−1) = −6 < 0 → Maximum bei x = −1',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Schema: f\' berechnen → f\' = 0 lösen → f\'\' berechnen → f\'\' an den Kandidaten auswerten.',
    sortingHints: ['Erst ableiten, dann Nullstellen, dann zweite Ableitung.', 'f\'\' entscheidet: positiv = Min, negativ = Max.'],
    errorQuestion: 'Jemand behauptet: "f(x) = x³ hat bei x = 0 ein lokales Minimum, weil f\'(0) = 0." Was ist falsch?',
    errorOptions: [
      'f\'(x) = 3x², also f\'(0) = 0 ist richtig, aber f\'\'(0) = 0 → kein Extremum, sondern Sattelpunkt',
      'f\'(0) = 0 ist bereits falsch',
      'x³ hat kein Minimum, weil es negativ ist',
      'Man braucht f\'\'\'(0), um ein Minimum zu bestätigen',
    ],
    errorCorrect: 0,
    errorExplanation: 'f\'\'(x) = 6x. f\'\'(0) = 0 → kein Extremum durch dieses Kriterium. Vorzeichentest: f\'(x) = 3x² ≥ 0 für alle x → kein Vorzeichenwechsel bei x = 0 → Sattelpunkt (Terrassenpunkt), kein Extremum.',
    errorHints: ['f\'\'(0) = 0: das zweite Kriterium versagt.', 'Vorzeichentest von f\' zeigt keinen Wechsel.'],
    transferQuestion: 'f(x) = −x² + 6x − 5. Berechne den maximalen Funktionswert.',
    transferAnswer: 4,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'f\'(x) = −2x + 6 = 0 → x = 3. f\'\'(x) = −2 < 0 → Maximum. f(3) = −9 + 18 − 5 = 4.',
    transferHints: ['f\'(x) = −2x + 6 = 0 → x = 3.', 'f(3) = −9 + 18 − 5 = 4.'],
  },

  'abl-2-1': {
    explanation: String.raw`**Vertiefung Produktregel:** $(u \cdot v)' = u' \cdot v + u \cdot v'$. Eselsbrücke: "Strich-1 mal 2, plus 1 mal Strich-2". Achtung: $(u \cdot v)' \neq u' \cdot v'$! Die Produktregel wird immer benötigt, wenn zwei Funktionen multipliziert werden.`,
    conceptQuestion: 'f(x) = x²·eˣ. Was ist f\'(x)?',
    conceptOptions: [
      '2x·eˣ',
      '2x·eˣ + x²·eˣ',
      'x²·eˣ',
      '2x·eˣ − x²·eˣ',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'Produktregel mit u = x², v = eˣ: f\'(x) = u\'v + uv\' = 2x·eˣ + x²·eˣ = eˣ(2x + x²).',
    conceptHints: ['u = x², v = eˣ. u\' = 2x, v\' = eˣ.', 'Produktregel: u\'v + uv\'.'],
    calcQuestion: 'f(x) = x·eˣ. Berechne f\'(1) auf 2 Dezimalstellen. (e ≈ 2,718)',
    calcAnswer: 5.44,
    calcTolerance: 0.05,
    calcUnit: '',
    calcExplanation: 'Produktregel: f\'(x) = eˣ + x·eˣ = (1+x)eˣ. f\'(1) = 2·e = 2·2,718 ≈ 5,44.',
    calcHints: ['f\'(x) = (1+x)eˣ.', '2·e ≈ 2·2,718.'],
    trueFalseStatement: 'Die Ableitung des Produkts (f·g)\' ist gleich f\'·g\'.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. (f·g)\' = f\'·g + f·g\', nicht f\'·g\'. Der häufigste Fehler bei der Produktregel ist, einfach beide Ableitungen zu multiplizieren.',
    trueFalseHints: ['Gegenbeispiel: f = x, g = x. (x·x)\' = (x²)\' = 2x, aber f\'·g\' = 1·1 = 1 ≠ 2x.', 'Produktregel: zwei Terme, kein Produkt der Ableitungen.'],
    matchingQuestion: 'Ordne die Funktion ihrer Ableitung via Produktregel zu.',
    matchingPairs: [
      { left: 'x·sin(x)', right: 'sin(x) + x·cos(x)' },
      { left: 'x²·ln(x)', right: '2x·ln(x) + x' },
      { left: 'eˣ·cos(x)', right: 'eˣ·cos(x) − eˣ·sin(x)' },
    ],
    matchingExplanation: 'Bei x·sin(x): u\'=1, v=sin(x), uv\'=x·cos(x). Bei x²·ln(x): u\'=2x, v=ln(x), uv\'=x²·(1/x)=x. Bei eˣ·cos(x): u\'=v=eˣ, uv\'=eˣ·(−sin x).',
    matchingHints: ['Produktregel immer: u\'v + uv\'.', 'Reihenfolge: erst ersten Faktor ableiten, dann zweiten.'],
    sortingQuestion: 'Leite f(x) = (x+1)·sin(x) mit der Produktregel ab. Ordne die Schritte.',
    sortingItems: [
      'u = x+1, v = sin(x) identifizieren',
      'u\' = 1, v\' = cos(x) berechnen',
      'Produktregel ansetzen: f\'(x) = u\'v + uv\'',
      '1·sin(x) + (x+1)·cos(x) einsetzen',
      'Ergebnis: f\'(x) = sin(x) + (x+1)cos(x)',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Produktregel-Schema: Faktoren identifizieren → ableiten → Formel ansetzen → einsetzen → vereinfachen.',
    sortingHints: ['Erst Faktoren benennen, dann ableiten.', 'Formel: u\'v + uv\'.'],
    errorQuestion: 'Jemand rechnet (x²·sin x)\' = 2x·cos x. Was ist der Fehler?',
    errorOptions: [
      'Beide Faktoren wurden gleichzeitig abgeleitet; der zweite Term x²·cos x fehlt',
      'sin(x) wurde falsch abgeleitet',
      '2x ist nicht die Ableitung von x²',
      'Das Ergebnis muss negativ sein',
    ],
    errorCorrect: 0,
    errorExplanation: 'Korrekt: (x²·sin x)\' = 2x·sin x + x²·cos x. Es fehlt der zweite Term der Produktregel: u·v\' = x²·cos x.',
    errorHints: ['Produktregel hat immer ZWEI Terme.', 'u\'v und uv\' dürfen nicht fehlen.'],
    transferQuestion: 'f(x) = x³·eˣ. Berechne f\'(0).',
    transferAnswer: 0,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'f\'(x) = 3x²·eˣ + x³·eˣ = eˣ(3x² + x³). f\'(0) = e⁰·(0 + 0) = 1·0 = 0.',
    transferHints: ['f\'(x) = 3x²·eˣ + x³·eˣ.', 'x = 0 einsetzen: alle Terme mit x verschwinden.'],
  },

  'abl-2-2': {
    explanation: String.raw`**Vertiefung Quotientenregel:** $\left(\frac{u}{v}\right)' = \frac{u'v - uv'}{v^2}$. Eselsbrücke: **NAZ** — Nenner mal Ableitung Zähler minus Zähler mal Ableitung Nenner, geteilt durch Nenner². Achtung: Die Reihenfolge im Zähler ist festgelegt — nicht u·v\' − u\'·v.`,
    conceptQuestion: 'f(x) = sin(x)/eˣ. Was ist f\'(x)?',
    conceptOptions: [
      '(cos(x)·eˣ − sin(x)·eˣ) / e²ˣ',
      'cos(x)/eˣ',
      '(sin(x) + cos(x))/eˣ',
      '−cos(x)/eˣ',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Quotientenregel: u = sin x, v = eˣ, u\' = cos x, v\' = eˣ. f\'(x) = (cos x·eˣ − sin x·eˣ)/e²ˣ = (cos x − sin x)/eˣ.',
    conceptHints: ['NAZ: u\' = cos x, v = eˣ im Zähler zuerst.', 'e²ˣ im Nenner kann als eˣ im Bruch vereinfacht werden.'],
    calcQuestion: 'f(x) = x/(x+1). Berechne f\'(2) als gekürzten Bruch. Gib den Dezimalwert an.',
    calcAnswer: 0.1111,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'f\'(x) = [(x+1)·1 − x·1]/(x+1)² = 1/(x+1)². f\'(2) = 1/9 ≈ 0,1111.',
    calcHints: ['f\'(x) = 1/(x+1)².', 'f\'(2) = 1/(2+1)² = 1/9.'],
    trueFalseStatement: 'Die Quotientenregel lautet (u/v)\' = (u\'v + uv\')/v².',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Die korrekte Quotientenregel lautet (u\'v − uv\')/v² mit Minus. Das Plus ist die Produktregel.',
    trueFalseHints: ['Quotientenregel: Minus im Zähler.', 'Produktregel hat ein Plus; Quotientenregel ein Minus.'],
    matchingQuestion: 'Ordne die Funktion ihrer Ableitung zu.',
    matchingPairs: [
      { left: '1/x²', right: '−2/x³' },
      { left: 'eˣ/x', right: '(eˣ·x − eˣ)/x²' },
      { left: 'sin(x)/cos(x) = tan(x)', right: '1/cos²(x)' },
    ],
    matchingExplanation: 'Bei 1/x²: als x^(−2) → −2x^(−3). Bei eˣ/x: Quotientenregel mit u=eˣ, v=x. Bei tan: Quotientenregel + sin²+cos²=1 → 1/cos².',
    matchingHints: ['tan(x) = sin/cos. Quotientenregel anwenden.', 'sin²+cos²=1 vereinfacht den Zähler bei tan.'],
    sortingQuestion: 'Leite f(x) = x²/(x+1) mit der Quotientenregel ab. Ordne die Schritte.',
    sortingItems: [
      'u = x², v = x+1 identifizieren',
      'u\' = 2x, v\' = 1 berechnen',
      'Zähler: u\'v − uv\' = 2x(x+1) − x²·1',
      'Zähler vereinfachen: 2x² + 2x − x² = x² + 2x',
      'Ergebnis: f\'(x) = (x² + 2x)/(x+1)²',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Schema: u und v identifizieren → ableiten → Zähler berechnen → vereinfachen → Nenner v² schreiben.',
    sortingHints: ['Zähler: u\'v − uv\'. Nenner: v².', '2x(x+1) = 2x²+2x.'],
    errorQuestion: 'Für f(x) = x/sin(x) rechnet jemand f\'(x) = 1/cos(x). Was ist falsch?',
    errorOptions: [
      'Die Quotientenregel wurde nicht angewendet; der zweite Term im Zähler fehlt',
      'Die Ableitung von x ist nicht 1',
      'sin(x)\' = −cos(x)',
      'Der Nenner muss sin²(x) − cos²(x) sein',
    ],
    errorCorrect: 0,
    errorExplanation: 'Korrekt: (x/sin x)\' = (1·sin x − x·cos x)/sin²(x). Der zweite Term −x·cos x fehlt komplett.',
    errorHints: ['Quotientenregel hat immer zwei Terme im Zähler.', 'NAZ: u\'v − uv\'. Der uv\'-Term fehlt.'],
    transferQuestion: 'f(x) = (x²+1)/(x−1). Berechne f\'(2).',
    transferAnswer: 2,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'f\'(x) = [2x(x−1) − (x²+1)·1]/(x−1)² = (2x²−2x−x²−1)/(x−1)² = (x²−2x−1)/(x−1)². f\'(2) = (4−4−1)/1 = −1. Neurechnung: Zähler 2·2·(2−1)−(4+1) = 4−5 = −1. Nenner (2−1)² = 1. f\'(2) = −1.',
    transferAnswer: -1,
    transferTolerance: 0.001,
    transferExplanation: 'f\'(x) = [2x(x−1) − (x²+1)]/(x−1)². Bei x=2: Zähler = 2·2·1 − 5 = 4 − 5 = −1. Nenner = 1². f\'(2) = −1.',
    transferHints: ['u = x²+1, v = x−1. u\' = 2x, v\' = 1.', 'Zähler bei x=2: 2·2·1 − 5 = −1.'],
  },

  'abl-2-3': {
    explanation: String.raw`**Vertiefung Kettenregel Schritt für Schritt:** Identifiziere zuerst die Schachtelung: Was ist die äußerste Funktion? Was steckt darin? Bei mehrfacher Verkettung (z.B. $\sin(e^{x^2})$) von außen nach innen vorgehen und bei jedem Schritt die innere Ableitung hinzumultiplizieren.`,
    conceptQuestion: 'f(x) = sin(3x²). Welche Identifikation ist korrekt?',
    conceptOptions: [
      'Äußere: 3x², Innere: sin',
      'Äußere: sin, Innere: 3x²',
      'Äußere: x², Innere: 3sin',
      'Keine Kettenregel nötig',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'Die äußerste Operation ist sin(…). Innen steht 3x². Äußere ableiten: cos(3x²). Innere ableiten: 6x. Ergebnis: f\'(x) = 6x·cos(3x²).',
    conceptHints: ['Welche Funktion wird zuletzt ausgeführt? Das ist die äußere.', 'sin(…) wird als letztes angewendet → sin ist äußere Funktion.'],
    calcQuestion: 'f(x) = e^(−2x). Berechne f\'(0).',
    calcAnswer: -2,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'Kettenregel: f\'(x) = e^(−2x)·(−2) = −2e^(−2x). f\'(0) = −2·e⁰ = −2·1 = −2.',
    calcHints: ['Innere Ableitung von −2x ist −2.', 'e⁰ = 1.'],
    trueFalseStatement: 'f(x) = ln(x²+1) hat die Ableitung f\'(x) = 1/(x²+1).',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Kettenregel: Äußere (ln u)\' = 1/u, innere (x²+1)\' = 2x. Also f\'(x) = 2x/(x²+1).',
    trueFalseHints: ['Die innere Ableitung 2x darf nicht vergessen werden.', '(ln u)\' = 1/u · u\'.'],
    matchingQuestion: 'Ordne die verkettete Funktion ihrer vollständigen Ableitung zu.',
    matchingPairs: [
      { left: '(x²+3)⁵', right: '10x(x²+3)⁴' },
      { left: 'cos(x³)', right: '−3x²·sin(x³)' },
      { left: 'ln(2x+1)', right: '2/(2x+1)' },
    ],
    matchingExplanation: 'Bei (x²+3)⁵: äußere 5u⁴, innere 2x → 5(x²+3)⁴·2x = 10x(x²+3)⁴. Bei cos(x³): äußere −sin, innere 3x². Bei ln(2x+1): äußere 1/u, innere 2.',
    matchingHints: ['Immer innere Ableitung hinzumultiplizieren.', 'Innere von x³ ist 3x².'],
    sortingQuestion: 'Leite f(x) = e^(sin x) mit der Kettenregel ab.',
    sortingItems: [
      'Äußere Funktion: e^u, Innere: u = sin(x)',
      'Äußere Ableitung: e^u = e^(sin x)',
      'Innere Ableitung: (sin x)\' = cos(x)',
      'Multiplizieren: e^(sin x)·cos(x)',
      'f\'(x) = cos(x)·e^(sin x)',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'f(x) = e^(sin x): e^u bleibt als äußere Ableitung erhalten; cos(x) kommt als innere Ableitung dazu.',
    sortingHints: ['e^u → e^u (äußere Ableitung bleibt gleich).', 'Mal innere Ableitung cos(x).'],
    errorQuestion: 'f(x) = (2x+1)³. Jemand schreibt f\'(x) = 3(2x+1)². Was fehlt?',
    errorOptions: [
      'Der Faktor 2 aus der inneren Ableitung von 2x+1',
      'Das Minuszeichen',
      'Der Exponent muss 2 sein, nicht 3−1=2',
      'Der Ausdruck sollte 6(2x+1)³ sein',
    ],
    errorCorrect: 0,
    errorExplanation: 'Korrekt: f\'(x) = 3(2x+1)²·2 = 6(2x+1)². Die innere Ableitung (2x+1)\' = 2 fehlt.',
    errorHints: ['(2x+1)\' = 2, nicht 1.', 'Innere Ableitung ist immer mal hinzuzunehmen.'],
    transferQuestion: 'f(x) = sin(2x)·e^(−x). Berechne f\'(0). (cos 0 = 1, sin 0 = 0, e⁰ = 1)',
    transferAnswer: 2,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'Produktregel + Kettenregel: f\'(x) = 2cos(2x)·e^(−x) + sin(2x)·(−e^(−x)). f\'(0) = 2·1·1 + 0·(−1) = 2.',
    transferHints: ['Produktregel: u = sin(2x), v = e^(−x).', 'sin(0) = 0, der zweite Term fällt weg.'],
  },

  'abl-2-4': {
    explanation: String.raw`**Vertiefung gemischte Regeln:** Analysiere erst die Struktur: Summe → Summenregel, Produkt → Produktregel, Quotient → Quotientenregel, Verkettung → Kettenregel. Oft sind Regeln zu kombinieren, z.B. Produkt zweier verketteter Funktionen → Produktregel + Kettenregel für jeden Faktor.`,
    conceptQuestion: 'f(x) = x²·sin(3x). Welche Regeln werden benötigt?',
    conceptOptions: [
      'Nur Kettenregel',
      'Produktregel (für x²·sin) + Kettenregel (für sin(3x))',
      'Nur Produktregel',
      'Quotientenregel',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'x² und sin(3x) werden multipliziert → Produktregel. sin(3x) ist verkettet → Kettenregel bei der Ableitung von v = sin(3x): v\' = 3cos(3x).',
    conceptHints: ['Produkt zweier Funktionen → Produktregel.', 'sin(3x) ist verkettet → Kettenregel beim Ableiten.'],
    calcQuestion: 'f(x) = eˣ·sin(x). Berechne f\'(π/2) näherungsweise. (e^(π/2) ≈ 4,81, sin(π/2) = 1, cos(π/2) = 0)',
    calcAnswer: 4.81,
    calcTolerance: 0.05,
    calcUnit: '',
    calcExplanation: 'Produktregel: f\'(x) = eˣ·sin(x) + eˣ·cos(x) = eˣ(sin x + cos x). f\'(π/2) = e^(π/2)·(1+0) = 4,81.',
    calcHints: ['f\'(x) = eˣ(sin x + cos x).', 'Einsetzen: e^(π/2)·(1+0).'],
    trueFalseStatement: 'Bei f(x) = sin(x)/eˣ darf man Kettenregel und Quotientenregel nicht kombinieren.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Regeln können beliebig kombiniert werden. Alternativ kann man f(x) = sin(x)·e^(−x) schreiben und Produkt- + Kettenregel verwenden.',
    trueFalseHints: ['Regeln schließen sich nie gegenseitig aus.', 'sin(x)/eˣ = sin(x)·e^(−x) — beide Darstellungen sind lösbar.'],
    matchingQuestion: 'Ordne die Funktion der Hauptregel zu, die benötigt wird.',
    matchingPairs: [
      { left: 'x·ln(x)', right: 'Produktregel' },
      { left: 'sin(x)/x', right: 'Quotientenregel' },
      { left: 'e^(x²+1)', right: 'Kettenregel' },
    ],
    matchingExplanation: 'x·ln(x): Produkt zweier Funktionen → Produktregel. sin(x)/x: Quotient → Quotientenregel. e^(x²+1): Verkettung → Kettenregel.',
    matchingHints: ['Erkenne die Grundstruktur: Produkt/Quotient/Verkettung.', 'Mehrere Regeln können gleichzeitig nötig sein.'],
    sortingQuestion: 'Leite f(x) = x·e^(x²) ab (Produkt- + Kettenregel). Ordne die Schritte.',
    sortingItems: [
      'Produktregel ansetzen: u = x, v = e^(x²)',
      'u\' = 1 berechnen',
      'v\' mit Kettenregel: 2x·e^(x²)',
      'Produktregel: f\'(x) = 1·e^(x²) + x·2x·e^(x²)',
      'Vereinfachen: f\'(x) = e^(x²)(1 + 2x²)',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Produktregel als Rahmen, Kettenregel für v = e^(x²) anwenden, dann zusammenfassen.',
    sortingHints: ['v = e^(x²): Kettenregel liefert v\' = 2x·e^(x²).', 'Produktregel: u\'v + uv\'.'],
    errorQuestion: 'f(x) = ln(x²)·sin(x). Jemand rechnet f\'(x) = (2/x)·cos(x). Was fehlt?',
    errorOptions: [
      'Der zweite Term der Produktregel: ln(x²)·cos(x)',
      'Das Minus bei cos(x)',
      'Die Kettenregel bei ln(x²)',
      'Die Funktion kann nicht abgeleitet werden',
    ],
    errorCorrect: 0,
    errorExplanation: 'Korrekt: f\'(x) = (2/x)·sin(x) + ln(x²)·cos(x). Der zweite Term der Produktregel u·v\' = ln(x²)·cos(x) fehlt.',
    errorHints: ['Produktregel hat immer zwei Terme: u\'v UND uv\'.', 'Nur u\'v wurde berechnet.'],
    transferQuestion: 'f(x) = x²·cos(x). Berechne f\'(π). (cos π = −1, sin π = 0)',
    transferAnswer: -2,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'Produktregel: f\'(x) = 2x·cos(x) + x²·(−sin x). f\'(π) = 2π·(−1) + π²·0 = −2π ≈ −6,28. Warte — Frage nach numerischem Ergebnis: f\'(π) = −2π.',
    transferAnswer: -6.283,
    transferTolerance: 0.01,
    transferExplanation: 'f\'(x) = 2x·cos(x) − x²·sin(x). f\'(π) = 2π·cos(π) − π²·sin(π) = 2π·(−1) − 0 = −2π ≈ −6,283.',
    transferHints: ['f\'(x) = 2x·cos(x) − x²·sin(x).', 'sin(π) = 0, cos(π) = −1. −2π ≈ −6,283.'],
  },

  'abl-3-1': {
    explanation: String.raw`**Vertiefung Monotonie und Extremwerte:** Aus dem Vorzeichen von $f'$ lässt sich die Monotonie lesen: $f' > 0$ → steigend, $f' < 0$ → fallend. An den Nullstellen von $f'$ liegen Kandidaten für Extremstellen. Der **Vorzeichenwechsel** von $f'$ entscheidet: $+ \to -$ ist Maximum, $- \to +$ ist Minimum.`,
    conceptQuestion: 'f\'(x) wechselt bei x₀ das Vorzeichen von + nach −. Was bedeutet das?',
    conceptOptions: [
      'f hat bei x₀ ein lokales Minimum',
      'f hat bei x₀ ein lokales Maximum',
      'f hat bei x₀ einen Wendepunkt',
      'f hat bei x₀ eine Nullstelle',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'Vorzeichenwechsel + → −: f steigt vor x₀ und fällt danach → lokales Maximum bei x₀.',
    conceptHints: ['+ → − : Funktion steigt, dann fällt → Spitze oben → Maximum.', '− → + : Funktion fällt, dann steigt → Tal → Minimum.'],
    calcQuestion: 'f(x) = x³ − 6x² + 9x + 1. Bestimme die x-Koordinate des lokalen Maximums.',
    calcAnswer: 1,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'f\'(x) = 3x² − 12x + 9 = 3(x−1)(x−3) = 0 → x = 1 oder x = 3. f\'\'(1) = 6·1−12 = −6 < 0 → Maximum bei x = 1.',
    calcHints: ['f\'(x) = 3x² − 12x + 9 = 0.', 'f\'\'(x) = 6x − 12. Bei x=1: f\'\'(1) = −6 < 0.'],
    trueFalseStatement: 'f\'(x) > 0 für alle x im Intervall (a,b) bedeutet, dass f auf (a,b) streng monoton steigend ist.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Positive Ableitung bedeutet positive Steigung überall im Intervall → Funktion steigt überall → streng monoton steigend.',
    trueFalseHints: ['f\' > 0 = Steigung positiv = Funktion geht bergauf.', 'Streng monoton steigend: x₁ < x₂ → f(x₁) < f(x₂).'],
    matchingQuestion: 'Ordne das Vorzeichen von f\'(x) dem Monotonieverhalten zu.',
    matchingPairs: [
      { left: "f'(x) > 0", right: 'f steigt streng monoton' },
      { left: "f'(x) < 0", right: 'f fällt streng monoton' },
      { left: "f'(x₀) = 0 mit + → − Wechsel", right: 'lokales Maximum bei x₀' },
    ],
    matchingExplanation: 'Vorzeichen von f\' bestimmt direkt das Monotonieverhalten. An Nullstellen entscheidet der Vorzeichenwechsel über den Extremtyp.',
    matchingHints: ['Positiv = bergauf, negativ = bergab.', 'Vorzeichenwechsel bei der Nullstelle = Extremum.'],
    sortingQuestion: 'Bestimme die Monotoniebereiche von f(x) = x³ − 3x in der richtigen Reihenfolge.',
    sortingItems: [
      'f\'(x) = 3x² − 3 berechnen',
      'f\'(x) = 0: 3x²=3 → x = ±1',
      'Vorzeichentabelle für f\'(x) erstellen',
      'x < −1: f\'(x) > 0 → steigend',
      '−1 < x < 1: f\'(x) < 0 → fallend',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Ableitungsschritte: f\' berechnen → Nullstellen → Vorzeichentabelle → Monotoniebereiche ablesen.',
    sortingHints: ['Nullstellen teilen die Zahlenachse in Bereiche.', 'In jedem Bereich Vorzeichen von f\' prüfen.'],
    errorQuestion: 'f(x) = x⁴. Jemand sagt: "x₀ = 0 ist ein Minimum, weil f\'(0) = 0." Was fehlt?',
    errorOptions: [
      'Die Bestätigung durch f\'\'(0) oder Vorzeichenwechsel von f\'',
      'f\'(x) = 4x³ ist falsch',
      'x⁴ hat kein Minimum',
      'f(0) muss zuerst berechnet werden',
    ],
    errorCorrect: 0,
    errorExplanation: 'f\'(0) = 0 ist notwendig, aber nicht hinreichend. Hier: f\'\'(0) = 12·0² = 0 → zweites Kriterium versagt. Vorzeichentest: f\'(x) = 4x³ wechselt von − zu + bei x=0 → tatsächlich Minimum, aber die Begründung muss das zeigen.',
    errorHints: ['f\' = 0 allein beweist kein Extremum.', 'f\'\' oder Vorzeichenwechsel von f\' sind notwendig.'],
    transferQuestion: 'f(x) = −2x² + 8x − 3. Berechne den maximalen Funktionswert.',
    transferAnswer: 5,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'f\'(x) = −4x + 8 = 0 → x = 2. f\'\'(x) = −4 < 0 → Maximum. f(2) = −8 + 16 − 3 = 5.',
    transferHints: ['f\'(x) = −4x+8 = 0 → x = 2.', 'f(2) = −8+16−3.'],
  },

  'abl-3-2': {
    explanation: String.raw`**Vertiefung Krümmung und Wendepunkte:** $f''(x) > 0$ → linksgekrümmt (Schüsselform $\cup$), $f''(x) < 0$ → rechtsgekrümmt (Hügelform $\cap$). Ein Wendepunkt ist ein Punkt, an dem die Krümmung das Vorzeichen wechselt. Notwendig: $f''(x_0) = 0$. Hinreichend: $f'''(x_0) \neq 0$.`,
    conceptQuestion: 'Welche Aussage über f\'\'(x) ist korrekt?',
    conceptOptions: [
      'f\'\'(x) > 0 bedeutet, die Kurve fällt',
      'f\'\'(x) > 0 bedeutet, die Kurve ist linksgekrümmt (nach oben gewölbt)',
      'f\'\'(x) = 0 beweist einen Wendepunkt',
      'f\'\'(x) < 0 bedeutet, die Kurve hat ein Minimum',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'f\'\'(x) > 0 bedeutet: Die Steigung f\' nimmt zu → Kurve wölbt sich nach oben (Schüsselform). f\'\'(x) < 0 → Steigung nimmt ab → Hügelform.',
    conceptHints: ['f\'\' ist die Ableitung von f\'. Positiv = f\' steigt.', 'Schüsselform ∪ → f\'\' > 0.'],
    calcQuestion: 'f(x) = x⁴ − 6x² + 1. An welcher positiven Stelle liegt ein Wendepunkt?',
    calcAnswer: 1,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'f\'\'(x) = 12x² − 12 = 12(x²−1) = 0 → x = ±1. f\'\'\'(x) = 24x. f\'\'\'(1) = 24 ≠ 0 → Wendepunkt bei x = 1.',
    calcHints: ['f\'\'(x) = 12x² − 12 = 0 → x² = 1 → x = ±1.', 'f\'\'\' ≠ 0 bestätigt den Wendepunkt.'],
    trueFalseStatement: 'f\'\'(x₀) = 0 ist hinreichend für einen Wendepunkt bei x₀.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. f\'\'(x₀) = 0 ist nur notwendig. Gegenbeispiel: f(x) = x⁴, f\'\'(0) = 12·0² = 0, aber x = 0 ist ein Minimum, kein Wendepunkt. Hinreichend ist f\'\'\'(x₀) ≠ 0 oder ein Vorzeichenwechsel von f\'\'.',
    trueFalseHints: ['x⁴ hat bei x=0 kein Krümmungswechsel, obwohl f\'\'(0)=0.', 'Hinreichend ist der Vorzeichenwechsel von f\'\'.'],
    matchingQuestion: 'Ordne das Vorzeichen von f\'\'(x) der Krümmungsform zu.',
    matchingPairs: [
      { left: "f''(x) > 0", right: 'linksgekrümmt, Schüsselform ∪' },
      { left: "f''(x) < 0", right: 'rechtsgekrümmt, Hügelform ∩' },
      { left: "f''(x₀) = 0 mit Vorzeichenwechsel", right: 'Wendepunkt bei x₀' },
    ],
    matchingExplanation: 'Vorzeichen von f\'\' beschreibt die Krümmungsrichtung. Wechselt f\'\' das Vorzeichen, liegt ein Wendepunkt vor.',
    matchingHints: ['∪ = Schüssel = linksgekrümmt = f\'\'>0.', '∩ = Hügel = rechtsgekrümmt = f\'\'<0.'],
    sortingQuestion: 'Bestimme Wendepunkte von f(x) = x³ − 3x in der richtigen Reihenfolge.',
    sortingItems: [
      'f\'(x) = 3x² − 3 berechnen',
      'f\'\'(x) = 6x berechnen',
      'f\'\'(x) = 0 setzen: x = 0',
      'f\'\'\'(x) = 6 ≠ 0 → Wendepunkt bestätigt',
      'Wendepunkt: (0, f(0)) = (0, 0)',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Für Wendepunkte: f\' → f\'\' → f\'\' = 0 lösen → f\'\'\' prüfen → y-Wert berechnen.',
    sortingHints: ['Erst f\'\' berechnen, dann Nullstellen.', 'f\'\'\' ≠ 0 ist die Bestätigung.'],
    errorQuestion: 'f(x) = x⁴. Jemand sagt: "Wendepunkt bei x=0, weil f\'\'(0)=0." Was ist falsch?',
    errorOptions: [
      'f\'\'(0) = 0, aber f\'\'\' (0) = 0 ebenfalls, kein Vorzeichenwechsel von f\'\' → kein Wendepunkt',
      'f\'\'(x) = 4x², also f\'\'(0) ≠ 0',
      'x⁴ hat keinen Definitionsbereich',
      'Wendepunkte brauchen f\' = 0, nicht f\'\' = 0',
    ],
    errorCorrect: 0,
    errorExplanation: 'f(x) = x⁴: f\'\'(x) = 12x². f\'\'(0) = 0, aber f\'\'\'(x) = 24x → f\'\'\'(0) = 0. f\'\' wechselt bei x=0 nicht das Vorzeichen (f\'\'≥0 überall) → kein Wendepunkt, sondern Minimum.',
    errorHints: ['f\'\' = 12x² ≥ 0 für alle x → kein Vorzeichenwechsel.', 'Kein Vorzeichenwechsel = kein Wendepunkt.'],
    transferQuestion: 'f(x) = x³ − 3x² + 2. Berechne den y-Wert des Wendepunkts.',
    transferAnswer: 0,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'f\'\'(x) = 6x − 6 = 0 → x = 1. f\'\'\'(x) = 6 ≠ 0 → Wendepunkt. f(1) = 1 − 3 + 2 = 0.',
    transferHints: ['f\'\'(x) = 6x−6 = 0 → x = 1.', 'f(1) = 1−3+2 = 0.'],
  },

  'abl-3-3': {
    explanation: String.raw`**Vertiefung vollständige Kurvendiskussion:** Schema: (1) Definitionsbereich, (2) Symmetrie ($f(-x)$ prüfen), (3) Nullstellen ($f=0$), (4) Ableitungen berechnen, (5) Extrema ($f'=0$, $f''$ auswerten), (6) Wendepunkte ($f''=0$, $f'''$ prüfen), (7) Verhalten $x \to \pm\infty$, (8) Graph skizzieren.`,
    conceptQuestion: 'f(x) = x⁴ − 8x² ist punktsymmetrisch zum Ursprung. Stimmt das?',
    conceptOptions: [
      'Ja, weil x⁴ und x² ungerade Potenzen haben',
      'Nein. f(−x) = x⁴ − 8x² = f(x) → f ist achsensymmetrisch zur y-Achse',
      'Ja, denn alle Terme sind negativ',
      'Nein, f hat gar keine Symmetrie',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'f(−x) = (−x)⁴ − 8(−x)² = x⁴ − 8x² = f(x). Damit gilt f(−x) = f(x) → achsensymmetrisch. Punktsymmetrie würde f(−x) = −f(x) erfordern.',
    conceptHints: ['Gerade Potenzen (x², x⁴) liefern f(−x) = f(x) → Achsensymmetrie.', 'Ungerade Potenzen (x, x³) liefern f(−x) = −f(x) → Punktsymmetrie.'],
    calcQuestion: 'f(x) = x³ − 3x + 2. Berechne den y-Wert des lokalen Maximums.',
    calcAnswer: 4,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'f\'(x) = 3x²−3 = 0 → x = ±1. f\'\'(−1) = −6 < 0 → Maximum bei x=−1. f(−1) = −1+3+2 = 4.',
    calcHints: ['Extremstellen: x = ±1. f\'\' bestimmt ob Max oder Min.', 'f\'\'(−1) = 6·(−1) = −6 < 0 → Maximum.'],
    trueFalseStatement: 'Für f(x) = 2x³ − 6x + 1 gilt: f(x) → +∞ für x → +∞.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Der führende Term ist 2x³. Für x → +∞: 2x³ → +∞. Positiver Koeffizient und ungerade Potenz → +∞.',
    trueFalseHints: ['Führender Term bestimmt das Verhalten.', 'Positiver Koeffizient × ungerade Potenz: +∞ für x → +∞.'],
    matchingQuestion: 'Ordne den Kurvendiskussions-Schritt dem zugehörigen Werkzeug zu.',
    matchingPairs: [
      { left: 'Extrema bestimmen', right: "f'(x) = 0 lösen und f'' auswerten" },
      { left: 'Wendepunkte bestimmen', right: "f''(x) = 0 lösen und f''' prüfen" },
      { left: 'Symmetrie prüfen', right: 'f(−x) mit f(x) und −f(x) vergleichen' },
    ],
    matchingExplanation: 'Jeder Schritt hat sein eigenes Werkzeug. Extrema: f\'. Wendepunkte: f\'\'. Symmetrie: Einsetzen von −x.',
    matchingHints: ['Extrema brauchen f\', Wendepunkte brauchen f\'\'.', 'Symmetrie: f(−x) = f(x) → achsen; f(−x) = −f(x) → punkt.'],
    sortingQuestion: 'Bringe die vollständige Kurvendiskussion von f(x) = x³ − 3x + 2 in die richtige Reihenfolge.',
    sortingItems: [
      'D = ℝ, keine Einschränkungen',
      'f(−x) = −x³+3x+2 ≠ ±f(x): keine Symmetrie',
      'Nullstellen: f(x) = 0 → x ≈ −2; x=1 (doppelt)',
      'f\'(x) = 3x²−3, f\'\'(x) = 6x berechnen',
      'Extrema: x=±1; Max bei x=−1, Min bei x=1',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Schema einhalten: Definitionsbereich → Symmetrie → Nullstellen → Ableitungen → Extrema → Wendepunkte → Grenzwerte.',
    sortingHints: ['Immer mit Definitionsbereich starten.', 'Symmetrie vor Nullstellen.'],
    errorQuestion: 'Jemand sucht Extrema von f(x) = x³ − 12x und findet nur x = 2. Was wurde übersehen?',
    errorOptions: [
      'f\'(x) = 3x²−12 = 3(x−2)(x+2) = 0 hat zwei Lösungen: x = 2 und x = −2',
      'Die Ableitung ist f\'(x) = 3x² − 12x',
      'x = 2 ist kein Extremum',
      'Man braucht f\'\'\' für Extrema',
    ],
    errorCorrect: 0,
    errorExplanation: 'f\'(x) = 3x²−12 = 0 → x² = 4 → x = ±2. Beide Lösungen müssen betrachtet werden. Bei x = −2: f\'\'(−2) = −12 < 0 → Maximum. Bei x = 2: f\'\'(2) = 12 > 0 → Minimum.',
    errorHints: ['x² = 4 hat zwei Lösungen: ±2.', 'Beide Kandidaten durch f\'\' prüfen.'],
    transferQuestion: 'f(x) = x⁴ − 2x². Bestimme die Anzahl der lokalen Extremstellen.',
    transferAnswer: 3,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'f\'(x) = 4x³−4x = 4x(x²−1) = 4x(x−1)(x+1) = 0 → x ∈ {−1, 0, 1}. f\'\'(x) = 12x²−4. f\'\'(0) = −4 < 0 → Maximum. f\'\'(±1) = 8 > 0 → Minima. Insgesamt 3 Extremstellen.',
    transferHints: ['f\'(x) = 4x³−4x = 4x(x²−1) = 0.', 'Drei Nullstellen → drei Extremstellen-Kandidaten.'],
  },

  'abl-3-4': {
    exam: true,
    explanation: String.raw`**Prüfungsvertiefung Kurvendiskussion:** An der TU Wien wird die vollständige Kurvendiskussion als ein zusammenhängender Prozess bewertet. Alle Schritte müssen begründet werden: Nullstellen, Extrema mit Typ-Nachweis, Wendepunkte mit Vorzeichenwechsel-Bestätigung, Grenzwertverhalten und Asymptoten.`,
    conceptQuestion: 'f(x) = xe^(−x) für x ≥ 0. Welche Aussage ist korrekt?',
    conceptOptions: [
      'f hat kein Maximum, weil eˣ immer wächst',
      'f hat ein globales Maximum bei x = 1 mit f(1) = 1/e',
      'f hat ein Maximum bei x = 0',
      'f ist monoton steigend für alle x ≥ 0',
    ],
    conceptCorrect: 1,
    conceptExplanation: 'f\'(x) = e^(−x)−xe^(−x) = (1−x)e^(−x) = 0 → x = 1. f\'\'(1) = (x−2)e^(−x)|_{x=1} = −e^(−1) < 0 → Maximum. f(1) = e^(−1) = 1/e ≈ 0,368.',
    conceptHints: ['Produktregel: f\' = (1−x)e^(−x).', 'e^(−x) > 0 immer → Vorzeichen von f\' hängt von (1−x) ab.'],
    calcQuestion: 'f(x) = x³ − 12x. Berechne den Wert des lokalen Maximums f(−2).',
    calcAnswer: 16,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'f\'(x) = 3x²−12 = 0 → x = ±2. f\'\'(−2) = 6·(−2) = −12 < 0 → Maximum. f(−2) = −8+24 = 16.',
    calcHints: ['f\'(x) = 3x²−12 = 0 → x = ±2.', 'f(−2) = (−2)³−12·(−2) = −8+24.'],
    trueFalseStatement: 'f(x) = x⁴ − 4x³ hat bei x = 0 einen Sattelpunkt (Terrassenpunkt), kein lokales Extremum.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. f\'(x) = 4x³−12x² = 4x²(x−3) = 0 → x = 0 oder x = 3. f\'\'(0) = 0 → zweites Kriterium versagt. Vorzeichentest: f\'(x) = 4x²(x−3). Für x < 0: f\' < 0. Für 0 < x < 3: f\' < 0. Kein Vorzeichenwechsel → Sattelpunkt, kein Extremum.',
    trueFalseHints: ['f\'\' = 0 → zweites Kriterium versagt.', 'Vorzeichentest: f\' wechselt Vorzeichen nicht bei x = 0.'],
    matchingQuestion: 'Ordne die Eigenschaften von f(x) = x³ − 12x der richtigen Aussage zu.',
    matchingPairs: [
      { left: 'Lokales Maximum', right: 'x = −2, f(−2) = 16' },
      { left: 'Lokales Minimum', right: 'x = 2, f(2) = −16' },
      { left: 'Wendepunkt', right: 'x = 0, f(0) = 0' },
    ],
    matchingExplanation: 'f\'= 3x²−12=0 → x=±2. f\'\'=6x → f\'\'(−2)=−12<0 (Max), f\'\'(2)=12>0 (Min). f\'\'=6x=0 → x=0, f\'\'\'=6≠0 → Wendepunkt.',
    matchingHints: ['f\'\'(−2) < 0 → Maximum.', 'f\'\' = 0 bei x = 0 → Wendepunkt.'],
    sortingQuestion: 'Vollständige Kurvendiskussion von f(x) = x⁴ − 8x² in der richtigen Reihenfolge.',
    sortingItems: [
      'D = ℝ; f(−x) = f(x) → achsensymmetrisch',
      'Nullstellen: x⁴−8x²=x²(x²−8)=0 → x=0, x=±2√2',
      'f\'(x) = 4x³−16x = 4x(x²−4) = 0 → x=0, x=±2',
      'f\'\'(x) = 12x²−16: f\'\'(0)=−16<0 (Max), f\'\'(±2)=32>0 (Min)',
      'Wendepunkte: f\'\'=12x²−16=0 → x=±1/√3·√3=±2/√3',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Reihenfolge: Definitionsbereich/Symmetrie → Nullstellen → Ableitungen/Extrema → zweite Ableitung/Minima-Maxima → Wendepunkte.',
    sortingHints: ['Immer: D und Symmetrie zuerst.', 'Ableitungen vor Extrema.'],
    errorQuestion: 'f(x) = x²/(x²+1). Jemand behauptet: lim(x→∞) f(x) = 0. Welcher Fehler liegt vor?',
    errorOptions: [
      'Der Grenzwert ist 1, nicht 0; Zähler und Nenner wachsen mit x² gleich schnell',
      'Der Grenzwert ist ∞',
      'Der Grenzwert ist nicht definiert',
      'Der Grenzwert hängt vom Vorzeichen von x ab',
    ],
    errorCorrect: 0,
    errorExplanation: 'f(x) = x²/(x²+1). Durch x² dividieren: 1/(1+1/x²). Für x→∞: 1/x²→0 → Grenzwert = 1/1 = 1. Die Funktion hat die horizontale Asymptote y = 1.',
    errorHints: ['Durch x² (höchste Potenz) dividieren.', '1/x² → 0 für x → ∞.'],
    transferQuestion: 'f(x) = x·e^(−x²). Berechne f\'(0).',
    transferAnswer: 1,
    transferTolerance: 0.001,
    transferUnit: '',
    transferExplanation: 'Produktregel + Kettenregel: f\'(x) = e^(−x²) + x·(−2x)·e^(−x²) = e^(−x²)(1−2x²). f\'(0) = e⁰·(1−0) = 1.',
    transferHints: ['Produktregel: u=x, v=e^(−x²). v\'=−2x·e^(−x²) (Kettenregel).', 'f\'(0) = e⁰·(1−0) = 1.'],
  },
}

export const ableitungSupplements = Object.fromEntries(
  Object.entries(profiles).map(([lessonId, profile]) => [
    lessonId,
    {
      explanation: profile.explanation,
      exercises: bank(profile),
    },
  ])
)
