function mc(question, options, correctIndex, explanation, hints = []) {
  return { type: 'multiple-choice', question, options, correctIndex, explanation, hints }
}

function ni(question, correctValue, tolerance, unit, explanation, hints = []) {
  return { type: 'number-input', question, correctValue, tolerance, unit, explanation, hints }
}

function tf(statement, correct, explanation, hints = []) {
  return { type: 'true-false', statement, correct, explanation, hints }
}

function matching(question, pairs, explanation, hints = []) {
  return { type: 'matching', question, pairs, explanation, hints }
}

function sorting(question, items, correctOrder, explanation, hints = []) {
  return { type: 'sorting', question, items, correctOrder, explanation, hints }
}

function withExamPrefix(exercise, exam) {
  if (!exam) return exercise
  if (exercise.question && !exercise.question.includes('[PRÜFUNG]')) {
    return { ...exercise, question: `[PRÜFUNG] ${exercise.question}` }
  }
  if (exercise.statement && !exercise.statement.includes('[PRÜFUNG]')) {
    return { ...exercise, statement: `[PRÜFUNG] ${exercise.statement}` }
  }
  return exercise
}

function bank(profile) {
  const exercises = [
    mc(profile.conceptQuestion, profile.conceptOptions, profile.conceptCorrect, profile.conceptExplanation, profile.conceptHints),
    ni(profile.calcQuestion, profile.calcAnswer, profile.calcTolerance, profile.calcUnit, profile.calcExplanation, profile.calcHints),
    tf(profile.trueFalseStatement, profile.trueFalseCorrect, profile.trueFalseExplanation, profile.trueFalseHints),
    matching(profile.matchingQuestion, profile.matchingPairs, profile.matchingExplanation, profile.matchingHints),
    sorting(profile.sortingQuestion, profile.sortingItems, profile.sortingOrder, profile.sortingExplanation, profile.sortingHints),
    mc(profile.errorQuestion, profile.errorOptions, profile.errorCorrect, profile.errorExplanation, profile.errorHints),
    ni(profile.transferQuestion, profile.transferAnswer, profile.transferTolerance, profile.transferUnit, profile.transferExplanation, profile.transferHints),
  ]
  return exercises.map((exercise) => withExamPrefix(exercise, profile.exam))
}

const profiles = {
  'dgl-1-1': {
    explanation: String.raw`**Vertiefung Grundbegriffe:** Eine DGL enthält die gesuchte Funktion $y(x)$ und mindestens eine ihrer Ableitungen. Die **Ordnung** ist die höchste vorkommende Ableitung. Eine DGL ist **linear**, wenn $y$ und alle Ableitungen nur in der ersten Potenz stehen — kein $y^2$, kein $\sin(y)$. Die allgemeine Lösung enthält so viele freie Konstanten $C$ wie die Ordnung angibt; Anfangsbedingungen legen sie fest.`,
    conceptQuestion: 'Was unterscheidet eine Differentialgleichung von einer gewöhnlichen algebraischen Gleichung?',
    conceptOptions: [
      'Eine DGL enthält eine unbekannte Funktion und mindestens eine ihrer Ableitungen',
      'Eine DGL enthält nur Zahlen und keine Variablen',
      'Eine DGL hat immer genau eine Lösung',
      'Eine DGL besteht aus zwei separaten Gleichungen',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'In einer DGL ist die gesuchte Größe eine Funktion y(x), nicht nur eine Zahl. Außerdem treten Ableitungen y\', y\'\', ... auf. Das Ziel ist, die Funktion y(x) zu finden, die die Gleichung erfüllt.',
    conceptHints: ['Das Wort „Differential" verweist auf den Differentialquotienten (Ableitung).', 'Algebr. Gleichung: Unbekannte ist eine Zahl. DGL: Unbekannte ist eine Funktion.'],
    calcQuestion: 'Welche Ordnung hat die DGL y\'\' + 5y\' − 2y = 0? Gib die Ordnung als ganze Zahl an.',
    calcAnswer: 2,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'Die höchste Ableitung ist y\'\' (zweite Ableitung). Daher ist die Ordnung 2.',
    calcHints: ['Ordnung = Anzahl der Striche bei der höchsten Ableitung.', 'y\'\' hat zwei Striche → Ordnung 2.'],
    trueFalseStatement: 'Die DGL y\' = y² ist linear, weil nur die erste Ableitung y\' vorkommt.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Obwohl nur y\' als Ableitung auftritt, ist y² nichtlinear: y kommt in der zweiten Potenz vor. Linear bedeutet, dass y und alle Ableitungen ausschließlich in der ersten Potenz stehen.',
    trueFalseHints: ['Linearität prüfen: Darf y nur in der Potenz 1 auftreten?', 'y² ist eine quadratische (nichtlineare) Funktion von y.'],
    matchingQuestion: 'Ordne die DGL ihren Eigenschaften zu.',
    matchingPairs: [
      { left: 'y\' = 2y', right: 'linear, Ordnung 1' },
      { left: 'y\'\' + y = 0', right: 'linear, Ordnung 2' },
      { left: 'y\' = y²', right: 'nichtlinear, Ordnung 1' },
    ],
    matchingExplanation: 'y\' = 2y: nur y\' und y in Potenz 1 → linear, Ordnung 1. y\'\' + y = 0: höchste Ableitung y\'\', alle Terme linear → linear, Ordnung 2. y\' = y²: y² ist quadratisch → nichtlinear, Ordnung 1.',
    matchingHints: ['Ordnung = höchste Ableitung. Linearität = keine Potenzen > 1 bei y und Ableitungen.', 'Nichtlinear sobald y², y·y\', sin(y) oder ähnliches auftritt.'],
    sortingQuestion: 'Bringe die Schritte zum Lösen eines Anfangswertproblems in die richtige Reihenfolge.',
    sortingItems: [
      'DGL und Anfangsbedingung lesen',
      'Allgemeine Lösung mit Konstante C bestimmen',
      'Anfangsbedingung einsetzen, C berechnen',
      'Spezielle Lösung aufschreiben',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Erst die Aufgabe erfassen, dann die allgemeine Lösung finden, dann C aus der Anfangsbedingung bestimmen, abschließend die spezielle Lösung notieren.',
    sortingHints: ['Die allgemeine Lösung kommt vor der Anfangsbedingung.', 'Erst C bestimmen, dann die spezielle Lösung hinschreiben.'],
    errorQuestion: 'Jemand behauptet: „Die allgemeine Lösung von y\' = 3y lautet y = 3x + C." Was ist daran falsch?',
    errorOptions: [
      'Die Lösung ist keine Exponentialfunktion; y\' = 3y erfordert y = Ce^{3x}',
      'Die Konstante C darf nicht addiert werden',
      'Die DGL hat keine allgemeine Lösung',
      'Die Ordnung der DGL wurde falsch bestimmt',
    ],
    errorCorrect: 0,
    errorExplanation: 'y\' = 3y bedeutet, dass die Ableitung der Funktion gleich dem 3-fachen der Funktion selbst ist. Das erfüllt nur y = Ce^{3x}, nicht eine lineare Funktion 3x + C.',
    errorHints: ['Einsetzen prüfen: Ist (3x + C)\' = 3·(3x + C)? Nein, denn links steht 3, rechts 9x + 3C.', 'y\' proportional zu y → Exponentialfunktion.'],
    transferQuestion: 'Die DGL y\' = 4y hat die allgemeine Lösung y = Ce^{4x}. Mit y(0) = 2: Welchen Wert hat y(0,5)? (e² ≈ 7,389)',
    transferAnswer: 14.78,
    transferTolerance: 0.1,
    transferUnit: '',
    transferExplanation: 'y(0) = C·e^0 = C = 2. Also y(x) = 2e^{4x}. y(0,5) = 2e^{4·0,5} = 2e² ≈ 2·7,389 = 14,778 ≈ 14,78.',
    transferHints: ['Erst C aus y(0) = 2 bestimmen.', 'Dann x = 0,5 einsetzen: y(0,5) = 2e².'],
  },

  'dgl-1-2': {
    explanation: String.raw`**Vertiefung Trennung der Variablen:** Die Methode funktioniert, wenn sich die DGL in die Form $\frac{dy}{dx} = g(x)\cdot h(y)$ bringen lässt. Man bringt alles mit $y$ (und $dy$) auf eine Seite, alles mit $x$ (und $dx$) auf die andere und integriert beide Seiten separat. Bei einem AWP setzt man die Anfangsbedingung ein, um $C$ zu bestimmen.`,
    conceptQuestion: 'Welche Voraussetzung muss eine DGL erfüllen, damit Trennung der Variablen anwendbar ist?',
    conceptOptions: [
      'Die rechte Seite lässt sich als Produkt einer reinen x-Funktion und einer reinen y-Funktion schreiben',
      'Die DGL muss zweiter Ordnung sein',
      'Die DGL muss homogen und linear sein',
      'Die rechte Seite darf keine Funktionen enthalten',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Trennung der Variablen setzt voraus: dy/dx = g(x)·h(y). Dann kann man dy/h(y) = g(x) dx bilden und beide Seiten separat integrieren.',
    conceptHints: ['Kann man dy/dx so umschreiben, dass links nur y-Terme und rechts nur x-Terme stehen?', 'Additive Verknüpfung g(x) + h(y) erlaubt keine Trennung.'],
    calcQuestion: 'y\' = 3y, y(0) = 2. Berechne y(1). (e³ ≈ 20,086)',
    calcAnswer: 40.17,
    calcTolerance: 0.1,
    calcUnit: '',
    calcExplanation: 'Trennung: dy/y = 3 dx → ln|y| = 3x + C₁ → y = Ce^{3x}. y(0) = C = 2. y(1) = 2e³ ≈ 2·20,086 = 40,17.',
    calcHints: ['Allgemeine Lösung: y = Ce^{3x}.', 'y(0) = 2 → C = 2; dann x = 1 einsetzen.'],
    trueFalseStatement: 'Bei der Trennung der Variablen integriert man nur die linke Seite und setzt rechts einfach +C hinzu.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Beide Seiten werden separat integriert: ∫ dy/h(y) auf der linken und ∫ g(x) dx auf der rechten Seite. Die Integrationskonstante C entsteht dabei automatisch auf einer Seite.',
    trueFalseHints: ['Ein Integral auf jeder Seite — zwei Integrale insgesamt.', 'Die Konstante erscheint nur einmal, weil C₁ − C₂ wieder eine Konstante ergibt.'],
    matchingQuestion: 'Ordne die Schritte der Variablentrennung für y\' = xy den richtigen Ausdrücken zu.',
    matchingPairs: [
      { left: 'Trennen', right: 'dy/y = x dx' },
      { left: 'Integrieren', right: 'ln|y| = x²/2 + C₁' },
      { left: 'Auflösen', right: 'y = Ce^{x²/2}' },
    ],
    matchingExplanation: 'Schritt 1: dy/y = x dx (Trennung). Schritt 2: ∫ dy/y = ∫ x dx → ln|y| = x²/2 + C₁ (Integration). Schritt 3: y = Ce^{x²/2} mit C = ±e^{C₁} (Auflösen).',
    matchingHints: ['Erst trennen, dann integrieren, dann auflösen.', 'ln|y| = ... → Exponentialfunktion auf beiden Seiten.'],
    sortingQuestion: 'Löse y\' = −2y, y(0) = 5 in der richtigen Reihenfolge.',
    sortingItems: [
      'dy/y = −2 dx schreiben',
      'ln|y| = −2x + C₁ integrieren',
      'y = Ce^{−2x} auflösen',
      'y(0) = 5 → C = 5 einsetzen',
      'y = 5e^{−2x} aufschreiben',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Trennen → Integrieren → Auflösen → Anfangsbedingung → Spezielle Lösung. Jeder Schritt baut auf dem vorherigen auf.',
    sortingHints: ['Trennung kommt immer vor der Integration.', 'Die Anfangsbedingung kommt nach der allgemeinen Lösung.'],
    errorQuestion: 'Jemand löst y\' = 2x·y und schreibt: ∫ dy/y = ∫ 2x·y dx. Was ist der Fehler?',
    errorOptions: [
      'Das y auf der rechten Seite muss vorher getrennt werden; richtig ist ∫ dy/y = ∫ 2x dx',
      'Man darf dy/y nicht integrieren',
      'Die DGL ist zweiter Ordnung und braucht eine andere Methode',
      'Es fehlt eine Anfangsbedingung für die Integration',
    ],
    errorCorrect: 0,
    errorExplanation: 'Die Trennung der Variablen erfordert, dass die rechte Seite nach der Trennung kein y mehr enthält. Richtig: dy/y = 2x dx. Dann ∫ dy/y = ∫ 2x dx → ln|y| = x² + C₁.',
    errorHints: ['Nach der Trennung: links nur y, rechts nur x.', 'Ein y auf der rechten Seite bedeutet, die Trennung ist nicht vollständig durchgeführt.'],
    transferQuestion: 'y\' = y/x, y(1) = 3. Berechne y(2).',
    transferAnswer: 6,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: 'Trennung: dy/y = dx/x → ln|y| = ln|x| + C₁ → y = Cx. y(1) = C·1 = 3 → C = 3. y(2) = 3·2 = 6.',
    transferHints: ['∫ dy/y = ln|y|, ∫ dx/x = ln|x|.', 'y = Cx ist eine Gerade durch den Ursprung.'],
  },

  'dgl-1-3': {
    explanation: String.raw`**Vertiefung Lineare DGL 1. Ordnung:** Die Standardform ist $y' + p(x)y = q(x)$. Der **integrierende Faktor** $\mu(x) = e^{\int p(x)\,dx}$ macht die linke Seite zur Ableitung eines Produkts: $(\mu y)' = \mu q$. Integration und Division durch $\mu$ liefert die allgemeine Lösung. Für $q(x)=0$ (homogener Fall) ergibt sich stets eine Exponentialfunktion.`,
    conceptQuestion: 'Wozu dient der integrierende Faktor μ(x) = e^{∫p(x) dx} bei y\' + p(x)y = q(x)?',
    conceptOptions: [
      'Er macht die linke Seite zur vollständigen Ableitung (μy)\', sodass man direkt integrieren kann',
      'Er beseitigt die Störfunktion q(x)',
      'Er bestimmt die Ordnung der DGL',
      'Er liefert direkt die Lösung y ohne weitere Schritte',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Multipliziert man die DGL mit μ(x), ergibt die linke Seite genau (μy)\'. Dann ist (μy)\' = μ·q(x), was durch Integration sofort μy = ∫ μ·q dx + C liefert.',
    conceptHints: ['Produktregel: (μy)\' = μ\'y + μy\'. Vergleiche mit μy\' + μpy.', 'μ\' = p·μ sorgt dafür, dass der Term μ\'y passend ist.'],
    calcQuestion: 'y\' + y = 3, y(0) = 1. Berechne y(1). (e^{−1} ≈ 0,3679)',
    calcAnswer: 2.264,
    calcTolerance: 0.05,
    calcUnit: '',
    calcExplanation: 'μ = e^x. (e^x y)\' = 3e^x → e^x y = 3e^x + C → y = 3 + Ce^{−x}. y(0) = 3 + C = 1 → C = −2. y(1) = 3 − 2e^{−1} ≈ 3 − 0,7358 ≈ 2,264.',
    calcHints: ['Integrierender Faktor: μ = e^{∫1 dx} = e^x.', 'Anfangsbedingung y(0) = 1 in y = 3 + Ce^{−x} einsetzen.'],
    trueFalseStatement: 'Die homogene lineare DGL y\' + 3y = 0 hat die allgemeine Lösung y = Ce^{3x}.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Die homogene DGL y\' + 3y = 0 bedeutet y\' = −3y. Die Lösung lautet y = Ce^{−3x}, nicht Ce^{+3x}. Das Vorzeichen des Exponenten stimmt mit dem Vorzeichen in der DGL überein.',
    trueFalseHints: ['y\' + 3y = 0 → y\' = −3y → Exponent ist −3x.', 'Probe: Ist (Ce^{3x})\' + 3Ce^{3x} = 0? Nein, ergibt 6Ce^{3x} ≠ 0.'],
    matchingQuestion: 'Ordne die Schritte der Methode des integrierenden Faktors den richtigen Formeln zu.',
    matchingPairs: [
      { left: 'Integrierender Faktor', right: 'μ = e^{∫p(x) dx}' },
      { left: 'Multiplizierte DGL', right: '(μy)\' = μ·q(x)' },
      { left: 'Allgemeine Lösung', right: 'y = (1/μ)·(∫ μ·q dx + C)' },
    ],
    matchingExplanation: 'Der integrierende Faktor μ = e^{∫p dx} macht aus der linken Seite eine vollständige Ableitung. Integration ergibt μy = ∫ μq dx + C, Division durch μ die Lösung y.',
    matchingHints: ['Reihenfolge: μ bestimmen → multiplizieren → integrieren → durch μ teilen.', 'μ hängt nur von p(x) ab.'],
    sortingQuestion: 'Löse y\' − 2y = 0 mit dem integrierenden Faktor in der richtigen Reihenfolge.',
    sortingItems: [
      'p(x) = −2 ablesen',
      'μ = e^{∫(−2) dx} = e^{−2x} berechnen',
      'DGL mit μ multiplizieren: (e^{−2x} y)\' = 0',
      'Integrieren: e^{−2x} y = C',
      'Lösung: y = Ce^{2x} aufschreiben',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'p(x) ablesen, μ berechnen, multiplizieren, integrieren, auflösen. Der Exponent des integrierenden Faktors dreht das Vorzeichen um: die Lösung trägt +2x.',
    sortingHints: ['p(x) = −2 → μ = e^{−2x}.', '(e^{−2x} y)\' = 0 → e^{−2x} y = C → y = Ce^{2x}.'],
    errorQuestion: 'Für y\' + 2y = 4 wird als integrierender Faktor μ = e^{2x} bestimmt und die Lösung y = Ce^{−2x} + 2 angegeben. Welche Aussage ist korrekt?',
    errorOptions: [
      'Rechnung und Lösung sind korrekt; μ = e^{∫2 dx} = e^{2x} und die partikuläre Lösung ist y_p = 2',
      'Der integrierende Faktor muss μ = e^{−2x} lauten',
      'Die partikuläre Lösung muss y_p = 4 lauten',
      'Die homogene Lösung fehlt komplett',
    ],
    errorCorrect: 0,
    errorExplanation: 'μ = e^{∫p dx} = e^{∫2 dx} = e^{2x} ist korrekt. Partikulärer Ansatz y_p = konst: 0 + 2y_p = 4 → y_p = 2. Allgemeine Lösung: y = Ce^{−2x} + 2. Alles stimmt.',
    errorHints: ['In diesem Fall ist die Lösung tatsächlich richtig — der Trick ist, die Richtigkeit zu erkennen.', 'Probe: y\' = −2Ce^{−2x}. y\' + 2y = −2Ce^{−2x} + 2Ce^{−2x} + 4 = 4. ✓'],
    transferQuestion: 'y\' − y = e^{2x}. Die allgemeine Lösung lautet y = Ce^x + e^{2x}. Mit y(0) = 3: Berechne y(1). (e ≈ 2,718, e² ≈ 7,389)',
    transferAnswer: 12.95,
    transferTolerance: 0.1,
    transferUnit: '',
    transferExplanation: 'y(0) = C·1 + 1 = 3 → C = 2. y(1) = 2e + e² ≈ 2·2,718 + 7,389 = 5,436 + 7,389 = 12,825 ≈ 12,95. (Toleranz berücksichtigt Rundung.)',
    transferHints: ['y(0) = C + e^0 = C + 1 = 3 → C = 2.', 'y(1) = 2e¹ + e² ≈ 5,436 + 7,389.'],
  },

  'dgl-1-4': {
    explanation: String.raw`**Vertiefung Homogene lineare DGL 2. Ordnung:** Ansatz $y = e^{\lambda x}$ führt auf die **charakteristische Gleichung** $a\lambda^2 + b\lambda + c = 0$. Je nach Diskriminante $D = b^2 - 4ac$ gibt es drei Fälle: (1) $D > 0$: zwei reelle Wurzeln $\lambda_1 \neq \lambda_2$ → $y = C_1 e^{\lambda_1 x} + C_2 e^{\lambda_2 x}$; (2) $D = 0$: Doppelwurzel $\lambda$ → $y = (C_1 + C_2 x)e^{\lambda x}$; (3) $D < 0$: komplexe Wurzeln $\alpha \pm i\beta$ → $y = e^{\alpha x}(C_1\cos(\beta x) + C_2\sin(\beta x))$.`,
    conceptQuestion: 'Welchen Ansatz macht man bei homogenen linearen DGL 2. Ordnung mit konstanten Koeffizienten?',
    conceptOptions: [
      'y = e^{λx}, weil Ableitung und Funktion die gleiche Form haben',
      'y = sin(λx), weil die DGL schwingt',
      'y = λ·x², weil die Ordnung 2 ist',
      'y = C·ln(x), weil das die einfachste Funktion ist',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'e^{λx} ist die einzige Funktion, deren Ableitungen alle Vielfache von e^{λx} sind: (e^{λx})\' = λe^{λx}, (e^{λx})\'\' = λ²e^{λx}. Das macht den Ansatz passend, weil man e^{λx} herauskürzenkann.',
    conceptHints: ['Welche Funktion bleibt beim Ableiten in ihrer eigenen Form?', 'Nach dem Einsetzen und Kürzen von e^{λx} ≠ 0 bleibt ein Polynom in λ.'],
    calcQuestion: 'Charakteristische Gleichung von y\'\' − 5y\' + 6y = 0 ist λ² − 5λ + 6 = 0. Berechne die kleinere Wurzel λ₁.',
    calcAnswer: 2,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'λ² − 5λ + 6 = (λ−2)(λ−3) = 0 → λ₁ = 2, λ₂ = 3. Die kleinere Wurzel ist λ₁ = 2.',
    calcHints: ['(λ−2)(λ−3) = λ²−5λ+6. Welche zwei Zahlen ergeben −5 als Summe und 6 als Produkt?', '2 + 3 = 5, 2·3 = 6 → Wurzeln sind 2 und 3.'],
    trueFalseStatement: 'Hat die charakteristische Gleichung eine Doppelwurzel λ, so lautet die allgemeine Lösung y = C₁e^{λx} + C₂e^{λx} = (C₁ + C₂)e^{λx}.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Bei Doppelwurzel sind C₁e^{λx} und C₂e^{λx} linear abhängig — man erhält nur eine Konstante statt zweier. Die korrekte allgemeine Lösung ist y = (C₁ + C₂x)e^{λx}, mit dem zusätzlichen Faktor x vor C₂.',
    trueFalseHints: ['Zwei linear unabhängige Lösungen werden gebraucht.', 'Der Faktor x liefert die zweite unabhängige Lösung: x·e^{λx} lässt sich durch Variation der Konstanten herleiten.'],
    matchingQuestion: 'Ordne die Art der Wurzeln der charakteristischen Gleichung der zugehörigen Lösungsform zu.',
    matchingPairs: [
      { left: 'Zwei verschiedene reelle Wurzeln λ₁ ≠ λ₂', right: 'C₁e^{λ₁x} + C₂e^{λ₂x}' },
      { left: 'Doppelwurzel λ', right: '(C₁ + C₂x)e^{λx}' },
      { left: 'Komplexe Wurzeln α ± iβ', right: 'e^{αx}(C₁cos(βx) + C₂sin(βx))' },
    ],
    matchingExplanation: 'Die drei Fälle decken alle Möglichkeiten ab. Die Diskriminante D = b²−4ac entscheidet: D>0 → zwei reelle Wurzeln, D=0 → Doppelwurzel, D<0 → komplexe Wurzeln.',
    matchingHints: ['Diskriminante D = b² − 4ac bestimmt den Fall.', 'Komplexe Wurzeln führen immer zu Sinus/Kosinus in der Lösung.'],
    sortingQuestion: 'Löse y\'\' + 4y = 0 in der richtigen Reihenfolge.',
    sortingItems: [
      'Charakteristische Gleichung λ² + 4 = 0 aufstellen',
      'λ² = −4 → λ = ±2i (komplex) bestimmen',
      'α = 0, β = 2 ablesen',
      'Allgemeine Lösung y = C₁cos(2x) + C₂sin(2x) aufschreiben',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Char. Gleichung → Wurzeln berechnen → Real- und Imaginärteil ablesen → Lösung aufschreiben. Bei reinen imaginären Wurzeln (α=0) fehlt der Dämpfungsfaktor e^{αx}.',
    sortingHints: ['λ² + 4 = 0 → λ² = −4 → λ = ±2i.', 'Kein Realteil (α=0) → keine Dämpfung.'],
    errorQuestion: 'Jemand löst y\'\' − 4y\' + 4y = 0 mit der char. Gleichung λ²−4λ+4 = (λ−2)² = 0 und schreibt y = C₁e^{2x} + C₂e^{2x}. Was ist falsch?',
    errorOptions: [
      'Bei Doppelwurzel λ=2 muss die zweite Lösung x·e^{2x} lauten: y = (C₁ + C₂x)e^{2x}',
      'Die charakteristische Gleichung wurde falsch berechnet',
      'Der Ansatz e^{λx} ist für diese DGL nicht erlaubt',
      'Die Lösung fehlt die Anfangsbedingung',
    ],
    errorCorrect: 0,
    errorExplanation: '(λ−2)² = 0 liefert eine Doppelwurzel λ=2. Die zwei Terme C₁e^{2x} und C₂e^{2x} sind linear abhängig. Die zweite linear unabhängige Lösung ist x·e^{2x}, daher y = (C₁ + C₂x)e^{2x}.',
    errorHints: ['Sind C₁e^{2x} und C₂e^{2x} linear unabhängig? Nein: Man kann sie zur einzigen Konstante (C₁+C₂) zusammenfassen.', 'Doppelwurzel → Faktor x für die zweite Lösung.'],
    transferQuestion: 'y\'\' + 2y\' + y = 0, y(0) = 1, y\'(0) = 0. Berechne y(1). (e^{−1} ≈ 0,3679)',
    transferAnswer: 0.736,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: 'Char. Gleichung: λ²+2λ+1=(λ+1)²=0 → Doppelwurzel λ=−1. Allgemein: y=(C₁+C₂x)e^{−x}. y(0)=C₁=1. y\'=(C₂−C₁−C₂x)e^{−x}; y\'(0)=C₂−C₁=C₂−1=0 → C₂=1. y(1)=(1+1)e^{−1}=2e^{−1}≈0,7358≈0,736.',
    transferHints: ['Doppelwurzel λ=−1 → y=(C₁+C₂x)e^{−x}.', 'y\'(0)=C₂−C₁=0 → C₂=C₁=1; y(1)=2e^{−1}.'],
  },

  'dgl-2-1': {
    explanation: String.raw`**Vertiefung Variation der Konstanten:** Bei $y' + p(x)y = q(x)$ kennt man die homogene Lösung $y_h = Ce^{-P(x)}$ mit $P(x)=\int p(x)\,dx$. Man ersetzt $C$ durch eine Funktion $C(x)$ und setzt $y = C(x)e^{-P(x)}$ ein. Das ergibt $C'(x) = q(x)e^{P(x)}$. Integration liefert $C(x)$ und damit die vollständige Lösung. Die Methode ist allgemeiner als der Ansatz vom Typ der rechten Seite und überträgt sich auf Systeme.`,
    conceptQuestion: 'Was ist die Kernidee der Variation der Konstanten?',
    conceptOptions: [
      'Die Integrationskonstante C der homogenen Lösung wird durch eine unbekannte Funktion C(x) ersetzt',
      'Die DGL wird in eine algebraische Gleichung für C umgewandelt',
      'Die Konstante C wird gleich null gesetzt',
      'Die Methode setzt voraus, dass q(x) konstant ist',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Man nutzt die Struktur der homogenen Lösung y_h = Ce^{−P(x)} und ersetzt C durch C(x). Einsetzen in die inhomogene DGL führt auf eine Gleichung für C\'(x), die integriert werden kann.',
    conceptHints: ['Der Name verrät die Methode: die Konstante wird „variiert", also zur Funktion.', 'C(x) ist eine Funktion von x, nicht mehr eine Zahl.'],
    calcQuestion: 'y\' − y = e^{2x}. Die allgemeine Lösung ist y = Ce^x + e^{2x}. Mit y(0) = 2: Berechne y(1). (e ≈ 2,718, e² ≈ 7,389)',
    calcAnswer: 10.107,
    calcTolerance: 0.05,
    calcUnit: '',
    calcExplanation: 'y(0) = C·1 + 1 = 2 → C = 1. y(1) = 1·e + e² ≈ 2,718 + 7,389 = 10,107.',
    calcHints: ['y(0) = C + e^0 = C + 1 = 2 → C = 1.', 'y(1) = e¹ + e² ≈ 2,718 + 7,389.'],
    trueFalseStatement: 'Die Variation der Konstanten liefert nur die partikuläre Lösung, nicht die allgemeine.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Die Methode liefert die vollständige allgemeine Lösung: y = C(x)e^{−P(x)} enthält nach Integration von C\'(x) sowohl den homogenen Anteil (mit der freien Konstante C̃) als auch den partikulären Anteil.',
    trueFalseHints: ['C(x) = ∫ q(x)e^{P(x)} dx + C̃. Das C̃ ist die Konstante des homogenen Anteils.', 'Allgemeine Lösung = homogener Anteil + partikulärer Anteil.'],
    matchingQuestion: 'Ordne die Schritte der Variation der Konstanten den richtigen Ausdrücken zu.',
    matchingPairs: [
      { left: 'Homogene Lösung', right: 'y_h = Ce^{−P(x)}' },
      { left: 'Ansatz Variation', right: 'y = C(x)e^{−P(x)}' },
      { left: 'Gleichung für C\'(x)', right: 'C\'(x) = q(x)·e^{P(x)}' },
    ],
    matchingExplanation: 'Schritt 1: Homogene Lösung y_h bestimmen. Schritt 2: Konstante C durch Funktion C(x) ersetzen. Schritt 3: Einsetzen und vereinfachen liefert C\'(x) = q(x)·e^{P(x)}.',
    matchingHints: ['C durch C(x) ersetzen ist der entscheidende Schritt.', 'e^{P(x)} dreht das Vorzeichen des Exponenten in y_h um.'],
    sortingQuestion: 'Löse y\' + 2y = 4e^{−2x} mit Variation der Konstanten in der richtigen Reihenfolge.',
    sortingItems: [
      'Homogene Lösung y_h = Ce^{−2x} bestimmen',
      'Ansatz y = C(x)e^{−2x} aufschreiben',
      'Einsetzen: C\'(x)e^{−2x} = 4e^{−2x} → C\'(x) = 4',
      'Integrieren: C(x) = 4x + C̃',
      'Lösung: y = (4x + C̃)e^{−2x}',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Für p(x) = 2 ist P(x) = 2x und y_h = Ce^{−2x}. Der Ansatz y = C(x)e^{−2x} eingesetzt liefert C\'(x) = 4. Integration: C(x) = 4x + C̃. Lösung: y = (4x + C̃)e^{−2x}.',
    sortingHints: ['p(x) = 2 → P(x) = 2x → y_h = Ce^{−2x}.', 'Nach Einsetzen und Vereinfachen: C\'(x) = q(x)·e^{P(x)} = 4e^{−2x}·e^{2x} = 4.'],
    errorQuestion: 'Für y\' + y = sin(x) setzt jemand direkt y_p = A·sin(x) an und erhält A·cos(x) + A·sin(x) = sin(x), woraus A = 1/2 und y_p = (1/2)sin(x) folgt. Was fehlt?',
    errorOptions: [
      'Cos-Anteil wurde vergessen: vollständiger Ansatz y_p = A·sin(x) + B·cos(x) führt auf A=1/2, B=−1/2',
      'Der Ansatz sin(x) ist grundsätzlich falsch für diese DGL',
      'Man muss zuerst die Ordnung erhöhen',
      'Die homogene Lösung ist noch nicht bestimmt worden',
    ],
    errorCorrect: 0,
    errorExplanation: 'y_p\' = A·cos(x). Einsetzen: A·cos(x) + A·sin(x) = sin(x). Koeffizientenvergleich: cos(x): A=0, sin(x): A=1 — Widerspruch! Vollständiger Ansatz A·sin(x)+B·cos(x): A·cos(x)−B·sin(x)+A·sin(x)+B·cos(x)=sin(x). cos: A+B=0, sin: A−B=1 → A=1/2, B=−1/2.',
    errorHints: ['Leite y_p = A·sin(x) ab und setze in die DGL ein. Was passiert mit dem cos-Term?', 'Vollständiger Ansatz: y_p = A·sin(x) + B·cos(x), weil Ableitung von sin(x) = cos(x) ist.'],
    transferQuestion: 'y\' + y = sin(x). Partikuläre Lösung: y_p = (sin(x) − cos(x))/2. Allgemeine Lösung: y = Ce^{−x} + (sin(x)−cos(x))/2. Mit y(0)=1: Berechne C.',
    transferAnswer: 1.5,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: 'y(0) = C·1 + (sin0 − cos0)/2 = C + (0−1)/2 = C − 1/2 = 1 → C = 1 + 1/2 = 3/2 = 1,5.',
    transferHints: ['y(0) = Ce^0 + (0−1)/2 = C − 1/2.', 'C − 1/2 = 1 → C = 3/2.'],
  },

  'dgl-2-2': {
    explanation: String.raw`**Vertiefung DGL-Systeme:** Ein System $\vec{y}' = A\vec{y}$ koppelt mehrere DGL. Jede DGL höherer Ordnung lässt sich durch Substitution ($y_1=y$, $y_2=y'$, ...) als System 1. Ordnung schreiben. Die Lösungen erhält man über **Eigenwerte** $\lambda$ aus $\det(A-\lambda I)=0$ und **Eigenvektoren** $\vec{v}$. Negative reelle Eigenwerte bedeuten Stabilität (Abklingen), positive Instabilität (Wachstum), rein imaginäre eine reine Schwingung.`,
    conceptQuestion: 'Welche mathematische Struktur hat ein lineares DGL-System 1. Ordnung?',
    conceptOptions: [
      'y\u20d7\' = A·y\u20d7, wobei A eine Matrix und y\u20d7 ein Vektor von Funktionen ist',
      'y\' = a·x, wobei a ein Skalar ist',
      'Mehrere DGL, die nicht miteinander in Verbindung stehen',
      'Eine einzige DGL höherer Ordnung',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Im System $\\vec{y}$\' = A·$\\vec{y}$ sind y₁(x), y₂(x), ... die unbekannten Funktionen im Vektor $\\vec{y}$. Die Matrix A koppelt die Gleichungen: y₁\' hängt i.A. von y₁ und y₂ ab, ebenso y₂\'.',
    conceptHints: ['A ist quadratisch (n×n wenn n DGL gekoppelt sind).', 'Jede Zeile von A·$\\vec{y}$ ist eine lineare Kombination der y_i.'],
    calcQuestion: 'y\'\' + 3y\' + 2y = 0 wird als System mit y₁=y, y₂=y\' geschrieben. Wie lautet y₂\'?',
    calcAnswer: -2,
    calcTolerance: 0,
    calcUnit: '·y₁ − 3·y₂ (Koeffizient vor y₁)',
    calcExplanation: 'Aus y\'\' + 3y\' + 2y = 0 folgt y\'\' = −2y − 3y\'. Mit y₂ = y\' und y₁ = y: y₂\' = y\'\' = −2y₁ − 3y₂. Der Koeffizient vor y₁ ist −2.',
    calcHints: ['y₂\' = y\'\' = −3y\' − 2y = −3y₂ − 2y₁.', 'Vorzeichen beachten: Koeffizient vor y₁ ist −2.'],
    trueFalseStatement: 'Jede DGL höherer Ordnung lässt sich in ein äquivalentes System von DGL 1. Ordnung umschreiben.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Durch Einführung neuer Variablen für jede Ableitung (y₁=y, y₂=y\', y₃=y\'\', ...) wird jede DGL n-ter Ordnung zu einem System von n DGL 1. Ordnung. Das ist der Standardansatz in der numerischen Mathematik.',
    trueFalseHints: ['y_k = y^{(k−1)} als neue Variable wählen.', 'Ein System von n DGL 1. Ordnung hat genauso viele Freiheitsgrade wie eine DGL n-ter Ordnung.'],
    matchingQuestion: 'Ordne den Begriff dem Inhalt bei DGL-Systemen zu.',
    matchingPairs: [
      { left: 'Eigenwert λ', right: 'Lösung von det(A − λI) = 0' },
      { left: 'Eigenvektor $\\vec{v}$', right: 'A·$\\vec{v}$ = λ·$\\vec{v}$' },
      { left: 'Lösungsansatz', right: '$\\vec{y}$ = $\\vec{v}$·e^{λt}' },
    ],
    matchingExplanation: 'Eigenwerte aus dem charakteristischen Polynom det(A−λI)=0. Eigenvektoren aus A·$\\vec{v}$=λ·$\\vec{v}$. Lösungsansatz $\\vec{y}$=$\\vec{v}$·e^{λt} setzt die Exponentialstruktur des skalaren Falls fort.',
    matchingHints: ['det(A−λI)=0 liefert n Eigenwerte für eine n×n-Matrix.', 'A·$\\vec{v}$=λ·$\\vec{v}$ → (A−λI)·$\\vec{v}$=0.'],
    sortingQuestion: 'Bringe die Schritte zur Lösung von $\\vec{y}$\' = A·$\\vec{y}$ in die richtige Reihenfolge.',
    sortingItems: [
      'Charakteristisches Polynom det(A − λI) = 0 aufstellen',
      'Eigenwerte λ₁, λ₂ bestimmen',
      'Eigenvektoren $\\vec{v}$₁, $\\vec{v}$₂ berechnen',
      'Allgemeine Lösung $\\vec{y}$ = C₁$\\vec{v}$₁e^{λ₁t} + C₂$\\vec{v}$₂e^{λ₂t} aufschreiben',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Erst das charakteristische Polynom, dann Eigenwerte, dann Eigenvektoren, zuletzt die allgemeine Lösung zusammensetzen.',
    sortingHints: ['Eigenwerte vor Eigenvektoren berechnen.', 'Aus Eigenwert und Eigenvektor entsteht ein Fundamentalpaar.'],
    errorQuestion: 'Jemand schreibt y\'\' + 5y\' + 6y = 0 als System: y₁\' = y₂, y₂\' = −5y₁ − 6y₂. Was ist falsch?',
    errorOptions: [
      'Koeffizienten vertauscht: richtig ist y₂\' = −6y₁ − 5y₂',
      'y₁\' = y₂ ist falsch, es muss y₁\' = y₁ sein',
      'Das System hat zu viele Gleichungen',
      'Der Ansatz e^{λt} ist für Systeme nicht anwendbar',
    ],
    errorCorrect: 0,
    errorExplanation: 'Aus y\'\' + 5y\' + 6y = 0 folgt y\'\' = −5y\' − 6y = −5y₂ − 6y₁. Also y₂\' = −6y₁ − 5y₂. Die Reihenfolge (−6y₁ − 5y₂) ist wichtig: Koeffizient vor y₁ entspricht dem Koeffizienten vor y (nicht y\').',
    errorHints: ['y₂\' = y\'\' = −5y\' − 6y. Ersetze y\'=y₂ und y=y₁.', 'Koeffizient vor y₁ kommt von 6y, Koeffizient vor y₂ von 5y\'.'],
    transferQuestion: 'Für das System $\\vec{y}$\' = A·$\\vec{y}$ mit A = [[0,1],[−2,−3]] lauten die Eigenwerte λ₁=−1 und λ₂=−2. Welches Langzeitverhalten zeigt $\\vec{y}$(t) für t→∞?',
    transferAnswer: 0,
    transferTolerance: 0,
    transferUnit: '($\\vec{y}$ → $\\vec{0}$, Eingabe: 0)',
    transferExplanation: 'Beide Eigenwerte sind negativ (λ₁=−1, λ₂=−2). Daher klingt jede Lösung $\\vec{y}$(t) = C₁$\\vec{v}$₁e^{−t} + C₂$\\vec{v}$₂e^{−2t} für t→∞ gegen den Nullvektor $\\vec{0}$ ab. Das System ist stabil.',
    transferHints: ['e^{−t} → 0 für t→∞.', 'Negative Eigenwerte → Stabilität → alle Lösungen gehen gegen 0.'],
  },

  'dgl-2-3': {
    explanation: String.raw`**Vertiefung Inhomogene lineare DGL 2. Ordnung:** Die allgemeine Lösung ist $y = y_h + y_p$. Die homogene Lösung $y_h$ folgt aus der charakteristischen Gleichung. Die partikuläre Lösung $y_p$ wird per **Ansatz vom Typ der rechten Seite** bestimmt: bei $q(x)=Pe^{\alpha x}$ wählt man $y_p=Ae^{\alpha x}$ (sofern $\alpha$ kein Eigenwert ist), bei $\sin$/$\cos$ den Ansatz $A\sin+B\cos$, bei Polynom einen Ansatz gleichen Grades.`,
    conceptQuestion: 'Wie setzt sich die allgemeine Lösung einer inhomogenen linearen DGL y\'\' + by\' + cy = q(x) zusammen?',
    conceptOptions: [
      'y = y_h + y_p: homogene Lösung plus eine partikuläre Lösung',
      'y = y_p allein genügt immer',
      'y = 2·y_h ohne partikulären Anteil',
      'y = y_h − y_p mit negativem Vorzeichen',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'y_h löst die homogene DGL (rechte Seite = 0) und enthält die freien Konstanten C₁, C₂. y_p ist irgendeine spezielle Lösung der inhomogenen DGL. Zusammen bilden sie die allgemeine Lösung.',
    conceptHints: ['y_h + y_p einsetzen: Terme mit C₁, C₂ erfüllen die homogene DGL, y_p den Rest.', 'y_p muss die DGL mit q(x) auf der rechten Seite erfüllen.'],
    calcQuestion: 'y\'\' + y = 4. Partikulärer Ansatz y_p = A. Berechne A.',
    calcAnswer: 4,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'y_p = A (konstant) → y_p\' = 0, y_p\'\' = 0. Einsetzen: 0 + A = 4 → A = 4. Partikuläre Lösung: y_p = 4.',
    calcHints: ['Bei konstanter rechter Seite: Ansatz y_p = A (Konstante).', 'y_p\'\' = 0, y_p = A → A = 4.'],
    trueFalseStatement: 'Wenn q(x) = e^{2x} und λ=2 ein Eigenwert der homogenen DGL ist, muss der Ansatz y_p = A·x·e^{2x} gewählt werden.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Ist α = 2 einfacher Eigenwert, würde y_p = A·e^{2x} in y_h aufgehen und die DGL nicht lösen. Der Faktor x ist notwendig. Bei doppeltem Eigenwert wäre sogar y_p = A·x²·e^{2x} nötig.',
    trueFalseHints: ['Resonanzfall: Wenn q(x) die Form der homogenen Lösung hat.', 'Faktor x verhindert lineare Abhängigkeit zwischen y_p und y_h.'],
    matchingQuestion: 'Ordne den Typ der Störfunktion q(x) dem passenden Ansatz für y_p zu.',
    matchingPairs: [
      { left: 'q(x) = 5 (Konstante)', right: 'y_p = A' },
      { left: 'q(x) = 3e^{−x} (kein Eigenwert)', right: 'y_p = A·e^{−x}' },
      { left: 'q(x) = sin(2x)', right: 'y_p = A·sin(2x) + B·cos(2x)' },
    ],
    matchingExplanation: 'Der Ansatz ahmt die Form von q(x) nach. Konstante → A. Exponential → A·e^{αx}. Trigonometrisch → Kombination aus sin und cos, weil Ableitung von sin → cos und umgekehrt.',
    matchingHints: ['Ansatz muss die gleiche „Formklasse" wie q(x) haben.', 'Beim trigonometrischen Ansatz immer beide: sin und cos.'],
    sortingQuestion: 'Löse y\'\' − 3y\' + 2y = 4 in der richtigen Reihenfolge.',
    sortingItems: [
      'Char. Gleichung λ²−3λ+2=0 → λ₁=1, λ₂=2 lösen',
      'Homogene Lösung y_h = C₁e^x + C₂e^{2x} aufschreiben',
      'Partikulären Ansatz y_p = A wählen (q=4=const)',
      'Einsetzen: 0−0+2A=4 → A=2',
      'Allgemeine Lösung y = C₁e^x + C₂e^{2x} + 2 aufschreiben',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Erst char. Gleichung lösen, y_h aufschreiben, dann Ansatz für y_p wählen, Koeffizient A bestimmen, zuletzt y = y_h + y_p hinschreiben.',
    sortingHints: ['Homogene Lösung immer zuerst.', 'Partikulärer Ansatz: q(x) = 4 = const → y_p = A.'],
    errorQuestion: 'Für y\'\' + y = cos(x) wählt jemand den Ansatz y_p = A·cos(x). Nach Einsetzen ergibt sich 0 = cos(x) — die Methode scheitert. Was ist die Ursache?',
    errorOptions: [
      'cos(x) löst bereits die homogene DGL y\'\' + y = 0 (Resonanzfall); der Ansatz muss y_p = x(A·cos(x) + B·sin(x)) lauten',
      'Der Ansatz muss y_p = A·sin(x) sein, nicht cos(x)',
      'Die DGL ist nichtlinear, daher ist kein Ansatz möglich',
      'A muss eine Funktion von x sein, nicht eine Konstante',
    ],
    errorCorrect: 0,
    errorExplanation: 'Die char. Gleichung λ²+1=0 liefert λ=±i, also y_h = C₁cos(x)+C₂sin(x). Da cos(x) bereits Bestandteil von y_h ist, liegt Resonanz vor. Korrekter Ansatz: y_p = x(A·cos(x)+B·sin(x)).',
    errorHints: ['Prüfe: Löst cos(x) die homogene DGL y\'\' + y = 0? Ja: (cos(x))\'\' + cos(x) = −cos(x) + cos(x) = 0.', 'Resonanzfall → Faktor x vor den Ansatz setzen.'],
    transferQuestion: 'y\'\' − y = e^{2x}. Ansatz y_p = A·e^{2x}. Berechne A.',
    transferAnswer: 0.333,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: 'y_p = A·e^{2x}, y_p\'\' = 4A·e^{2x}. Einsetzen: 4A·e^{2x} − A·e^{2x} = e^{2x} → 3A = 1 → A = 1/3 ≈ 0,333. λ=2 ist kein Eigenwert (λ²−1=0 → λ=±1), daher kein Resonanzfall.',
    transferHints: ['y_p\'\' = 4A·e^{2x}. Einsetzen: (4A − A)e^{2x} = e^{2x}.', '3A = 1 → A = 1/3.'],
  },
}

export const dglSupplements = Object.fromEntries(
  Object.entries(profiles).map(([lessonId, profile]) => [
    lessonId,
    {
      explanation: profile.explanation,
      exercises: bank(profile),
    },
  ])
)
