function mc(question, options, correctIndex, explanation, hints = []) {
  return { type: 'multiple-choice', question, options, correctIndex, explanation, hints }
}

function ni(question, correctAnswer, tolerance, unit, explanation, hints = []) {
  return { type: 'number-input', question, correctAnswer, tolerance, unit, explanation, hints }
}

function tf(statement, correct, explanation, hints = []) {
  return { type: 'true-false', statement, correct, explanation, hints }
}

function matching(question, pairs, explanation, hints = []) {
  return { type: 'matching', question, pairs, explanation, hints }
}

function sorting(question, items, correctOrder, explanation, hints = []) {
  return { type: 'sorting', question, items, correctOrder, explanation, hints }
}

function withExamPrefix(exercise, exam) {
  if (!exam) return exercise
  if (exercise.question && !exercise.question.includes('[PRÜFUNG]')) {
    return { ...exercise, question: `[PRÜFUNG] ${exercise.question}` }
  }
  if (exercise.statement && !exercise.statement.includes('[PRÜFUNG]')) {
    return { ...exercise, statement: `[PRÜFUNG] ${exercise.statement}` }
  }
  return exercise
}

function bank(profile) {
  const exercises = [
    mc(profile.conceptQuestion, profile.conceptOptions, profile.conceptCorrect, profile.conceptExplanation, profile.conceptHints),
    ni(profile.calcQuestion, profile.calcAnswer, profile.calcTolerance, profile.calcUnit, profile.calcExplanation, profile.calcHints),
    tf(profile.trueFalseStatement, profile.trueFalseCorrect, profile.trueFalseExplanation, profile.trueFalseHints),
    matching(profile.matchingQuestion, profile.matchingPairs, profile.matchingExplanation, profile.matchingHints),
    sorting(profile.sortingQuestion, profile.sortingItems, profile.sortingOrder, profile.sortingExplanation, profile.sortingHints),
    mc(profile.errorQuestion, profile.errorOptions, profile.errorCorrect, profile.errorExplanation, profile.errorHints),
    ni(profile.transferQuestion, profile.transferAnswer, profile.transferTolerance, profile.transferUnit, profile.transferExplanation, profile.transferHints),
  ]
  return exercises.map((exercise) => withExamPrefix(exercise, profile.exam))
}

const profiles = {
  'int-1-1': {
    explanation: String.raw`**Vertiefung Stammfunktion:** Die Stammfunktion $F(x)$ erfüllt $F'(x) = f(x)$. Integration ist die Umkehrung der Differentiation. Da beim Ableiten jede Konstante verschwindet, gibt es stets unendlich viele Stammfunktionen — sie unterscheiden sich nur um eine additive Konstante $C$.`,
    conceptQuestion: 'Was muss für eine Stammfunktion F(x) von f(x) stets gelten?',
    conceptOptions: ["F'(x) = f(x)", "f'(x) = F(x)", 'F(x) = f(x)', "F'(x) = 0"],
    conceptCorrect: 0,
    conceptExplanation: "Die definierende Eigenschaft: Leitet man F ab, erhält man f. Kurz: F'(x) = f(x). Deshalb nennt man Integration auch 'Umkehrung der Differentiation'.",
    conceptHints: ['Welche Operation ist die Umkehrung der Ableitung?', 'Prüfe: Leite F ab — erhältst du f?'],
    calcQuestion: 'F(x) = x⁴ + 3x + 7 ist die Stammfunktion von f(x). Berechne f(2).',
    calcAnswer: 35,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: "f(x) = F'(x) = 4x³ + 3. f(2) = 4·8 + 3 = 32 + 3 = 35.",
    calcHints: ["Leite F(x) ab, um f(x) zu erhalten.", 'f(x) = 4x³ + 3. Setze x = 2 ein.'],
    trueFalseStatement: 'Zwei Stammfunktionen von f(x) können sich höchstens um eine additive Konstante unterscheiden.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Wenn F und G beide Stammfunktionen von f sind, dann ist (F − G)′ = f − f = 0, also ist F − G eine Konstante C.',
    trueFalseHints: ['Was ist die Ableitung einer Konstanten?', 'Denke: (F(x) − G(x))′ = f(x) − f(x) = 0.'],
    matchingQuestion: 'Ordne jeder Funktion f(x) ihre Stammfunktion F(x) zu (C = 0).',
    matchingPairs: [
      { left: 'f(x) = 2x', right: 'F(x) = x²' },
      { left: 'f(x) = 3x²', right: 'F(x) = x³' },
      { left: 'f(x) = 0', right: 'F(x) = C' },
    ],
    matchingExplanation: 'Probe durch Ableiten: (x²)′ = 2x ✓, (x³)′ = 3x² ✓, (C)′ = 0 ✓.',
    matchingHints: ['Leite die rechte Seite ab und prüfe, ob du die linke erhältst.', 'Die Stammfunktion von 0 ist eine beliebige Konstante.'],
    sortingQuestion: 'Bringe den Prüfungsweg "Ist F Stammfunktion von f?" in die richtige Reihenfolge.',
    sortingItems: ['F(x) aufschreiben', "F'(x) berechnen", "Vergleich: F'(x) = f(x)?", 'Ergebnis: Ja oder Nein'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Man prüft F durch Ableiten und Vergleichen. Das ist schneller als nochmals zu integrieren.',
    sortingHints: ['Zuerst aufschreiben, dann ableiten.', 'Der Vergleich ist der entscheidende Schritt.'],
    errorQuestion: 'Warum ist die Aussage "Die einzige Stammfunktion von f(x) = 2x ist F(x) = x²" falsch?',
    errorOptions: [
      'Weil es unendlich viele Stammfunktionen gibt: F(x) = x² + C für beliebiges C',
      'Weil (x²)′ ≠ 2x ist',
      'Weil f(x) = 2x keine Stammfunktion besitzt',
      'Weil die Stammfunktion immer negativ sein muss',
    ],
    errorCorrect: 0,
    errorExplanation: 'Auch F(x) = x² + 5 ist eine Stammfunktion von 2x, denn (x² + 5)′ = 2x. Die Integrationskonstante C macht die Aussage "die einzige" falsch.',
    errorHints: ['Was passiert beim Ableiten mit einer Konstanten?', 'Alle F(x) = x² + C mit beliebigem C sind Stammfunktionen.'],
    transferQuestion: 'Gegeben: F(x) = 2sin(x) + x². Welchen Wert hat f(π)? (f = F′)',
    transferAnswer: 2 * Math.PI,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: "f(x) = F′(x) = 2cos(x) + 2x. f(π) = 2cos(π) + 2π = 2·(−1) + 2π = −2 + 2π ≈ 4,283.",
    transferHints: ["Leite F ab: (2sin(x))′ = 2cos(x), (x²)′ = 2x.", 'f(π) = 2·(−1) + 2·π = 2π − 2 ≈ 4,28.'],
  },

  'int-1-2': {
    explanation: String.raw`**Vertiefung Grundintegrale:** Die wichtigsten Stammfunktionen sind Tabellenwerte. Lerne: $\int x^n\,dx = \frac{x^{n+1}}{n+1}+C$ ($n\neq -1$), $\int e^x\,dx = e^x+C$, $\int \sin x\,dx = -\cos x+C$, $\int \cos x\,dx = \sin x+C$, $\int \frac{1}{x}\,dx = \ln|x|+C$.`,
    conceptQuestion: 'Welches Grundintegral ist korrekt?',
    conceptOptions: ['∫sin(x) dx = cos(x) + C', '∫sin(x) dx = −cos(x) + C', '∫cos(x) dx = −sin(x) + C', '∫eˣ dx = x·eˣ + C'],
    conceptCorrect: 1,
    conceptExplanation: '∫sin(x) dx = −cos(x) + C, denn (−cos(x))′ = sin(x). Merke: Beim Integrieren von sin kommt ein Minuszeichen hinzu.',
    conceptHints: ['Leite −cos(x) ab: (−cos(x))′ = sin(x).', 'Beim Integrieren von sin wechselt das Vorzeichen gegenüber der Ableitung.'],
    calcQuestion: 'Berechne ∫x⁴ dx und werte die Stammfunktion (ohne C) bei x = 2 aus.',
    calcAnswer: 32 / 5,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: '∫x⁴ dx = x⁵/5 + C. Bei x = 2: 2⁵/5 = 32/5 = 6,4.',
    calcHints: ['Potenzregel: ∫xⁿ dx = x^(n+1)/(n+1).', '2⁵ = 32. Dann durch 5 teilen.'],
    trueFalseStatement: '∫(1/x) dx = ln(x) + C gilt für alle reellen x ≠ 0.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Korrekt ist ∫(1/x) dx = ln|x| + C, weil ln nur für positive Argumente definiert ist, 1/x aber auch für x < 0 existiert. Der Betrag ist unverzichtbar.',
    trueFalseHints: ['Was ist der Definitionsbereich von ln?', 'Für x < 0 ist ln(x) nicht definiert — 1/x aber schon.'],
    matchingQuestion: 'Ordne Funktion und Stammfunktion zu.',
    matchingPairs: [
      { left: '∫eˣ dx', right: 'eˣ + C' },
      { left: '∫cos(x) dx', right: 'sin(x) + C' },
      { left: '∫x⁻² dx', right: '−x⁻¹ + C' },
    ],
    matchingExplanation: '(eˣ)′ = eˣ ✓; (sin x)′ = cos x ✓; (−x⁻¹)′ = x⁻² ✓. x⁻² ist x^(−2): Potenzregel mit n = −2 ergibt x^(−1)/(−1) = −x⁻¹.',
    matchingHints: ['Prüfe durch Ableiten.', 'Für x^(−2): Potenzregel ergibt x^(−2+1)/(−2+1) = −x⁻¹.'],
    sortingQuestion: 'Berechne ∫3x² dx Schritt für Schritt in der richtigen Reihenfolge.',
    sortingItems: ['Faktorregel: 3 vor das Integral ziehen', 'Potenzregel: ∫x² dx = x³/3', '3 mit x³/3 multiplizieren', 'Ergebnis x³ + C notieren'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: '∫3x² dx = 3·∫x² dx = 3·(x³/3) + C = x³ + C. Probe: (x³)′ = 3x² ✓.',
    sortingHints: ['Erst Faktor herausziehen, dann Potenzregel.', '3 · (1/3) = 1 — der Faktor kürzt sich.'],
    errorQuestion: 'Welches Ergebnis ist falsch?',
    errorOptions: ['∫x³ dx = x⁴/4 + C', '∫eˣ dx = eˣ + C', '∫cos(x) dx = sin(x) + C', '∫sin(x) dx = cos(x) + C'],
    errorCorrect: 3,
    errorExplanation: '∫sin(x) dx = −cos(x) + C (mit Minuszeichen!). Probe: (−cos x)′ = sin x ✓. Die Antwort "cos(x) + C" fehlt das Minus.',
    errorHints: ['Leite cos(x) ab: (cos x)′ = −sin x.', 'Leite −cos(x) ab: (−cos x)′ = +sin x ✓.'],
    transferQuestion: 'Berechne den Wert der Stammfunktion F(x) = −cos(x) + eˣ an der Stelle x = 0.',
    transferAnswer: 0,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'F(0) = −cos(0) + e⁰ = −1 + 1 = 0.',
    transferHints: ['cos(0) = 1 und e⁰ = 1.', '−1 + 1 = 0.'],
  },

  'int-1-3': {
    explanation: String.raw`**Vertiefung Bestimmtes Integral und Hauptsatz:** Der Hauptsatz lautet $\int_a^b f(x)\,dx = F(b)-F(a)$. Berechne zuerst die Stammfunktion $F$, dann setze die Grenzen ein und bilde die Differenz. Die Reihenfolge ist immer: oben minus unten.`,
    conceptQuestion: 'Was besagt der Hauptsatz der Differential- und Integralrechnung?',
    conceptOptions: [
      '∫ₐᵇ f(x) dx = F(b) − F(a), wobei F′ = f',
      '∫ₐᵇ f(x) dx = f(b) − f(a)',
      '∫ₐᵇ f(x) dx = F(a) − F(b)',
      '∫ₐᵇ f(x) dx = F(a+b)',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Der Hauptsatz: ∫ₐᵇ f(x) dx = F(b) − F(a), wobei F eine beliebige Stammfunktion von f ist. Die Integrationskonstante C kürzt sich immer heraus: (F(b) + C) − (F(a) + C) = F(b) − F(a).',
    conceptHints: ['Obere Grenze minus untere Grenze.', 'C kürzt sich heraus, weil es in F(b) und F(a) gleich ist.'],
    calcQuestion: 'Berechne ∫₁³ (2x + 1) dx mit dem Hauptsatz.',
    calcAnswer: 10,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'Stammfunktion: F(x) = x² + x. F(3) − F(1) = (9 + 3) − (1 + 1) = 12 − 2 = 10.',
    calcHints: ['Stammfunktion von 2x ist x², von 1 ist x.', 'F(3) = 9 + 3 = 12, F(1) = 1 + 1 = 2.'],
    trueFalseStatement: '∫₀² eˣ dx = e² − 1.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Stammfunktion F(x) = eˣ. F(2) − F(0) = e² − e⁰ = e² − 1 ≈ 6,389.',
    trueFalseHints: ['∫eˣ dx = eˣ + C.', 'e⁰ = 1.'],
    matchingQuestion: 'Ordne das Integral seinem Wert zu.',
    matchingPairs: [
      { left: '∫₀¹ x dx', right: '1/2' },
      { left: '∫₀π sin(x) dx', right: '2' },
      { left: '∫₁ᵉ (1/x) dx', right: '1' },
    ],
    matchingExplanation: '∫₀¹ x dx = [x²/2]₀¹ = 1/2. ∫₀π sin dx = [−cos x]₀π = 1+1 = 2. ∫₁ᵉ (1/x) dx = [ln x]₁ᵉ = 1−0 = 1.',
    matchingHints: ['Berechne F(b) − F(a) für jedes Paar.', 'ln(e) = 1, ln(1) = 0.'],
    sortingQuestion: 'Bringe die Schritte zur Berechnung von ∫₀² x³ dx in die richtige Reihenfolge.',
    sortingItems: ['Stammfunktion F(x) = x⁴/4 bestimmen', 'F(2) = 16/4 = 4 berechnen', 'F(0) = 0 berechnen', 'Differenz F(2) − F(0) = 4 bilden'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: '∫₀² x³ dx = [x⁴/4]₀² = 2⁴/4 − 0 = 16/4 = 4.',
    sortingHints: ['Erst Stammfunktion, dann Grenzen einsetzen, dann subtrahieren.', '2⁴ = 16, 16/4 = 4.'],
    errorQuestion: 'Bei ∫₀² x² dx wurde F(x) = 3x berechnet und F(2) − F(0) = 6 erhalten. Was ist falsch?',
    errorOptions: [
      'Die Stammfunktion ist falsch: ∫x² dx = x³/3, nicht 3x',
      'Die Grenzen wurden falsch eingesetzt',
      'Es hätte ∫₀² 2x dx gelautet',
      'Das Ergebnis 6 stimmt zufällig',
    ],
    errorCorrect: 0,
    errorExplanation: '∫x² dx = x³/3 + C, nicht 3x. 3x wäre die Ableitung, nicht die Stammfunktion. Richtig: [x³/3]₀² = 8/3 ≈ 2,67.',
    errorHints: ['Leite x³/3 ab — erhältst du x²?', '(x³/3)′ = 3x²/3 = x² ✓. Aber (3x)′ = 3 ≠ x².'],
    transferQuestion: 'Berechne ∫₀^(π/2) cos(x) dx.',
    transferAnswer: 1,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'Stammfunktion: F(x) = sin(x). F(π/2) − F(0) = sin(π/2) − sin(0) = 1 − 0 = 1.',
    transferHints: ['∫cos(x) dx = sin(x) + C.', 'sin(π/2) = 1, sin(0) = 0.'],
  },

  'int-1-4': {
    explanation: String.raw`**Vertiefung Flächenberechnung:** Das bestimmte Integral kann negativ werden, wenn $f(x)<0$. Für die geometrische Fläche (immer positiv) muss man Nullstellen suchen, Teilintervalle getrennt integrieren und Beträge aufaddieren. Zwischen zwei Kurven: $A=\int_a^b[f(x)-g(x)]\,dx$ mit $f\geq g$.`,
    conceptQuestion: 'Was muss man tun, damit das bestimmte Integral korrekt die Fläche (und nicht das Vorzeichen-behaftete Integral) berechnet, wenn f(x) < 0 in einem Teilintervall?',
    conceptOptions: [
      'Nullstellen finden und auf jedem Teilintervall getrennt integrieren und Beträge aufaddieren',
      'Das Integral direkt auswerten — das Vorzeichen spielt keine Rolle',
      'Die Funktion quadrieren',
      'Das Integral von b nach a statt a nach b berechnen',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Wenn f das Vorzeichen wechselt, liefert das Integral einen "Saldo" — positive und negative Flächen heben sich auf. Die geometrische Fläche erhält man nur durch Betragsaddition der Teilintegrale.',
    conceptHints: ['Stell dir vor: die Fläche unter der x-Achse wäre "negativ".', 'Nullstellen trennen die Gebiete mit positivem und negativem Vorzeichen.'],
    calcQuestion: 'Berechne die Fläche, die von f(x) = x² − 4 und der x-Achse eingeschlossen wird. (Nullstellen bei x = ±2)',
    calcAnswer: 32 / 3,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: 'Auf [−2, 2] gilt f(x) ≤ 0. Fläche = |∫₋₂² (x² − 4) dx| = |[x³/3 − 4x]₋₂²| = |(8/3 − 8) − (−8/3 + 8)| = |−16/3 − 16/3| = 32/3 ≈ 10,67.',
    calcHints: ['f(x) = x² − 4 ist auf [−2, 2] negativ.', 'A = |∫₋₂² (x² − 4) dx|. Betrag nehmen!'],
    trueFalseStatement: '∫₀^(2π) sin(x) dx = 0, weil sich positive und negative Flächen aufheben.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. [−cos x]₀^(2π) = −cos(2π) + cos(0) = −1 + 1 = 0. Die geometrische Fläche beträgt aber 4 (zweimal 2).',
    trueFalseHints: ['Das Integral berechnet die "signed area".', 'Auf [0, π] ist sin positiv, auf [π, 2π] negativ — gleich groß.'],
    matchingQuestion: 'Ordne Integralausdruck und seine geometrische Bedeutung zu.',
    matchingPairs: [
      { left: 'A = ∫ₐᵇ f(x) dx (f ≥ 0)', right: 'Fläche unter f über der x-Achse' },
      { left: 'A = ∫ₐᵇ [f(x)−g(x)] dx (f ≥ g)', right: 'Fläche zwischen f und g' },
      { left: 'A = |∫ₐᵇ f(x) dx|', right: 'Betrag des Integrals (ohne Vorzeichenkorrektur)' },
    ],
    matchingExplanation: 'Die erste Form gilt nur für f ≥ 0. Die zweite für zwei Kurven. Der Betrag allein reicht nicht, wenn das Vorzeichen im Intervall wechselt.',
    matchingHints: ['Überleg, wann jeder Ausdruck korrekt ist.', 'Betrag allein reicht nicht bei Vorzeichenwechsel.'],
    sortingQuestion: 'Berechne die Fläche zwischen f(x) = x und g(x) = x² auf [0,1] in der richtigen Reihenfolge.',
    sortingItems: ['Schnittpunkte: x = x² → x = 0 und x = 1', 'Prüfen: x ≥ x² auf (0,1)', 'Integral ∫₀¹ (x − x²) dx aufstellen', 'Stammfunktion: x²/2 − x³/3', 'Einsetzen: 1/2 − 1/3 = 1/6'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: '1/2 − 1/3 = 3/6 − 2/6 = 1/6 ≈ 0,167.',
    sortingHints: ['Erst Schnittpunkte, dann "oben minus unten".', '1/2 − 1/3: Hauptnenner 6.'],
    errorQuestion: 'Die Fläche von f(x) = sin(x) auf [0, 2π] wird als ∫₀^(2π) sin(x) dx = 0 berechnet. Was ist falsch an dieser Aussage für die Fläche?',
    errorOptions: [
      'Das Integral ergibt zwar 0, aber die geometrische Fläche ist 4 — nicht 0',
      'Das Integral ist falsch berechnet; es müsste 2π sein',
      'sin(x) hat auf [0, 2π] keine negativen Werte',
      'Die Grenzen müssen immer dieselbe Vorzeichenzone abdecken',
    ],
    errorCorrect: 0,
    errorExplanation: 'Das Integral berechnet den vorzeichenbehafteten Flächeninhalt. Positive und negative Anteile heben sich auf. Die geometrische Fläche ist 2 + 2 = 4.',
    errorHints: ['sin ist auf [π, 2π] negativ.', 'Geometrische Fläche = |∫₀^π sin dx| + |∫π^(2π) sin dx| = 2 + 2 = 4.'],
    transferQuestion: 'Berechne die Fläche zwischen f(x) = 4 − x² und der x-Achse (Nullstellen bei x = ±2).',
    transferAnswer: 32 / 3,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: 'f ≥ 0 auf [−2, 2]. A = ∫₋₂² (4 − x²) dx = [4x − x³/3]₋₂² = (8 − 8/3) − (−8 + 8/3) = 16/3 + 16/3 = 32/3 ≈ 10,67.',
    transferHints: ['Auf [−2, 2] ist f ≥ 0, also kein Betragsproblem.', 'Nutze Symmetrie: A = 2·∫₀² (4 − x²) dx.'],
  },

  'int-1-5': {
    explanation: String.raw`**Vertiefung Lineare Substitution:** Für lineare Argumente $ax+b$ gilt die Kurzformel: $\int f(ax+b)\,dx = \frac{1}{a}\cdot F(ax+b)+C$. Der Faktor $1/a$ entsteht automatisch durch die Substitution $u=ax+b$, $du=a\,dx$.`,
    conceptQuestion: 'Warum entsteht bei ∫f(ax+b) dx ein Faktor 1/a im Ergebnis?',
    conceptOptions: [
      'Weil beim Rückgängigmachen der Substitution u = ax+b gilt: du = a·dx, also dx = du/a',
      'Weil man bei linearen Funktionen immer durch die Steigung dividiert',
      'Weil das Integral sonst negativ würde',
      'Der Faktor 1/a entsteht nicht — das Ergebnis ist einfach F(ax+b)',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Substitution: u = ax+b → du = a·dx → dx = du/a. Das du/a erzeugt den Faktor 1/a vor dem Integral. Probe durch Ableiten bestätigt das.',
    conceptHints: ['Substituiere u = ax+b und berechne du.', 'dx = du/a → Faktor 1/a entsteht.'],
    calcQuestion: 'Berechne ∫cos(3x) dx und werte die Stammfunktion (ohne C) bei x = π/6 aus.',
    calcAnswer: 1 / 3,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: '∫cos(3x) dx = (1/3)·sin(3x) + C. Bei x = π/6: (1/3)·sin(3·π/6) = (1/3)·sin(π/2) = (1/3)·1 = 1/3.',
    calcHints: ['Lineare Substitution: ∫cos(ax) dx = (1/a)·sin(ax) + C.', 'sin(π/2) = 1.'],
    trueFalseStatement: '∫e^(5x) dx = 5·e^(5x) + C.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Richtig: ∫e^(5x) dx = (1/5)·e^(5x) + C. Probe: ((1/5)·e^(5x))′ = (1/5)·5·e^(5x) = e^(5x) ✓. Der Faktor ist 1/5, nicht 5.',
    trueFalseHints: ['Ableiten von (1/5)·e^(5x) ergibt e^(5x).', 'Ableiten von 5·e^(5x) ergibt 25·e^(5x) ≠ e^(5x).'],
    matchingQuestion: 'Ordne Integral und Stammfunktion zu.',
    matchingPairs: [
      { left: '∫sin(2x) dx', right: '−cos(2x)/2 + C' },
      { left: '∫e^(−x) dx', right: '−e^(−x) + C' },
      { left: '∫(3x+1)⁴ dx', right: '(3x+1)⁵/15 + C' },
    ],
    matchingExplanation: '1/a-Regel: sin(2x) → −cos(2x)/2; e^(−x): a = −1 → −e^(−x); (3x+1)⁴: a = 3, n = 4 → (3x+1)⁵/(5·3) = (3x+1)⁵/15.',
    matchingHints: ['Für jedes Beispiel: Faktor 1/a bestimmen.', 'Probe durch Ableiten.'],
    sortingQuestion: 'Berechne ∫(2x−1)³ dx durch lineare Substitution in der richtigen Reihenfolge.',
    sortingItems: ['u = 2x − 1 setzen', 'du = 2 dx, also dx = du/2', '∫u³ · (du/2) = (1/2)·u⁴/4', 'Rücksubstitution: (2x−1)⁴/8 + C'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: '(1/2)·(u⁴/4) = u⁴/8. Zurück: (2x−1)⁴/8 + C. Probe: ((2x−1)⁴/8)′ = 4(2x−1)³·2/8 = (2x−1)³ ✓.',
    sortingHints: ['Erst u setzen, dann du berechnen.', '(1/2)·(1/4) = 1/8.'],
    errorQuestion: 'Jemand berechnet ∫sin(4x) dx = cos(4x) + C. Welcher Fehler wurde gemacht?',
    errorOptions: [
      'Der Faktor 1/4 fehlt und das Vorzeichen ist falsch: richtig ist −cos(4x)/4 + C',
      'sin integriert zu −cos, aber der Faktor ist korrekt',
      'Der Faktor müsste 4 sein: 4·(−cos(4x))',
      'Jedes sin-Integral ergibt cos ohne Faktor',
    ],
    errorCorrect: 0,
    errorExplanation: 'Lineare Substitution: ∫sin(4x) dx = −cos(4x)/4 + C. Probe: (−cos(4x)/4)′ = sin(4x)·4/4 = sin(4x) ✓. Zwei Fehler: fehlendes Minus und fehlender Faktor 1/4.',
    errorHints: ['∫sin(u) du = −cos(u) + C.', 'Mit a = 4: Faktor 1/4 multiplizieren.'],
    transferQuestion: 'Berechne ∫₀^1 e^(2x) dx (Ergebnis auf 2 Nachkommastellen).',
    transferAnswer: (Math.E * Math.E - 1) / 2,
    transferTolerance: 0.02,
    transferUnit: '',
    transferExplanation: 'Stammfunktion: F(x) = e^(2x)/2. F(1) − F(0) = e²/2 − 1/2 = (e² − 1)/2 ≈ (7,389 − 1)/2 ≈ 3,19.',
    transferHints: ['∫e^(2x) dx = e^(2x)/2 + C.', '(e² − 1)/2 ≈ 6,389/2 ≈ 3,19.'],
  },

  'int-2-1': {
    explanation: String.raw`**Vertiefung Substitution:** Die Substitution kehrt die Kettenregel um: $\int f(g(x))\cdot g'(x)\,dx \overset{u=g(x)}{=} \int f(u)\,du$. Erkenne den inneren Ausdruck $g(x)$ und prüfe, ob $g'(x)$ (bis auf einen konstanten Faktor) ebenfalls im Integranden steht.`,
    conceptQuestion: 'Wie erkennt man, dass sich eine Substitution u = g(x) eignet?',
    conceptOptions: [
      "Wenn g'(x) (bis auf einen konstanten Faktor) ebenfalls im Integranden vorkommt",
      'Wenn der Integrand eine Summe ist',
      'Wenn das Integral bestimmt ist',
      'Immer — Substitution ist universell anwendbar',
    ],
    conceptCorrect: 0,
    conceptExplanation: "Substitution funktioniert, wenn du g(x) und gleichzeitig g'(x) im Integranden siehst. Dann kann g'(x)·dx durch du ersetzt werden. Fehlt g'(x), muss man es durch einen Faktor künstlich erzeugen.",
    conceptHints: ['Suche einen "inneren Ausdruck" und seine Ableitung im Integrand.', "Kettenregel rückwärts: f(g(x))·g'(x) integriert zu f(u) du."],
    calcQuestion: 'Berechne ∫2x·(x² + 3)⁴ dx mit u = x² + 3. Gib den Koeffizienten vor (x²+3)⁵ an.',
    calcAnswer: 1 / 5,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'u = x² + 3, du = 2x dx. ∫u⁴ du = u⁵/5 + C = (x² + 3)⁵/5 + C. Koeffizient: 1/5.',
    calcHints: ['du = 2x dx — genau das steht im Integral.', '∫u⁴ du = u⁵/5.'],
    trueFalseStatement: 'Bei der Substitution u = g(x) muss man nach dem Integrieren g(x) für u einsetzen (Rücksubstitution).',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Das Ergebnis muss wieder in der Originalvariable x ausgedrückt werden. Nur bei bestimmten Integralen kann man stattdessen die Grenzen umrechnen und auf Rücksubstitution verzichten.',
    trueFalseHints: ['Das Endergebnis soll in x stehen, nicht in u.', 'Ausnahme: Grenzen mitmutransformieren bei bestimmten Integralen.'],
    matchingQuestion: 'Ordne Integral und Substitution zu.',
    matchingPairs: [
      { left: '∫2x·eˣ² dx', right: 'u = x²' },
      { left: '∫cos(x)·sin(x) dx', right: 'u = sin(x)' },
      { left: '∫3x²·(x³+1)² dx', right: 'u = x³ + 1' },
    ],
    matchingExplanation: "Immer den 'inneren Ausdruck' wählen, dessen Ableitung im Integranden erscheint. (x²)' = 2x ✓; (sin x)' = cos x ✓; (x³+1)' = 3x² ✓.",
    matchingHints: ['Prüfe jeweils: Ist die Ableitung von u im Integral vorhanden?', 'Der Faktor vor dx muss g′(x) sein (bis auf Konstanten).'],
    sortingQuestion: 'Berechne ∫cos(x)·sin³(x) dx mit u = sin(x) in der richtigen Reihenfolge.',
    sortingItems: ['u = sin(x) setzen', 'du = cos(x) dx erkennen', '∫u³ du schreiben', 'u⁴/4 + C berechnen', 'Rücksubstitution: sin⁴(x)/4 + C'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'cos(x) dx = du perfekt. ∫u³ du = u⁴/4. Rück: sin⁴(x)/4 + C. Probe: (sin⁴(x)/4)′ = 4sin³(x)·cos(x)/4 = sin³(x)·cos(x) ✓.',
    sortingHints: ['cos(x) ist die Ableitung von sin(x) — ideal!', 'Rücksubstitution am Ende nicht vergessen.'],
    errorQuestion: 'Jemand berechnet ∫x·eˣ² dx mit u = x² und erhält eˣ²/2 + C. Was ist richtig?',
    errorOptions: [
      'Das Ergebnis eˣ²/2 + C ist korrekt — der Faktor 1/2 kommt aus du = 2x dx',
      'Das Ergebnis ist eˣ² + C (ohne Faktor)',
      'Die Substitution u = x² ist hier nicht anwendbar',
      'Das Ergebnis muss 2eˣ² + C sein',
    ],
    errorCorrect: 0,
    errorExplanation: 'u = x², du = 2x dx → x dx = du/2. ∫eᵘ · (du/2) = eᵘ/2 + C = eˣ²/2 + C. Das ist korrekt!',
    errorHints: ['x dx = du/2 wegen du = 2x dx.', '∫eᵘ · (1/2) du = eᵘ/2 + C.'],
    transferQuestion: 'Berechne ∫₀¹ 2x·e^(x²) dx (exaktes Ergebnis auf 2 Nachkommastellen).',
    transferAnswer: Math.E - 1,
    transferTolerance: 0.02,
    transferUnit: '',
    transferExplanation: 'u = x², du = 2x dx. Grenzen: x=0 → u=0, x=1 → u=1. ∫₀¹ eᵘ du = [eᵘ]₀¹ = e − 1 ≈ 1,718.',
    transferHints: ['Grenzen umrechnen: x=0 → u=0², x=1 → u=1².', '[eᵘ]₀¹ = e¹ − e⁰ = e − 1.'],
  },

  'int-2-2': {
    explanation: String.raw`**Vertiefung Partielle Integration:** Die Formel $\int u\cdot v'\,dx = u\cdot v - \int u'\cdot v\,dx$ kommt von der Produktregel. Wähle $u$ so, dass $u'$ einfacher wird. Typisch: $u$ = Polynom oder $\ln x$, $v'$ = $e^x$, $\sin x$, $\cos x$.`,
    conceptQuestion: 'Woher stammt die Formel für partielle Integration?',
    conceptOptions: [
      "Aus der Produktregel der Ableitung: (u·v)' = u'·v + u·v'",
      'Aus dem Hauptsatz der Integralrechnung',
      'Aus der Kettenregel der Ableitung',
      'Sie ist eine eigenständige Definition ohne Herleitung',
    ],
    conceptCorrect: 0,
    conceptExplanation: "(u·v)' = u'·v + u·v'. Umgestellt: u·v' = (u·v)' − u'·v. Integrieren: ∫u·v' dx = u·v − ∫u'·v dx. Die Integrationskonstante ist in u·v enthalten.",
    conceptHints: ['Starte mit der Produktregel (u·v)′.', 'Stelle nach u·v′ um und integriere beide Seiten.'],
    calcQuestion: '∫x·eˣ dx = x·eˣ − eˣ + C. Berechne den Wert des bestimmten Integrals ∫₀¹ x·eˣ dx auf 2 Nachkommastellen.',
    calcAnswer: 1,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: '[x·eˣ − eˣ]₀¹ = (1·e − e) − (0·1 − 1) = 0 − (−1) = 1.',
    calcHints: ['Stammfunktion: F(x) = x·eˣ − eˣ = eˣ(x−1).', 'F(1) = e·0 = 0, F(0) = 1·(−1) = −1. Differenz: 0−(−1) = 1.'],
    trueFalseStatement: '∫ln(x) dx = x·ln(x) − x + C.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Partielle Integration mit u = ln(x), v′ = 1, also v = x. ∫ln(x) dx = x·ln(x) − ∫(1/x)·x dx = x·ln(x) − x + C. Probe: (x·ln x − x)′ = ln x + 1 − 1 = ln x ✓.',
    trueFalseHints: ['Setze u = ln(x), v′ = 1.', 'u′ = 1/x, v = x. Dann: x·ln x − ∫1 dx.'],
    matchingQuestion: 'Ordne das Integral der richtigen Wahl von u und v′ zu.',
    matchingPairs: [
      { left: '∫x·eˣ dx', right: 'u = x, v′ = eˣ' },
      { left: '∫x·cos(x) dx', right: 'u = x, v′ = cos(x)' },
      { left: '∫ln(x) dx', right: 'u = ln(x), v′ = 1' },
    ],
    matchingExplanation: 'Wähle u so, dass u′ einfacher als u ist. Für Polynome gilt: Polynom als u. Für ln: ln als u (kein v′ möglich, also v′ = 1).',
    matchingHints: ['u′ soll einfacher werden.', 'ln(x) hat keine leichte Stammfunktion — also ln als u.'],
    sortingQuestion: 'Berechne ∫x·cos(x) dx mit partieller Integration in der richtigen Reihenfolge.',
    sortingItems: ['u = x, v′ = cos(x) wählen', "u' = 1, v = sin(x) berechnen", '∫x·cos(x) dx = x·sin(x) − ∫sin(x) dx aufschreiben', '∫sin(x) dx = −cos(x) berechnen', 'Ergebnis: x·sin(x) + cos(x) + C'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'x·sin(x) − (−cos(x)) + C = x·sin(x) + cos(x) + C. Probe: (x·sin x + cos x)′ = sin x + x·cos x − sin x = x·cos x ✓.',
    sortingHints: ['Erst u und v′ wählen, dann ableiten/integrieren.', 'Das −∫sin x dx = −(−cos x) = +cos x.'],
    errorQuestion: 'Jemand berechnet ∫x·eˣ dx = x·eˣ + eˣ + C. Was ist falsch?',
    errorOptions: [
      'Das Vorzeichen ist falsch: richtig ist x·eˣ − eˣ + C',
      'u und v′ wurden vertauscht',
      'eˣ hat keine Stammfunktion',
      'Das Ergebnis ist korrekt',
    ],
    errorCorrect: 0,
    errorExplanation: 'Partiell: u = x, v′ = eˣ, u′ = 1, v = eˣ. ∫x·eˣ dx = x·eˣ − ∫1·eˣ dx = x·eˣ − eˣ + C. Das Minus vor dem Restintegral ergibt − eˣ, nicht + eˣ.',
    errorHints: ['Die Formel lautet u·v − ∫u′·v dx.', 'Das Minus vor dem Restintegral überträgt sich auf eˣ.'],
    transferQuestion: 'Berechne ∫x²·eˣ dx = eˣ(x² − 2x + 2) + C. Werte die Stammfunktion bei x = 0 aus.',
    transferAnswer: 2,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'F(0) = e⁰·(0 − 0 + 2) = 1·2 = 2.',
    transferHints: ['e⁰ = 1.', '0² − 2·0 + 2 = 2.'],
  },

  'int-2-3': {
    explanation: String.raw`**Vertiefung Partialbruchzerlegung:** Gebrochen-rationale Funktionen $P(x)/Q(x)$ (mit $\deg P < \deg Q$) werden in einfache Brüche zerlegt. Für jeden verschiedenen reellen Linearfaktor $(x-a)$ im Nenner kommt ein Summand $A/(x-a)$. Dann: $\int A/(x-a)\,dx = A\cdot\ln|x-a|+C$.`,
    conceptQuestion: 'Wann setzt man die Partialbruchzerlegung ein?',
    conceptOptions: [
      'Bei gebrochen-rationalen Funktionen P(x)/Q(x) mit deg(P) < deg(Q)',
      'Bei Produkten wie x·eˣ',
      'Bei allen Integralen mit trigonometrischen Funktionen',
      'Immer als erste Methode',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Partialbruchzerlegung ist die Methode der Wahl für P(x)/Q(x) mit deg(P) < deg(Q). Ist deg(P) ≥ deg(Q), muss man zuerst Polynomdivision durchführen.',
    conceptHints: ['Erkenne: Zählergrad < Nennergrad?', 'Sonst erst Polynomdivision.'],
    calcQuestion: 'Bestimme A in 1/(x(x+2)) = A/x + B/(x+2) durch Einsetzen von x = 0.',
    calcAnswer: 0.5,
    calcTolerance: 0.001,
    calcUnit: '',
    calcExplanation: 'Multipliziere mit x(x+2): 1 = A(x+2) + Bx. Setze x = 0: 1 = A·2 → A = 1/2 = 0,5.',
    calcHints: ['Multipliziere mit dem Hauptnenner.', 'x = 0 einsetzen, damit B wegfällt.'],
    trueFalseStatement: '∫1/(x−3) dx = ln|x−3| + C.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Das ist ein direktes Grundintegral der Form ∫1/(x−a) dx = ln|x−a| + C. Probe: (ln|x−3|)′ = 1/(x−3) ✓.',
    trueFalseHints: ['∫1/u du = ln|u| + C mit u = x − 3.', 'du = dx hier.'],
    matchingQuestion: 'Ordne den Nennertyp und den Partialbruch-Ansatz zu.',
    matchingPairs: [
      { left: '(x−1)(x+2)', right: 'A/(x−1) + B/(x+2)' },
      { left: '(x−1)²', right: 'A/(x−1) + B/(x−1)²' },
      { left: 'x(x²+1)', right: 'A/x + (Bx+C)/(x²+1)' },
    ],
    matchingExplanation: 'Verschiedene Linearfaktoren: ein Bruch pro Faktor. Wiederholter Faktor: mehrfache Terme. Irreduzibler quadratischer Faktor: (Bx+C) im Zähler.',
    matchingHints: ['Für jeden Faktor im Nenner einen Summand.', 'Bei (x−a)² braucht man A/(x−a) und B/(x−a)².'],
    sortingQuestion: 'Berechne ∫1/((x−1)(x+1)) dx durch Partialbruchzerlegung in der richtigen Reihenfolge.',
    sortingItems: [
      'Ansatz: 1/((x−1)(x+1)) = A/(x−1) + B/(x+1)',
      'Mit (x−1)(x+1) multiplizieren: 1 = A(x+1) + B(x−1)',
      'x = 1 einsetzen: A = 1/2; x = −1 einsetzen: B = −1/2',
      '∫[(1/2)/(x−1) − (1/2)/(x+1)] dx',
      'Ergebnis: (1/2)·ln|x−1| − (1/2)·ln|x+1| + C',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'A = 1/2, B = −1/2. ∫(1/2)·(1/(x−1) − 1/(x+1)) dx = (1/2)(ln|x−1| − ln|x+1|) + C.',
    sortingHints: ['Erst Ansatz, dann Koeffizienten bestimmen.', 'Einsetzmethode: je einen Faktor zu Null machen.'],
    errorQuestion: 'Für 2/(x(x+2)) wird der Ansatz A/x² + B/(x+2) verwendet. Was ist falsch?',
    errorOptions: [
      'Der Faktor x taucht nur einmal auf, also A/x (nicht A/x²)',
      'Der Ansatz ist korrekt für wiederholte Faktoren',
      'B/(x+2) müsste (Bx+C)/(x+2) lauten',
      'Es fehlt ein weiterer Term',
    ],
    errorCorrect: 0,
    errorExplanation: 'x tritt im Nenner x(x+2) nur einfach auf. Für x^1 lautet der Ansatz A/x, nicht A/x². A/x² käme nur bei x² im Nenner.',
    errorHints: ['Einfacher Linearfaktor → einfacher Bruch.', 'x² → dann A/x + B/x².'],
    transferQuestion: 'Berechne ∫1/(x(x+2)) dx. Werte die Stammfunktion bei x = 2 aus (Ergebnis auf 3 Nachkommastellen). Verwende A = 1/2, B = −1/2.',
    transferAnswer: (Math.log(1) - Math.log(4)) / 2 - (Math.log(0.5) - Math.log(2)) / 2,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: 'Stammfunktion: F(x) = (1/2)·ln|x| − (1/2)·ln|x+2| + C. F(2) = (1/2)·ln(2) − (1/2)·ln(4) = (1/2)·(ln2 − ln4) = (1/2)·ln(1/2) ≈ (1/2)·(−0,693) ≈ −0,347.',
    transferHints: ['F(x) = (1/2)·ln|x| − (1/2)·ln|x+2|.', 'ln(2) − ln(4) = ln(2/4) = ln(1/2) ≈ −0,693.'],
  },

  'int-2-4': {
    explanation: String.raw`**Vertiefung Gemischte Integrationstechniken:** Erkenne die Struktur des Integranden: Ist eine Substitution sichtbar? Ist es ein Produkt aus Polynom und $e^x$/sin/cos → Partielle Integration. Ist es gebrochen-rational → Partialbruch. Ist der Zähler die Ableitung des Nenners → $\ln$-Formel.`,
    conceptQuestion: 'Welche Technik eignet sich für ∫x·sin(x) dx?',
    conceptOptions: [
      'Partielle Integration (Produkt aus Polynom und Sinus)',
      'Substitution (kein g(x) und g′(x) sichtbar)',
      'Partialbruchzerlegung (keine rationale Funktion)',
      'Direkte Integration mit Grundintegral',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'x·sin(x) ist ein Produkt aus Polynom (x) und trigonometrischer Funktion. Das ist das klassische Muster für partielle Integration. Substitution würde nicht helfen, da x und sin(x) keine Kompositionsstruktur bilden.',
    conceptHints: ['Suche das Muster: Polynom · (eˣ/sin/cos) → Partielle Integration.', 'Gibt es eine Komposition f(g(x))·g′(x)? Wenn nein, ist Substitution ungeeignet.'],
    calcQuestion: '∫e^(2x) dx ergibt e^(2x)/2 + C. Berechne ∫₀¹ e^(2x) dx auf 2 Nachkommastellen.',
    calcAnswer: (Math.E * Math.E - 1) / 2,
    calcTolerance: 0.02,
    calcUnit: '',
    calcExplanation: '[e^(2x)/2]₀¹ = e²/2 − e⁰/2 = (e² − 1)/2 ≈ (7,389 − 1)/2 ≈ 3,19.',
    calcHints: ['Stammfunktion: e^(2x)/2 (lineare Substitution).', '(e² − 1)/2 ≈ 6,389/2 ≈ 3,19.'],
    trueFalseStatement: '∫(2x+3)/(x²+3x+5) dx = ln|x²+3x+5| + C, weil der Zähler die Ableitung des Nenners ist.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. (x²+3x+5)′ = 2x+3. Wenn Zähler = Ableitung des Nenners, gilt ∫f′(x)/f(x) dx = ln|f(x)| + C.',
    trueFalseHints: ['Leite den Nenner ab.', 'Muster: ∫f′/f dx = ln|f| + C.'],
    matchingQuestion: 'Ordne den Integranden der passenden Methode zu.',
    matchingPairs: [
      { left: '∫2x/(x²+1) dx', right: 'Substitution u = x²+1' },
      { left: '∫x·ln(x) dx', right: 'Partielle Integration' },
      { left: '∫1/(x(x−1)) dx', right: 'Partialbruchzerlegung' },
    ],
    matchingExplanation: '2x ist Ableitung von x²+1 → Substitution. x·ln(x): Produkt ohne Komposition → partielle Integration. 1/(x(x−1)): gebrochen-rational → Partialbruch.',
    matchingHints: ['Prüfe: Komposition? Produkt? Bruch?', 'Die Struktur des Integranden bestimmt die Methode.'],
    sortingQuestion: 'Erkenne die Methode und berechne ∫x·sin(x) dx in der richtigen Reihenfolge.',
    sortingItems: ['Partielle Integration wählen (Polynom · Trig)', 'u = x, v′ = sin(x) setzen', "u' = 1, v = −cos(x) berechnen", '∫x·sin(x) dx = −x·cos(x) + ∫cos(x) dx aufschreiben', 'Ergebnis: −x·cos(x) + sin(x) + C'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: '−x·cos(x) − ∫1·(−cos x) dx = −x·cos(x) + sin(x) + C. Probe: (−x·cos x + sin x)′ = −cos x + x·sin x + cos x = x·sin x ✓.',
    sortingHints: ['v = −cos(x) (Integral von sin).', '−∫(−cos x) dx = +∫cos x dx = sin x.'],
    errorQuestion: 'Für ∫sin²(x) dx wird die Substitution u = sin(x) versucht. Warum scheitert das?',
    errorOptions: [
      'du = cos(x) dx, aber cos(x) steht nicht im Integranden',
      'sin(x) kann nicht substituiert werden',
      'Substitution ergibt immer u²/2, was richtig ist',
      'Die Ableitung von sin²(x) fehlt',
    ],
    errorCorrect: 0,
    errorExplanation: 'u = sin(x) → du = cos(x) dx. Im Integral ∫sin²(x) dx steht kein cos(x) — die Substitution bleibt unvollständig. Korrekt: trigonometrische Identität sin²(x) = (1 − cos(2x))/2 verwenden.',
    errorHints: ["Substitution braucht g'(x) im Integranden.", 'cos(x) ist nicht in ∫sin²(x) dx vorhanden.'],
    transferQuestion: 'Berechne ∫₀^(π/2) x·cos(x) dx. (Exakt: π/2 − 1 ≈ 0,571)',
    transferAnswer: Math.PI / 2 - 1,
    transferTolerance: 0.02,
    transferUnit: '',
    transferExplanation: 'Partielle Integration: u = x, v′ = cos(x), v = sin(x). [x·sin(x)]₀^(π/2) − ∫₀^(π/2) sin(x) dx = π/2 − [−cos(x)]₀^(π/2) = π/2 − (0 − (−1)) = π/2 − 1 ≈ 0,571.',
    transferHints: ['[x·sin x]₀^(π/2) = π/2·1 − 0 = π/2.', '[−cos x]₀^(π/2) = −cos(π/2) + cos(0) = 0 + 1 = 1.'],
  },

  'int-3-1': {
    explanation: String.raw`**Vertiefung Volumen und Rotationskörper:** Rotiert $f(x)$ um die x-Achse, entsteht ein Körper aus unendlich vielen Kreisscheiben mit Radius $r=f(x)$. Das Volumen ist $V=\pi\int_a^b [f(x)]^2\,dx$. Sonderfall Hohlkörper (Ringmethode): $V=\pi\int_a^b([f(x)]^2-[g(x)]^2)\,dx$.`,
    conceptQuestion: 'Warum steht in der Rotationsvolumen-Formel [f(x)]² und nicht f(x)?',
    conceptOptions: [
      'Weil jede Querscheibe eine Kreisfläche π·r² hat und r = f(x) gilt',
      'Weil man beim Integrieren immer quadriert',
      'Weil der Radius das Quadrat der Höhe ist',
      'Weil Volumen immer in Quadratmetern angegeben wird',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Der Radius der Kreisscheibe an der Stelle x ist r = f(x). Die Scheibenfläche ist π·r² = π·[f(x)]². Das Volumen ist die Summe aller Scheibenflächen mal Dicke dx: V = π∫[f(x)]² dx.',
    conceptHints: ['Kreisfläche = π·r². Was ist r hier?', 'r = f(x) an jedem Punkt x.'],
    calcQuestion: 'f(x) = 2 rotiert auf [0, 3] um die x-Achse (Zylinder). Berechne V/π.',
    calcAnswer: 12,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'V = π·∫₀³ 4 dx = π·[4x]₀³ = π·12. Also V/π = 12. Probe: Zylinder V = π·r²·h = π·4·3 = 12π ✓.',
    calcHints: ['[f(x)]² = 4.', 'V/π = ∫₀³ 4 dx = 12.'],
    trueFalseStatement: 'Bei der Rotation von f(x) = √x auf [0, 4] um die x-Achse vereinfacht sich [f(x)]² = x.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. (√x)² = x. Das ist einer der Vorteile der Formel: Wurzeln verschwinden beim Quadrieren. V = π·∫₀⁴ x dx = π·8.',
    trueFalseHints: ['(√x)² = x — kein Wurzelzeichen mehr!', 'V/π = ∫₀⁴ x dx = [x²/2]₀⁴ = 8.'],
    matchingQuestion: 'Ordne Funktion/Intervall dem Rotationskörper zu.',
    matchingPairs: [
      { left: 'f(x) = R, [0, h]', right: 'Zylinder' },
      { left: 'f(x) = (R/h)·x, [0, h]', right: 'Kegel' },
      { left: 'f(x) = √(R²−x²), [−R, R]', right: 'Kugel' },
    ],
    matchingExplanation: 'Konstante → Zylinder. Lineare Funktion durch Ursprung → Kegel. Halbkreis → Kugel. Klassische Geometrieformeln entstehen als Spezialfälle.',
    matchingHints: ['Zylinder hat konstanten Radius.', 'Kegel hat linear wachsenden Radius.'],
    sortingQuestion: 'Berechne das Volumen des Kegels mit f(x) = x auf [0, 3] (V/π) in der richtigen Reihenfolge.',
    sortingItems: ['[f(x)]² = x² berechnen', 'V = π·∫₀³ x² dx aufstellen', 'Stammfunktion x³/3 bestimmen', 'Grenzen einsetzen: [x³/3]₀³ = 9', 'V/π = 9 ablesen'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'V = π·[x³/3]₀³ = π·9 = 9π. Probe: Kegel V = (1/3)·π·r²·h = (1/3)·π·9·3 = 9π ✓.',
    sortingHints: ['Erst quadrieren, dann integrieren.', '3³/3 = 27/3 = 9.'],
    errorQuestion: 'Jemand berechnet für f(x) = 3 auf [0, 2]: V = π·∫₀² 3 dx = 6π. Was ist falsch?',
    errorOptions: [
      '[f(x)]² = 9, nicht 3 — richtig: V = π·∫₀² 9 dx = 18π',
      'Der Faktor π darf nicht vor das Integral',
      'Das Intervall [0, 2] ist zu groß',
      'Die Formel V = π·∫f dx gilt für Längen, nicht Flächen',
    ],
    errorCorrect: 0,
    errorExplanation: 'In der Rotationsformel steht [f(x)]²: [3]² = 9. Also V = π·∫₀² 9 dx = π·18 = 18π. Ohne Quadrieren wäre es die Fläche unter f, nicht das Volumen.',
    errorHints: ['V = π·∫[f(x)]² dx — das Quadrat ist entscheidend.', '3² = 9, nicht 3.'],
    transferQuestion: 'f(x) = √x rotiert auf [0, 4] um die x-Achse. Berechne V/π.',
    transferAnswer: 8,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: '[√x]² = x. V = π·∫₀⁴ x dx = π·[x²/2]₀⁴ = π·8. Also V/π = 8.',
    transferHints: ['(√x)² = x vereinfacht das Integral.', '[x²/2]₀⁴ = 16/2 − 0 = 8.'],
  },

  'int-3-2': {
    explanation: String.raw`**Vertiefung Schwerpunkte und Trägheitsmomente:** Für eine homogene Fläche unter $f(x)\geq 0$ gilt: $\bar{x}=\frac{1}{A}\int_a^b x\cdot f(x)\,dx$, $A=\int_a^b f(x)\,dx$. Das Flächenträgheitsmoment bezüglich der y-Achse ist $I_y=\int_a^b x^2\cdot f(x)\,dx$ — wichtig für Biegesteifigkeit von Balken.`,
    conceptQuestion: 'Was bedeutet der Flächenschwerpunkt x̄ physikalisch?',
    conceptOptions: [
      'Der Punkt, an dem man die Fläche auf einer Nadelspitze ausbalancieren könnte',
      'Der Mittelpunkt des Integrationsintervalls',
      'Der Maximum-Wert von f(x)',
      'Die Summe aller x-Koordinaten geteilt durch die Anzahl',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'x̄ ist der gewichtete Mittelwert der x-Position, gewichtet mit der Flächendichte f(x). Am Schwerpunkt würde die Fläche auf einer Nadel balancieren — er ist das "Massenzentrum" der Fläche.',
    conceptHints: ['Denke an Gleichgewicht: Links und rechts vom Schwerpunkt gleiche "Drehmomente".', 'Gewichteter Mittelwert: Σ(x · m) / Σm mit m → f(x)·dx.'],
    calcQuestion: 'Berechne x̄ für f(x) = x auf [0, 2]. (A = ∫₀² x dx = 2)',
    calcAnswer: 4 / 3,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: 'x̄ = (1/2)·∫₀² x·x dx = (1/2)·∫₀² x² dx = (1/2)·[x³/3]₀² = (1/2)·(8/3) = 4/3 ≈ 1,333.',
    calcHints: ['A = [x²/2]₀² = 2.', 'x̄ = (1/A)·∫x·f(x) dx = (1/2)·∫₀² x² dx.'],
    trueFalseStatement: 'Der Schwerpunkt x̄ muss immer innerhalb des Integrationsintervalls [a, b] liegen.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. x̄ ist ein gewichteter Mittelwert aller x-Werte in [a, b]. Gewichtete Mittelwerte liegen immer zwischen dem kleinsten und größten Wert — also in [a, b].',
    trueFalseHints: ['Ein Mittelwert liegt stets zwischen Minimum und Maximum.', 'Physikalisch: Das Gleichgewicht liegt immer "innerhalb" des Systems.'],
    matchingQuestion: 'Ordne die technische Größe ihrer Integralformel zu.',
    matchingPairs: [
      { left: 'Fläche A', right: '∫ₐᵇ f(x) dx' },
      { left: 'Schwerpunkt x̄ (unnormiert)', right: '∫ₐᵇ x·f(x) dx' },
      { left: 'Trägheitsmoment Iy (unnormiert)', right: '∫ₐᵇ x²·f(x) dx' },
    ],
    matchingExplanation: 'Jede Größe "gewichtet" mit einer höheren Potenz von x: x⁰ → Fläche, x¹ → Schwerpunktmoment, x² → Trägheitsmoment.',
    matchingHints: ['Höhere x-Potenz → höheres Moment.', 'x̄ = (1/A)·∫x·f dx (normiert).'],
    sortingQuestion: 'Berechne x̄ für f(x) = 1 auf [0, 3] in der richtigen Reihenfolge.',
    sortingItems: ['A = ∫₀³ 1 dx = 3 berechnen', '∫₀³ x·1 dx = [x²/2]₀³ = 9/2 berechnen', 'x̄ = (1/3)·(9/2) aufstellen', 'x̄ = 9/6 = 3/2 = 1,5 ablesen'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'f(x) = 1 (gleichmäßige Fläche). Der Schwerpunkt liegt genau in der Mitte: x̄ = (0+3)/2 = 1,5 ✓.',
    sortingHints: ['Für konstante f liegt der Schwerpunkt in der Mitte.', '(1/3)·(9/2) = 9/6 = 3/2.'],
    errorQuestion: 'Jemand berechnet x̄ = ∫₀² x·f(x) dx ohne durch A zu dividieren. Was ist falsch?',
    errorOptions: [
      'x̄ muss durch die Fläche A dividiert werden: x̄ = (1/A)·∫x·f dx',
      'Das Integral ist von oben nach unten auszuwerten',
      'x·f(x) muss quadriert werden',
      'Das Integral ist korrekt — A = 1 immer',
    ],
    errorCorrect: 0,
    errorExplanation: 'Ohne Division durch A erhält man das (unnormierte) statische Moment, nicht den Schwerpunkt. x̄ = (1/A)·∫x·f(x) dx. A = 1 gilt nur für Einheitsflächen.',
    errorHints: ['x̄ ist ein Mittelwert — muss normiert werden.', 'Ohne /A: x nimmt zu bei größerem Intervall — das wäre kein Schwerpunkt.'],
    transferQuestion: 'Berechne x̄ für f(x) = x² auf [0, 3]. (A = ∫₀³ x² dx = 9)',
    transferAnswer: 9 / 4,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: '∫₀³ x·x² dx = ∫₀³ x³ dx = [x⁴/4]₀³ = 81/4. x̄ = (1/9)·(81/4) = 81/36 = 9/4 = 2,25.',
    transferHints: ['∫₀³ x³ dx = 3⁴/4 = 81/4.', 'x̄ = (1/9)·(81/4) = 9/4.'],
  },

  'int-3-3': {
    explanation: String.raw`**Vertiefung Numerische Integration:** Wenn keine geschlossene Stammfunktion existiert, nähert man das Integral numerisch an. **Trapezregel** (n gleiche Intervalle): $\int_a^b f\,dx \approx \frac{h}{2}[f(x_0)+2f(x_1)+\cdots+2f(x_{n-1})+f(x_n)]$. **Simpsonregel** (n gerade): $\int_a^b f\,dx \approx \frac{h}{3}[f(x_0)+4f(x_1)+2f(x_2)+\cdots+4f(x_{n-1})+f(x_n)]$ mit $h=(b-a)/n$.`,
    conceptQuestion: 'Warum ist numerische Integration manchmal notwendig?',
    conceptOptions: [
      'Manche Funktionen (z.B. e^(−x²)) haben keine geschlossene Stammfunktion',
      'Numerische Methoden sind immer genauer als analytische',
      'Alle Integrale sind analytisch nicht lösbar',
      'Weil Computer keine Stammfunktionen kennen',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Funktionen wie e^(−x²), sin(x)/x oder √(1+x⁴) haben keine elementare Stammfunktion. Für solche Integrale ist numerische Näherung unverzichtbar.',
    conceptHints: ['Denk an das Gaußsche Fehlerintegral ∫e^(−x²) dx.', 'Nicht jede stetige Funktion ist analytisch integrierbar.'],
    calcQuestion: 'Trapezregel mit n = 2 für ∫₀² x² dx: h = 1, Stützstellen x₀=0, x₁=1, x₂=2. Berechne den Näherungswert.',
    calcAnswer: 3,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: 'T = (h/2)·[f(0) + 2f(1) + f(2)] = (1/2)·[0 + 2·1 + 4] = (1/2)·6 = 3. Exakt: 8/3 ≈ 2,667. Fehler: 0,333 (Trapezregel überschätzt hier).',
    calcHints: ['f(0) = 0, f(1) = 1, f(2) = 4.', 'T = (1/2)·[0 + 2·1 + 4].'],
    trueFalseStatement: 'Die Simpsonregel ist im Allgemeinen genauer als die Trapezregel, weil sie Parabeln statt Geraden durch die Stützpunkte legt.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Die Trapezregel approximiert durch Geraden (Polynome 1. Grades), Simpson durch Parabeln (2. Grades). Höherer Polynomgrad → kleinerer Fehler bei gleicher Intervallanzahl.',
    trueFalseHints: ['Trapez: Gerade zwischen zwei Punkten.', 'Simpson: Parabel durch drei Punkte — passt besser an gekrümmte Funktionen.'],
    matchingQuestion: 'Ordne Methode und Gewichtsschema zu.',
    matchingPairs: [
      { left: 'Trapezregel (n = 2)', right: 'Gewichte: 1, 2, 1 (mal h/2)' },
      { left: 'Simpsonregel (n = 2)', right: 'Gewichte: 1, 4, 1 (mal h/3)' },
      { left: 'Rechteckregel (links)', right: 'Gewichte: 1, 1 (mal h), nur linke Punkte' },
    ],
    matchingExplanation: 'Trapez: h/2·(f₀ + 2f₁ + f₂). Simpson: h/3·(f₀ + 4f₁ + f₂). Rechteck: h·(f₀ + f₁) (links-Variante).',
    matchingHints: ['Das mittlere Gewicht unterscheidet die Methoden.', 'Simpson: 1-4-1-4-...-1. Trapez: 1-2-2-...-2-1.'],
    sortingQuestion: 'Wende die Simpsonregel mit n = 2 auf ∫₀² x² dx an (h = 1) in der richtigen Reihenfolge.',
    sortingItems: ['Stützstellen x₀=0, x₁=1, x₂=2 berechnen', 'Funktionswerte: f(0)=0, f(1)=1, f(2)=4 bestimmen', 'Simpson-Schema: (h/3)·[f₀ + 4f₁ + f₂] aufstellen', '(1/3)·[0 + 4·1 + 4] = (1/3)·8 berechnen', 'Ergebnis: 8/3 ≈ 2,667'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Simpson: (1/3)·(0 + 4 + 4) = 8/3 ≈ 2,667. Das ist exakt! Simpsonregel ist für Polynome bis Grad 3 exakt.',
    sortingHints: ['h = (b−a)/n = 2/2 = 1.', '4·f(1) = 4·1 = 4. Dann 0 + 4 + 4 = 8. Mal 1/3.'],
    errorQuestion: 'Bei der Trapezregel für ∫₀⁴ f dx mit n = 2 setzt jemand h = 4. Was ist falsch?',
    errorOptions: [
      'h = (b−a)/n = (4−0)/2 = 2, nicht 4',
      'h = (b−a) = 4 ist korrekt',
      'n muss gerade sein bei der Trapezregel',
      'Das Intervall [0, 4] ist für die Trapezregel zu groß',
    ],
    errorCorrect: 0,
    errorExplanation: 'Die Schrittweite h ist die Breite eines Teilintervalls: h = (b−a)/n = 4/2 = 2. Mit h = 4 würde man nur ein Trapez über das doppelte Intervall auswerten.',
    errorHints: ['h = Intervallbreite / Anzahl der Teilintervalle.', '(b−a) = 4, n = 2 → h = 4/2 = 2.'],
    transferQuestion: 'Trapezregel mit n = 2 für ∫₀¹ eˣ dx: h = 0,5, f(0) = 1, f(0,5) ≈ 1,6487, f(1) ≈ 2,7183. Berechne den Näherungswert auf 3 Nachkommastellen.',
    transferAnswer: (0.5 / 2) * (1 + 2 * 1.6487 + 2.7183),
    transferTolerance: 0.005,
    transferUnit: '',
    transferExplanation: 'T = (0,5/2)·[1 + 2·1,6487 + 2,7183] = 0,25·[1 + 3,2974 + 2,7183] = 0,25·7,0157 ≈ 1,754. Exakt: e − 1 ≈ 1,718.',
    transferHints: ['T = (h/2)·[f(x₀) + 2f(x₁) + f(x₂)].', '0,25·(1 + 3,2974 + 2,7183) = 0,25·7,0157.'],
  },
}

export const integralrechnungSupplements = Object.fromEntries(
  Object.entries(profiles).map(([lessonId, profile]) => [
    lessonId,
    {
      explanation: profile.explanation,
      exercises: bank(profile),
    },
  ])
)
