function mc(question, options, correctIndex, explanation, hints = [], wrongAnswerExplanations = undefined) {
  return {
    type: 'multiple-choice',
    question,
    options,
    correctIndex,
    explanation,
    hints,
    ...(wrongAnswerExplanations ? { wrongAnswerExplanations } : {}),
  }
}

function ni(question, correctValue, tolerance, unit, explanation, hints = []) {
  return { type: 'number-input', question, correctValue, tolerance, unit, explanation, hints }
}

function tf(statement, correct, explanation, hints = []) {
  return { type: 'true-false', statement, correct, explanation, hints }
}

function matching(question, pairs, explanation, hints = []) {
  return { type: 'matching', question, pairs, explanation, hints }
}

function sorting(question, items, correctOrder, explanation, hints = []) {
  return { type: 'sorting', question, items, correctOrder, explanation, hints }
}

function withExamPrefix(exercise, exam) {
  if (!exam) return exercise
  if (exercise.question && !exercise.question.includes('[PRÜFUNG]')) {
    return { ...exercise, question: `[PRÜFUNG] ${exercise.question}` }
  }
  if (exercise.statement && !exercise.statement.includes('[PRÜFUNG]')) {
    return { ...exercise, statement: `[PRÜFUNG] ${exercise.statement}` }
  }
  return exercise
}

function bank(profile) {
  const exercises = [
    mc(profile.conceptQuestion, profile.conceptOptions, profile.conceptCorrect, profile.conceptExplanation, profile.conceptHints, profile.conceptWrongAnswers),
    ni(profile.calcQuestion, profile.calcAnswer, profile.calcTolerance, profile.calcUnit, profile.calcExplanation, profile.calcHints),
    tf(profile.trueFalseStatement, profile.trueFalseCorrect, profile.trueFalseExplanation, profile.trueFalseHints),
    matching(profile.matchingQuestion, profile.matchingPairs, profile.matchingExplanation, profile.matchingHints),
    sorting(profile.sortingQuestion, profile.sortingItems, profile.sortingOrder, profile.sortingExplanation, profile.sortingHints),
    mc(profile.errorQuestion, profile.errorOptions, profile.errorCorrect, profile.errorExplanation, profile.errorHints, profile.errorWrongAnswers),
    ni(profile.transferQuestion, profile.transferAnswer, profile.transferTolerance, profile.transferUnit, profile.transferExplanation, profile.transferHints),
  ]
  return exercises.map((exercise) => withExamPrefix(exercise, profile.exam))
}

const profiles = {
  'la-1-1': {
    explanation: String.raw`**Vertiefung Grundoperationen:** Die drei Grundoperationen einer Matrix — Addition, Skalarmultiplikation und Transposition — laufen elementweise. Bei Addition müssen beide Matrizen dieselbe Dimension $m \times n$ haben. Bei der Transposition wird aus $A_{m\times n}$ die Matrix $A^T_{n\times m}$: Zeile $i$ von $A$ wird Spalte $i$ von $A^T$.`,
    conceptQuestion: 'Welche Bedingung muss gelten, damit A + B berechnet werden kann?',
    conceptOptions: [
      'A und B müssen dieselbe Dimension m × n haben',
      'A und B müssen quadratisch sein',
      'A muss mehr Zeilen als B haben',
      'Die Determinanten von A und B müssen gleich sein',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Die Addition ist nur elementweise definiert, d.h. a_{ij} + b_{ij}. Das geht nur, wenn beide Matrizen an jedem Platz (i,j) einen Eintrag haben — also gleiche Dimension.',
    conceptHints: ['Denke an Vektoren: zwei Vektoren addiert man nur, wenn sie dieselbe Anzahl Einträge haben.', 'Gleiche Dimension = gleiche Anzahl Zeilen und gleiche Anzahl Spalten.'],
    calcQuestion: 'A = [[3,1],[2,4]] und B = [[1,2],[3,0]]. Berechne das Element (1,2) von A + B.',
    calcAnswer: 3,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'Element (1,2) von A+B ist a_{12} + b_{12} = 1 + 2 = 3.',
    calcHints: ['Element (1,2) bedeutet: erste Zeile, zweite Spalte.', 'Addiere die entsprechenden Elemente: 1 + 2 = 3.'],
    trueFalseStatement: 'Die Transposition einer 3×2-Matrix ergibt eine 2×3-Matrix.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Bei der Transposition werden Zeilen und Spalten vertauscht. Aus m×n wird n×m, also aus 3×2 wird 2×3.',
    trueFalseHints: ['Transposition = Zeilen werden zu Spalten.', 'Aus A_{m×n} wird A^T_{n×m}.'],
    matchingQuestion: 'Ordne die Grundoperationen ihren Rechenregeln zu.',
    matchingPairs: [
      { left: 'Addition', right: 'elementweise, gleiche Dimension nötig' },
      { left: 'Skalarmultiplikation', right: 'jeden Eintrag mit Skalar multiplizieren' },
      { left: 'Transposition', right: 'Zeilen und Spalten vertauschen' },
    ],
    matchingExplanation: 'Diese drei Grundoperationen sind voneinander unabhängig und werden alle elementweise oder strukturell definiert.',
    matchingHints: ['Skalarmultiplikation: jedes a_{ij} wird mit λ multipliziert.', 'Transposition: a_{ij} wird zu a^T_{ji}.'],
    sortingQuestion: 'Bringe die Schritte zur Berechnung von 2·A^T in die richtige Reihenfolge.',
    sortingItems: ['Matrix A aufschreiben', 'A transponieren: Zeilen zu Spalten', 'Jeden Eintrag mit 2 multiplizieren', 'Ergebnis notieren'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Erst transponieren, dann skalieren — oder umgekehrt: (λA)^T = λA^T, die Reihenfolge ist hier vertauschbar.',
    sortingHints: ['Transposition und Skalarmultiplikation kommutieren.', 'Lies (2A)^T = 2·A^T.'],
    errorQuestion: 'Welcher Fehler steckt in der Aussage: "A + B geht immer, wenn A quadratisch ist"?',
    errorOptions: [
      'A und B müssen gleiche Dimension haben, nicht nur A quadratisch',
      'A muss immer größer als B sein',
      'Quadratische Matrizen dürfen nie addiert werden',
      'Addition erfordert, dass det(A) ≠ 0',
    ],
    errorCorrect: 0,
    errorExplanation: 'Quadratisch bedeutet nur, dass Zeilen- und Spaltenanzahl von A gleich sind. Für A + B brauchen A und B dieselbe Dimension, unabhängig davon ob sie quadratisch sind.',
    errorHints: ['Gegenbeispiel: A ist 3×3, B ist 2×2 — beide quadratisch, aber A+B ist nicht definiert.', 'Dimension muss übereinstimmen.'],
    transferQuestion: 'A = [[2,4],[6,8]]. Berechne das Element (2,1) von A^T.',
    transferAnswer: 4,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'a^T_{ij} = a_{ji}. Also a^T_{21} = a_{12} = 4. Zeile 2, Spalte 1 von A^T entspricht Zeile 1, Spalte 2 von A = 4.',
    transferHints: ['a^T_{ij} = a_{ji}.', 'Element (2,1) von A^T = Element (1,2) von A.'],
  },
  'la-1-2': {
    explanation: String.raw`**Vertiefung Matrizenmultiplikation:** Das Produkt $C = A \cdot B$ ist nur definiert, wenn die Spaltenzahl von $A$ gleich der Zeilenzahl von $B$ ist. Das Element $c_{ij}$ ist das Skalarprodukt der $i$-ten Zeile von $A$ mit der $j$-ten Spalte von $B$: $c_{ij} = \sum_k a_{ik} \cdot b_{kj}$. Matrizenmultiplikation ist im Allgemeinen nicht kommutativ: $A \cdot B \neq B \cdot A$.`,
    conceptQuestion: 'Welche Dimension hat das Produkt C = A·B, wenn A eine 3×4-Matrix und B eine 4×2-Matrix ist?',
    conceptOptions: ['3×2', '4×4', '3×4', '2×3'],
    conceptCorrect: 0,
    conceptExplanation: 'A ist m×k (3×4), B ist k×n (4×2). Das Produkt hat Dimension m×n = 3×2. Die inneren Dimensionen (k=4) müssen übereinstimmen und fallen heraus.',
    conceptHints: ['Schema: (m×k)·(k×n) = (m×n).', 'Innere Dimension muss gleich sein, äußere Dimensionen bleiben.'],
    calcQuestion: 'A = [[1,2],[3,4]] und B = [[1,0],[0,1]]. Berechne das Element (1,1) von A·B.',
    calcAnswer: 1,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'c_{11} = Zeile 1 von A · Spalte 1 von B = [1,2]·[1,0] = 1·1 + 2·0 = 1. B ist die Einheitsmatrix, also A·B = A.',
    calcHints: ['c_{11} = a_{11}·b_{11} + a_{12}·b_{21}.', 'Die Einheitsmatrix lässt jede Matrix unverändert.'],
    trueFalseStatement: 'Für beliebige quadratische Matrizen A und B gilt immer A·B = B·A.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Matrizenmultiplikation ist im Allgemeinen nicht kommutativ. Gegenbeispiel: A=[[1,2],[0,1]], B=[[1,0],[1,1]] — die Produkte A·B und B·A unterscheiden sich.',
    trueFalseHints: ['Kommutativgesetz gilt bei Zahlen, nicht allgemein bei Matrizen.', 'Probe: Multipliziere ein einfaches Beispiel in beiden Reihenfolgen.'],
    matchingQuestion: 'Ordne die Multiplikationseigenschaften ihren Aussagen zu.',
    matchingPairs: [
      { left: 'Dimensionsregel', right: '(m×k)·(k×n) = (m×n)' },
      { left: 'Nicht kommutativ', right: 'A·B ≠ B·A im Allgemeinen' },
      { left: 'Assoziativ', right: '(A·B)·C = A·(B·C)' },
    ],
    matchingExplanation: 'Diese drei Eigenschaften sind das Fundament beim Rechnen mit Matrizenprodukten.',
    matchingHints: ['Assoziativgesetz gilt, Kommutativgesetz nicht.', 'Dimensionsregel: innere Dimension muss gleich sein.'],
    sortingQuestion: 'Ordne den Rechenweg für c_{12} = (Zeile 1 von A) · (Spalte 2 von B) bei 2×2-Matrizen.',
    sortingItems: ['Zeile 1 von A ablesen: [a_{11}, a_{12}]', 'Spalte 2 von B ablesen: [b_{12}, b_{22}]', 'Elementweise multiplizieren', 'Produkte addieren: c_{12} = a_{11}·b_{12} + a_{12}·b_{22}'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Das Zeile-mal-Spalte-Prinzip muss für jedes Element c_{ij} einzeln durchgeführt werden.',
    sortingHints: ['Erst Zeile i von A, dann Spalte j von B.', 'Summe der elementweisen Produkte.'],
    errorQuestion: 'Warum ist die Berechnung C = A·B falsch, wenn A eine 2×3-Matrix und B eine 2×3-Matrix ist?',
    errorOptions: [
      'Spaltenzahl von A (3) ≠ Zeilenzahl von B (2), Multiplikation nicht definiert',
      'Beide Matrizen müssen quadratisch sein',
      'A·B ist nur für gleiche Matrizen definiert',
      'Die Determinante muss ungleich null sein',
    ],
    errorCorrect: 0,
    errorExplanation: 'Die inneren Dimensionen müssen übereinstimmen: Spaltenzahl von A = Zeilenzahl von B. Hier: 3 ≠ 2, also ist A·B nicht definiert. B·A (2×3)·(2×3) wäre ebenfalls undefiniert.',
    errorHints: ['Prüfe: Spaltenzahl von A = Zeilenzahl von B?', '(m×k)·(k×n): das k muss gleich sein.'],
    transferQuestion: 'A = [[2,1],[0,3]] und B = [[1,0],[2,1]]. Berechne das Element (2,2) von A·B.',
    transferAnswer: 3,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'c_{22} = Zeile 2 von A · Spalte 2 von B = [0,3]·[0,1] = 0·0 + 3·1 = 3.',
    transferHints: ['Zeile 2 von A ist [0,3].', 'Spalte 2 von B ist [0,1].'],
  },
  'la-1-3': {
    explanation: String.raw`**Vertiefung Determinanten:** Die Determinante einer $2\times2$-Matrix ist $\det A = a_{11}a_{22} - a_{12}a_{21}$. Bei $3\times3$ nutzt man den Laplaceschen Entwicklungssatz: Entwicklung nach einer Zeile oder Spalte. Regel von Sarrus ist eine praktische Mnemotechnik. Die Determinante gibt das orientierte Volumen des durch die Spaltenvektoren aufgespannten Körpers an.`,
    conceptQuestion: 'Was bedeutet es, wenn det(A) = 0?',
    conceptOptions: [
      'Die Matrix ist singulär und hat keine Inverse',
      'Die Matrix ist die Einheitsmatrix',
      'Die Matrix hat Rang n',
      'Die Spalten der Matrix sind orthogonal',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'det(A) = 0 bedeutet, dass die Spalten (oder Zeilen) linear abhängig sind. Die Matrix ist singulär: sie hat keine Inverse und das zugehörige LGS ist nicht eindeutig lösbar.',
    conceptHints: ['Singulär = nicht invertierbar.', 'Linear abhängige Spalten spannen keinen vollen Raum auf.'],
    calcQuestion: 'Berechne det([[3,1],[2,4]]).',
    calcAnswer: 10,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'det = 3·4 - 1·2 = 12 - 2 = 10. Formel: a_{11}·a_{22} - a_{12}·a_{21}.',
    calcHints: ['Formel für 2×2: ad - bc.', '3·4 = 12, 1·2 = 2, Differenz = 10.'],
    trueFalseStatement: 'det(A·B) = det(A) · det(B) gilt für quadratische Matrizen gleicher Dimension.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Der Multiplikationssatz für Determinanten: det(A·B) = det(A)·det(B). Dies gilt für quadratische Matrizen gleicher Größe.',
    trueFalseHints: ['Determinante ist multiplikativ.', 'Folgerung: det(A²) = det(A)².'],
    matchingQuestion: 'Ordne die Determinanten-Rechenregeln ihren Aussagen zu.',
    matchingPairs: [
      { left: 'det([[a,b],[c,d]])', right: 'ad - bc' },
      { left: 'det(A^T)', right: 'det(A)' },
      { left: 'Zeile doppelt', right: 'det = 0' },
    ],
    matchingExplanation: 'Diese Regeln sind zentral für die Determinantenrechnung und Klausuraufgaben.',
    matchingHints: ['Zwei gleiche Zeilen oder Spalten: det = 0.', 'Transposition ändert den Wert der Determinante nicht.'],
    sortingQuestion: 'Bringe den Laplace-Entwicklungssatz nach der ersten Zeile für eine 3×3-Matrix in Reihenfolge.',
    sortingItems: ['Erste Zeile a_{11}, a_{12}, a_{13} ablesen', 'Vorzeichen (+,-,+) für Positionen bestimmen', 'Zu jedem Element die 2×2-Untermatrix (Minor) bilden', 'det = a_{11}·M_{11} - a_{12}·M_{12} + a_{13}·M_{13} berechnen'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Entwicklung nach Zeile 1: alternierendes Vorzeichen beginnt mit +.',
    sortingHints: ['Vorzeichen: (-1)^{i+j}.', 'Minor M_{ij} = Determinante nach Streichen von Zeile i und Spalte j.'],
    errorQuestion: 'Welcher Fehler steckt in det([[2,3],[1,4]]) = 2·4 + 3·1 = 11?',
    errorOptions: [
      'Es muss ad - bc sein, nicht ad + bc: det = 8 - 3 = 5',
      'Die Formel lautet a+d für 2×2',
      'det ist immer positiv',
      '2×2-Determinanten werden per Sarrus berechnet',
    ],
    errorCorrect: 0,
    errorExplanation: 'Die korrekte Formel ist det = ad - bc = 2·4 - 3·1 = 8 - 3 = 5. Das Minus-Zeichen wird häufig vergessen.',
    errorHints: ['Merke: Hauptdiagonale minus Nebendiagonale.', 'ad - bc, nicht ad + bc.'],
    transferQuestion: 'Berechne det([[1,2,0],[0,3,1],[0,0,2]]) einer oberen Dreiecksmatrix.',
    transferAnswer: 6,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'Bei einer Dreiecksmatrix ist det = Produkt der Diagonalelemente = 1·3·2 = 6.',
    transferHints: ['Dreiecksmatrix: det = Produkt der Hauptdiagonale.', '1·3·2 = 6.'],
  },
  'la-1-4': {
    explanation: String.raw`**Vertiefung Inverse Matrix:** Die Inverse $A^{-1}$ existiert genau dann, wenn $\det(A) \neq 0$. Es gilt $A \cdot A^{-1} = A^{-1} \cdot A = I$. Für eine $2\times2$-Matrix: $A^{-1} = \frac{1}{\det A}\begin{pmatrix} d & -b \\ -c & a \end{pmatrix}$. Bei größeren Matrizen nutzt man den Gauss-Jordan-Algorithmus auf der erweiterten Matrix $[A | I]$.`,
    conceptQuestion: 'Wann existiert die Inverse einer quadratischen Matrix A?',
    conceptOptions: [
      'Genau dann, wenn det(A) ≠ 0',
      'Immer, wenn A quadratisch ist',
      'Genau dann, wenn A symmetrisch ist',
      'Genau dann, wenn alle Einträge positiv sind',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Eine Matrix heißt regulär (invertierbar), wenn ihre Determinante ungleich null ist. Ist det(A) = 0, ist A singulär und hat keine Inverse.',
    conceptHints: ['det(A) = 0 → singulär → nicht invertierbar.', 'Invertierbar ↔ vollen Rang ↔ det ≠ 0.'],
    calcQuestion: 'A = [[2,1],[1,1]]. Berechne det(A).',
    calcAnswer: 1,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'det(A) = 2·1 - 1·1 = 2 - 1 = 1. Da det ≠ 0, existiert A^{-1}.',
    calcHints: ['det([[a,b],[c,d]]) = ad - bc.', '2·1 - 1·1 = 1.'],
    trueFalseStatement: 'Wenn A^{-1} existiert, dann gilt A · A^{-1} = I (Einheitsmatrix).',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Die Definition der Inversen lautet A·A^{-1} = A^{-1}·A = I. Die Einheitsmatrix ist das neutrale Element der Matrizenmultiplikation.',
    trueFalseHints: ['I ist das neutrale Element: A·I = A.', 'Die Inverse kehrt die Wirkung von A um.'],
    matchingQuestion: 'Ordne die Begriffe zur Invertierbarkeit ihren Bedeutungen zu.',
    matchingPairs: [
      { left: 'Reguläre Matrix', right: 'det ≠ 0, Inverse existiert' },
      { left: 'Singuläre Matrix', right: 'det = 0, nicht invertierbar' },
      { left: 'Einheitsmatrix I', right: 'A·A^{-1} = I' },
    ],
    matchingExplanation: 'Die Begriffe regulär und singulär sind zentral für die Invertierbarkeit.',
    matchingHints: ['Regulär = invertierbar = vollen Rang.', 'Singulär = nicht invertierbar = det = 0.'],
    sortingQuestion: 'Ordne die Schritte zur Berechnung von A^{-1} mit Gauss-Jordan.',
    sortingItems: ['Erweiterte Matrix [A | I] aufstellen', 'Gauss-Elimination auf linker Seite', 'Rückwärtseinsetzen bis Einheitsmatrix links steht', 'Rechte Seite ablesen: das ist A^{-1}'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Gauss-Jordan transformiert [A|I] zu [I|A^{-1}]. Die Zeilenoperationen, die A zu I machen, machen I zu A^{-1}.',
    sortingHints: ['Ziel: linke Seite wird zur Einheitsmatrix.', 'Dieselben Operationen auf der rechten Seite ergeben A^{-1}.'],
    errorQuestion: 'Warum ist die Aussage falsch: "Jede quadratische Matrix ist invertierbar"?',
    errorOptions: [
      'Singuläre Matrizen (det = 0) haben keine Inverse',
      'Nur 2×2-Matrizen sind invertierbar',
      'Invertierbarkeit erfordert symmetrische Matrizen',
      'Invertierbarkeit erfordert ganzzahlige Einträge',
    ],
    errorCorrect: 0,
    errorExplanation: 'Quadratisch ist notwendig, aber nicht hinreichend für Invertierbarkeit. Beispiel: [[1,2],[2,4]] hat det = 0 und ist nicht invertierbar, obwohl quadratisch.',
    errorHints: ['Gegenbeispiel: [[1,2],[2,4]] ist quadratisch, aber det = 0.', 'det = 0 → singulär → keine Inverse.'],
    transferQuestion: 'A = [[2,1],[1,1]]. Berechne das Element (1,1) von A^{-1} mit der 2×2-Formel: A^{-1} = (1/det)·[[d,-b],[-c,a]].',
    transferAnswer: 1,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'det(A) = 1. A^{-1} = (1/1)·[[1,-1],[-1,2]]. Element (1,1) = 1.',
    transferHints: ['d ist das Element (2,2) von A, also d = 1.', 'A^{-1}_{11} = d/det = 1/1 = 1.'],
  },
  'la-1-5': {
    explanation: String.raw`**Vertiefung Rang einer Matrix:** Der Rang $\text{rg}(A)$ ist die Anzahl der linear unabhängigen Zeilen (= Spalten). Man bestimmt ihn durch Gauss-Elimination: der Rang ist die Anzahl der Nicht-Null-Zeilen in der Zeilenstufenform. Für eine $m \times n$-Matrix gilt $\text{rg}(A) \leq \min(m,n)$. Ein LGS $A\vec{x}=\vec{b}$ ist lösbar genau dann, wenn $\text{rg}(A) = \text{rg}([A|\vec{b}])$.`,
    conceptQuestion: 'Wie wird der Rang einer Matrix bestimmt?',
    conceptOptions: [
      'Anzahl der Nicht-Null-Zeilen nach Gauss-Elimination',
      'Anzahl aller Zeilen der Matrix',
      'Wert der Determinante',
      'Anzahl der Spalten minus Zeilen',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Durch Gauss-Elimination bringt man die Matrix in Zeilenstufenform. Die Anzahl der Zeilen mit mindestens einem Nicht-Null-Eintrag ist der Rang.',
    conceptHints: ['Zeilenstufenform hat Nullzeilen am Ende.', 'Rang = Anzahl Pivot-Elemente.'],
    calcQuestion: 'Welchen maximalen Rang kann eine 3×4-Matrix haben?',
    calcAnswer: 3,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'Der Rang ist maximal min(m,n) = min(3,4) = 3. Man sagt, die Matrix hat vollen Zeilenrang.',
    calcHints: ['rg(A) ≤ min(Zeilen, Spalten).', 'min(3,4) = 3.'],
    trueFalseStatement: 'Eine 4×4-Matrix mit det(A) ≠ 0 hat Rang 4.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. det(A) ≠ 0 ist äquivalent dazu, dass alle Zeilen linear unabhängig sind, also Rang = n = 4.',
    trueFalseHints: ['det ≠ 0 ↔ vollen Rang ↔ invertierbar.', 'n×n-Matrix mit vollem Rang: rg = n.'],
    matchingQuestion: 'Ordne die Rang-Aussagen ihren Bedeutungen zu.',
    matchingPairs: [
      { left: 'rg(A) = n für n×n-Matrix', right: 'A ist invertierbar' },
      { left: 'rg(A) < n für n×n-Matrix', right: 'A ist singulär' },
      { left: 'rg([A|b]) > rg(A)', right: 'LGS ist unlösbar' },
    ],
    matchingExplanation: 'Der Rang entscheidet über Invertierbarkeit und Lösbarkeit von LGS.',
    matchingHints: ['Rang = vollen Rang → invertierbar.', 'Wenn b die rechte Seite die Konsistenz bricht, ist das LGS unlösbar.'],
    sortingQuestion: 'Ordne die Schritte zur Rangbestimmung einer Matrix.',
    sortingItems: ['Matrix aufschreiben', 'Gauss-Elimination durchführen', 'Zeilenstufenform ablesen', 'Nicht-Null-Zeilen zählen: das ist der Rang'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Gauss → Zeilenstufenform → Pivot-Zeilen zählen = Rang.',
    sortingHints: ['Gauss-Elimination führt zur Zeilenstufenform.', 'Nullzeilen tragen nicht zum Rang bei.'],
    errorQuestion: 'Welcher Fehler steckt in: "Eine 3×3-Matrix hat immer Rang 3"?',
    errorOptions: [
      'Wenn Zeilen linear abhängig sind, ist der Rang kleiner als 3',
      'Rang wird aus der Anzahl der Spalten berechnet',
      'Der Rang kann nicht größer als 0 sein',
      'Rang ist nur für quadratische Matrizen definiert',
    ],
    errorCorrect: 0,
    errorExplanation: 'Beispiel: [[1,2,3],[2,4,6],[1,2,3]] — alle drei Zeilen sind linear abhängig, Rang = 1. Rang ist nie automatisch gleich der Matrixgröße.',
    errorHints: ['Linear abhängige Zeilen reduzieren den Rang.', 'Rang ≤ min(m,n), kann aber kleiner sein.'],
    transferQuestion: 'Eine Matrix hat nach Gauss-Elimination 2 Nicht-Null-Zeilen und 1 Nullzeile. Wie groß ist der Rang?',
    transferAnswer: 2,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'Der Rang ist die Anzahl der Nicht-Null-Zeilen in der Zeilenstufenform: rg(A) = 2.',
    transferHints: ['Nullzeilen zählen nicht zum Rang.', 'Rang = Anzahl der Pivotzeilen.'],
  },
  'la-2-1': {
    explanation: String.raw`**Vertiefung Lineare Gleichungssysteme:** Ein LGS $A\vec{x} = \vec{b}$ hat genau eine Lösung, wenn $\text{rg}(A) = \text{rg}([A|\vec{b}]) = n$ (Anzahl Variablen). Es hat unendlich viele Lösungen bei $\text{rg}(A) = \text{rg}([A|\vec{b}]) < n$, und keine Lösung wenn $\text{rg}(A) < \text{rg}([A|\vec{b}])$. Die Gauss-Elimination bringt die erweiterte Matrix $[A|\vec{b}]$ in Zeilenstufenform.`,
    conceptQuestion: 'Wann hat ein LGS A·x = b keine Lösung?',
    conceptOptions: [
      'Wenn rg(A) < rg([A|b])',
      'Wenn A quadratisch ist',
      'Wenn det(A) ≠ 0',
      'Wenn die Matrix mehr Spalten als Zeilen hat',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Keine Lösung bedeutet: die rechte Seite b ist linear unabhängig von den Spalten von A. Das erkennt man am Rangkriterium: rg(A) < rg([A|b]).',
    conceptHints: ['Rangkriterium: rg(A) = rg([A|b]) → lösbar.', 'rg(A) < rg([A|b]) → unlösbar.'],
    calcQuestion: 'LGS: x + 2y = 5, 3x + 6y = 15. Wie viele freie Parameter hat die Lösungsmenge?',
    calcAnswer: 1,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'Die zweite Gleichung ist das 3-fache der ersten (linear abhängig). rg(A) = 1 = rg([A|b]) < n = 2. Freie Parameter = n - rg(A) = 2 - 1 = 1.',
    calcHints: ['Zeile 2 = 3·Zeile 1: linear abhängig.', 'Nach Elimination: eine Pivotzeile, eine freie Variable.'],
    trueFalseStatement: 'Ein LGS mit mehr Gleichungen als Unbekannten ist immer unlösbar.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Überbestimmte Systeme können lösbar sein, wenn die zusätzlichen Gleichungen mit den anderen konsistent sind (redundant). Entscheidend ist das Rangkriterium.',
    trueFalseHints: ['Mehr Gleichungen als Unbekannte heißt überbestimmt, nicht automatisch unlösbar.', 'Konsistenz entscheidet: rg(A) = rg([A|b])?'],
    matchingQuestion: 'Ordne die Lösungsfälle ihren Bedingungen zu.',
    matchingPairs: [
      { left: 'Eindeutige Lösung', right: 'rg(A) = rg([A|b]) = n' },
      { left: 'Unendlich viele Lösungen', right: 'rg(A) = rg([A|b]) < n' },
      { left: 'Keine Lösung', right: 'rg(A) < rg([A|b])' },
    ],
    matchingExplanation: 'Das Rangkriterium (Satz von Rouché-Capelli) entscheidet vollständig über die Lösungsmenge.',
    matchingHints: ['n = Anzahl der Unbekannten.', 'rg([A|b]) kann maximal rg(A)+1 größer sein.'],
    sortingQuestion: 'Ordne die Schritte der Gauss-Elimination für ein 3×3-LGS.',
    sortingItems: ['Erweiterte Matrix [A|b] aufstellen', 'Pivot in Spalte 1 wählen', 'Einträge unter dem Pivot eliminieren', 'Weiter zur nächsten Spalte', 'Rückwärtseinsetzen für Lösung'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Gauss läuft spaltenweise von links nach rechts. Nach Vorwärtselimination folgt Rückwärtseinsetzen.',
    sortingHints: ['Pivot = erstes Nicht-Null-Element in der Spalte.', 'Elimination: Vielfaches der Pivotzeile subtrahieren.'],
    errorQuestion: 'Welcher Fehler steckt in: "Ein LGS mit det(A)=0 hat immer keine Lösung"?',
    errorOptions: [
      'det(A)=0 bedeutet entweder keine oder unendlich viele Lösungen — je nach Rangkriterium für [A|b]',
      'det(A)=0 bedeutet immer eindeutige Lösung',
      'Die Determinante entscheidet nicht über die Lösbarkeit',
      'Nur bei quadratischen Matrizen kann det=0 vorkommen',
    ],
    errorCorrect: 0,
    errorExplanation: 'Ist det(A) = 0, so ist das System entweder unlösbar oder hat unendlich viele Lösungen. Welcher Fall vorliegt, bestimmt das Rangkriterium mit der erweiterten Matrix [A|b].',
    errorHints: ['det=0 schließt eindeutige Lösung aus.', 'Rangkriterium für b entscheidet ob keine oder viele Lösungen.'],
    transferQuestion: 'Ein 2×2-LGS hat nach Elimination die Zeilenstufenform [[1,3,|4],[0,0,|0]]. Wie viele freie Variablen gibt es?',
    transferAnswer: 1,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'rg(A) = 1, n = 2 Variablen. Anzahl freier Variablen = n - rg(A) = 2 - 1 = 1.',
    transferHints: ['Freie Variablen = n - Rang.', 'Eine Nullzeile bedeutet eine freie Variable.'],
  },
  'la-2-2': {
    explanation: String.raw`**Vertiefung Gauss-Jordan:** Der Gauss-Jordan-Algorithmus geht über die einfache Gauss-Elimination hinaus: Er eliminiert nicht nur unterhalb, sondern auch oberhalb der Pivotelemente und normiert die Pivots auf 1. Das Ergebnis ist die reduzierte Zeilenstufenform (RREF). Damit können Lösungen direkt abgelesen werden — kein Rückwärtseinsetzen nötig. Auch $A^{-1}$ berechnet man so: $[A|I] \to [I|A^{-1}]$.`,
    conceptQuestion: 'Was unterscheidet Gauss-Jordan von der einfachen Gauss-Elimination?',
    conceptOptions: [
      'Gauss-Jordan eliminiert auch oberhalb der Pivots und normiert Pivots auf 1',
      'Gauss-Jordan arbeitet nur mit 2×2-Matrizen',
      'Gauss-Jordan erlaubt Spaltenoperationen',
      'Gauss-Jordan benötigt immer eine quadratische Matrix',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Gauss erzeugt eine obere Dreiecksform. Gauss-Jordan erzeugt zusätzlich durch Rückelimination die vollreduzierte Form (RREF), bei der die Lösung direkt ablesbar ist.',
    conceptHints: ['Gauss: nur unterhalb der Diagonale eliminieren.', 'Gauss-Jordan: auch oberhalb + Pivot = 1.'],
    calcQuestion: 'RREF-Matrix: [[1,0,|3],[0,1,|2]]. Was ist x₁?',
    calcAnswer: 3,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'In der RREF steht x₁ = 3 direkt in der ersten Zeile: [1,0|3] bedeutet 1·x₁ + 0·x₂ = 3.',
    calcHints: ['RREF: Lösung direkt ablesen.', 'Erste Zeile: x₁ = 3.'],
    trueFalseStatement: 'Beim Gauss-Jordan-Verfahren zur Berechnung von A^{-1} wird die erweiterte Matrix [A|I] in die Form [I|A^{-1}] überführt.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Dieselben Zeilenoperationen, die A in die Einheitsmatrix überführen, transformieren I in A^{-1}.',
    trueFalseHints: ['[A|I] → [I|A^{-1}] ist das Gauss-Jordan-Inversionsverfahren.', 'Nur möglich, wenn det(A) ≠ 0.'],
    matchingQuestion: 'Ordne die Begriffe der reduzierten Zeilenstufenform zu.',
    matchingPairs: [
      { left: 'Pivot', right: 'führende 1 in jeder Nicht-Null-Zeile' },
      { left: 'RREF', right: 'vollreduzierte Zeilenstufenform' },
      { left: 'Rückelimination', right: 'Einträge oberhalb des Pivots eliminieren' },
    ],
    matchingExplanation: 'RREF (Reduced Row Echelon Form) ist das Ziel des Gauss-Jordan-Verfahrens.',
    matchingHints: ['Jede Pivotspalte hat nur eine 1 und sonst Nullen.', 'Rückelimination macht aus oberer Dreiecksform die RREF.'],
    sortingQuestion: 'Ordne die Schritte des Gauss-Jordan-Verfahrens.',
    sortingItems: ['[A|b] aufstellen', 'Vorwärtselimination (Gauss)', 'Pivot auf 1 normieren', 'Rückelimination oberhalb der Pivots', 'Lösung direkt ablesen'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Gauss-Jordan = Gauss + Normierung + Rückelimination → RREF → Lösung direkt ablesbar.',
    sortingHints: ['Normierung: Zeile durch Pivot dividieren.', 'Rückelimination: Einträge über dem Pivot zu null machen.'],
    errorQuestion: 'Welche Operation ist beim Gauss-Jordan-Verfahren NICHT erlaubt?',
    errorOptions: [
      'Zwei Spalten vertauschen',
      'Eine Zeile durch ihr Pivotelement dividieren',
      'Ein Vielfaches einer Zeile zu einer anderen addieren',
      'Zwei Zeilen miteinander tauschen',
    ],
    errorCorrect: 0,
    errorExplanation: 'Spaltenoperationen würden die Zuordnung der Variablen ändern und sind beim Gauss-Jordan-Verfahren (wie bei der einfachen Gauss-Elimination) nicht erlaubt.',
    errorHints: ['Nur Zeilenoperationen sind erlaubt.', 'Spalten vertauschen würde x₁ und x₂ vertauschen — das verfälscht die Lösung.'],
    transferQuestion: 'Nach Gauss-Jordan ergibt sich RREF: [[1,0,0,|2],[0,1,0,|5],[0,0,1,|-1]]. Was ist x₃?',
    transferAnswer: -1,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'Die dritte Zeile lautet 0·x₁ + 0·x₂ + 1·x₃ = -1, also x₃ = -1.',
    transferHints: ['RREF: Lösung direkt ablesen.', 'Dritte Zeile: x₃ = -1.'],
  },
  'la-2-3': {
    explanation: String.raw`**Vertiefung Eigenwerte und Eigenvektoren:** $\vec{v}$ ist Eigenvektor von $A$ zum Eigenwert $\lambda$, wenn $A\vec{v} = \lambda\vec{v}$ mit $\vec{v} \neq \vec{0}$. Die Eigenwerte erhält man aus dem charakteristischen Polynom $\det(A - \lambda I) = 0$. Für jeden Eigenwert $\lambda$ bestimmt man dann den Eigenraum: die Lösungen von $(A - \lambda I)\vec{v} = \vec{0}$.`,
    conceptQuestion: 'Was beschreibt die Gleichung A·v = λ·v?',
    conceptOptions: [
      'Die Matrix A streckt den Vektor v nur — ohne Richtungsänderung',
      'A und v haben dieselbe Determinante',
      'λ ist der Betrag von v',
      'v ist eine Zeile von A',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Ein Eigenvektor v wird durch A nur gestreckt (oder gestaucht, gespiegelt), nicht in seiner Richtung geändert. λ ist der Streckungsfaktor.',
    conceptHints: ['Eigenvektor behält seine Richtung unter Multiplikation mit A.', 'λ kann negativ sein (Richtungsumkehr) oder null (v wird auf 0 abgebildet).'],
    calcQuestion: 'A = [[3,0],[0,2]]. Berechne einen Eigenwert von A durch Ablesen der Diagonale.',
    calcAnswer: 3,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'Bei Diagonalmatrizen sind die Diagonaleinträge direkt die Eigenwerte: λ₁ = 3, λ₂ = 2.',
    calcHints: ['Diagonalmatrix: Eigenwerte stehen auf der Diagonale.', 'Beide Werte 3 und 2 sind korrekt; 3 wird hier als Antwort erwartet.'],
    trueFalseStatement: 'Das charakteristische Polynom det(A − λI) = 0 liefert die Eigenwerte von A.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Die Eigenwerte sind genau die Werte λ, für die (A − λI) singulär ist, d.h. det(A − λI) = 0.',
    trueFalseHints: ['Singuläre Matrix: det = 0.', 'Die Gleichung det(A−λI)=0 heißt charakteristische Gleichung.'],
    matchingQuestion: 'Ordne die Begriffe der Eigenwerttheorie ihren Definitionen zu.',
    matchingPairs: [
      { left: 'Eigenwert λ', right: 'Lösung von det(A−λI) = 0' },
      { left: 'Eigenvektor v', right: 'Lösung von (A−λI)v = 0, v ≠ 0' },
      { left: 'Eigenraum', right: 'Lösungsraum von (A−λI)v = 0' },
    ],
    matchingExplanation: 'Eigenwert, Eigenvektor und Eigenraum sind eng miteinander verknüpft.',
    matchingHints: ['Erst Eigenwert berechnen, dann Eigenvektor bestimmen.', 'Eigenraum kann mehrdimensional sein.'],
    sortingQuestion: 'Ordne den Berechnungsweg für Eigenwerte und Eigenvektoren einer 2×2-Matrix.',
    sortingItems: ['Charakteristisches Polynom det(A−λI) aufstellen', 'Polynom gleich null setzen', 'Eigenwerte λ₁, λ₂ lösen', 'Für jeden Eigenwert (A−λI)v=0 lösen', 'Eigenvektoren angeben'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Erst Eigenwerte, dann Eigenvektoren — in dieser Reihenfolge.',
    sortingHints: ['Eigenvektoren hängen von den Eigenwerten ab.', 'Für jeden Eigenwert ein eigenes LGS lösen.'],
    errorQuestion: 'Welcher Fehler steckt in: "Der Nullvektor v=0 ist ein Eigenvektor"?',
    errorOptions: [
      'Eigenvektoren müssen per Definition von null verschieden sein',
      'Eigenvektoren müssen Länge 1 haben',
      'Der Nullvektor hat keinen Eigenwert',
      'Nur quadratische Matrizen haben Eigenvektoren',
    ],
    errorCorrect: 0,
    errorExplanation: 'Die Definition fordert v ≠ 0. A·0 = λ·0 = 0 gilt für jede Matrix und jeden λ — das wäre trivial und bedeutungslos.',
    errorHints: ['v = 0 erfüllt A·v = λ·v immer — daher ausgeschlossen.', 'Eigenvektoren sind nichttriviale Lösungen.'],
    transferQuestion: 'A = [[2,0],[0,5]]. Welcher Eigenwert gehört zum Eigenvektor [0,1]^T? (Gib den Eigenwert an)',
    transferAnswer: 5,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'A·[0,1]^T = [2·0+0·1, 0·0+5·1]^T = [0,5]^T = 5·[0,1]^T. Also λ = 5.',
    transferHints: ['Multipliziere A mit [0,1]^T.', 'Der Streckungsfaktor ist der Eigenwert.'],
  },
  'la-2-4': {
    explanation: String.raw`**Vertiefung Anwendungen im Maschinenbau:** LGS treten in vielen Maschinenbau-Bereichen auf: Knotenspannungsanalyse in Netzwerken (Kirchhoffsche Gesetze), Kräftegleichgewicht in Fachwerken, FEM-Steifigkeitsmatrizen und Netzwerksimulationen. Bei $n$ unbekannten Kräften oder Spannungen stellt man $n$ Gleichgewichtsbedingungen auf und löst $A\vec{F} = \vec{b}$ mit Gauss-Elimination.`,
    conceptQuestion: 'In einem Fachwerk mit 3 unbekannten Stabkräften werden 3 Gleichgewichtsbedingungen aufgestellt. Welches mathematische Problem entsteht?',
    conceptOptions: [
      'Ein 3×3-LGS der Form A·F = b',
      'Eine skalare Gleichung',
      'Ein Eigenwertproblem',
      'Ein Optimierungsproblem',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'n Unbekannte + n Gleichgewichtsbedingungen = n×n-LGS. Die Koeffizientenmatrix A enthält die Richtungskoeffizienten der Stabkräfte, b den Lastvektor.',
    conceptHints: ['Pro Knoten: 2 Gleichgewichtsbedingungen (x und y).', 'Die Stabkräfte sind die Unbekannten.'],
    calcQuestion: 'Ein System hat die Lösung x₁ = 3 kN, x₂ = 4 kN. Berechne die Resultierende F = √(x₁² + x₂²) in kN.',
    calcAnswer: 5,
    calcTolerance: 0.01,
    calcUnit: 'kN',
    calcExplanation: 'F = √(3² + 4²) = √(9 + 16) = √25 = 5 kN. Pythagoras im Kräftedreieck.',
    calcHints: ['Pythagoras: F = √(Fx² + Fy²).', '√(9+16) = √25 = 5.'],
    trueFalseStatement: 'In der FEM werden Steifigkeitsmatrizen aufgestellt, die zu einem LGS K·u = f führen, wobei u die Knotenverschiebungen sind.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Die Finite-Elemente-Methode führt auf das globale Gleichungssystem K·u = f, wobei K die Steifigkeitsmatrix, u der Verschiebungsvektor und f der Kraftvektor ist.',
    trueFalseHints: ['FEM diskretisiert partielle Differentialgleichungen zu LGS.', 'K ist symmetrisch und positiv definit.'],
    matchingQuestion: 'Ordne die Anwendungen linearer Gleichungssysteme im Maschinenbau zu.',
    matchingPairs: [
      { left: 'Fachwerk', right: 'Stabkräfte aus Gleichgewichtsbedingungen' },
      { left: 'Elektrisches Netzwerk', right: 'Knotenspannungen via Kirchhoff' },
      { left: 'FEM', right: 'Steifigkeitsmatrix K·u = f' },
    ],
    matchingExplanation: 'LGS sind das universelle Werkzeug für lineare Gleichgewichtsprobleme in der Ingenieurpraxis.',
    matchingHints: ['Kirchhoff: Summe der Ströme = 0 an jedem Knoten.', 'Fachwerk: Σ Fx = 0, Σ Fy = 0 an jedem Knoten.'],
    sortingQuestion: 'Ordne die Schritte zur LGS-Lösung eines Fachwerkproblems.',
    sortingItems: ['Fachwerk skizzieren und Stabkräfte benennen', 'Gleichgewichtsbedingungen an Knoten aufstellen', 'LGS in Matrixform A·F = b schreiben', 'Gauss-Elimination durchführen', 'Stabkräfte F interpretieren (Zug/Druck)'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Systematisches Vorgehen: Modell → Gleichungen → Matrixform → Lösung → Interpretation.',
    sortingHints: ['Zuerst das mechanische Modell, dann die Mathematik.', 'Positive Stabkraft = Zug, negative = Druck.'],
    errorQuestion: 'In einem Fachwerk-LGS ergibt Gauss det(A) = 0. Was bedeutet das physikalisch?',
    errorOptions: [
      'Das Fachwerk ist statisch unbestimmt oder instabil — zu wenige oder abhängige Gleichgewichtsbedingungen',
      'Die Stabkräfte sind alle null',
      'Das Fachwerk hat keine Last',
      'Es wurden zu viele Knoten gewählt',
    ],
    errorCorrect: 0,
    errorExplanation: 'det(A) = 0 heißt: die Gleichgewichtsbedingungen sind linear abhängig oder das Fachwerk ist kinematisch (instabil). In beiden Fällen ist kein eindeutiges Kräftegleichgewicht berechenbar.',
    errorHints: ['det = 0 → singuläres System → keine eindeutige Lösung.', 'Statisch überbestimmt: mehr Unbekannte als Gleichungen.'],
    transferQuestion: 'Ein Knoten im Fachwerk hat Gleichgewicht: F₁ + F₂ = 10 kN und F₁ - F₂ = 2 kN. Berechne F₁ in kN.',
    transferAnswer: 6,
    transferTolerance: 0.01,
    transferUnit: 'kN',
    transferExplanation: 'Addition beider Gleichungen: 2·F₁ = 12 kN → F₁ = 6 kN.',
    transferHints: ['Addiere beide Gleichungen.', '(F₁+F₂) + (F₁-F₂) = 10+2 → 2F₁ = 12.'],
  },
}

export const lineareAlgebraSupplements = Object.fromEntries(
  Object.entries(profiles).map(([lessonId, profile]) => [
    lessonId,
    {
      explanation: profile.explanation,
      exercises: bank(profile),
    },
  ])
)
