function mc(question, options, correctIndex, explanation, hints = [], wrongAnswerExplanations = undefined) {
  return {
    type: 'multiple-choice',
    question,
    options,
    correctIndex,
    explanation,
    hints,
    ...(wrongAnswerExplanations ? { wrongAnswerExplanations } : {}),
  }
}

function ni(question, correctValue, tolerance, unit, explanation, hints = []) {
  return { type: 'number-input', question, correctValue, tolerance, unit, explanation, hints }
}

function tf(statement, correct, explanation, hints = []) {
  return { type: 'true-false', statement, correct, explanation, hints }
}

function matching(question, pairs, explanation, hints = []) {
  return { type: 'matching', question, pairs, explanation, hints }
}

function sorting(question, items, correctOrder, explanation, hints = []) {
  return { type: 'sorting', question, items, correctOrder, explanation, hints }
}

function withExamPrefix(exercise, exam) {
  if (!exam) return exercise
  if (exercise.question && !exercise.question.includes('[PRÜFUNG]')) {
    return { ...exercise, question: `[PRÜFUNG] ${exercise.question}` }
  }
  if (exercise.statement && !exercise.statement.includes('[PRÜFUNG]')) {
    return { ...exercise, statement: `[PRÜFUNG] ${exercise.statement}` }
  }
  return exercise
}

function bank(profile) {
  const exercises = [
    mc(profile.conceptQuestion, profile.conceptOptions, profile.conceptCorrect, profile.conceptExplanation, profile.conceptHints, profile.conceptWrongAnswers),
    ni(profile.calcQuestion, profile.calcAnswer, profile.calcTolerance, profile.calcUnit, profile.calcExplanation, profile.calcHints),
    tf(profile.trueFalseStatement, profile.trueFalseCorrect, profile.trueFalseExplanation, profile.trueFalseHints),
    matching(profile.matchingQuestion, profile.matchingPairs, profile.matchingExplanation, profile.matchingHints),
    sorting(profile.sortingQuestion, profile.sortingItems, profile.sortingOrder, profile.sortingExplanation, profile.sortingHints),
    mc(profile.errorQuestion, profile.errorOptions, profile.errorCorrect, profile.errorExplanation, profile.errorHints, profile.errorWrongAnswers),
    ni(profile.transferQuestion, profile.transferAnswer, profile.transferTolerance, profile.transferUnit, profile.transferExplanation, profile.transferHints),
  ]
  return exercises.map((exercise) => withExamPrefix(exercise, profile.exam))
}

const profiles = {
  'py-1-1': {
    explanation: String.raw`**Vertiefung Variablen & Datentypen:** Python erkennt den Typ automatisch — du schreibst nur \`x = 42\` ohne Typ-Schlüsselwort. Unterscheide \`int\` (ganze Zahl), \`float\` (Dezimalzahl), \`str\` (Text) und \`list\` (Folge von Werten). In Matlab ist jede Zahl standardmäßig \`double\`; Strings werden mit \`"..."\` oder \`'...'\` geschrieben. Typumwandlungen in Python: \`int()\`, \`float()\`, \`str()\`.`,
    conceptQuestion: 'Welchen Typ hat `x` nach `x = 7` in Python?',
    conceptOptions: ['float', 'int', 'str', 'double'],
    conceptCorrect: 1,
    conceptExplanation: 'Ganzzahlen ohne Dezimalpunkt werden in Python als `int` gespeichert.',
    conceptHints: ['Achte darauf, ob ein Dezimalpunkt vorhanden ist.', 'In Python gibt es kein `double` — das ist ein Matlab/C-Begriff.'],
    calcQuestion: 'Was gibt `len([1, 2, 3, 4, 5])` zurück?',
    calcAnswer: 5,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: '`len()` zählt die Elemente einer Liste. Die Liste hat 5 Einträge.',
    calcHints: ['`len()` gibt die Anzahl der Elemente zurück.', 'Zähle die Elemente in der eckigen Klammer.'],
    trueFalseStatement: 'In Matlab ist der Standarddatentyp für Zahlen `double`, während Python zwischen `int` und `float` unterscheidet.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Matlab speichert alle Zahlen standardmäßig als `double`-Gleitkommazahlen. Python unterscheidet dagegen explizit zwischen ganzzahligem `int` und dezimalem `float`.',
    trueFalseHints: ['Denke daran, was passiert, wenn du in Matlab `x = 3` schreibst.', 'In Python hat `3` und `3.0` einen anderen Typ.'],
    matchingQuestion: 'Ordne Python-Datentypen ihrem Matlab-Äquivalent zu.',
    matchingPairs: [
      { left: 'int (z.B. x = 5)', right: 'int32 / int64 in Matlab' },
      { left: 'float (z.B. x = 5.0)', right: 'double (Standard in Matlab)' },
      { left: 'str (z.B. s = "Hallo")', right: 'string / char in Matlab' },
    ],
    matchingExplanation: 'Python trennt Typen klar; Matlab nutzt standardmäßig `double` und `char`/`string` für Text.',
    matchingHints: ['Matlab-Standard für Zahlen ist `double`.', 'Python-`str` entspricht Matlab-`string` oder `char`.'],
    sortingQuestion: 'Bringe die Python-Zeilen in die richtige Reihenfolge, um den Typ einer Variable zu prüfen.',
    sortingItems: ['x = 42', 'print(type(x))', '# Ausgabe: <class \'int\'>', '# Typumwandlung: y = float(x)'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Erst Variable anlegen, dann Typ abfragen und ausgeben, dann bei Bedarf umwandeln.',
    sortingHints: ['Variable muss vor `type()` existieren.', 'Die Typumwandlung kommt nach der Ausgabe des ursprünglichen Typs.'],
    errorQuestion: 'Was ist falsch an `x = int("3.14")` in Python?',
    errorOptions: [
      '`int()` kann keinen String mit Dezimalpunkt direkt umwandeln',
      '`int()` existiert in Python nicht',
      'Strings können in Python gar nicht umgewandelt werden',
      'Es fehlt ein Semikolon am Zeilenende',
    ],
    errorCorrect: 0,
    errorExplanation: '`int()` erwartet einen String ohne Dezimalpunkt. Richtig wäre: `int(float("3.14"))` — erst zu `float`, dann zu `int`.',
    errorHints: ['`int("3")` funktioniert. `int("3.14")` nicht.', 'Zwei-Schritt-Umwandlung: String → float → int.'],
    transferQuestion: 'Was gibt `int(float("7.9"))` zurück?',
    transferAnswer: 7,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: '`float("7.9")` ergibt `7.9`, `int(7.9)` schneidet die Nachkommastellen ab → `7`.',
    transferHints: ['`int()` rundet nicht, es schneidet ab.', '`float("7.9")` ist der erste Schritt.'],
  },

  'py-1-2': {
    explanation: String.raw`**Vertiefung Operatoren & Ausdrücke:** In Python liefert \`/\` immer ein \`float\` (z.B. \`6 / 2 = 3.0\`). Ganzzahldivision: \`//\`. Rest: \`%\`. Potenz: \`**\`. In Matlab ist die Division \`/\` ebenfalls Gleitkomma, die Ganzzahldivision heißt \`floor(a/b)\`, Modulo \`mod(a,b)\` und Potenz \`^\`. Merke: Python-\`**\` ↔ Matlab-\`^\`; Python-\`%\` ↔ Matlab-\`mod()\`.`,
    conceptQuestion: 'Welcher Operator berechnet in Python den Rest einer Division?',
    conceptOptions: ['/', '//', '%', '**'],
    conceptCorrect: 2,
    conceptExplanation: '`%` ist der Modulo-Operator: `17 % 5 = 2`, weil 17 = 3×5 + 2.',
    conceptHints: ['`//` ist die Ganzzahldivision, `%` der Rest.', 'In Matlab heißt dieser Operator `mod(a,b)`.'],
    calcQuestion: 'Was ergibt `2 ** 10` in Python?',
    calcAnswer: 1024,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: '`**` ist der Potenz-Operator. 2¹⁰ = 1024.',
    calcHints: ['`**` entspricht der mathematischen Potenz.', '2¹⁰ = 2·2·2·2·2·2·2·2·2·2.'],
    trueFalseStatement: 'In Python ergibt `7 / 2` den Wert `3`, weil die Division ganzzahlig ist.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. `7 / 2 = 3.5` in Python 3 — der `/`-Operator liefert immer ein `float`. Für Ganzzahldivision braucht man `7 // 2 = 3`.',
    trueFalseHints: ['In Python 3 wurde das Verhalten von `/` geändert.', 'Für Ganzzahldivision gibt es `//`.'],
    matchingQuestion: 'Ordne Python-Operatoren ihren Matlab-Äquivalenten zu.',
    matchingPairs: [
      { left: 'Python: **', right: 'Matlab: ^' },
      { left: 'Python: %', right: 'Matlab: mod(a,b)' },
      { left: 'Python: //', right: 'Matlab: floor(a/b)' },
    ],
    matchingExplanation: 'Python hat eingebaute Operatoren für Ganzzahldivision und Modulo. Matlab nutzt dafür Funktionen.',
    matchingHints: ['Potenz ist in beiden Sprachen ein Operator, aber mit unterschiedlichem Symbol.', 'Matlab-`mod()` entspricht Python-`%`.'],
    sortingQuestion: 'Bringe die Auswertung von `3 + 2 ** 3 * 2` in die richtige Reihenfolge.',
    sortingItems: ['Potenz zuerst: 2 ** 3 = 8', 'Dann Multiplikation: 8 * 2 = 16', 'Dann Addition: 3 + 16 = 19', 'Ergebnis: 19'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Operatorreihenfolge: Potenz → Multiplikation → Addition. Ergebnis: 19.',
    sortingHints: ['Potenz hat die höchste Priorität.', 'Dann Punkt- vor Strichrechnung.'],
    errorQuestion: 'Was ist am folgenden Matlab-Code falsch, wenn man ihn 1:1 in Python übernimmt: `x = 2^8`?',
    errorOptions: [
      'In Python ist `^` der XOR-Operator, nicht Potenz',
      'In Python darf man keine Hochzahlen berechnen',
      '`2^8` ist in Python nicht erlaubt, weil 8 ungerade ist',
      'Es fehlt `import math` für die Potenz',
    ],
    errorCorrect: 0,
    errorExplanation: 'In Python ist `^` der bitweise XOR-Operator. `2^8 = 10` (bitweise). Für Potenz muss man `2**8` schreiben.',
    errorHints: ['In Python ist `**` die Potenz.', '`^` hat in Python eine andere Bedeutung als in Matlab.'],
    transferQuestion: 'Was ergibt `(100 % 7) + (100 // 7)` in Python?',
    transferAnswer: 16,
    calcTolerance: 0,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: '100 // 7 = 14 (ganzzahliger Quotient), 100 % 7 = 2 (Rest), 2 + 14 = 16.',
    transferHints: ['100 = 14×7 + 2.', 'Erst Rest und Quotient einzeln berechnen, dann addieren.'],
  },

  'py-1-3': {
    explanation: String.raw`**Vertiefung Listen & Arrays:** Eine Python-\`list\` ist flexibel (gemischte Typen, veränderlich), aber nicht für numerische Rechnungen optimiert. \`numpy.array\` ist für homogene Zahlen gedacht und unterstützt elementweise Operationen direkt. In Matlab gibt es nur einen Array-Typ (Matrix/Vektor als \`double\`-Array); der Index startet bei 1. In Python und NumPy startet der Index bei 0.`,
    conceptQuestion: 'Was ist der Hauptunterschied zwischen einer Python-`list` und einem `numpy.array`?',
    conceptOptions: [
      '`numpy.array` ist für homogene numerische Daten optimiert und unterstützt elementweise Mathematik',
      'Eine `list` kann keine Zahlen speichern',
      '`numpy.array` kann nur Integer speichern',
      'Eine `list` startet bei Index 1, `numpy.array` bei Index 0',
    ],
    conceptCorrect: 0,
    conceptExplanation: '`numpy.array` unterstützt elementweise Operationen wie `a * 2` oder `a + b` direkt. Bei einer `list` würde `a * 2` die Liste verdoppeln, nicht die Elemente.',
    conceptHints: ['`list` ist für allgemeine Sequenzen, `numpy.array` für Zahlenrechnungen.', 'Denke an Vektorrechnung: `a + b` funktioniert bei NumPy elementweise.'],
    calcQuestion: 'Was gibt `len([10, 20, 30, 40])` zurück?',
    calcAnswer: 4,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'Die Liste hat 4 Elemente, also gibt `len()` 4 zurück.',
    calcHints: ['`len()` zählt die Elemente.', 'Zähle: 10, 20, 30, 40 — das sind 4 Stück.'],
    trueFalseStatement: 'In Python startet der Listenindex bei 0, in Matlab startet der Vektorindex bei 1.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Python-Indizes beginnen bei 0: `a[0]` ist das erste Element. In Matlab ist `a(1)` das erste Element.',
    trueFalseHints: ['In Python: `a[0]` = erstes Element.', 'In Matlab: `a(1)` = erstes Element.'],
    matchingQuestion: 'Ordne Python-Konstrukte ihren Matlab-Äquivalenten zu.',
    matchingPairs: [
      { left: 'np.array([1, 2, 3])', right: '[1 2 3] (Zeilenvektor)' },
      { left: 'a[0]', right: 'a(1) — erstes Element' },
      { left: 'a[-1]', right: 'a(end) — letztes Element' },
    ],
    matchingExplanation: 'Negative Indizes in Python greifen von hinten auf die Liste zu. In Matlab nutzt man `end` für das letzte Element.',
    matchingHints: ['Python `a[-1]` = letztes Element.', 'Matlab nutzt runde Klammern für Indizes.'],
    sortingQuestion: 'Bringe den Code zur Erstellung und Verwendung eines NumPy-Arrays in die richtige Reihenfolge.',
    sortingItems: ['import numpy as np', 'a = np.array([1, 2, 3, 4])', 'b = a * 2', 'print(b)  # [2 4 6 8]'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Erst NumPy importieren, dann Array anlegen, dann elementweise Operation, dann ausgeben.',
    sortingHints: ['`import` kommt immer zuerst.', 'Array anlegen vor der Berechnung.'],
    errorQuestion: 'Was ist falsch, wenn man `a = [1, 2, 3]` als Python-`list` anlegt und dann `a * 2` als elementweise Verdoppelung interpretiert?',
    errorOptions: [
      '`list * 2` verdoppelt die Liste, nicht die Werte — Ergebnis ist `[1, 2, 3, 1, 2, 3]`',
      '`list * 2` ist ein Syntaxfehler',
      '`list * 2` ergibt immer 0',
      '`list * 2` potenziert alle Elemente',
    ],
    errorCorrect: 0,
    errorExplanation: '`[1, 2, 3] * 2 = [1, 2, 3, 1, 2, 3]` — die Liste wird wiederholt. Für elementweise Multiplikation braucht man `np.array([1, 2, 3]) * 2`.',
    errorHints: ['`list * n` in Python wiederholt die Liste n-mal.', 'Elementweise Operationen brauchen `numpy.array`.'],
    transferQuestion: 'Was ist `np.array([3, 6, 9])[1]`?',
    transferAnswer: 6,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'Index 1 ist das zweite Element (Python startet bei 0): 3 → Index 0, 6 → Index 1.',
    transferHints: ['Index 0 = erstes Element.', 'Index 1 = zweites Element.'],
  },

  'py-1-4': {
    explanation: String.raw`**Vertiefung Kontrollstrukturen:** Python nutzt **Einrückung** (4 Leerzeichen) statt \`end\` oder \`{}\` zur Blockstruktur. In Matlab enden Blöcke mit \`end\`. Schleifen: Python \`for x in range(n)\` ↔ Matlab \`for x = 1:n\`. Bedingte Ausführung: Python \`if / elif / else\` ↔ Matlab \`if / elseif / else / end\`.`,
    conceptQuestion: 'Was erzeugt `range(5)` in Python?',
    conceptOptions: [
      'Die Folge 0, 1, 2, 3, 4',
      'Die Folge 1, 2, 3, 4, 5',
      'Die Folge 0, 1, 2, 3, 4, 5',
      'Eine leere Sequenz',
    ],
    conceptCorrect: 0,
    conceptExplanation: '`range(5)` erzeugt die Zahlen von 0 bis 4 (5 Werte, ohne die 5 selbst). Der Startindex ist 0.',
    conceptHints: ['`range(n)` startet bei 0 und endet bei n-1.', 'Es werden genau n Werte erzeugt.'],
    calcQuestion: 'Wie oft wird der Schleifenkörper bei `for i in range(3):` ausgeführt?',
    calcAnswer: 3,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: '`range(3)` erzeugt 0, 1, 2 — drei Werte, also drei Durchläufe.',
    calcHints: ['`range(3)` hat genau 3 Elemente.', 'Zähle: i=0, i=1, i=2.'],
    trueFalseStatement: 'In Python werden Code-Blöcke (for, if, def) durch Einrückung definiert, nicht durch `end`-Schlüsselwörter.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Python nutzt konsistente Einrückung (üblicherweise 4 Leerzeichen) zur Blockstruktur. Matlab und viele andere Sprachen nutzen `end`.',
    trueFalseHints: ['In Matlab endet jedes `for`/`if`/`while` mit `end`.', 'In Python ist die Einrückung syntaktisch zwingend.'],
    matchingQuestion: 'Ordne Python-Kontrollstrukturen ihren Matlab-Äquivalenten zu.',
    matchingPairs: [
      { left: 'for x in range(n):', right: 'for x = 1:n ... end' },
      { left: 'elif', right: 'elseif' },
      { left: 'while x < 10:', right: 'while x < 10 ... end' },
    ],
    matchingExplanation: 'Die Konzepte sind ähnlich, die Syntax unterscheidet sich. Python nutzt Einrückung, Matlab nutzt `end`.',
    matchingHints: ['Python kennt kein `elseif`, sondern `elif`.', 'Matlab-`for` läuft über Wertebereiche mit `:`.'],
    sortingQuestion: 'Bringe die Python-Schleife zur Summe 1+2+3+4+5 in die richtige Reihenfolge.',
    sortingItems: ['summe = 0', 'for i in range(1, 6):', '    summe += i', 'print(summe)  # 15'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Erst Summenvariable initialisieren, dann Schleife, dann akkumulieren, dann ausgeben.',
    sortingHints: ['`summe` muss vor der Schleife auf 0 gesetzt werden.', '`range(1, 6)` erzeugt 1, 2, 3, 4, 5.'],
    errorQuestion: 'Was ist falsch an diesem Python-Code?\n```\nfor i in range(5)\n    print(i)\n```',
    errorOptions: [
      'Der Doppelpunkt nach `range(5)` fehlt',
      'Die Einrückung fehlt',
      '`range(5)` ist kein gültiger Ausdruck',
      '`print` muss vor der Schleife stehen',
    ],
    errorCorrect: 0,
    errorExplanation: 'In Python muss nach `for`-Zeile ein Doppelpunkt stehen: `for i in range(5):`. Das ist ein Syntaxfehler.',
    errorHints: ['Jeder Block-Einleiter (for, if, def, while) endet mit `:`.', 'Vergleiche mit `if x > 0:` — gleicher Aufbau.'],
    transferQuestion: 'Was gibt diese Schleife aus? `s = 0\nfor i in range(4): s += i\nprint(s)` — Welchen Wert hat `s`?',
    transferAnswer: 6,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: '`range(4)` erzeugt 0, 1, 2, 3. Summe: 0+1+2+3 = 6.',
    transferHints: ['`range(4)` = 0, 1, 2, 3.', '0+1+2+3 = 6.'],
  },

  'py-1-5': {
    explanation: String.raw`**Vertiefung Funktionen definieren:** In Python wird eine Funktion mit \`def name(parameter):\` eingeleitet, der Rückgabewert mit \`return\`. In Matlab: \`function y = name(x) ... end\`. Python-Funktionen können mehrere Werte mit einem Tupel zurückgeben: \`return a, b\`. Standardwerte für Parameter: \`def f(x, n=2)\`. Wichtig: Einrückung innerhalb der Funktion ist zwingend.`,
    conceptQuestion: 'Wie gibt eine Python-Funktion mehrere Werte gleichzeitig zurück?',
    conceptOptions: [
      'Mit `return a, b` — Python gibt ein Tupel zurück',
      'Mit `return a; return b`',
      'Python-Funktionen können nur einen Wert zurückgeben',
      'Mit `output(a, b)`',
    ],
    conceptCorrect: 0,
    conceptExplanation: '`return a, b` gibt ein Tupel `(a, b)` zurück. In Matlab: `function [a, b] = f(x)`.',
    conceptHints: ['Python packt mehrere Rückgabewerte automatisch in ein Tupel.', 'In Matlab schreibt man `[a, b] = f(x)`.'],
    calcQuestion: 'Wie viele Parameter hat `def berechne(kraft, flaeche, faktor=1.0):`?',
    calcAnswer: 3,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'Die Funktion hat drei Parameter: `kraft`, `flaeche` und `faktor` (mit Standardwert).',
    calcHints: ['Zähle alle Namen nach `def berechne(`.', 'Standardwerte ändern nichts an der Anzahl der Parameter.'],
    trueFalseStatement: 'In Python ist das Schlüsselwort `def` nötig, um eine Funktion zu definieren, während Matlab das Schlüsselwort `function` verwendet.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Python: `def meine_funktion(x):`. Matlab: `function y = meine_funktion(x)`. Beide leiten die Funktionsdefinition ein.',
    trueFalseHints: ['`def` steht für "define" in Python.', 'In Matlab kommt auch der Rückgabevariablenname in die Signatur.'],
    matchingQuestion: 'Ordne Python-Funktionssyntax ihrer Matlab-Entsprechung zu.',
    matchingPairs: [
      { left: 'def f(x):', right: 'function y = f(x)' },
      { left: 'return wert', right: 'y = wert (am Ende der Matlab-Funktion)' },
      { left: 'def f(x, n=2):', right: 'keine direkte Entsprechung — Matlab nutzt nargin' },
    ],
    matchingExplanation: 'Python hat elegantere Standardwerte (Default-Parameter). Matlab prüft mit `nargin`, wie viele Argumente übergeben wurden.',
    matchingHints: ['In Matlab wird die Rückgabevariable in der Signatur benannt.', '`return` in Python beendet die Funktion sofort.'],
    sortingQuestion: 'Bringe die Python-Funktion zur Berechnung von σ = F/A in die richtige Reihenfolge.',
    sortingItems: ['def spannung(kraft, flaeche):', '    sigma = kraft / flaeche', '    return sigma', 'ergebnis = spannung(1000, 0.5)'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Funktionskopf → Berechnung im Körper → return → Aufruf außerhalb.',
    sortingHints: ['`def` leitet die Funktion ein.', '`return` muss eingerückt sein (Teil der Funktion).'],
    errorQuestion: 'Was ist falsch an dieser Python-Funktion?\n```\ndef quadrat(x):\nreturn x ** 2\n```',
    errorOptions: [
      '`return` ist nicht eingerückt — es muss zum Funktionskörper gehören',
      '`**` ist kein gültiger Potenz-Operator',
      'Funktionen benötigen immer mindestens 2 Parameter',
      '`def` darf nicht verwendet werden',
    ],
    errorCorrect: 0,
    errorExplanation: '`return` muss eingerückt sein, um Teil der Funktion zu sein. Ohne Einrückung ist es ein SyntaxError.',
    errorHints: ['Alles, was zur Funktion gehört, muss eingerückt sein.', 'Einrückung mit 4 Leerzeichen ist Standard.'],
    transferQuestion: 'Was gibt `def f(x): return x * 3` aufgerufen als `f(7)` zurück?',
    transferAnswer: 21,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'f(7) = 7 * 3 = 21.',
    transferHints: ['Setze x=7 in den Funktionskörper ein.', '7 × 3 = 21.'],
  },

  'py-2-1': {
    explanation: String.raw`**Vertiefung NumPy Grundlagen:** \`numpy\` (alias \`np\`) ist die Grundlage für numerisches Rechnen in Python. Kernkonzept: \`np.array()\` erzeugt homogene Arrays. **Broadcasting** erlaubt Operationen zwischen Arrays unterschiedlicher Form, solange die Dimensionen kompatibel sind. Nützliche Funktionen: \`np.zeros(n)\`, \`np.ones(n)\`, \`np.linspace(start, stop, n)\`, \`np.arange(start, stop, step)\`.`,
    conceptQuestion: 'Was bedeutet Broadcasting in NumPy?',
    conceptOptions: [
      'Arrays unterschiedlicher Form können in Operationen kombiniert werden, wenn die Dimensionen kompatibel sind',
      'NumPy sendet Daten über das Netzwerk',
      'Broadcasting ist ein Fehler, wenn Arrays unterschiedliche Längen haben',
      'Alle Array-Elemente werden gleichzeitig gedruckt',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Broadcasting erlaubt z.B. `np.array([1,2,3]) + 10 = [11, 12, 13]` — der Skalar 10 wird auf alle Elemente angewendet.',
    conceptHints: ['Ein Skalar kann mit einem Array addiert werden.', 'NumPy passt die Formen automatisch an, wenn möglich.'],
    calcQuestion: 'Was gibt `np.zeros(4).size` zurück?',
    calcAnswer: 4,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: '`np.zeros(4)` erzeugt ein Array mit 4 Nullen. `.size` gibt die Anzahl der Elemente zurück: 4.',
    calcHints: ['`np.zeros(n)` erzeugt n Nullen.', '`.size` gibt die Gesamtzahl der Elemente an.'],
    trueFalseStatement: 'In NumPy führt `a * b` bei zwei Arrays eine elementweise Multiplikation durch, nicht eine Matrixmultiplikation.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. `*` ist elementweise in NumPy. Für Matrixmultiplikation braucht man `@` oder `np.dot(a, b)`.',
    trueFalseHints: ['`*` = elementweise, `@` = Matrixmultiplikation.', 'In Matlab ist `*` Matrixmultiplikation, `.*` elementweise.'],
    matchingQuestion: 'Ordne NumPy-Funktionen ihren Matlab-Äquivalenten zu.',
    matchingPairs: [
      { left: 'np.linspace(0, 1, 5)', right: 'linspace(0, 1, 5)' },
      { left: 'np.zeros(3)', right: 'zeros(1, 3)' },
      { left: 'a @ b', right: 'a * b (Matrixmultiplikation)' },
    ],
    matchingExplanation: 'NumPy orientiert sich stark an Matlab — viele Funktionsnamen sind identisch. Der Unterschied liegt im Operator für Matrixmultiplikation.',
    matchingHints: ['`linspace` gibt es in beiden Sprachen.', 'Matlab-`*` ist Matrixmultiplikation; Python-`*` ist elementweise.'],
    sortingQuestion: 'Bringe den Code zur Berechnung des Mittelwerts mit NumPy in die richtige Reihenfolge.',
    sortingItems: ['import numpy as np', 'daten = np.array([2.0, 4.0, 6.0, 8.0])', 'mittelwert = np.mean(daten)', 'print(mittelwert)  # 5.0'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Import → Array anlegen → Berechnung → Ausgabe.',
    sortingHints: ['`import` immer zuerst.', '`np.mean()` berechnet den arithmetischen Mittelwert.'],
    errorQuestion: 'Was ist falsch an `a = np.array([1, 2, 3]); b = np.array([1, 2]); c = a + b`?',
    errorOptions: [
      'Arrays unterschiedlicher Länge können nicht direkt addiert werden',
      '`np.array` kann keine Integer speichern',
      '`+` funktioniert nicht mit NumPy-Arrays',
      'Man braucht `np.add()` statt `+`',
    ],
    errorCorrect: 0,
    errorExplanation: 'Broadcasting funktioniert nur, wenn die Formen kompatibel sind. Arrays der Länge 3 und 2 sind nicht kompatibel — das führt zu einem `ValueError`.',
    errorHints: ['Elementweise Operationen brauchen gleich lange Arrays (oder Skalare).', 'Prüfe mit `a.shape` und `b.shape` die Formen.'],
    transferQuestion: 'Was ist `np.sum(np.array([1, 2, 3, 4]))`?',
    transferAnswer: 10,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: '`np.sum()` summiert alle Elemente: 1+2+3+4 = 10.',
    transferHints: ['`np.sum()` addiert alle Array-Elemente.', '1+2+3+4 = 10.'],
  },

  'py-2-2': {
    explanation: String.raw`**Vertiefung Matplotlib — Daten visualisieren:** Das Standardmuster ist: \`import matplotlib.pyplot as plt\`, dann \`plt.plot(x, y)\`, Achsenbeschriftungen mit \`plt.xlabel()\` / \`plt.ylabel()\`, Legende mit \`plt.legend()\`, Titel mit \`plt.title()\`, Anzeige mit \`plt.show()\`. Für mehrere Kurven: mehrere \`plt.plot()\`-Aufrufe vor \`plt.show()\`. In Matlab: \`plot(x,y)\`, \`xlabel()\`, \`legend()\`, \`title()\`.`,
    conceptQuestion: 'Welcher Befehl zeigt in Matplotlib den fertigen Plot an?',
    conceptOptions: ['plt.show()', 'plt.display()', 'plt.render()', 'plt.draw()'],
    conceptCorrect: 0,
    conceptExplanation: '`plt.show()` rendert und zeigt das Diagramm. Ohne diesen Aufruf wird in vielen Umgebungen kein Fenster geöffnet.',
    conceptHints: ['`plt.show()` kommt immer am Ende.', 'In Jupyter Notebooks erscheint der Plot oft auch ohne `plt.show()`.'],
    calcQuestion: 'Wie viele Datenpunkte enthält `np.linspace(0, 10, 11)`?',
    calcAnswer: 11,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: '`np.linspace(start, stop, num)` erzeugt `num` gleichmäßig verteilte Punkte. Mit `num=11`: 0, 1, 2, ..., 10 — also 11 Punkte.',
    calcHints: ['Das dritte Argument von `linspace` ist die Anzahl der Punkte.', 'Von 0 bis 10 in ganzen Schritten: 0,1,2,...,10 = 11 Werte.'],
    trueFalseStatement: 'Mit `plt.plot(x, y, label="Kurve")` und anschließendem `plt.legend()` erscheint eine Legende im Diagramm.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. `label=` definiert den Text, `plt.legend()` aktiviert die Legende im Plot.',
    trueFalseHints: ['Ohne `plt.legend()` wird das Label ignoriert.', 'Mehrere `plot()`-Aufrufe können verschiedene Labels haben.'],
    matchingQuestion: 'Ordne Matplotlib-Befehle ihren Matlab-Äquivalenten zu.',
    matchingPairs: [
      { left: 'plt.xlabel("Zeit [s]")', right: 'xlabel("Zeit [s]")' },
      { left: 'plt.title("Messung")', right: 'title("Messung")' },
      { left: 'plt.legend()', right: 'legend()' },
    ],
    matchingExplanation: 'Die Funktionsnamen sind in Python und Matlab sehr ähnlich. In Python wird `plt.` vorangestellt.',
    matchingHints: ['In Matlab braucht man kein Präfix wie `plt.`.', 'Die Argumentsyntax ist oft identisch.'],
    sortingQuestion: 'Bringe den Code für einen einfachen Sinus-Plot in die richtige Reihenfolge.',
    sortingItems: ['import numpy as np; import matplotlib.pyplot as plt', 'x = np.linspace(0, 2*np.pi, 100)', 'plt.plot(x, np.sin(x), label="sin(x)")', 'plt.xlabel("x"); plt.ylabel("y"); plt.legend(); plt.show()'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Import → x-Achse anlegen → Plot erstellen → Beschriften und anzeigen.',
    sortingHints: ['`linspace` erzeugt die x-Werte.', 'Beschriftung und `plt.show()` kommen nach dem Plot-Aufruf.'],
    errorQuestion: 'Was fehlt in diesem Code, damit die Legende erscheint?\n```\nplt.plot(x, y)\nplt.show()\n```',
    errorOptions: [
      'Es fehlt `label=` im `plot()`-Aufruf und `plt.legend()` vor `plt.show()`',
      'Es fehlt `plt.grid()`',
      'Es fehlt `plt.title()`',
      'Legendenparameter werden in `plt.show()` übergeben',
    ],
    errorCorrect: 0,
    errorExplanation: 'Für eine Legende braucht man: (1) `label="..."` im `plot()`-Aufruf und (2) `plt.legend()` vor `plt.show()`.',
    errorHints: ['`label=` und `plt.legend()` müssen beide vorhanden sein.', 'Ohne `label` weiß die Legende nicht, was sie anzeigen soll.'],
    transferQuestion: 'Wie viele Datenpunkte plottet `plt.plot(np.linspace(0,5,6), np.linspace(0,5,6))`?',
    transferAnswer: 6,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: '`np.linspace(0, 5, 6)` erzeugt 6 Punkte: 0, 1, 2, 3, 4, 5. Plot verbindet 6 Datenpunkte.',
    transferHints: ['Das dritte Argument von `linspace` ist die Anzahl der Punkte.', 'x und y haben die gleiche Länge.'],
  },

  'py-2-3': {
    explanation: String.raw`**Vertiefung Gleichungen lösen & Optimierung:** \`scipy.optimize.fsolve(f, x0)\` findet Nullstellen einer Funktion \`f\` ausgehend vom Startwert \`x0\`. \`scipy.optimize.minimize(f, x0)\` minimiert eine Funktion. In Matlab: \`fzero(f, x0)\` für Nullstellen, \`fminbnd\` oder \`fmincon\` für Optimierung. Wichtig: \`fsolve\` löst \`f(x) = 0\`, nicht \`f(x) = c\`. Gleichung umstellen: \`g(x) = f(x) - c = 0\`.`,
    conceptQuestion: 'Wie muss die Gleichung `x**2 = 4` formuliert werden, damit `fsolve` sie lösen kann?',
    conceptOptions: [
      'Als `f(x) = x**2 - 4 = 0`, also `f = lambda x: x**2 - 4`',
      'Als `f(x) = x**2 == 4`',
      'Als `f(x) = 4 / x**2`',
      '`fsolve` löst direkt `x**2 = 4` ohne Umformung',
    ],
    conceptCorrect: 0,
    conceptExplanation: '`fsolve` sucht Nullstellen von `f(x)`. Gleichung auf `f(x) = 0` umformen: `x**2 - 4 = 0`.',
    conceptHints: ['`fsolve` löst `f(x) = 0`, nicht `f(x) = c`.', 'Immer auf die rechte Seite bringen: `f(x) = lhs - rhs`.'],
    calcQuestion: 'Was gibt `fsolve(lambda x: x - 5, 0)` näherungsweise zurück?',
    calcAnswer: 5,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: 'Die Funktion `f(x) = x - 5` ist Null bei x = 5. `fsolve` findet diesen Wert.',
    calcHints: ['`x - 5 = 0` → x = 5.', '`fsolve` startet von x0=0 und konvergiert zur Nullstelle.'],
    trueFalseStatement: '`scipy.optimize.fsolve` kann nur Gleichungen mit einer Unbekannten lösen.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. `fsolve` kann auch Systeme nichtlinearer Gleichungen lösen — die Funktion gibt dann einen Vektor zurück und `x0` ist ein Startvektor.',
    trueFalseHints: ['`fsolve` akzeptiert vektorwertige Funktionen.', 'Für Systeme: `f` gibt eine Liste zurück, `x0` ist eine Liste.'],
    matchingQuestion: 'Ordne Python/SciPy-Funktionen ihren Matlab-Äquivalenten zu.',
    matchingPairs: [
      { left: 'fsolve(f, x0)', right: 'fzero(f, x0)' },
      { left: 'minimize(f, x0)', right: 'fminbnd / fmincon' },
      { left: 'lambda x: x**2 - 4', right: '@(x) x^2 - 4 (anonyme Funktion)' },
    ],
    matchingExplanation: 'Matlab und SciPy haben ähnliche Konzepte für numerische Lösung. Matlab nutzt `@(x)` für anonyme Funktionen, Python `lambda`.',
    matchingHints: ['`lambda` in Python entspricht `@(x)` in Matlab.', '`fzero` in Matlab findet Nullstellen.'],
    sortingQuestion: 'Bringe den Code zur Lösung von `x**3 - 8 = 0` mit fsolve in die richtige Reihenfolge.',
    sortingItems: ['from scipy.optimize import fsolve', 'f = lambda x: x**3 - 8', 'loesung = fsolve(f, 1.0)', 'print(loesung)  # [2.]'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Import → Funktion definieren → `fsolve` aufrufen → Ergebnis ausgeben. Die Lösung ist x=2, weil $2^3=8$.',
    sortingHints: ['`from scipy.optimize import fsolve` gibt den spezifischen Import.', '`f(x) = x**3 - 8 = 0` hat die Lösung x = 2.'],
    errorQuestion: 'Was ist falsch, wenn man `fsolve(f, x0)` mit `f = lambda x: x**2 - 4` und `x0 = 0` aufruft?',
    errorOptions: [
      'x0 = 0 liegt nahe dem lokalen Maximum — `fsolve` könnte nicht konvergieren oder nur eine Wurzel finden',
      '`fsolve` erwartet ganze Zahlen als Startwert',
      '`lambda` funktioniert nicht mit `fsolve`',
      '`x**2 - 4` hat keine Lösung',
    ],
    errorCorrect: 0,
    errorExplanation: 'x**2 - 4 = 0 hat Lösungen bei x = 2 und x = -2. Von x0=0 ist der Gradient Null — `fsolve` kann Probleme haben. Besser: x0 = 1 oder x0 = -1.',
    errorHints: ['Startwert nahe der erwarteten Lösung wählen.', 'Bei x=0 ist die Ableitung von x**2-4 gleich 0.'],
    transferQuestion: 'Was ist die Lösung von `x - 7 = 0`? (Gib x an.)',
    transferAnswer: 7,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: '`f(x) = x - 7 = 0` → x = 7.',
    transferHints: ['Nullstelle von `x - 7` finden.', 'x - 7 = 0 → x = 7.'],
  },

  'py-2-4': {
    explanation: String.raw`**Vertiefung Numerische Integration & DGL:** \`scipy.integrate.quad(f, a, b)\` berechnet das bestimmte Integral von \`a\` bis \`b\`. Rückgabe: \`(wert, fehler)\`. \`scipy.integrate.solve_ivp(f, [t0,tf], y0)\` löst Anfangswertprobleme. DGL-Form für \`solve_ivp\`: \`f(t, y)\` gibt \`dy/dt\` zurück. In Matlab: \`integral(f, a, b)\` und \`ode45\`.`,
    conceptQuestion: 'Welche Form muss die Funktion `f` haben, damit `solve_ivp(f, [0, 10], [1])` funktioniert?',
    conceptOptions: [
      'f(t, y) gibt dy/dt zurück (Ableitung in Abhängigkeit von t und y)',
      'f(y) gibt den nächsten y-Wert zurück',
      'f(t) gibt t**2 zurück',
      'f(t, y) gibt das Integral zurück',
    ],
    conceptCorrect: 0,
    conceptExplanation: '`solve_ivp` löst y\'(t) = f(t, y). Die Funktion `f` muss die rechte Seite der DGL beschreiben: Eingabe ist (t, y), Ausgabe ist dy/dt.',
    conceptHints: ['`solve_ivp` löst Anfangswertprobleme y\' = f(t, y).', '`y0` ist der Anfangswert zum Zeitpunkt t0.'],
    calcQuestion: 'Was gibt `quad(lambda x: 1, 0, 5)` näherungsweise als ersten Rückgabewert zurück?',
    calcAnswer: 5,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: 'Das Integral von 1 über [0, 5] ist 5 (Fläche eines Rechtecks mit Höhe 1 und Breite 5).',
    calcHints: ['$\\int_0^5 1\\,dx = [x]_0^5 = 5 - 0 = 5$.', '`quad` gibt (Integralwert, Fehlerabschätzung) zurück.'],
    trueFalseStatement: '`scipy.integrate.quad(f, a, b)` gibt nur den Integralwert zurück, keine Fehlerabschätzung.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. `quad` gibt ein Tupel `(wert, absfehler)` zurück. Man schreibt: `wert, fehler = quad(f, a, b)`.',
    trueFalseHints: ['`quad` gibt zwei Werte zurück.', 'Tuple-Unpacking: `wert, fehler = quad(f, a, b)`.'],
    matchingQuestion: 'Ordne SciPy-Integrationsfunktionen ihren Matlab-Äquivalenten zu.',
    matchingPairs: [
      { left: 'quad(f, a, b)', right: 'integral(f, a, b)' },
      { left: 'solve_ivp(f, [t0,tf], y0)', right: 'ode45(f, [t0 tf], y0)' },
      { left: 'wert, fehler = quad(f, a, b)', right: 'wert = integral(f, a, b)' },
    ],
    matchingExplanation: 'Matlab-`ode45` entspricht `solve_ivp`. `quad` ist das Python-Äquivalent zu Matlabs `integral()`.',
    matchingHints: ['`ode45` ist der klassische Matlab-DGL-Löser.', 'Matlab-`integral()` gibt nur den Wert zurück.'],
    sortingQuestion: 'Bringe den Code zur numerischen Integration von $\\int_0^1 x^2\\,dx$ in die richtige Reihenfolge.',
    sortingItems: ['from scipy.integrate import quad', 'f = lambda x: x**2', 'wert, fehler = quad(f, 0, 1)', 'print(wert)  # ≈ 0.3333'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Import → Funktion definieren → Integral berechnen → Ergebnis ausgeben. $\\int_0^1 x^2\\,dx = 1/3 \\approx 0.333$.',
    sortingHints: ['`from scipy.integrate import quad` ist der Import.', '$\\int_0^1 x^2\\,dx = [x^3/3]_0^1 = 1/3$.'],
    errorQuestion: 'Was ist falsch, wenn man `solve_ivp` aufruft als `solve_ivp(lambda t: -t, [0, 5], [1])`?',
    errorOptions: [
      'Die Lambda-Funktion hat nur einen Parameter `t`, muss aber `f(t, y)` sein',
      '`solve_ivp` akzeptiert keine Lambda-Funktionen',
      'Der Anfangswert `[1]` muss eine Zahl, keine Liste sein',
      'Das Zeitintervall muss als `t_span=(0, 5)` übergeben werden',
    ],
    errorCorrect: 0,
    errorExplanation: '`solve_ivp` erwartet `f(t, y)` mit zwei Parametern. `lambda t: -t` hat nur einen — das führt zu einem TypeError.',
    errorHints: ['Die Funktion für `solve_ivp` muss immer (t, y) als Parameter haben.', 'Richtig: `lambda t, y: -t`.'],
    transferQuestion: 'Was ist $\\int_0^2 2\\,dx$? (Exakter Wert)',
    transferAnswer: 4,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: '$\\int_0^2 2\\,dx = 2 \\times 2 = 4$ (Fläche eines Rechtecks mit Höhe 2 und Breite 2).',
    transferHints: ['Integral einer Konstanten c über [a,b] ist c·(b-a).', '2 × (2-0) = 4.'],
  },

  'py-3-1': {
    explanation: String.raw`**Vertiefung Festigkeitsberechnung:** Die Grundformel der Normalspannung ist $\sigma = F / A$. In Python schreibt man diese direkt als Funktion mit klaren Variablennamen. Wichtig: Einheiten müssen konsistent sein (N und m² → Pa, oder N und mm² → MPa). NumPy erlaubt die Berechnung für ganze Arrays von Werten auf einmal — ideal für Parameterstudien.`,
    conceptQuestion: 'Welche Python-Funktion berechnet die Normalspannung σ = F/A korrekt?',
    conceptOptions: [
      'def sigma(F, A): return F / A',
      'def sigma(F, A): return F * A',
      'def sigma(F, A): return A / F',
      'def sigma(F, A): return F + A',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'σ = F/A — Kraft durch Fläche. Die Python-Implementierung ist eine direkte Übersetzung der Formel.',
    conceptHints: ['σ = F / A ist die Definition der Normalspannung.', 'Kraft im Zähler, Fläche im Nenner.'],
    calcQuestion: 'Was gibt `1000 / 0.002` in Python zurück? ($\\sigma$ in Pa bei F=1000 N, A=0.002 $m^2$)',
    calcAnswer: 500000,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: '$\\sigma = F/A = 1000$ N $/ 0{,}002$ $m^2 = 500\\,000$ Pa = 500 kPa.',
    calcHints: ['1000 / 0.002 = 1000 × 500 = 500 000.', 'Einheit: $N/m^2$ = Pa.'],
    trueFalseStatement: 'In Python kann man eine Festigkeitsberechnung für mehrere Kraftwerte gleichzeitig durchführen, indem man ein `numpy.array` als Argument übergibt.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. `def sigma(F, A): return F / A` funktioniert mit NumPy-Arrays dank Broadcasting — die Berechnung wird elementweise durchgeführt.',
    trueFalseHints: ['NumPy-Arrays unterstützen elementweise Division.', 'Eine Funktion für Skalare funktioniert meist auch für Arrays.'],
    matchingQuestion: 'Ordne Festigkeitsvariablen ihrer Python-Entsprechung zu.',
    matchingPairs: [
      { left: 'σ (Normalspannung)', right: 'sigma = F / A' },
      { left: 'F (Kraft in N)', right: 'kraft = 1000  # Newton' },
      { left: 'A (Fläche in $m^2$)', right: 'flaeche = np.pi * (d/2)**2' },
    ],
    matchingExplanation: 'Gute Variablennamen machen den Code selbstdokumentierend. Kreisfläche: $A = \\pi r^2 = \\pi (d/2)^2$.',
    matchingHints: ['`np.pi` ist π in Python.', 'Radius = Durchmesser / 2.'],
    sortingQuestion: 'Bringe die Berechnung der Spannung eines Rundstabs in die richtige Reihenfolge.',
    sortingItems: ['import numpy as np', 'd = 0.02  # Durchmesser in m', 'A = np.pi * (d/2)**2', 'sigma = 5000 / A  # F=5000 N', 'print(f"Spannung: {sigma:.1f} Pa")'],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Import → Geometrie → Fläche berechnen → Spannung berechnen → Ausgeben.',
    sortingHints: ['`np.pi` braucht den Import.', '$A = \\pi r^2$ mit $r = d/2$.'],
    errorQuestion: 'Was ist falsch, wenn man für $\\sigma = F/A$ die Fläche in $mm^2$ einsetzt und die Kraft in N?',
    errorOptions: [
      'Das Ergebnis hat dann die Einheit $N/mm^2$ = MPa, nicht Pa — man muss die Einheit dokumentieren',
      'Division durch $mm^2$ ist in Python verboten',
      'NumPy kann keine $mm^2$-Werte verarbeiten',
      '$N/mm^2$ ist keine gültige Einheit',
    ],
    errorCorrect: 0,
    errorExplanation: 'Python kennt keine Einheiten — es rechnet nur mit Zahlen. $N/mm^2$ = MPa ist physikalisch korrekt, muss aber im Code durch Kommentare klar gemacht werden.',
    errorHints: ['Python ignoriert Einheiten — der Programmierer muss konsistent sein.', '$N/mm^2$ = MPa (Megapascal).'],
    transferQuestion: 'Berechne $\\sigma = F/A$ für $F = 2000$ N und $A = 0.004$ $m^2$. Gib $\\sigma$ in Pa an.',
    transferAnswer: 500000,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'σ = 2000 / 0,004 = 500 000 Pa.',
    transferHints: ['σ = F / A.', '2000 / 0.004 = 500 000.'],
  },

  'py-3-2': {
    explanation: String.raw`**Vertiefung Datenauswertung & Messdaten:** NumPy bietet die wichtigsten statistischen Funktionen: \`np.mean()\` (Mittelwert), \`np.std()\` (Standardabweichung), \`np.min()\` / \`np.max()\`. Für lineare Regression: \`np.polyfit(x, y, 1)\` gibt \`[m, b]\` zurück (Steigung und Achsenabschnitt). In Matlab: \`mean()\`, \`std()\`, \`polyfit(x,y,1)\` — sehr ähnlich.`,
    conceptQuestion: 'Was gibt `np.std(data)` zurück?',
    conceptOptions: [
      'Die Standardabweichung der Daten',
      'Die Summe aller Datenpunkte',
      'Den Median der Daten',
      'Die Varianz der Daten',
    ],
    conceptCorrect: 0,
    conceptExplanation: '`np.std()` berechnet die Standardabweichung. Die Varianz wäre `np.var()`, der Median `np.median()`.',
    conceptHints: ['`std` steht für Standard Deviation (Standardabweichung).', 'Standardabweichung = Wurzel der Varianz.'],
    calcQuestion: 'Was gibt `np.mean(np.array([2, 4, 6, 8]))` zurück?',
    calcAnswer: 5,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: 'Mittelwert = (2+4+6+8)/4 = 20/4 = 5.',
    calcHints: ['`np.mean()` berechnet den arithmetischen Mittelwert.', '(2+4+6+8)/4 = 20/4 = 5.'],
    trueFalseStatement: '`np.polyfit(x, y, 1)` gibt für eine lineare Regression die Koeffizienten in der Reihenfolge [Achsenabschnitt, Steigung] zurück.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. `np.polyfit(x, y, 1)` gibt `[Steigung, Achsenabschnitt]` zurück — höchste Potenz zuerst. Also: `m, b = np.polyfit(x, y, 1)`.',
    trueFalseHints: ['NumPy gibt Koeffizienten vom höchsten zum niedrigsten Grad zurück.', 'Für y = mx + b: `polyfit` gibt [m, b] zurück.'],
    matchingQuestion: 'Ordne NumPy-Statistikfunktionen ihren Matlab-Äquivalenten zu.',
    matchingPairs: [
      { left: 'np.mean(x)', right: 'mean(x)' },
      { left: 'np.std(x)', right: 'std(x)' },
      { left: 'np.polyfit(x, y, 1)', right: 'polyfit(x, y, 1)' },
    ],
    matchingExplanation: 'Die Funktionsnamen sind in NumPy und Matlab nahezu identisch. In Python wird `np.` vorangestellt.',
    matchingHints: ['Matlab und NumPy teilen viele Funktionsnamen.', 'In Python ist der Import `import numpy as np` nötig.'],
    sortingQuestion: 'Bringe die Schritte einer linearen Regression in die richtige Reihenfolge.',
    sortingItems: ['x = np.array([1, 2, 3, 4, 5])', 'y = np.array([2.1, 3.9, 6.2, 7.8, 10.1])', 'm, b = np.polyfit(x, y, 1)', 'print(f"Steigung: {m:.2f}, Achsenabschnitt: {b:.2f}")'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'x-Daten → y-Daten → Regression → Ausgabe der Koeffizienten.',
    sortingHints: ['Daten müssen vor der Regression vorhanden sein.', '`polyfit(x, y, 1)` für lineare Regression (Grad 1).'],
    errorQuestion: 'Was gibt `np.std([5, 5, 5, 5])` zurück?',
    errorOptions: [
      '0 — alle Werte sind gleich, keine Streuung',
      '5 — der Mittelwert',
      '20 — die Summe',
      '1 — Standardwert',
    ],
    errorCorrect: 0,
    errorExplanation: 'Wenn alle Werte identisch sind, gibt es keine Abweichung vom Mittelwert. Die Standardabweichung ist 0.',
    errorHints: ['Standardabweichung misst die Streuung um den Mittelwert.', 'Kein Unterschied zwischen Werten → keine Streuung → σ = 0.'],
    transferQuestion: 'Was ist `np.mean(np.array([10, 20, 30]))`?',
    transferAnswer: 20,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: 'Mittelwert = (10+20+30)/3 = 60/3 = 20.',
    transferHints: ['Alle Werte addieren und durch die Anzahl teilen.', '(10+20+30)/3 = 20.'],
  },

  'py-3-3': {
    explanation: String.raw`**Vertiefung Simulation: Feder-Masse-Dämpfer:** Das Feder-Masse-Dämpfer-System wird als DGL 2. Ordnung beschrieben: $m\ddot{x} + d\dot{x} + kx = F(t)$. Für \`solve_ivp\` wird es in zwei gekoppelte DGL 1. Ordnung umgewandelt: $y_0 = x$, $y_1 = \dot{x}$, dann $\dot{y}_0 = y_1$ und $\dot{y}_1 = (F - d \cdot y_1 - k \cdot y_0) / m$. In Matlab nutzt man \`ode45\` auf dieselbe Art.`,
    conceptQuestion: 'Warum wird eine DGL 2. Ordnung wie das Feder-Masse-System in zwei DGL 1. Ordnung umgewandelt?',
    conceptOptions: [
      'Weil `solve_ivp` und `ode45` nur DGL-Systeme 1. Ordnung lösen können',
      'Weil DGL 2. Ordnung keine Lösungen haben',
      'Weil Python keine zweiten Ableitungen kennt',
      'Weil Feder-Masse-Systeme immer linear sind',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Numerische ODE-Löser wie `solve_ivp` und `ode45` erwarten y\' = f(t, y). Eine DGL 2. Ordnung muss durch Substitution (x, ẋ als Zustandsvektor) umgeformt werden.',
    conceptHints: ['`solve_ivp` erwartet ein System y\' = f(t, y).', 'Substitution: y[0] = x, y[1] = ẋ.'],
    calcQuestion: 'Für m=1, d=0, k=1, x(0)=1, ẋ(0)=0: Was ist die Eigenfrequenz $\\omega_0 = \\sqrt{k/m}$?',
    calcAnswer: 1,
    calcTolerance: 0,
    calcUnit: '',
    calcExplanation: '$\\omega_0 = \\sqrt{k/m} = \\sqrt{1/1} = 1$ rad/s.',
    calcHints: ['$\\omega_0 = \\sqrt{k/m}$.', '$\\sqrt{1/1} = 1$.'],
    trueFalseStatement: 'Für `solve_ivp` wird das Feder-Masse-Dämpfer-System als Funktion `f(t, y)` übergeben, wobei `y[0]` die Position und `y[1]` die Geschwindigkeit ist.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Der Zustandsvektor y enthält Position und Geschwindigkeit. `f` gibt [ẋ, ẍ] = [y[1], (F - d*y[1] - k*y[0])/m] zurück.',
    trueFalseHints: ['y[0] = Position x, y[1] = Geschwindigkeit ẋ.', 'Die Funktion gibt die Ableitungen zurück.'],
    matchingQuestion: 'Ordne Systemparameter des Feder-Masse-Dämpfers ihrem Python-Code zu.',
    matchingPairs: [
      { left: 'Masse m', right: 'm = 2.0  # kg' },
      { left: 'Federkonstante k', right: 'k = 100.0  # N/m' },
      { left: 'Dämpfungskonstante d', right: 'd = 5.0  # Ns/m' },
    ],
    matchingExplanation: 'Klare Variablennamen mit Einheiten als Kommentar machen Simulationscode lesbar und wartbar.',
    matchingHints: ['Kommentare mit Einheiten sind in technischen Skripten Pflicht.', 'SI-Einheiten verwenden.'],
    sortingQuestion: 'Bringe die Systemfunktion für einen ungedämpften Schwinger (d=0) in die richtige Reihenfolge.',
    sortingItems: ['def feder_masse(t, y, m, k):', '    x, v = y[0], y[1]', '    ax = -k * x / m', '    return [v, ax]'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Funktionskopf → Zustandsvariablen entpacken → Beschleunigung berechnen → [ẋ, ẍ] zurückgeben.',
    sortingHints: ['`y[0]` = Position, `y[1]` = Geschwindigkeit.', 'Rückgabe ist [Geschwindigkeit, Beschleunigung].'],
    errorQuestion: 'Was ist falsch an `def f(t, y): return -k * y` für ein Feder-Masse-System mit m=1, wenn y ein Vektor [x, v] ist?',
    errorOptions: [
      'Die Funktion gibt einen skalaren Wert zurück, aber `solve_ivp` erwartet einen Vektor [ẋ, ẍ]',
      '`-k * y` ist kein gültiger Python-Ausdruck',
      '`t` wird nicht verwendet und muss weggelassen werden',
      'Der Parameter `k` muss als globale Variable definiert sein',
    ],
    errorCorrect: 0,
    errorExplanation: 'Für ein System 2. Ordnung muss die Funktion `[v, -k*x/m]` zurückgeben — einen Vektor mit Ableitungen beider Zustandsgrößen.',
    errorHints: ['`solve_ivp` erwartet für ein System `n` Ableitungen.', 'Rückgabe muss `[y[1], -k*y[0]/m]` sein.'],
    transferQuestion: 'Für k=4, m=1: Was ist $\\omega_0 = \\sqrt{k/m}$?',
    transferAnswer: 2,
    transferTolerance: 0,
    transferUnit: '',
    transferExplanation: '$\\omega_0 = \\sqrt{4/1} = \\sqrt{4} = 2$ rad/s.',
    transferHints: ['$\\omega_0 = \\sqrt{k/m}$.', '$\\sqrt{4} = 2$.'],
  },
}

export const pythonMatlabSupplements = Object.fromEntries(
  Object.entries(profiles).map(([lessonId, profile]) => [
    lessonId,
    {
      explanation: profile.explanation,
      exercises: bank(profile),
    },
  ])
)
