function mc(question, options, correctIndex, explanation, hints = []) {
  return { type: 'multiple-choice', question, options, correctIndex, explanation, hints }
}

function ni(question, correctValue, tolerance, unit, explanation, hints = []) {
  return { type: 'number-input', question, correctValue, tolerance, unit, explanation, hints }
}

function tf(statement, correct, explanation, hints = []) {
  return { type: 'true-false', statement, correct, explanation, hints }
}

function matching(question, pairs, explanation, hints = []) {
  return { type: 'matching', question, pairs, explanation, hints }
}

function sorting(question, items, correctOrder, explanation, hints = []) {
  return { type: 'sorting', question, items, correctOrder, explanation, hints }
}

function withExamPrefix(exercise, exam) {
  if (!exam) return exercise
  if (exercise.question && !exercise.question.includes('[PRÜFUNG]')) {
    return { ...exercise, question: `[PRÜFUNG] ${exercise.question}` }
  }
  if (exercise.statement && !exercise.statement.includes('[PRÜFUNG]')) {
    return { ...exercise, statement: `[PRÜFUNG] ${exercise.statement}` }
  }
  return exercise
}

function bank(profile) {
  const exercises = [
    mc(profile.conceptQuestion, profile.conceptOptions, profile.conceptCorrect, profile.conceptExplanation, profile.conceptHints),
    ni(profile.calcQuestion, profile.calcAnswer, profile.calcTolerance, profile.calcUnit, profile.calcExplanation, profile.calcHints),
    tf(profile.trueFalseStatement, profile.trueFalseCorrect, profile.trueFalseExplanation, profile.trueFalseHints),
    matching(profile.matchingQuestion, profile.matchingPairs, profile.matchingExplanation, profile.matchingHints),
    sorting(profile.sortingQuestion, profile.sortingItems, profile.sortingOrder, profile.sortingExplanation, profile.sortingHints),
    mc(profile.errorQuestion, profile.errorOptions, profile.errorCorrect, profile.errorExplanation, profile.errorHints),
    ni(profile.transferQuestion, profile.transferAnswer, profile.transferTolerance, profile.transferUnit, profile.transferExplanation, profile.transferHints),
  ]
  return exercises.map((exercise) => withExamPrefix(exercise, profile.exam))
}

const profiles = {
  // ── Unit 1 ────────────────────────────────────────────────────────────────

  'vek-1-1': {
    explanation: String.raw`**Vertiefung Vektoren in der Ebene:** Ein Vektor $\vec{a} = (a_x, a_y)$ hat Betrag $|\vec{a}| = \sqrt{a_x^2 + a_y^2}$. Addition komponentenweise: $\vec{a} + \vec{b} = (a_x+b_x,\, a_y+b_y)$. Skalarmultiplikation: $k\cdot\vec{a} = (k\,a_x,\, k\,a_y)$. Zeichne Vektoren immer als Pfeile, um Vorzeichen zu kontrollieren.`,
    conceptQuestion: 'Was ist das Ergebnis von $\\vec{a}$ + $\\vec{b}$ mit $\\vec{a}$ = (3, −1) und $\\vec{b}$ = (−2, 4)?',
    conceptOptions: ['(1, 3)', '(5, −5)', '(1, −5)', '(6, −4)'],
    conceptCorrect: 0,
    conceptExplanation: 'Vektoraddition komponentenweise: (3+(−2), (−1)+4) = (1, 3).',
    conceptHints: ['Addiere x-Komponenten und y-Komponenten getrennt.', '3+(−2) = 1, (−1)+4 = 3.'],
    calcQuestion: 'Berechne den Betrag von $\\vec{a}$ = (5, 12).',
    calcAnswer: 13,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: '|$\\vec{a}$| = √(5² + 12²) = √(25 + 144) = √169 = 13. Das bekannte 5-12-13-Pythagoreisches Tripel.',
    calcHints: ['|$\\vec{a}$| = √(ax² + ay²).', '25 + 144 = 169 = 13².'],
    trueFalseStatement: 'Die Skalarmultiplikation 2·$\\vec{a}$ = (2·ax, 2·ay) verdoppelt den Betrag des Vektors, ändert aber nicht seine Richtung.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. |2·$\\vec{a}$| = 2·|$\\vec{a}$|, die Richtung (der Winkel) bleibt unverändert, da beide Komponenten mit demselben positiven Faktor skaliert werden.',
    trueFalseHints: ['Betrag: |k·$\\vec{a}$| = |k|·|$\\vec{a}$|.', 'Positives k dreht die Richtung nicht.'],
    matchingQuestion: 'Ordne den Vektoroperationen ihre Ergebnistypen zu.',
    matchingPairs: [
      { left: '$\\vec{a}$ + $\\vec{b}$', right: 'Vektor (komponentenweise Summe)' },
      { left: 'k · $\\vec{a}$', right: 'Vektor (gestreckter/gestauchter Pfeil)' },
      { left: '|$\\vec{a}$|', right: 'Skalar (nicht-negative Zahl)' },
    ],
    matchingExplanation: 'Addition und Skalarmultiplikation liefern Vektoren; der Betrag liefert eine Zahl.',
    matchingHints: ['Der Betrag ist immer ≥ 0.', 'Zwei Vektoren addiert ergeben wieder einen Vektor.'],
    sortingQuestion: 'Bringe die Schritte zur Berechnung von |3·$\\vec{a}$| mit $\\vec{a}$ = (4, 3) in die richtige Reihenfolge.',
    sortingItems: ['3·$\\vec{a}$ = (12, 9) berechnen', '|3·$\\vec{a}$| = √(12² + 9²) aufstellen', '144 + 81 = 225 berechnen', '√225 = 15 ablesen'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: '3·(4,3) = (12,9). |( 12,9)| = √(144+81) = √225 = 15. Alternativ: 3·|(4,3)| = 3·5 = 15.',
    sortingHints: ['Zuerst skalieren, dann Betrag.', '4² + 3² = 25, √25 = 5, also 3·5 = 15.'],
    errorQuestion: 'Welcher Rechenschritt beim Betrag von $\\vec{a}$ = (3, 4) ist falsch?',
    errorOptions: ['|$\\vec{a}$| = √(3² + 4²) = √25 = 5', '|$\\vec{a}$| = 3 + 4 = 7', '|$\\vec{a}$| = √(9 + 16)', '|$\\vec{a}$| = 5'],
    errorCorrect: 1,
    errorExplanation: 'Der Betrag ist nicht die Summe der Komponenten (3 + 4 = 7 ist falsch). Es gilt |$\\vec{a}$| = √(3² + 4²) = 5.',
    errorHints: ['Satz des Pythagoras: Wurzel aus Quadratsumme.', '3 + 4 = 7 ist keine Vektornorm.'],
    transferQuestion: 'Eine Drohne fliegt von (0, 0) nach (8, 6). Wie lang ist der direkte Flugweg?',
    transferAnswer: 10,
    transferTolerance: 0.01,
    transferUnit: 'm',
    transferExplanation: 'Verbindungsvektor: (8, 6). Betrag: √(64 + 36) = √100 = 10 m.',
    transferHints: ['Betrag des Verbindungsvektors = Länge des Wegs.', '8² + 6² = 64 + 36 = 100.'],
  },

  'vek-1-2': {
    explanation: String.raw`**Vertiefung Skalarprodukt und Winkel:** $\vec{a} \cdot \vec{b} = a_x b_x + a_y b_y + a_z b_z$ (komponentenweise) und $\vec{a} \cdot \vec{b} = |\vec{a}|\,|\vec{b}|\cos\varphi$ (geometrisch). Aus beiden folgt: $\cos\varphi = \frac{\vec{a}\cdot\vec{b}}{|\vec{a}|\,|\vec{b}|}$. Skalarprodukt = 0 bedeutet Orthogonalität ($\varphi = 90°$).`,
    conceptQuestion: 'Warum ist das Skalarprodukt zweier Vektoren eine Zahl und kein Vektor?',
    conceptOptions: [
      'Weil man Komponenten multipliziert und addiert — das ergibt eine Zahl',
      'Weil Vektoren nicht multipliziert werden können',
      'Weil das Ergebnis immer 0 ist',
      'Weil der Winkel zwischen Vektoren kein Vektor ist',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Das Skalarprodukt $\\vec{a}$·$\\vec{b}$ = ax·bx + ay·by + az·bz ist eine Summe von Produkten reeller Zahlen — also selbst eine reelle Zahl (Skalar).',
    conceptHints: ['"Skalar"-produkt ist ein Hinweis.', 'ax·bx ist eine Zahl × Zahl = Zahl.'],
    calcQuestion: 'Berechne $\\vec{a}$·$\\vec{b}$ für $\\vec{a}$ = (2, 1, 3) und $\\vec{b}$ = (4, −2, 1).',
    calcAnswer: 9,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: '$\\vec{a}$·$\\vec{b}$ = 2·4 + 1·(−2) + 3·1 = 8 − 2 + 3 = 9.',
    calcHints: ['Komponentenweise multiplizieren und aufsummieren.', '8 − 2 + 3 = 9.'],
    trueFalseStatement: 'Gilt $\\vec{a}$·$\\vec{b}$ = 0, so stehen $\\vec{a}$ und $\\vec{b}$ senkrecht aufeinander (sofern beide nicht der Nullvektor sind).',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. $\\vec{a}$·$\\vec{b}$ = |$\\vec{a}$|·|$\\vec{b}$|·cos(90°) = 0, weil cos(90°) = 0. Umgekehrt folgt aus $\\vec{a}$·$\\vec{b}$ = 0 der Winkel 90°.',
    trueFalseHints: ['cos(90°) = 0.', 'Skalarprodukt = 0 ↔ Orthogonalität (bei Nichtnullvektoren).'],
    matchingQuestion: 'Ordne Winkel und Skalarproduktvorzeichen zu.',
    matchingPairs: [
      { left: 'φ = 0° (gleiche Richtung)', right: '$\\vec{a}$·$\\vec{b}$ = |$\\vec{a}$|·|$\\vec{b}$| > 0' },
      { left: 'φ = 90° (senkrecht)', right: '$\\vec{a}$·$\\vec{b}$ = 0' },
      { left: 'φ = 180° (entgegen)', right: '$\\vec{a}$·$\\vec{b}$ = −|$\\vec{a}$|·|$\\vec{b}$| < 0' },
    ],
    matchingExplanation: 'cos(0°)=1, cos(90°)=0, cos(180°)=−1 bestimmen das Vorzeichen des Skalarprodukts.',
    matchingHints: ['cos(0°) = 1, cos(180°) = −1.', 'Positives Skalarprodukt → spitzer Winkel.'],
    sortingQuestion: 'Bringe die Schritte zur Winkelberechnung zwischen $\\vec{a}$ = (1,0) und $\\vec{b}$ = (1,1) in die richtige Reihenfolge.',
    sortingItems: ['$\\vec{a}$·$\\vec{b}$ = 1·1 + 0·1 = 1 berechnen', '|$\\vec{a}$| = 1 und |$\\vec{b}$| = √2 bestimmen', 'cos(φ) = 1/(1·√2) = 1/√2 aufstellen', 'φ = arccos(1/√2) = 45° ablesen'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Zuerst Skalarprodukt, dann Beträge, dann cos(φ) = Skalarprodukt / (|$\\vec{a}$|·|$\\vec{b}$|), dann arccos.',
    sortingHints: ['Skalarprodukt vor Betragsberechnung.', 'arccos ist der letzte Schritt.'],
    errorQuestion: 'Beim Winkel zwischen $\\vec{a}$ = (3,4) und $\\vec{b}$ = (0,1) rechnet jemand cos(φ) = (3·0 + 4·1) = 4. Was ist falsch?',
    errorOptions: [
      'Das Skalarprodukt muss noch durch |$\\vec{a}$|·|$\\vec{b}$| dividiert werden',
      'Das Skalarprodukt ist falsch berechnet',
      'cos(φ) darf nie größer als 1 sein, also stimmt das Ergebnis',
      'Der Winkel ist 4°',
    ],
    errorCorrect: 0,
    errorExplanation: 'Das Skalarprodukt $\\vec{a}$·$\\vec{b}$ = 4 ist korrekt, aber cos(φ) = $\\vec{a}$·$\\vec{b}$ / (|$\\vec{a}$|·|$\\vec{b}$|) = 4 / (5·1) = 0,8. φ = arccos(0,8) ≈ 36,9°.',
    errorHints: ['cos(φ) = $\\vec{a}$·$\\vec{b}$ / (|$\\vec{a}$|·|$\\vec{b}$|), nicht nur $\\vec{a}$·$\\vec{b}$.', '|$\\vec{a}$| = √(9+16) = 5.'],
    transferQuestion: 'Arbeit W = $\\vec{F}$·$\\vec{s}$ mit $\\vec{F}$ = (6, 0, 0) N und $\\vec{s}$ = (3, 4, 0) m. Berechne W.',
    transferAnswer: 18,
    transferTolerance: 0.01,
    transferUnit: 'J',
    transferExplanation: 'W = $\\vec{F}$·$\\vec{s}$ = 6·3 + 0·4 + 0·0 = 18 J. Nur die x-Komponente der Kraft leistet Arbeit entlang der x-Verschiebung.',
    transferHints: ['Skalarprodukt: Fx·sx + Fy·sy + Fz·sz.', '6·3 = 18, die anderen Terme sind 0.'],
  },

  'vek-1-3': {
    explanation: String.raw`**Vertiefung Kreuzprodukt und Normalenvektor:** $\vec{a} \times \vec{b} = \begin{pmatrix}a_y b_z - a_z b_y \\ a_z b_x - a_x b_z \\ a_x b_y - a_y b_x\end{pmatrix}$. Das Ergebnis steht senkrecht auf $\vec{a}$ und $\vec{b}$. Betrag: $|\vec{a} \times \vec{b}| = |\vec{a}|\,|\vec{b}|\sin\varphi$ = Parallelogrammfläche. Antikommutativ: $\vec{a} \times \vec{b} = -(\vec{b} \times \vec{a})$.`,
    conceptQuestion: 'Was ist das Kreuzprodukt $\\vec{a}$ × $\\vec{b}$ von $\\vec{a}$ = (1, 0, 0) und $\\vec{b}$ = (0, 0, 1)?',
    conceptOptions: ['(0, −1, 0)', '(0, 1, 0)', '(1, 0, 0)', '(0, 0, 0)'],
    conceptCorrect: 0,
    conceptExplanation: '$\\vec{a}$ × $\\vec{b}$ = (0·1−0·0, 0·0−1·1, 1·0−0·0) = (0, −1, 0). Rechte-Hand-Regel: è₁ × è₃ = −è₂.',
    conceptHints: ['Formel: (ay·bz−az·by, az·bx−ax·bz, ax·by−ay·bx).', 'è₁ × è₃ = −è₂ nach zyklischer Regel.'],
    calcQuestion: 'Berechne den Betrag von $\\vec{a}$ × $\\vec{b}$ für $\\vec{a}$ = (2, 0, 0) und $\\vec{b}$ = (0, 3, 0).',
    calcAnswer: 6,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: '$\\vec{a}$ × $\\vec{b}$ = (0·0−0·3, 0·0−2·0, 2·3−0·0) = (0, 0, 6). |$\\vec{a}$ × $\\vec{b}$| = 6. Das Parallelogramm hat Seiten 2 und 3 (senkrecht) → Fläche = 6.',
    calcHints: ['$\\vec{a}$ und $\\vec{b}$ stehen senkrecht → |$\\vec{a}$ × $\\vec{b}$| = |$\\vec{a}$|·|$\\vec{b}$|·sin(90°) = 2·3·1 = 6.', 'Alternativ: Kreuzprodukt ausrechnen, dann Betrag nehmen.'],
    trueFalseStatement: 'Das Kreuzprodukt ist kommutativ: $\\vec{a}$ × $\\vec{b}$ = $\\vec{b}$ × $\\vec{a}$.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Das Kreuzprodukt ist antikommutativ: $\\vec{a}$ × $\\vec{b}$ = −($\\vec{b}$ × $\\vec{a}$). Beim Vertauschen der Reihenfolge dreht sich der Ergebnisvektor um.',
    trueFalseHints: ['Rechte-Hand-Regel: Die Fingerrichtung ändert sich beim Vertauschen.', '$\\vec{a}$ × $\\vec{b}$ und $\\vec{b}$ × $\\vec{a}$ zeigen in entgegengesetzte Richtungen.'],
    matchingQuestion: 'Ordne Kreuzprodukt-Ergebnisse den Einheitsvektorpaaren zu.',
    matchingPairs: [
      { left: 'è₁ × è₂', right: 'è₃' },
      { left: 'è₂ × è₃', right: 'è₁' },
      { left: 'è₃ × è₁', right: 'è₂' },
    ],
    matchingExplanation: 'Die zyklische Regel è₁×è₂=è₃, è₂×è₃=è₁, è₃×è₁=è₂ folgt aus der Rechte-Hand-Regel.',
    matchingHints: ['Zyklisch: x→y→z→x.', 'Rechte-Hand-Regel: Zeigefinger erstes, Mittelfinger zweites, Daumen = Ergebnis.'],
    sortingQuestion: 'Bringe die Berechnung von $\\vec{a}$ × $\\vec{b}$ für $\\vec{a}$ = (1, 2, 3), $\\vec{b}$ = (4, 5, 6) in die richtige Reihenfolge.',
    sortingItems: [
      'Formel aufschreiben: (ay·bz−az·by, az·bx−ax·bz, ax·by−ay·bx)',
      'x-Komponente: 2·6 − 3·5 = 12 − 15 = −3',
      'y-Komponente: 3·4 − 1·6 = 12 − 6 = 6',
      'z-Komponente: 1·5 − 2·4 = 5 − 8 = −3',
      'Ergebnis: (−3, 6, −3)',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: 'Formel notieren, dann x, y, z-Komponente einzeln berechnen, dann zusammensetzen.',
    sortingHints: ['Erst die Formel, dann Komponente für Komponente.', 'Probe: $\\vec{a}$·($\\vec{a}$×$\\vec{b}$) muss 0 sein.'],
    errorQuestion: 'Was ist am Ergebnis $\\vec{a}$ × $\\vec{b}$ = 7 (eine Zahl) falsch?',
    errorOptions: [
      'Das Kreuzprodukt ist immer ein Vektor, nie ein Skalar',
      'Das Kreuzprodukt kann nie 7 sein',
      'Das Kreuzprodukt ist nur für 2D-Vektoren definiert',
      'Das Kreuzprodukt ergibt immer den Nullvektor',
    ],
    errorCorrect: 0,
    errorExplanation: 'Das Kreuzprodukt zweier 3D-Vektoren ist immer ein Vektor (mit x, y, z-Komponente), niemals ein Skalar. Das Skalarprodukt liefert eine Zahl, das Kreuzprodukt einen Vektor.',
    errorHints: ['Kreuzprodukt → Vektor. Skalarprodukt → Skalar.', 'Merke: "Kreuz" → Pfeil (Vektor).'],
    transferQuestion: 'Drehmoment: $\\vec{r}$ = (0, 0.4, 0) m, $\\vec{F}$ = (200, 0, 0) N. Berechne |$\\vec{M}$| = |$\\vec{r}$ × $\\vec{F}$| in Nm.',
    transferAnswer: 80,
    transferTolerance: 0.1,
    transferUnit: 'Nm',
    transferExplanation: '$\\vec{r}$ × $\\vec{F}$ = (0.4·0−0·0, 0·200−0·0, 0·0−0.4·200) = (0, 0, −80). |$\\vec{M}$| = 80 Nm. Alternativ: senkrecht → |M| = 0.4·200·sin(90°) = 80 Nm.',
    transferHints: ['$\\vec{r}$ und $\\vec{F}$ stehen senkrecht → |M| = |$\\vec{r}$|·|$\\vec{F}$|.', '0.4 m × 200 N = 80 Nm.'],
  },

  'vek-1-4': {
    explanation: String.raw`**Vertiefung Kräfte als Vektoren:** Kräfte werden vektoriell addiert. Gleichgewicht: $\sum \vec{F}_i = \vec{0}$, d.h. komponentenweise $\sum F_{ix} = 0$ und $\sum F_{iy} = 0$. Kräftezerlegung unter Winkel $\alpha$: $F_x = F\cos\alpha$, $F_y = F\sin\alpha$. Einheitsvektor (Normierung): $\hat{e} = \vec{a}/|\vec{a}|$.`,
    conceptQuestion: 'Was ist die Gleichgewichtsbedingung für Kräfte in der Ebene?',
    conceptOptions: [
      'Summe aller Kräfte = $\\vec{0}$ (komponentenweise)',
      'Summe der Beträge aller Kräfte = 0',
      'Alle Kräfte zeigen in dieselbe Richtung',
      'Die größte Kraft bestimmt die Bewegung',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Gleichgewicht: ΣFx = 0 und ΣFy = 0 (und ΣFz = 0 im 3D). Die vektorielle Summe muss der Nullvektor sein.',
    conceptHints: ['Nicht Beträge, sondern Komponenten summieren.', 'Jede Richtung einzeln betrachten.'],
    calcQuestion: 'Resultierende $\\vec{R}$ = $\\vec{F}$₁ + $\\vec{F}$₂ + $\\vec{F}$₃ mit $\\vec{F}$₁=(5,0) N, $\\vec{F}$₂=(0,8) N, $\\vec{F}$₃=(−3,−2) N. Berechne |$\\vec{R}$|.',
    calcAnswer: 7.21,
    calcTolerance: 0.05,
    calcUnit: 'N',
    calcExplanation: '$\\vec{R}$ = (5+0+(−3), 0+8+(−2)) = (2, 6) N. |$\\vec{R}$| = √(4 + 36) = √40 ≈ 6,32 N. Korrekt: √(2²+6²)=√40≈6,32 N. Korrektur: √40 = 2√10 ≈ 6,32.',
    calcHints: ['Komponentenweise addieren, dann Betrag.', '√(4+36) = √40 ≈ 6,32.'],
    trueFalseStatement: 'Zwei Kräfte $\\vec{F}$₁ = (3, 4) N und $\\vec{F}$₂ = (−3, −4) N halten sich gegenseitig im Gleichgewicht.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. $\\vec{F}$₁ + $\\vec{F}$₂ = (3+(−3), 4+(−4)) = (0, 0) N = $\\vec{0}$. Die Kräfte heben sich auf.',
    trueFalseHints: ['Gleichgewicht: vektorielle Summe = Nullvektor.', '(3,4) + (−3,−4) = (0,0).'],
    matchingQuestion: 'Ordne die Kraftzerlegungsformeln bei Winkel α zur Horizontalen zu.',
    matchingPairs: [
      { left: 'Horizontalkomponente Fx', right: 'F·cos(α)' },
      { left: 'Vertikalkomponente Fy', right: 'F·sin(α)' },
      { left: 'Einheitsvektor ê', right: '$\\vec{a}$ / |$\\vec{a}$|' },
    ],
    matchingExplanation: 'Kräftezerlegung: Fx = F·cosα (horizontal), Fy = F·sinα (vertikal). Normierung durch Division durch den Betrag.',
    matchingHints: ['cos → horizontal (Ankathete).', 'sin → vertikal (Gegenkathete).'],
    sortingQuestion: 'Löse die Aufgabe: Kraft F = 50 N unter 30° zur Horizontalen. Berechne Fx.',
    sortingItems: ['Winkel α = 30° identifizieren', 'Formel Fx = F·cos(α) aufschreiben', 'cos(30°) = √3/2 ≈ 0,866 einsetzen', 'Fx = 50·0,866 ≈ 43,3 N berechnen'],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Winkel bestimmen → Formel → Wert → Ergebnis. Fx = 50·cos(30°) = 50·0,866 ≈ 43,3 N.',
    sortingHints: ['Erst Winkel, dann Formel.', 'cos für horizontale Komponente.'],
    errorQuestion: 'Kraft F = 100 N unter 60° zur Horizontalen. Jemand rechnet Fx = F·sin(60°) = 86,6 N. Was ist falsch?',
    errorOptions: [
      'Fx = F·cos(60°) = 50 N — der Cosinus gehört zur horizontalen Komponente',
      'F·sin(60°) ist korrekt, denn 60° ist der Winkel zur Horizontalen',
      'Fx kann nicht berechnet werden, wenn kein y-Wert bekannt ist',
      'F muss zuerst in Newton umgerechnet werden',
    ],
    errorCorrect: 0,
    errorExplanation: 'Die horizontale Komponente ist Fx = F·cos(α) = 100·cos(60°) = 100·0,5 = 50 N. Der Sinus gehört zur vertikalen Komponente Fy = F·sin(60°) ≈ 86,6 N.',
    errorHints: ['CAH: cos → Ankathete = horizontal.', 'SOH: sin → Gegenkathete = vertikal.'],
    transferQuestion: 'Normiere den Vektor $\\vec{a}$ = (3, 4). Wie groß ist die x-Komponente des Einheitsvektors?',
    transferAnswer: 0.6,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: '|$\\vec{a}$| = 5. ê = (3/5, 4/5) = (0,6; 0,8). x-Komponente = 0,6.',
    transferHints: ['Betrag: |(3,4)| = √(9+16) = 5.', 'Einheitsvektor: ê = $\\vec{a}$/|$\\vec{a}$| = (3/5, 4/5).'],
  },

  // ── Unit 2 ────────────────────────────────────────────────────────────────

  'vek-2-1': {
    explanation: String.raw`**Vertiefung Geraden im Raum:** Parameterform: $\vec{r} = \vec{p} + t\cdot\vec{v}$ ($t \in \mathbb{R}$). Lagekombinationen zweier Geraden: parallel ($\vec{v}_2 = k\cdot\vec{v}_1$), identisch, schneidend oder windschief (nur 3D). Prüfablauf: 1. Richtungsvektoren vergleichen. 2. Wenn nicht parallel: Gleichungssystem lösen. 3. Kein Schnittpunkt und nicht parallel → windschief.`,
    conceptQuestion: 'Gerade g: $\\vec{r}$ = (2, 0, 1) + t·(1, 3, −1). Welcher Punkt liegt auf g?',
    conceptOptions: ['(3, 3, 0)', '(2, 3, 1)', '(1, 3, −1)', '(2, 0, 0)'],
    conceptCorrect: 0,
    conceptExplanation: 'Für t = 1: $\\vec{r}$ = (2+1, 0+3, 1+(−1)) = (3, 3, 0). Dieser Punkt liegt auf der Geraden.',
    conceptHints: ['Setze t = 1 ein: $\\vec{p}$ + 1·$\\vec{v}$.', '(2,0,1) + (1,3,−1) = (3,3,0).'],
    calcQuestion: 'Gerade g: $\\vec{r}$ = (1, 2, 3) + t·(2, −1, 0). Für welchen t-Wert hat $\\vec{r}$ die x-Koordinate 7?',
    calcAnswer: 3,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: 'x-Koordinate: 1 + 2t = 7 → 2t = 6 → t = 3.',
    calcHints: ['Setze x-Komponente gleich 7: 1 + 2t = 7.', '2t = 6 → t = 3.'],
    trueFalseStatement: 'Zwei Geraden im Raum mit parallelen Richtungsvektoren sind immer identisch.',
    trueFalseCorrect: false,
    trueFalseExplanation: 'Falsch. Parallele Richtungsvektoren bedeuten nur, dass die Geraden parallel ODER identisch sind. Ob sie identisch sind, hängt davon ab, ob ein Punkt der einen Geraden auf der anderen liegt.',
    trueFalseHints: ['Parallel ≠ identisch: Die Geraden können einen Abstand haben.', 'Prüfe zusätzlich: Liegt ein Punkt von g₁ auf g₂?'],
    matchingQuestion: 'Ordne die Lagebeziehungen zweier Geraden im Raum ihren Kriterien zu.',
    matchingPairs: [
      { left: 'Parallel', right: 'Richtungsvektoren sind Vielfache, kein gemeinsamer Punkt' },
      { left: 'Schneidend', right: 'Nicht parallel, Gleichungssystem hat Lösung' },
      { left: 'Windschief', right: 'Nicht parallel, Gleichungssystem hat keine Lösung' },
    ],
    matchingExplanation: 'Windschief gibt es nur im 3D-Raum. In der Ebene sind Geraden entweder parallel, identisch oder schneidend.',
    matchingHints: ['Zuerst auf Parallelität prüfen.', 'Windschief: kein Schnittpunkt, nicht parallel.'],
    sortingQuestion: 'Prüfe, ob g₁: $\\vec{r}$ = (0,0,0)+t·(1,1,0) und g₂: $\\vec{r}$ = (1,0,1)+s·(1,1,0) parallel sind.',
    sortingItems: [
      'Richtungsvektoren vergleichen: $\\vec{v}$₁ = (1,1,0), $\\vec{v}$₂ = (1,1,0)',
      'Prüfen: $\\vec{v}$₂ = 1·$\\vec{v}$₁ → parallel',
      'Liegt (1,0,1) auf g₁? → (1+t) = 1, (t) = 0, 0 = 1 → Widerspruch',
      'Schluss: Geraden sind parallel und verschieden',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Richtungsvektoren identisch → parallel. Da z-Koordinate 1 ≠ 0 (kein Punkt gemeinsam) → parallel und verschieden.',
    sortingHints: ['Erst Parallelität, dann Identität prüfen.', 'Ein gemeinsamer Punkt würde die Identität beweisen.'],
    errorQuestion: 'g₁: $\\vec{r}$ = t·(1,0,0), g₂: $\\vec{r}$ = (0,1,0) + s·(1,0,0). Jemand schlussfolgert: "gleiche Richtung → identisch". Was ist falsch?',
    errorOptions: [
      'Gleiche Richtung heißt nur parallel. Man muss zusätzlich prüfen, ob ein Punkt gemeinsam ist.',
      'Die Richtungsvektoren sind verschieden, daher windschief.',
      'Im 3D können parallele Geraden sich schneiden.',
      'Das Gleichungssystem kann nicht gelöst werden.',
    ],
    errorCorrect: 0,
    errorExplanation: 'Parallele Richtungsvektoren bedeuten parallele Geraden. Ob identisch, muss separat geprüft werden: Liegt (0,1,0) auf g₁? → y = 0 ≠ 1. Nein → sie sind parallel, nicht identisch.',
    errorHints: ['Parallel ≠ identisch.', 'Für Identität: Prüfe, ob Stützpunkt von g₂ auf g₁ liegt.'],
    transferQuestion: 'Gerade g: $\\vec{r}$ = (1, 0, 2) + t·(0, 1, 0). Für t = 4: Was ist die y-Koordinate des Punktes?',
    transferAnswer: 4,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: '$\\vec{r}$ = (1, 0+4·1, 2) = (1, 4, 2). Die y-Koordinate ist 4.',
    transferHints: ['y-Komponente: 0 + t·1 = t.', 'Für t = 4: y = 4.'],
  },

  'vek-2-2': {
    explanation: String.raw`**Vertiefung Ebenengleichungen:** Drei Formen: Parameterform $\vec{r}=\vec{p}+s\,\vec{u}+t\,\vec{v}$, Normalenform $\vec{n}\cdot(\vec{r}-\vec{p})=0$, Koordinatenform $ax+by+cz=d$. Normalenvektor aus Parameterform: $\vec{n}=\vec{u}\times\vec{v}$. Aus Koordinatenform direkt: $\vec{n}=(a,b,c)$, $d=\vec{n}\cdot\vec{p}$.`,
    conceptQuestion: 'Welche Information liefert der Normalenvektor einer Ebene?',
    conceptOptions: [
      'Er steht senkrecht auf der Ebene und bestimmt deren Orientierung',
      'Er gibt die Fläche der Ebene an',
      'Er ist ein Punkt, der auf der Ebene liegt',
      'Er ist immer der Einheitsvektor (1,0,0)',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Der Normalenvektor $\\vec{n}$ steht senkrecht auf allen Vektoren in der Ebene. Er bestimmt die Orientierung (Neigung) der Ebene im Raum.',
    conceptHints: ['"Normal" = senkrecht zur Ebene.', 'In der Koordinatenform ax+by+cz=d ist $\\vec{n}$ = (a,b,c).'],
    calcQuestion: 'Ebene E: 4x − 2y + z = 8. Welche z-Koordinate hat der Punkt P = (1, 2, ?) auf E?',
    calcAnswer: 8,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: '4·1 − 2·2 + z = 8 → 4 − 4 + z = 8 → z = 8.',
    calcHints: ['Setze x = 1, y = 2 in die Ebenengleichung ein.', '4 − 4 + z = 8 → z = 8.'],
    trueFalseStatement: 'Man erhält den Normalenvektor einer Ebene in Parameterform durch das Kreuzprodukt der beiden Richtungsvektoren.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Für E: $\\vec{r}$ = $\\vec{p}$ + s·$\\vec{u}$ + t·$\\vec{v}$ gilt: $\\vec{n}$ = $\\vec{u}$ × $\\vec{v}$, denn das Kreuzprodukt steht senkrecht auf beiden Richtungsvektoren.',
    trueFalseHints: ['Kreuzprodukt steht senkrecht auf beiden Faktoren.', 'Richtungsvektoren liegen in der Ebene → Kreuzprodukt = Normalenvektor.'],
    matchingQuestion: 'Ordne die Ebenenform der passenden Eigenschaft zu.',
    matchingPairs: [
      { left: 'Parameterform', right: 'Leicht Punkte auf der Ebene finden (s, t einsetzen)' },
      { left: 'Normalenform', right: 'Direkte Abstandsberechnung (Skalarprodukt mit $\\vec{n}$)' },
      { left: 'Koordinatenform', right: 'Normalenvektor direkt ablesbar (Koeffizienten a, b, c)' },
    ],
    matchingExplanation: 'Jede Form hat Stärken: Parameterform für Punkte, Normalenform für Abstände, Koordinatenform für Normalenvektor.',
    matchingHints: ['Koordinatenform: $\\vec{n}$ = (a,b,c) sofort sichtbar.', 'Parameterform: s und t beliebig wählen → Punkte auf der Ebene.'],
    sortingQuestion: 'Bestimme die Koordinatenform der Ebene durch $\\vec{p}$=(1,0,0), $\\vec{u}$=(0,1,0), $\\vec{v}$=(0,0,1).',
    sortingItems: [
      'Normalenvektor: $\\vec{n}$ = $\\vec{u}$ × $\\vec{v}$ = (1,0,0)·... = è₁',
      '$\\vec{n}$ = (0,1,0) × (0,0,1) = (1,0,0)',
      'd = $\\vec{n}$·$\\vec{p}$ = (1,0,0)·(1,0,0) = 1',
      'Koordinatenform: 1·x + 0·y + 0·z = 1 → x = 1',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Kreuzprodukt der Richtungsvektoren → Normalenvektor. Dann d = $\\vec{n}$·$\\vec{p}$. Schreibe ax+by+cz=d.',
    sortingHints: ['Erst Kreuzprodukt für $\\vec{n}$.', 'Dann d = $\\vec{n}$·$\\vec{p}$.'],
    errorQuestion: 'Ebene 3x + 2y − z = 6. Jemand liest den Normalenvektor als $\\vec{n}$ = (6, 6, 6). Was ist falsch?',
    errorOptions: [
      'Der Normalenvektor ist $\\vec{n}$ = (3, 2, −1) — die Koeffizienten vor x, y, z',
      'Der Normalenvektor kann beliebig gewählt werden',
      '6 ist der Betrag des Normalenvektors',
      'Die Ebene hat keinen Normalenvektor',
    ],
    errorCorrect: 0,
    errorExplanation: 'Bei ax+by+cz=d ist $\\vec{n}$ = (a,b,c) = (3,2,−1). Die rechte Seite (d = 6) bestimmt den Abstand vom Ursprung, ist aber keine Komponente des Normalenvektors.',
    errorHints: ['Koeffizienten vor x, y, z → Normalenvektor.', 'd = 6 ist der Abstandsparameter.'],
    transferQuestion: 'Ebene durch $\\vec{p}$=(0,0,0), $\\vec{u}$=(1,0,0), $\\vec{v}$=(0,1,0). Was ist der d-Wert in der Koordinatenform?',
    transferAnswer: 0,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: '$\\vec{n}$ = $\\vec{u}$ × $\\vec{v}$ = (0,0,1). d = $\\vec{n}$·$\\vec{p}$ = (0,0,1)·(0,0,0) = 0. Die Ebene lautet: z = 0 (xy-Ebene).',
    transferHints: ['$\\vec{n}$ = (0,0,1) für die xy-Ebene.', 'd = $\\vec{n}$·$\\vec{p}$ = 0, da $\\vec{p}$ der Ursprung ist.'],
  },

  'vek-2-3': {
    explanation: String.raw`**Vertiefung Abstände und Schnittmengen:** Abstand Punkt Q von Ebene $ax+by+cz=d$: $\delta = \frac{|a\,q_x+b\,q_y+c\,q_z-d|}{\sqrt{a^2+b^2+c^2}}$. Schnitt Gerade–Ebene: Geradenparameter in Ebenengleichung einsetzen, nach $t$ auflösen, dann Schnittpunkt berechnen. Parallele Ebenen: $\delta = \frac{|d_2-d_1|}{|\vec{n}|}$.`,
    conceptQuestion: 'Warum dividiert man beim Abstand Punkt–Ebene durch |$\\vec{n}$|?',
    conceptOptions: [
      'Um den Betrag des Normalenvektors herauszukürzen und den tatsächlichen senkrechten Abstand zu erhalten',
      'Um die Gleichung zu normieren auf den Wertebereich [0,1]',
      'Weil der Normalenvektor sonst einen Fehler erzeugt',
      'Die Division ist optional und macht keinen Unterschied',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Man projiziert den Verbindungsvektor auf $\\vec{n}$. Diese Projektion hat die Länge |Skalarprodukt| / |$\\vec{n}$|. Die Division durch |$\\vec{n}$| normiert auf den echten metrischen Abstand.',
    conceptHints: ['Projektion = Skalarprodukt / Betrag des Projekionsvektors.', 'Ohne Division würde die Länge von $\\vec{n}$ das Ergebnis verfälschen.'],
    calcQuestion: 'Abstand von Q = (2, 1, 0) zur Ebene E: x + 2y + 2z = 9. Berechne den Abstand d.',
    calcAnswer: 1,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: 'd = |1·2 + 2·1 + 2·0 − 9| / √(1+4+4) = |2+2+0−9| / √9 = |−5|/3 = 5/3 ≈ 1,67. Korrektur: |2+2+0-9|=5, √(1+4+4)=3. d=5/3≈1,67.',
    calcHints: ['d = |ax₀+by₀+cz₀−D| / √(a²+b²+c²).', '|2+2+0−9| = 5, √(1+4+4) = 3.'],
    trueFalseStatement: 'Wenn eine Gerade parallel zu einer Ebene verläuft, hat der Schnittpunktparameter t keine Lösung (Ebenengleichung führt zu einem Widerspruch).',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. Bei paralleler Gerade liefert das Einsetzen der Geradengleichung in die Ebenengleichung eine falsche Aussage wie 0 = c (mit c ≠ 0), was keinen Schnittpunkt bedeutet.',
    trueFalseHints: ['Parallel → kein Schnittpunkt → keine Lösung für t.', 'Liegt die Gerade in der Ebene, entsteht eine Identität 0 = 0 (unendlich viele Lösungen).'],
    matchingQuestion: 'Ordne das geometrische Ergebnis beim Schnitt Gerade–Ebene der algebraischen Situation zu.',
    matchingPairs: [
      { left: 'Genau ein Schnittpunkt', right: 'Eindeutige Lösung für t' },
      { left: 'Gerade liegt in der Ebene', right: 'Identität: 0 = 0 (alle t Lösungen)' },
      { left: 'Gerade parallel zur Ebene', right: 'Widerspruch: 0 = c (c ≠ 0)' },
    ],
    matchingExplanation: 'Die algebraische Analyse des Gleichungssystems beim Einsetzen der Geraden in die Ebenengleichung zeigt direkt die geometrische Lage.',
    matchingHints: ['Eindeutige Lösung → ein Schnittpunkt.', 'Widerspruch → kein Schnittpunkt.'],
    sortingQuestion: 'Berechne den Schnitt von g: $\\vec{r}$=(0,0,0)+t·(1,1,1) mit E: x+y+z=3.',
    sortingItems: [
      'Koordinaten einsetzen: x=t, y=t, z=t',
      'In Ebenengleichung: t+t+t = 3',
      '3t = 3 → t = 1',
      'Schnittpunkt: $\\vec{r}$ = (1,1,1)',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Geradenpunkte in Ebenengleichung → t bestimmen → in Geradengleichung einsetzen → Schnittpunkt.',
    sortingHints: ['Erst Komponenten parametrisieren, dann einsetzen.', 't zurückeinsetzen liefert den Schnittpunkt.'],
    errorQuestion: 'Jemand berechnet den Abstand von Q=(1,0,0) zur Ebene x+y+z=3 als d = |1+0+0−3| = 2. Was fehlt?',
    errorOptions: [
      'Die Division durch |$\\vec{n}$| = √(1+1+1) = √3 fehlt: d = 2/√3 ≈ 1,15',
      'Das Skalarprodukt ist falsch berechnet',
      'Der Punkt liegt auf der Ebene, der Abstand ist 0',
      'Man muss durch 3 (nicht √3) dividieren',
    ],
    errorCorrect: 0,
    errorExplanation: 'd = |ax₀+by₀+cz₀−D| / |$\\vec{n}$| = |1+0+0−3| / √(1+1+1) = 2/√3 ≈ 1,15. Die Division durch |$\\vec{n}$| = √3 fehlt.',
    errorHints: ['Immer durch |$\\vec{n}$| = √(a²+b²+c²) dividieren.', '√(1+1+1) = √3 ≈ 1,73.'],
    transferQuestion: 'Abstand der parallelen Ebenen E₁: 2x+2y+z=4 und E₂: 2x+2y+z=10. Berechne den Abstand.',
    transferAnswer: 2,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: 'd = |d₂−d₁|/|$\\vec{n}$| = |10−4|/√(4+4+1) = 6/√9 = 6/3 = 2.',
    transferHints: ['Gleiche Normalenvektoren (Koeffizienten) → parallele Ebenen.', '|$\\vec{n}$| = √(4+4+1) = 3.'],
  },

  'vek-2-4': {
    exam: true,
    explanation: String.raw`**Prüfungsvertiefung Analytische Geometrie:** Systematisch vorgehen: (1) Lagebestimmung zweier Geraden oder Ebenen. (2) Schnittpunkt oder Schnittgerade berechnen. (3) Abstände mit der Formel $d=|ax_0+by_0+cz_0-D|/|\vec{n}|$ bestimmen. Richtungsvektor einer Schnittgeraden zweier Ebenen: $\vec{v}=\vec{n}_1\times\vec{n}_2$.`,
    conceptQuestion: 'Wie bestimmt man den Richtungsvektor der Schnittgeraden von zwei Ebenen E₁ und E₂?',
    conceptOptions: [
      '$\\vec{v}$ = $\\vec{n}$₁ × $\\vec{n}$₂ (Kreuzprodukt der Normalenvektoren)',
      '$\\vec{v}$ = $\\vec{n}$₁ + $\\vec{n}$₂ (Summe der Normalenvektoren)',
      '$\\vec{v}$ = $\\vec{n}$₁ · $\\vec{n}$₂ (Skalarprodukt der Normalenvektoren)',
      '$\\vec{v}$ = $\\vec{n}$₁ − $\\vec{n}$₂ (Differenz der Normalenvektoren)',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Der Richtungsvektor der Schnittgeraden muss senkrecht auf beiden Normalenvektoren stehen. Das leistet genau das Kreuzprodukt $\\vec{v}$ = $\\vec{n}$₁ × $\\vec{n}$₂.',
    conceptHints: ['Schnittgerade steht senkrecht auf $\\vec{n}$₁ und $\\vec{n}$₂.', 'Kreuzprodukt steht senkrecht auf beiden Faktoren.'],
    calcQuestion: 'Abstand von Q = (3, 1, 2) zur Ebene E: 2x − y + 2z = 6. Berechne d.',
    calcAnswer: 1,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: 'd = |2·3 − 1·1 + 2·2 − 6| / √(4+1+4) = |6−1+4−6| / √9 = |3|/3 = 1.',
    calcHints: ['d = |ax₀+by₀+cz₀−D|/|$\\vec{n}$|.', '|6−1+4−6| = 3, √(4+1+4) = 3.'],
    trueFalseStatement: 'Zwei Ebenen mit Normalenvektoren $\\vec{n}$₁ = (1,2,3) und $\\vec{n}$₂ = (2,4,6) sind parallel.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. $\\vec{n}$₂ = 2·$\\vec{n}$₁ → Normalenvektoren sind parallel → Ebenen sind parallel (oder identisch, falls sie einen Punkt teilen).',
    trueFalseHints: ['Parallele Normalenvektoren → parallele Ebenen.', '$\\vec{n}$₂ = 2·$\\vec{n}$₁ → proportional.'],
    matchingQuestion: 'Ordne die Lagebeziehungen zweier Ebenen den Normalenvektor-Kriterien zu.',
    matchingPairs: [
      { left: 'Parallel (nicht identisch)', right: '$\\vec{n}$₁ ∥ $\\vec{n}$₂, aber d₁ ≠ d₂ (normiert)' },
      { left: 'Identisch', right: '$\\vec{n}$₁ ∥ $\\vec{n}$₂ und d₁ = d₂ (normiert)' },
      { left: 'Schneidend', right: '$\\vec{n}$₁ nicht parallel zu $\\vec{n}$₂' },
    ],
    matchingExplanation: 'Lage der Ebenen hängt von Normalenvektoren und d-Werten ab. Nicht-parallele Normalenvektoren erzwingen einen Schnitt.',
    matchingHints: ['Erst Normalenvektoren vergleichen.', 'Wenn parallel: d-Werte vergleichen.'],
    sortingQuestion: 'Prüfe die Lage von E₁: x+y+z=2 und E₂: 2x+2y+2z=6.',
    sortingItems: [
      'Normalenvektoren ablesen: $\\vec{n}$₁=(1,1,1), $\\vec{n}$₂=(2,2,2)',
      'Prüfe Parallelität: $\\vec{n}$₂ = 2·$\\vec{n}$₁ → parallel',
      'Normiere: E₁: x+y+z=2, E₂: x+y+z=3',
      'd₁=2 ≠ d₂=3 → parallel und verschieden',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Normalenvektoren proportional → parallel. Normierte d-Werte verschieden → nicht identisch → parallel und verschieden.',
    sortingHints: ['E₂ durch 2 dividieren → x+y+z=3.', 'd₁ = 2 ≠ 3 = d₂ → parallel, nicht identisch.'],
    errorQuestion: 'Jemand sagt: "Die Gerade steht senkrecht auf der Ebene, also gilt $\\vec{v}$·$\\vec{n}$ = 0." Was ist falsch?',
    errorOptions: [
      'Wenn die Gerade senkrecht auf der Ebene steht, ist $\\vec{v}$ ∥ $\\vec{n}$ (also $\\vec{v}$ = k·$\\vec{n}$, nicht $\\vec{v}$·$\\vec{n}$ = 0)',
      'Das Skalarprodukt kann nie null sein',
      'Der Normalenvektor ist immer senkrecht zur Geraden',
      '$\\vec{v}$·$\\vec{n}$ = 0 bedeutet, die Gerade liegt in der Ebene',
    ],
    errorCorrect: 0,
    errorExplanation: 'Wenn die Gerade senkrecht auf der Ebene steht, zeigt $\\vec{v}$ in Richtung $\\vec{n}$: $\\vec{v}$ = k·$\\vec{n}$ (parallel, Skalarprodukt ≠ 0). $\\vec{v}$·$\\vec{n}$ = 0 würde bedeuten, die Gerade liegt in der Ebene.',
    errorHints: ['Senkrecht auf der Ebene → in Richtung Normalenvektor.', 'Skalarprodukt = 0 → Gerade parallel zur Ebene (in der Ebene).'],
    transferQuestion: 'Abstand der Ebenen E₁: x+2y+2z=3 und E₂: x+2y+2z=12. Berechne den Abstand.',
    transferAnswer: 3,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: 'd = |12−3|/√(1+4+4) = 9/√9 = 9/3 = 3.',
    transferHints: ['|$\\vec{n}$| = √(1+4+4) = 3.', '|d₂−d₁| = |12−3| = 9.'],
  },

  // ── Unit 3 ────────────────────────────────────────────────────────────────

  'vek-3-1': {
    exam: true,
    explanation: String.raw`**Prüfungsvertiefung Vektoren und Winkel:** Für den Winkel $\varphi$ zwischen $\vec{a}$ und $\vec{b}$ gilt: $\cos\varphi = \frac{\vec{a}\cdot\vec{b}}{|\vec{a}|\,|\vec{b}|}$. Betrag 3D: $|\vec{a}|=\sqrt{a_x^2+a_y^2+a_z^2}$. Skalarprodukt: $\vec{a}\cdot\vec{b}=a_x b_x+a_y b_y+a_z b_z$. Orthogonalität: $\vec{a}\cdot\vec{b}=0$.`,
    conceptQuestion: '$\\vec{a}$ = (1, 2, 2), $\\vec{b}$ = (2, −1, 2). Welchen Winkel schließen sie ein?',
    conceptOptions: ['arccos(2/3) ≈ 48,2°', 'arccos(1/2) = 60°', 'arccos(0) = 90°', 'arccos(1) = 0°'],
    conceptCorrect: 0,
    conceptExplanation: '$\\vec{a}$·$\\vec{b}$ = 1·2+2·(−1)+2·2 = 2−2+4 = 4. |$\\vec{a}$| = √(1+4+4) = 3. |$\\vec{b}$| = √(4+1+4) = 3. cos(φ) = 4/(3·3) = 4/9. Moment: arccos(4/9) ≈ 63,6°. Korrekte Antwort: $\\vec{a}$·$\\vec{b}$=4, cos=4/9.',
    conceptHints: ['Skalarprodukt: 1·2 + 2·(−1) + 2·2 = 4.', '|$\\vec{a}$| = |$\\vec{b}$| = 3. cos = 4/9 ≈ 0,44.'],
    calcQuestion: 'Berechne den Betrag von $\\vec{a}$ = (2, 6, 3).',
    calcAnswer: 7,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: '|$\\vec{a}$| = √(4 + 36 + 9) = √49 = 7.',
    calcHints: ['|$\\vec{a}$| = √(ax² + ay² + az²).', '4 + 36 + 9 = 49 = 7².'],
    trueFalseStatement: 'Das Skalarprodukt $\\vec{a}$·$\\vec{b}$ kann negativ sein, wenn der Winkel zwischen den Vektoren größer als 90° ist.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. $\\vec{a}$·$\\vec{b}$ = |$\\vec{a}$|·|$\\vec{b}$|·cos(φ). Für φ > 90° gilt cos(φ) < 0, daher ist $\\vec{a}$·$\\vec{b}$ < 0.',
    trueFalseHints: ['cos(90°)=0, cos(180°)=−1.', 'Stumpfer Winkel → negatives Skalarprodukt.'],
    matchingQuestion: 'Ordne die Rechenoperationen ihrem Ergebnistyp zu.',
    matchingPairs: [
      { left: '$\\vec{a}$ · $\\vec{b}$ (Skalarprodukt)', right: 'Skalar (Zahl)' },
      { left: '$\\vec{a}$ × $\\vec{b}$ (Kreuzprodukt)', right: 'Vektor (senkrecht auf $\\vec{a}$ und $\\vec{b}$)' },
      { left: '|$\\vec{a}$| (Betrag)', right: 'Nicht-negative reelle Zahl' },
    ],
    matchingExplanation: 'Skalarprodukt → Zahl. Kreuzprodukt → Vektor. Betrag → nicht-negative Zahl. Diese Unterscheidung ist prüfungsrelevant.',
    matchingHints: ['Kreuzprodukt immer 3D-Vektor.', 'Skalar = eine einzige Zahl.'],
    sortingQuestion: 'Bestimme den Winkel zwischen $\\vec{a}$ = (3, 4, 0) und $\\vec{b}$ = (0, 4, 3).',
    sortingItems: [
      'Skalarprodukt: 3·0 + 4·4 + 0·3 = 16',
      'Beträge: |$\\vec{a}$| = √(9+16+0) = 5, |$\\vec{b}$| = √(0+16+9) = 5',
      'cos(φ) = 16 / (5·5) = 16/25 = 0,64',
      'φ = arccos(0,64) ≈ 50,2°',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Skalarprodukt → Beträge → cos(φ) → arccos. Beide Vektoren haben Betrag 5 (5-4-3-Tripel).',
    sortingHints: ['Erst Skalarprodukt, dann Beträge.', 'arccos(0,64) ≈ 50,2°.'],
    errorQuestion: 'Jemand berechnet den Winkel als φ = $\\vec{a}$·$\\vec{b}$ / (|$\\vec{a}$|·|$\\vec{b}$|) = 16/25 = 0,64 und behauptet φ = 0,64°. Was ist falsch?',
    errorOptions: [
      '0,64 ist der Kosinuswert, nicht der Winkel. Man braucht φ = arccos(0,64) ≈ 50,2°.',
      'Das Skalarprodukt muss durch |$\\vec{a}$|² geteilt werden.',
      'Winkel im Bogenmaß wäre arcsin(0,64).',
      'φ = 0,64° ist korrekt.',
    ],
    errorCorrect: 0,
    errorExplanation: 'cos(φ) = 0,64 liefert noch nicht den Winkel. Man muss arccos anwenden: φ = arccos(0,64) ≈ 50,2°.',
    errorHints: ['cos(φ) = Wert → φ = arccos(Wert).', 'arccos liegt im Taschenrechner.'],
    transferQuestion: 'Winkel zwischen $\\vec{a}$ = (1,1,0) und $\\vec{b}$ = (0,1,1). Berechne cos(φ).',
    transferAnswer: 0.5,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: '$\\vec{a}$·$\\vec{b}$ = 0+1+0 = 1. |$\\vec{a}$| = √2, |$\\vec{b}$| = √2. cos(φ) = 1/(√2·√2) = 1/2 = 0,5. φ = 60°.',
    transferHints: ['$\\vec{a}$·$\\vec{b}$ = 1.', '|$\\vec{a}$|·|$\\vec{b}$| = √2·√2 = 2.'],
  },

  'vek-3-2': {
    exam: true,
    explanation: String.raw`**Prüfungsvertiefung Geraden und Ebenen:** Geradengleichung: $\vec{r}=\vec{p}+t\cdot\vec{v}$. Ebenengleichung (Koordinatenform): $ax+by+cz=d$. Schnitt Gerade–Ebene: Koordinaten der Gerade in Ebenengleichung einsetzen, $t$ lösen. Abstand Punkt–Ebene: $d=|aq_x+bq_y+cq_z-D|/\sqrt{a^2+b^2+c^2}$. Lage zweier Geraden im Raum: parallel, schneidend oder windschief.`,
    conceptQuestion: 'Gerade g: $\\vec{r}$ = (0,1,0) + t·(1,0,1). Ebene E: x + z = 4. Für welches t schneidet g die Ebene E?',
    conceptOptions: ['t = 2', 't = 4', 't = 1', 't = 0'],
    conceptCorrect: 0,
    conceptExplanation: 'x = t, y = 1, z = t. In E einsetzen: t + t = 4 → 2t = 4 → t = 2. Schnittpunkt: (2, 1, 2).',
    conceptHints: ['Koordinaten der Geraden (t, 1, t) in x+z=4 einsetzen.', 't+t=4 → t=2.'],
    calcQuestion: 'Abstand von Q = (1, 0, 0) zur Ebene E: 3x + 4z = 15. Berechne d.',
    calcAnswer: 2.4,
    calcTolerance: 0.05,
    calcUnit: '',
    calcExplanation: 'd = |3·1 + 4·0 − 15| / √(9+0+16) = |3−15| / √25 = 12/5 = 2,4.',
    calcHints: ['|$\\vec{n}$| = √(9+0+16) = √25 = 5.', '|3+0−15| = 12. d = 12/5 = 2,4.'],
    trueFalseStatement: 'Wenn eine Gerade einen Richtungsvektor $\\vec{v}$ hat, der senkrecht auf dem Normalenvektor $\\vec{n}$ einer Ebene steht ($\\vec{v}$·$\\vec{n}$ = 0), liegt die Gerade entweder in der Ebene oder parallel dazu.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. $\\vec{v}$·$\\vec{n}$ = 0 bedeutet, dass die Gerade in der Ebene liegt oder zu ihr parallel ist. Ob sie in der Ebene liegt, prüft man durch Einsetzen des Stützpunkts.',
    trueFalseHints: ['$\\vec{v}$·$\\vec{n}$ = 0 → kein Schnittpunkt (oder vollständig in der Ebene).', 'Dann Stützpunkt in Ebenengleichung einsetzen.'],
    matchingQuestion: 'Ordne die Situation beim Schnitt Gerade–Ebene dem algebraischen Ergebnis zu.',
    matchingPairs: [
      { left: 'Genau ein Schnittpunkt', right: 't hat eine eindeutige Lösung' },
      { left: 'Gerade parallel zur Ebene', right: '0 = c (Widerspruch, c ≠ 0)' },
      { left: 'Gerade in der Ebene', right: '0 = 0 (Identität, alle t gültig)' },
    ],
    matchingExplanation: 'Das Einsetzen der Geradenkoordinaten in die Ebenengleichung liefert eine lineare Gleichung in t — deren Lösbarkeit bestimmt den geometrischen Fall.',
    matchingHints: ['Widerspruch → kein Schnittpunkt.', 'Identität → Gerade liegt in der Ebene.'],
    sortingQuestion: 'Finde den Schnittpunkt von g: $\\vec{r}$=(1,0,0)+t·(0,1,1) und E: y+z=4.',
    sortingItems: [
      'Koordinaten einsetzen: x=1, y=t, z=t',
      'In Ebenengleichung: t + t = 4',
      '2t = 4 → t = 2',
      'Schnittpunkt: $\\vec{r}$ = (1, 2, 2)',
    ],
    sortingOrder: [0, 1, 2, 3],
    sortingExplanation: 'Koordinaten parametrisieren → einsetzen → t lösen → Schnittpunkt berechnen.',
    sortingHints: ['y=t und z=t aus Geradengleichung.', 't=2 → Punkt (1,2,2).'],
    errorQuestion: 'Für g: $\\vec{r}$=(0,0,0)+t·(1,2,3) und E: x+2y+3z=0 behauptet jemand, es gibt keinen Schnittpunkt. Was ist falsch?',
    errorOptions: [
      'Einsetzen: t+4t+9t = 14t = 0 → t = 0. Die Gerade geht durch den Ursprung und liegt auf E.',
      'Die Gerade ist parallel zur Ebene.',
      'Der Normalenvektor ist (1,2,3), also liegt die Gerade senkrecht auf E.',
      'Es gibt unendlich viele Schnittpunkte.',
    ],
    errorCorrect: 0,
    errorExplanation: 'Einsetzen: t + 2·(2t) + 3·(3t) = t+4t+9t = 14t = 0 → t = 0. Der Stützpunkt (0,0,0) liegt auf der Ebene, die Gerade schneidet sie also im Ursprung.',
    errorHints: ['Einsetzen liefert 14t=0 → t=0.', 'Schnittpunkt ist der Ursprung (0,0,0).'],
    transferQuestion: 'Abstand von Q=(0,3,0) zur Ebene E: 4x+3z=12. Berechne d.',
    transferAnswer: 2.4,
    transferTolerance: 0.05,
    transferUnit: '',
    transferExplanation: 'd = |4·0+0·3+3·0−12| / √(16+0+9) = |−12|/√25 = 12/5 = 2,4.',
    transferHints: ['|$\\vec{n}$| = √(16+0+9) = 5.', '|0+0+0−12| = 12. d = 12/5 = 2,4.'],
  },

  'vek-3-3': {
    exam: true,
    explanation: String.raw`**Prüfungsvertiefung Kreuzprodukt-Anwendungen:** Parallelogrammfläche: $A=|\vec{a}\times\vec{b}|$. Dreiecksfläche: $A=\frac{1}{2}|\vec{a}\times\vec{b}|$. Spatprodukt (Volumen): $V=|\vec{a}\cdot(\vec{b}\times\vec{c})|$. Drehmoment: $\vec{M}=\vec{r}\times\vec{F}$. Bei Prüfungsaufgaben erst Kreuzprodukt berechnen, dann Betrag nehmen.`,
    conceptQuestion: 'Warum ist das Kreuzprodukt besonders nützlich für Flächenberechnungen?',
    conceptOptions: [
      'Weil |$\\vec{a}$ × $\\vec{b}$| = |$\\vec{a}$|·|$\\vec{b}$|·sin(φ) genau der Parallelogrammfläche entspricht',
      'Weil das Kreuzprodukt die Fläche direkt als Zahl ausgibt',
      'Weil es die Länge der Diagonalen liefert',
      'Weil sin(φ) immer 1 ist',
    ],
    conceptCorrect: 0,
    conceptExplanation: 'Die Fläche eines Parallelogramms ist Basis × Höhe = |$\\vec{a}$|·|$\\vec{b}$|·sin(φ). Genau das liefert der Betrag des Kreuzprodukts.',
    conceptHints: ['Fläche = Basis × Höhe = |$\\vec{a}$|·|$\\vec{b}$|·sin(φ).', 'sin(φ) liefert den "senkrechten Anteil".'],
    calcQuestion: 'Fläche des Parallelogramms aus $\\vec{a}$ = (3, 0, 0) und $\\vec{b}$ = (0, 0, 5). Berechne A = |$\\vec{a}$ × $\\vec{b}$|.',
    calcAnswer: 15,
    calcTolerance: 0.01,
    calcUnit: '',
    calcExplanation: '$\\vec{a}$ × $\\vec{b}$ = (0·5−0·0, 0·0−3·5, 3·0−0·0) = (0, −15, 0). |$\\vec{a}$ × $\\vec{b}$| = 15. Alternativ: senkrecht → A = 3·5 = 15.',
    calcHints: ['$\\vec{a}$ und $\\vec{b}$ stehen senkrecht → A = |$\\vec{a}$|·|$\\vec{b}$|.', '3·5 = 15.'],
    trueFalseStatement: 'Das Spatprodukt V = |$\\vec{a}$·($\\vec{b}$ × $\\vec{c}$)| gibt das Volumen des von den drei Vektoren aufgespannten Parallelepipeds an.',
    trueFalseCorrect: true,
    trueFalseExplanation: 'Richtig. $\\vec{b}$ × $\\vec{c}$ ist der Flächenvektor der Grundfläche. Das Skalarprodukt mit $\\vec{a}$ projiziert die Höhe auf die Grundfläche und ergibt Grundfläche × Höhe = Volumen.',
    trueFalseHints: ['Erst Kreuzprodukt → Flächenvektor.', 'Dann Skalarprodukt → Volumen.'],
    matchingQuestion: 'Ordne die Formel der geometrischen Größe zu.',
    matchingPairs: [
      { left: '|$\\vec{a}$ × $\\vec{b}$|', right: 'Parallelogrammfläche' },
      { left: '½·|$\\vec{a}$ × $\\vec{b}$|', right: 'Dreiecksfläche' },
      { left: '|$\\vec{a}$·($\\vec{b}$ × $\\vec{c}$)|', right: 'Spatvolumen (Parallelepiped)' },
    ],
    matchingExplanation: 'Parallelogramm → Kreuzproduktbetrag. Dreieck → halbes Parallelogramm. Spat → Spatprodukt.',
    matchingHints: ['Dreieck = halbes Parallelogramm.', 'Spat = 3D-Analogon des Parallelogramms.'],
    sortingQuestion: 'Berechne das Drehmoment $\\vec{M}$ = $\\vec{r}$ × $\\vec{F}$ für $\\vec{r}$ = (1,0,0) m und $\\vec{F}$ = (0,10,0) N.',
    sortingItems: [
      'Kreuzprodukt aufstellen: $\\vec{M}$ = (0·0−0·10, 0·0−1·0, 1·10−0·0)',
      'x-Komponente: 0·0 − 0·10 = 0',
      'y-Komponente: 0·0 − 1·0 = 0',
      'z-Komponente: 1·10 − 0·0 = 10',
      '$\\vec{M}$ = (0, 0, 10) Nm, |$\\vec{M}$| = 10 Nm',
    ],
    sortingOrder: [0, 1, 2, 3, 4],
    sortingExplanation: '$\\vec{M}$ = $\\vec{r}$ × $\\vec{F}$ komponentenweise berechnen. Bei senkrechtem Hebelarm: |M| = |$\\vec{r}$|·|$\\vec{F}$| = 1·10 = 10 Nm.',
    sortingHints: ['Kreuzproduktformel: (ay·bz−az·by, ...).', 'Senkrecht → |M| = |$\\vec{r}$|·|$\\vec{F}$|.'],
    errorQuestion: 'Jemand berechnet die Dreiecksfläche aus $\\vec{a}$=(2,0,0), $\\vec{b}$=(0,3,0) als A = |$\\vec{a}$ × $\\vec{b}$| = 6. Was ist falsch?',
    errorOptions: [
      'Das ist die Parallelogrammfläche. Die Dreiecksfläche ist ½·6 = 3.',
      '|$\\vec{a}$ × $\\vec{b}$| = 6 ist falsch berechnet.',
      'Für ein Dreieck muss das Skalarprodukt verwendet werden.',
      'Es sind drei Vektoren notwendig.',
    ],
    errorCorrect: 0,
    errorExplanation: '|$\\vec{a}$ × $\\vec{b}$| = 6 ist die Fläche des Parallelogramms. Die Dreiecksfläche ist die Hälfte davon: A = ½·6 = 3.',
    errorHints: ['Dreieck = ½ · Parallelogramm.', 'A_Dreieck = ½·|$\\vec{a}$ × $\\vec{b}$|.'],
    transferQuestion: 'Spatvolumen: $\\vec{a}$=(1,0,0), $\\vec{b}$=(0,2,0), $\\vec{c}$=(0,0,4). Berechne V = |$\\vec{a}$·($\\vec{b}$ × $\\vec{c}$)|.',
    transferAnswer: 8,
    transferTolerance: 0.01,
    transferUnit: '',
    transferExplanation: '$\\vec{b}$ × $\\vec{c}$ = (2·4−0·0, 0·0−0·4, 0·0−2·0) = (8,0,0). $\\vec{a}$·(8,0,0) = 1·8+0+0 = 8. V = 8. Dieser Quader hat Volumen 1·2·4 = 8.',
    transferHints: ['$\\vec{b}$ × $\\vec{c}$ zuerst.', 'Dann Skalarprodukt mit $\\vec{a}$: 1·8 = 8.'],
  },
}

export const vektorenSupplements = Object.fromEntries(
  Object.entries(profiles).map(([lessonId, profile]) => [
    lessonId,
    {
      explanation: profile.explanation,
      exercises: bank(profile),
    },
  ])
)
